### ISSUE TITLE
Write veteran conversation guide research plan

### ISSUE THREAD

**Issue by jcklpe** [department-of-veterans-affairs/va.gov-cms#9949] opened 2022-07-28 20:57 UTC
## Description
Following [this guide](https://depo-platform-documentation.scrollhelp.site/research-design/research-checklist) write out the conversation guide for the research plan.

[context](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/facilities/regional-offices/design)

## Acceptance Criteria
- [ ] make a research folder
- [ ] create a research plan
- [ ] prepare mockup
- [ ] create conversation guide

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by davidmpickett** [comment] 2022-09-07 15:23
Duplicate of https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10192

**Closed by davidmpickett** 2022-09-07 15:23 UTC
Labels: ⭐️ Facilities, Needs refining
