### ISSUE TITLE
VBA Other Nearby VA Locations shows the nearest VAMC, Vet Center, and Cemetery

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#14929] opened 2023-08-23 17:34 UTC
## User Story
As a Veteran using my VBA Regional Office's web page, I also want to see the VA medical center or clinic, Vet Center, and cemetery closest to me.

## Description or Additional Context 
Under VBA Other Nearby VA Locations, show the closest one of each type of facility: VAMC or clinic, Vet Center, and Cemetery.

[VBA Sketch file](https://www.sketch.com/s/891d33ae-152d-471c-ab5d-9aedf89cf6ff/p/FC995695-308A-4493-8461-D9AFE6DC6B25/canvas)

<img width="434" alt="Screenshot 2023-08-23 at 11 31 40 AM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/73648238/817944d5-0b64-4565-859c-f240c6a220b8">

Locations with published pages should be linked to the respective page. 

## Acceptance Criteria
- [x] Create a vets-website React component widget that shows and links each of the pages in this order
  - [x] Nearest VAMC (published Drupal page)
  - [x] Nearest Vet Center (published Drupal page)
  - [x] Nearest Cemetery (Facility Locator page)
- [x] Content build integrates the vets-website component.
- [x] Component is tested.
- [ ] Design is reviewed.
- [ ] Accessibility is reviewed.

## Team
Please check the team(s) that will do this work.

- [ ] CMS Team
- [ ] Public Websites
- [x] Facilities
- [ ] User support
- [ ] Accelerated Publishing

**Comment by maxx1128** [comment] 2023-11-17 15:28
Going off of [this Slack discussion,](https://dsva.slack.com/archives/C0FQSS30V/p1700164103259129?thread_ts=1700074404.370909&cid=C0FQSS30V) the likely solution for this will be using an altered version of the "nearby" widget that doesn't do any filtering with the API request, and we filter down the results on the front-end.

**Comment by xiongjaneg** [comment] 2023-11-29 21:40
@xiongjaneg Add sketch file link

**Comment by eselkin** [comment] 2024-02-21 23:21
Re Max's comment: Filtering after the return is incredibly difficult. It's clearer to use the multi-data reducers for each type of facility requested and do 3 requests, especially if we're limiting the results to a small number like 1 of each kind (small amount of data).

@xiongjaneg @mmiddaugh @jilladams 
How many facilities of each type (Health, Cemetery, Vet Center) should we be getting? 1 or multiple? If multiple, is there a maximum number?

**Background:**
The way Vet Centers works is to download all within a region, sort by distance, then display all within a radius in the sorted order.

**Driving distance:**
Since driving distance may be different than birds-eye distance should we get the nearest 3 or something and select the nearest 1 if 1 is the limit?

**Comment by jilladams** [comment] 2024-02-21 23:26
I think it might be useful to understand the technical options and then let UX help us decide, but defer to Michelle & Jane if they have other ideas. e.g. is it possible to pull any facilities within a radius and present them by distance, regardless of type? Or do you need to specify how many of each type to pull as a first step?

**Comment by eselkin** [comment] 2024-02-21 23:49
Technical options are:
**Mass search:**
If we do a mass search without specifying type we can't be guaranteed within the first page (it paginates results) or first few pages that 1 of each type will exist in the results. Also we get other types that aren't Health, Vet Center, and Cemetery and it's hard from the results to filter since Vet Center and Health and VBA come back with the Facility API's `type` as being "facility" and `facilityType` is odd and has multiple possible matches. We could likely have to go through multiple pages(requests) to get 1 of each type.

**Collect X# of each type**
Collect X (or 1) number of facilities of each type in 3 requests. It can't guarantee that 1 of each type exists (data could be an empty list that is returned), but it's a higher likelihood within 3 requests that we get at least one of each type.

@jilladams We don't specify how many of each type, but we specify the radius and the results per page (and the page number)

**Comment by xiongjaneg** [comment] 2024-02-22 15:22
My understanding is that we want the closest 1 of each type of facility.

**Comment by eselkin** [comment] 2024-02-22 20:59
@xiongjaneg Do we know if the closest is driving distance or birds-eye distance?

**Comment by eselkin** [comment] 2024-02-27 07:55
Mental Health Phone number is not available from vets-api at the time of writing this widget. Is that something coming in v1 of Lighthouse?

**Comment by eselkin** [comment] 2024-02-27 20:06
> I see `phone.mentalHealthClinic` in the [API documenation](https://developer.va.gov/explore/api/va-facilities/docs?version=current).
> 
I put it in like that expecting there to be some result with one but I was turning up nothing with a wide radius. Maybe it was just my starting point.

> It's not required, so there are still some [published facilities without mental health phone numbers](https://prod.cms.va.gov/admin/content/audit/phone-numbers?title=&type=health_care_local_facility&moderation_state=published&workbench_access_section__section=All&phone=).

Yep, neither Cleveland Health center has MH phone numbers.

**Comment by eselkin** [comment] 2024-02-27 23:16
Delay on this ticket is the codeclimate CI task that would never have let the NearByVetCenter component pass in its current state. I've refactored both the NearByVetCenter and the NearByVALocations to use a lot of the same components but it's still giving me an error in code climate so I'm trying to track it down.

However, ACs are done, testing is done. Just trying to get it into shape to pass code climate.

**Comment by laflannery** [comment] 2024-03-08 19:48
A question came up regarding the heading for "Other nearby VA locations" and the fact that it wasn't showing in the "On this page" component even though it's an H2. This is a known issue with react widgets - this heading isn't no always going to appear, it's inconsistent and if you don't see it at first will often appear with a page refresh.

A solution was proposed by @maxx1128 to move the heading out of the react widget and into content-build however this would mean that the heading would appear even if there were no locations - no bueno. So @eselkin built on this proposed solution and said that if we did do that, would could have the heading show with text that said "No nearby VA locations found." 

![Screenshot 2024-03-08 at 2 33 37 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/106678594/0bcdc003-d0b0-4300-b234-224d511c4dd3)

This way the headings on the page always show in "On this page" always and content will always show under any heading if it appears. However, we wanted to run this solution by @mmiddaugh and @xiongjaneg

**Comment by xiongjaneg** [comment] 2024-03-08 19:50
Adding to product sync Monday

**Comment by aklausmeier** [comment] 2024-03-08 21:10
I think this is an excellent solution.

**Comment by jilladams** [comment] 2024-03-18 23:50
@eselkin I noticed the vets-website PR is merged but the content-build isn't. Will that cause any issues with order of operations for showing up in prod, or are those 2 PRs not dependent in that way? Can you / @thejordanwood / @laflannery  also confirm status around design / a11y review?

**Comment by eselkin** [comment] 2024-03-19 15:16
No, won't cause issues, it has to happen that way. If the component didn't exist on Vets-website and it tried to bring it in in content-build it'd be blank, but this way nothing gets used.

There was no way to get the component on a tugboat to show for them, they could just see images.

**Comment by laflannery** [comment] 2024-03-19 17:12
There is also currently an issue with previewing VBA content on stage and prod so if we can't get it on a tugboat, to be honest I'm not entirely sure where Jordan and I are going to be able to see this to review it

**Comment by jilladams** [comment] 2024-03-19 17:54
Yep, fair. In that case, if we need to merge and review post deploy / ticket any fixes, I think that's probably reasonable unless @mmiddaugh you have concerns? (cc @xiongjaneg )

**Comment by jilladams** [comment] 2024-03-20 17:02
* Tugboat doesn't have a mapbox key, and that's why we can't preview this on Tugboat.
* Review Instances do have mapbox keys. You can't publish content off a Review Instance, though. 
* We could Stage it behind a flag. 

For now: we could get a screenshot of the FE display and the HTML for review. Eli to provide.

For Staging Review: this also has to be visible to Platform team. If Preview worked, Platform could probably see this. We need to get a ticket filed about the expected behavior of Preview servers for draft content. @mmiddaugh to follow up with CMS team.  (CMS team helpdesk ticket here was filed suggesting to remove the Preview button, which should be a no op: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17556)

We should file a feature request to CMS team for consideration to make Mapbox available on Tugboat, but they prob can't prioritize it anytime soon.

**Comment by laflannery** [comment] 2024-03-25 15:02
@eselkin I was able to look at this using preview now that its fixed - 2 things:
- Can we use the `<va-link>` component for the Titles of the facilities?
- When I'm focused on the facility titles, the focus indicator (the yellow/gold outline) is not visible. This screen shot you can see that I'm tabbed to the first facility, the link is showing in the bottom left but there's no outline
![Screenshot 2024-03-25 at 10 31 11 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/106678594/392a6bda-d6c1-4d63-bf41-261e4996d455)

**Comment by eselkin** [comment] 2024-03-25 21:43
Does the tab gold outline happen because of va-link or is there something about it being a widget that prevents that outline? I'll look more into it.

**Comment by jilladams** [comment] 2024-03-27 02:14
![Screenshot 2024-03-26 at 7 12 36 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/85581471/45a29b5b-f3ea-4be1-8144-fd9450111dd2)

I did also verify that while tabbing focus, the gold outline appears on facility titles (Chrome). Closing, but Laura feel free to reopen if you have any remaining concerns.

**Closed by jilladams** 2024-03-27 02:14 UTC
Labels: VA.gov frontend, Facilities, Regional office
