### ISSUE TITLE
Cleanup Old S3 Backups and implement lifecycle policy

### ISSUE THREAD

**Issue by ElijahLynn** [department-of-veterans-affairs/va.gov-cms#1692] opened 2020-05-05 17:32 UTC
## Background

Currently we are keeping a backup of the DB, Sanitized DB and Files/Assets every 15 minutes. We likely only need that frequency for a day or so, then after a week maybe every hour and after a month, just every day. I don't know what the perfect number is but the files backups are nearly 1GB, so this is 96GB a day and we should clean some of these out.

This should either be a Jenkins job or a Lambda function, probably Jenkins to keep everything in one place and better transparency. Maybe the job can also output the total size of the bucket before and after. 

## Acceptance Criteria

- [x] Backups are retained according to this policy:
  - one every 15 minutes for the past month
  - one per day for the past year
  - one per week in perpetuity
- [x] older backups surplus to the above have been removed, moved to a cheaper tier, or both
- [x] Above policy has been verified to comply with ATO

## Implementation Details
- [x] Backup Orchestration handled by Github Actions
  - [x] CMS AWS IAM Credentials created for GHA usage
  - [ ] Github action workflow written to:
    - [x] FInd and copy, daily, sanitized asset file and SQL backups
    - [x] FInd and copy, daily, unsanitized SQL backups
    - [x] FInd and copy, weekly, sanitized asset file and SQL backups
    - [x] FInd and copy, weekly, unsanitized SQL backups
    - [x] Merge changes into VA.gov-cms repo
- [x] CMS S3 Buckets use Lifecycle policies to manage data retention
  - [x] VSP Ops S3 Terraform module extended to implement Lifecycle policies
  - [ ] Modify CMS S3 bucket infrastructure code:
    - [x] 30 day file expiration policy applied to backups taken every 15 minutes
    - [x] 365 day file expiration policy applied to backups taken every day
    - [x] Immediately transition to Glacier policy applied to backups taken every week 
    - [x] Merge changes into Devops repo
- [x] Create one-time script to apply overall backup policy to all existing files.

### Implementation Order

1. Create and run script to organize existing files in lifecycle managed backup folders
2. Merge/Apply Lifecycle policy to backup folders
3. Merge/Apply script for Backup retention policy orchestration

**Comment by acrollet** [comment] 2021-05-12 16:18
@jefflbrauer @ElijahLynn @olivereri do you know of any data retention policies we should be aware of regarding this issue?

**Comment by acrollet** [comment] 2021-05-12 16:19
Moving this back to "needs refining" so that we can settle on the ACs.

**Comment by ElijahLynn** [comment] 2021-06-02 16:39
Using S3 Lifecycle rules should be used for this!

**Comment by ElijahLynn** [comment] 2021-06-02 16:40
> @jefflbrauer @ElijahLynn @olivereri do you know of any data retention policies we should be aware of regarding this issue?

This will be listed in the ATO if it exists.

**Comment by mchelen-gov** [comment] 2021-07-22 19:49
back of napkin calcs:

S3 Standard s3 aws govcloud us-west
https://aws.amazon.com/s3/pricing/
0.039 / gb

sanitized bucket =
77tb = $3k/mo
+ 0.5tb / day

backup bucket = 
2.6tb = $100/mo
+ 14gb / day

**Comment by ElijahLynn** [comment] 2021-07-22 19:52
`aws s3 ls --region us-gov-west-1 --summarize --human-readable --recursive "s3://dsva-vagov-prod-cms-backup-sanitized"`

> Total Objects: 70484
>    Total Size: 77.1 TiB


`aws s3 ls --region us-gov-west-1 --summarize --human-readable --recursive "s3://dsva-vagov-prod-cms-backup"`

> Total Objects: 35637
>    Total Size: 2.6 TiB

**Comment by ElijahLynn** [comment] 2021-07-22 19:56
Nearly $6,000 month in US Gov West 1:

![image](https://user-images.githubusercontent.com/1504756/126701565-81c4f420-47d2-48a6-8642-d8d42cf3d319.png)

**Comment by olivereri** [comment] 2021-08-03 22:23
Not sure if I understand this AC:

- [ ] Backups are retained according to this policy:
  - every 15 minutes for 1 month
  - every day for 1 year
  - every week in perpetuity

Does it mean if the backup frequency is X retain the backups for Y? Reviewing what we back up, there's only the asset files and sql backups and they are on a 15 minute backup frequency. I suppose I need help determining what we backup, but I'm pretty sure it's only these 2 things.

@mchelen-gov Do you have access to the ATO documentation for VA.gov CMS or the parent program? I'm pretty confident SQL and Asset file backups don't have a retention security control. I think it's important that we just have backups and a DR plan. I think file retention controls are more geared towards logs.

@ElijahLynn Do we intend to implement lifecycle policies in Terraform or directly on the bucket. Looking at the way we created the bucket in Terraform it doesn't appear easy to add these policies.

**Comment by olivereri** [comment] 2021-08-04 18:43
If we want to keep the S3 buckets tracked in Terraform one possible way is to extend the platform's module `terraform-aws-vsp-s3-bucket` to accept `lifecycle` arguments which doesn't currently support.

Otherwise, I'm mildly concerned we'd need to remove the bucket from the terraform state and attempt to re-import as a S3 bucket resource.

**Comment by olivereri** [comment] 2021-08-04 21:17
https://github.com/department-of-veterans-affairs/terraform-aws-vsp-s3-bucket/pull/2

**Comment by mchelen-gov** [comment] 2021-08-09 15:43
@olivereri we did some back of the napkin calcs on current costs, after digging into it can you tell if those estimates are roughly accurate, and about how much cost savings have been achieved here?

**Comment by olivereri** [comment] 2021-08-09 17:18
@mchelen-gov Not fully implemented yet so no cost savings yet, but since Elijah used the official AWS cost calculator I'd say it's fairly accurate.  We should expect to save the amount calculated if we were to clean it all up. But we won't be cleaning it all up, however we will dramatically reduce the number retained.

To make the estimate (post implementation) even more accurate we'll need to include the impact of our retention policy:
30 days worth of backups every 15 minutes = 360 files
1 year worth of daily backups = 365 files
Infinite weekly backups = 52 files year after year

Current asset file backups are about 5 Gb, holding that size constant we can project in the first year:
(360 + 365 + 52)*5Gb = 4.3 Tb

Per [AWS Simple Monthly Calculator](https://calculator.s3.amazonaws.com/index.html) _just for asset files_ alone this will cost the VA ~$171 per month. Additionally, the cost would increase by ~$40 every 4 years (52*5Gb = 260Gb) if we do not transition it out of S3 standard tier into a lower cost less accessible tier like Glacier.

The above formula will need to be applied to sanitized Database backups and Production Backups to get the whole picture. If we ballpark that these other sets of files require the same storage capacity, we're looking at ~12Tb which would cost ~$480 per month. 

**I predict this will reduce the current storage cost by a factor of 12.**

**Comment by olivereri** [comment] 2021-08-10 18:50
Getting some odd output from the Github Action workflow active on the `va.gov-cms-test` repository.  It appears it would only affect cms-test as the latest backup would never be found in one of the backup folders.  However, if production backups were to fail or stop for a period of time for `cms` buckets we'd see the run away effect in the below output snippet:

```
copy: s3://dsva-vagov-prod-cms-test-backup-sanitized/files/daily/files/daily/files/daily/files/daily/files/prod_cmsapp_files_2021-03-17-23-06.tgz to s3://dsva-vagov-prod-cms-test-backup-sanitized/files/daily/files/daily/files/daily/files/daily/files/daily/files/prod_cmsapp_files_2021-03-17-23-06.tgz
```

The crux of the issue is that there is no max depth search as these really aren't folders but a prefix on an object name that makes up the `Key`.  An easy fix is to move these backup "folders" to the top level so that the `s3api list-objects` command never searches in that specific prefix like it's doing now.

**Comment by olivereri** [comment] 2021-08-11 17:13
Discussed this with Faith Owusu-Sekyere the VSP ATO lead.  She said that data retention ranges from 1 hour to 90 days based on the sensitivity of the data stored. When asked she agreed that 90 days was a reasonable time frame for our data. Many ATO controls are worded as _meets or exceeds_ and our retention policy exceeds her guidance.

Conversation documented below in slack:
https://dsva.slack.com/archives/CNA780EDN/p1628630120013100

**Comment by olivereri** [comment] 2021-08-13 15:14
Went down the wrong path trying to meet this AC `older backups surplus to the above have been removed, moved to a cheaper tier, or both`. It's effectively a batch copy job to move existing backups to backup folders then implement lifecycle policies on all of the s3 folders.  Some of the work done is relevant like sorting through all of the backups and picking out one from everyday for the past year as well as finding a backup from every week  since the inception of the project.

Should have spent some extra time researching how to move large number of objects in S3. Copy commands as part of an SDK or CLI doesn't cut it. This is a job for S3 Batch Operations:

![image.png](https://images.zenhubusercontent.com/5f04cf8f49978b1615fee8c2/25280fdc-86b2-4fc7-8a75-cc2d78f9537b)

It takes a CSV file of the objects to be copied and handles the rest. Used a Python script to read from S3 and create the CSV file.

**Closed** 2021-08-13 19:57 UTC
Labels: DevOps, Core Application Team, Needs PO review, Infrastructure Cost

**Comment by olivereri** [comment] 2021-08-16 16:24
`aws s3 ls --region us-gov-west-1 --summarize --human-readable --recursive "s3://dsva-vagov-prod-cms-backup-sanitized"`

> Total Objects: 5461
>   Total Size: 11.3 TiB


`aws s3 ls --region us-gov-west-1 --summarize --human-readable --recursive "s3://dsva-vagov-prod-cms-backup"`

> Total Objects: 2758
>  Total Size: 363.9 GiB
[AWS Simple Cost Calc:](https://calculator.s3.amazonaws.com/index.html)
![image.png](https://images.zenhubusercontent.com/5f04cf8f49978b1615fee8c2/897840d3-8a8f-445f-a69d-7c3a3b0f33a0)

This is a very lazy estimate because `aws s3 ls` does not filter by storage class. A chunk of files in either bucket is in the lower cost Glacier tier of storage. However, the majority of objects are of the Standard Storage tier.

@mchelen-gov  It appears my factor of 12 cost reduction was fairly accurate.
