### ISSUE TITLE
[Social Media Links - Benefit Hub pages] Social media links in the Follow us section of these pages are broken

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#18265] opened 2024-06-03 14:22 UTC
## Description

Social media channel links under “Follow us” are broken on Benefit Hub page templates (e.g. https://www.va.gov/disability/)  This can be seen it on healthcare and disability.

<img width="440" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMzh2QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d6ec402f8ee8988b59195fa2a00f1fa474924aa2/image.png" alt="image.png" />

### Steps to Reproduce
1. Go to https://www.va.gov/disability/
2. Scroll down to the 'Follow us' area on right of screen
3. Click the Veterans Administration Facebook
4. Click any of the other social media  links

## Acceptance criteria

- [ ] Social Media links appropriately open the correct VA social media page

**Comment by jilladams** [comment] 2024-06-03 19:19
Noting: discussed with Dave / Fran in product sync that this missed today's daily deploy, and it doesn't warrant an OOB deploy. When this does deploy, we need to let Dave know so he can let VHA folks know it's fixed in prod. 

@randimays do you have a sense from your work here what happened? Curious if this was a regression that happened during icon work, or something else acted on these links. 

Also noting: Dave is curious about whether the broken link checker should have caught these, and I noted that they do not appear in the #content-broken-links channel. Might be because they're hard coded in templates and don't originate in Drupal content, not sure.

**Comment by randimays** [comment] 2024-06-03 20:23
@jilladams This was a regression caused by va-icon updates. I was fairly certain I'd clicked those links to check when I updated the icons, but somehow I missed them. The PR was a fix for a syntax issue.

**Comment by jilladams** [comment] 2024-06-03 22:48
Asked CMS whether the broken link checker should be checking links like this: https://dsva.slack.com/archives/CT4GZBM8F/p1717446503569169

**Comment by randimays** [comment] 2024-06-05 13:49
Successfully validated the fix in production. Closing!

**Closed by randimays** 2024-06-05 13:49 UTC
Labels: Defect, VA.gov frontend, Unplanned work, Public Websites
