### ISSUE TITLE
Table audit view: update query to include any new tables identified via #10793

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#10949] opened 2022-09-28 16:57 UTC
## Description
Table Audit view (https://prod.cms.va.gov/admin/content/audit/table-audit) is incomplete. Sitewide Content team identified that they know of additional pages with tables that are not represented here. 

#10793 will identify allllll tables, at any level of paragraph nesting. Once those have been identified, the Table Audit view should be updated to ensure that they appear.

## Acceptance Criteria
- [ ] Table Audit view displays all CMS-generated tables

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [X] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by laflannery** [comment] 2022-11-10 18:38
@jilladams I came across this and it seems like a duplicate of #10793 - both are to ensure that all tables are being displayed in the table audit. Do you know if this is a true duplicate and could it be closed or was this intended to be something else?

**Comment by jilladams** [comment] 2022-11-10 18:55
Pretty sure it ended up being a true dupe. The goal was: identify any tables missing that Sitewide Content knew should be there. I believe #10793 achieved that.

**Comment by laflannery** [comment] 2022-11-10 18:56
Ok, I just wanted to make sure I wasn't closing a ticket of yours that I misunderstood, thanks!

**Closed by laflannery** 2022-11-10 18:56 UTC
Labels: Drupal engineering, Needs refining, ⭐️ Sitewide CMS
