### ISSUE TITLE
Concord Vet Center appears closed in Facility Locator, but "Limited Hours" in CMS and on Vet Center page

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#6429] opened 2021-09-15 13:01 UTC
**Describe the defect**

**To Reproduce**

Compare  https://www.va.gov/find-locations/?page=1&address=94520&facilityType=vet_center&se[…]72&context=Concord%2C%20California%2094520%2C%20United%20States with https://www.va.gov/concord-vet-center/

**Expected behavior**
Status should match

**Screenshots**

![Concord_Vet_Center___Veterans_Affairs](https://user-images.githubusercontent.com/643678/133437917-d4a2c234-92cc-4639-a500-4a6c47c84226.png)

![Find_VA_Locations___Veterans_Affairs](https://user-images.githubusercontent.com/643678/133437948-0ac3a8ed-cb7b-4171-85eb-cd3bb83de6bc.png)

**Additional context**
Add any other context about the problem here. Reach out to the Product Managers to determine if it should be escalated as critical (prevents users from accomplishing their work with no known workaround and needs to be addressed within 2 business days).

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS objective (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Core Application Team`
- [x] `Product Support Team`

**Comment by swirtSJW** [comment] 2021-09-15 21:37
This was corrected in the data so I am closing this, but opening a pair of tickets for the root cause.

- Fix facility status push to lighthouse has publsihed -> draft logic flaw https://github.com/department-of-veterans-affairs/va.gov-cms/issues/6437
- [Improve workflow for enforcing a change of facility operating status gets published](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/6438)

**Closed** 2021-09-15 21:38 UTC
Labels: Defect, Needs refining, Product Support Team

**Comment by swirtSJW** [comment] 2021-09-15 21:41
The data was corrected and also a force push was performed to make sure all data was synced with lighthouse.
  
Lighthouse team reported that in total 11 facilities had drifted from what was in lighthouse before the bulk push.


"vha_667","NOTICE","NORMAL"
"vha_534QC","NORMAL","CLOSED",
"vha_693GA","NOTICE","NORMAL"
"vha_580GL","CLOSED","NORMAL"
"vha_640QB","NORMAL","NORMAL"  had a change to status info
"vc_0705V","CLOSED","LIMITED",
"vha_580GF","LIMITED","NORMAL"
"vha_580GC","LIMITED","NORMAL"
"vha_580GJ","LIMITED","NORMAL"
"vha_580BY","LIMITED","NORMAL"
