### ISSUE TITLE
[EPIC] Aging Content Notifications Framework (MVP)

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#15653] opened 2023-10-11 17:47 UTC
## Description
Content in general, and for the purpose of this Initiative, content types of banners (full-width, home page promo, and hope page news) in VA.gov become stale and aren’t monitored or updated on a regular cadence, allowing many of them to still display after a campaign or event has passed. Full-width banners should be used only for informational alerts or warning alerts.

Currently, there is a Notification system set on a 365 day cadence from set from the banner's Created date or if subsequently edited, Last Edited date.

To provide timely information to Veterans and other users of VA.gov, and ensure banners are replaced and/or monitored, we need to implement the ability for the notification system to send notification emails based on a cadence specific to particular content types, e.g. Full-Width banners will only display for seven (7) days, and notifications will be sent three days before the 7th day (telling them they need to edit to add a note that it is still needed, or archive the banner by the seventh day), then the morning of the 7th day (telling them they need to either edit to add a note that the banner is still needed, or archive), and finally, when auto-archiving is implemented, a notification will be sent telling them the banner was archived. This will also be used for Home Page Promo Banners, and Home Page News Banners, which will be set at 30 day notification sequences (future stories/initiative to actually implement). Take note that if other banner types are created in the future, then this framework needs to be extendable to accommodate them as well.

### User story

**AS A** PO/PM of content types of Banners
**I WANT** to have a framework wherein different notification timeframes/cadences may be assigned to different banner-types of content
**SO THAT** banners in VA.gov don't become stale and are updated at a prescribed cadence by editors

## Acceptance criteria
- [ ]

**Comment by jilladams** [comment] 2024-01-17 18:45
Closing as dupe of #15504

**Closed by jilladams** 2024-01-17 18:45 UTC
Labels: Epic, Needs refining, Banners and alerts, Public Websites, Product management, Aging Content
