### ISSUE TITLE
[Search] Turn on the maintenance banner when Search.gov confirms system maintenance dates - ~Oct 21

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#19341] opened 2024-09-26 22:56 UTC
**[2024-10-18]** Search.gov sent update on 10/18 stating that the infra release will be happening by 5pm EST on 10/21
**[2024-10-11]** Search.gov to update on status of the update by 10/25. Tagged into Sprint 15 fysa.
**[2024-10-1]** Update: Search.gov is moving their release to after 5pm ET on Friday, October 4th.

> We’re reaching out to let you know that after significant analysis, we have decided to change the release date of our system’s switch to a new infrastructure to this Friday, October 4, 2024, after 5pm ET.
>
> We will send a final confirmation that the switch is happening, or an update with the next scheduled date the morning of October 4, 2024.

<img src="https://github.com/user-attachments/assets/b7305045-c647-45ac-a717-06b7e621124d" width="400" />

## Description
 Search.gov is planning a significant deployment next Tuesday, **~~October 1st (TBD exact timing)~~ October 4th, 5pmET**. They've notified that:

"We plan to deploy our system to be switched to a new infrastructure next Tuesday, October 4th, 5pmET ~~1st~~. Here’s important information about this deployment:
- The release to production will be after business hours (Eastern Time)
- Customers may expect potential brief interruptions of search functionality and/or access and availability of the Admin Center
- Customers can report any issues related to this switch by contacting our team at search@gsa.gov
- We will send a final confirmation that the switch is happening, or an update with the next scheduled date the morning of October 4th ~~1~~, 2024

We want to turn on the banner to temporarily notify users of the outage without bringing down the entire sitewide search (because we won't know exactly how long their update will take) by using the feature flipper added in ticket #18206.

You can find the flipper (`search_gov_maintenance`) in Flipper Admin in both staging and production. The code changes we made to make use of this flipper are deployed in production (and not showing because the flippers are off). 

![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/19175324/f4450817-5a57-4bfa-84da-f95521527647)

### User story

**AS A** Veteran, their family member, caregiver and/or survivor
**I WANT** to be informed if the Search feature on VA.gov is experiencing issues or not available
**SO THAT** so my expectations are set prior to me attempting to use it and getting errors for every search.

### Engineering notes / background
Add an error banner to notify the user that we are experiencing outages with the service. We shouldn't use the typical maintenance banner as it calculates hours for the anticipated outage, and in our case that could be 30 hours... 100 hours... we're not sure.

## Acceptance criteria

- [ ] Error banner displays to users for VA.gov Search feature

**Comment by FranECross** [comment] 2024-09-27 14:31
@chriskim2311 @randimays I pulled this into Current Sprint/Not Started so that the banner can be displayed on October 1st. We don't know exact timing from search.gov yet, unfortunately. @mmiddaugh shared the information with us. cc @jilladams @dsasser

**Comment by jilladams** [comment] 2024-10-01 21:28
Moving to sprint 14 since date changed.

**Comment by jilladams** [comment] 2024-10-04 18:04
Flipper is here: https://api.va.gov/flipper/features/search_gov_maintenance

**Comment by SnowboardTechie** [comment] 2024-10-07 14:44
This morning with search.gov status all green, I disabled the flipper flag and search is now functioning as intended on va.gov

**Comment by randimays** [comment] 2024-10-07 14:59
Update from Search.gov in an email sent Friday ~3pm CST:

**BLUF**: They didn't do the Friday deploy of new infrastructure.

> Thank you for your support and patience as our team works to release the switch of our system to a new infrastructure. Unfortunately, due to unexpected technical challenges, we are confirming that the release date is delayed until further notice. 
> 
> Please accept our apology as we work hard to resolve this as quickly as possible. We acknowledge that this delay is frustrating. 
>
> Expect an update from the Search.gov team about the status of this transition no later than Friday, October 11, whether there is a confirmed date for deployment or another update. We will continue to provide regular updates until the release is live. 
>
> Until then, you can expect continued search functionality and reliability of our system. Our goal is to release the newly anticipated features, and deliver an improved Search.gov service. Please reach out to us at search@gsa.gov with any questions or concerns you may have.

<img src="https://github.com/user-attachments/assets/0c9861bd-bf8a-48df-9a1c-4fc3edd9079e" width="700" />

**Comment by jilladams** [comment] 2024-10-07 17:02
Moved it back to Ready.

**Comment by jilladams** [comment] 2024-10-11 16:49
https://dsva.slack.com/archives/C52CL1PKQ/p1728664983193139

![Image](https://github.com/user-attachments/assets/1743fc54-b58f-49b7-ba3c-3a68deb742b8)

**Comment by randimays** [comment] 2024-10-18 15:28
Search.gov sent an update saying they will be releasing their infrastructure update on Monday October 21 by 5pm EST.

<img src="https://github.com/user-attachments/assets/e995d510-459b-4ea8-9ef3-3eb3686b692e" width="500" />

>Our team is ready to release the switch of our system to a new infrastructure Monday, October 21.
>
>The [Search.gov](http://search.gov/) team will execute changes and expect them to go live by 5 PM Eastern time. If you should experience any interruption of search functionality or access issues to the Admin Center, please reach out to our team at [search@gsa.gov](mailto:search@gsa.gov).
>
>What to expect as a [Search.gov](http://search.gov/) customer:
> - Possible downtime and dropped connections between 5 PM and 9 PM Eastern time
> - Possible disruption of changes made in the Admin Center between 5 PM and 9 PM Eastern time

**Comment by jilladams** [comment] 2024-10-18 15:38
Noted! I put a calendar reminder on the team cal. I think we should turn on the warning midday, just in case.

**Comment by jilladams** [comment] 2024-10-23 22:11
Search banner was on from Mon afternoon through just now. Search infra deployed, introduced some bugs / infra issues, and Search was unstable for about 1.5 days. More details in monitoring channel starting here: https://dsva.slack.com/archives/C06RWEW3S3W/p1729613957493489

Closing.

**Closed by jilladams** 2024-10-23 22:11 UTC
Labels: VA.gov frontend, Search, Banners and alerts, Unplanned work, Public Websites, sitewide, VA.gov Search, current sprint, ghp-sprint
