### ISSUE TITLE
Platform Design Intent for FE Spotlight pattern

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#17505] opened 2024-03-13 14:08 UTC
## Description or Additional Context 
This follows up Jordan's work on #17208 

Note the comment in that ticket: "I updated [the Figma file](https://www.figma.com/file/ikCp2eOubIgbN1TwyEYIrN/VAMC-CMS-Master?type=design&node-id=108%3A1696&mode=design&t=cVz51Gik6zrpoMUl-1) to show the use cases and how we could solve for them. I also included a couple of comments in the file with thoughts on some Drupal guardrails we could implement."

Potential guardrails:
- Standardize the way emails and phone numbers are displayed. In Drupal, events have standard CTAs that editors can select from a dropdown. The events dropdown includes Register, Apply, RSVP, More details. On the FE, we would display as "Call/Email to X" or "Call/Email for more details"
- We could limit the CTA they provide for cards to include a link, phone number, or email. That way there aren't multiple CTAs on a card.

## Problems to focus on
Getting Platform guidance on bullet points, CTAs (not required), other examples that editors are doing in Spotlights.

Recommend only using 1 CTA and be able to add email. Potentially limit choices for CTA.

## Potential use cases

Phone numbers
- https://www.va.gov/boston-vet-center/ (the 2 local spotlights have both phone and a link)
- https://www.va.gov/ocala-vet-center/ A phone number AND a bullet list!
https://www.va.gov/scranton-vet-center/ 2 phone numbers

Email:
- https://www.va.gov/lancaster-vet-center/
- https://www.va.gov/phoenix-vet-center/ And a phone number!
- https://www.va.gov/fort-myers-vet-center/

No link:
- https://www.va.gov/sioux-falls-vet-center/
- https://www.va.gov/kona-vet-center/
- https://www.va.gov/portland-me-vet-center/ (The one about the new location here really shuts down my thought that all spotlights should have at east 1 CTA)

Multiple events
- https://www.va.gov/evansville-vet-center/ (This one doesn't happen to have 2 links but it could potentially, 1 per event)

## Acceptance Criteria
- [x] Prep for CC design intent
- [ ] ~Work with PM to schedule design intent~
- [ ] UX lead review is complete

**Comment by xiongjaneg** [comment] 2024-03-13 15:16
From Michelle: is there a character limit and can/should we consider it?

**Comment by aklausmeier** [comment] 2024-03-18 17:25
@thejordanwood I would like to see the 2 new spotlight patterns in full page mockups for design intent so we can share how this looks in context to the full page.

**Comment by thejordanwood** [comment] 2024-03-20 15:44
@aklausmeier I've created full page mockups for this and now show them in [the Figma file](https://www.figma.com/file/ikCp2eOubIgbN1TwyEYIrN/VAMC-CMS-Master?type=design&node-id=108%3A1696&mode=design&t=L2QS63BvovclEcLv-1). Since we both agree that the card component should be the outline style instead of the gray background, I've updated all instances of cards in the file to reflect that. 

Not sure if this is going to design intent anymore or if we're going to show this during the [VBA staging review](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17095#issuecomment-2009844648) instead. Either way, the design portion of this is ready for whatever we decide. 

cc: @xiongjaneg

**Comment by jilladams** [comment] 2024-03-20 16:43
Decisions: 
* We won't do Design Intent
* We will get flagged at VBA Staging Review for having an imposter component.
    * Amanda following up with Matt Dingee about it, based on going through Design Intent and Midpoint with the original design. 
    * We suspect it will not be launch blocking.
* Can we go ahead with the card component? It doesn't support phone numbers for CTA, bullets
    * Are we missing a design review step? No, it's happening today.

**Comment by aklausmeier** [comment] 2024-03-20 20:52
Confirmed with Matt Dingee. 

- Current Spotlights pattern will not be a staging blocker
- We should continue to update spotlight pattern to the va-card component. Right now, it is using an "imposter" summary box component in the eyes of design system.

**Comment by aklausmeier** [comment] 2024-03-20 22:23
Met with @laflannery and @thejordanwood to review use cases. None impact our ability to move forward with updating to standardizing with VA card (facilty) and related links components (system). CMS content types will need to be addressed but I think this ticket can be closed once FE design mockup is annotated and Jordan can move on to finalizing CMS design and updating related engineering tickets.

**Comment by thejordanwood** [comment] 2024-03-22 15:09
@laflannery has made updates to my first pass at annotations. This is ready for your review again @aklausmeier!

**Comment by aklausmeier** [comment] 2024-03-22 17:19
Looks great! Left one question for Laura in Figma.

**Comment by thejordanwood** [comment] 2024-03-25 14:49
@aklausmeier Looks like Laura answered that question, so I'm going to go ahead and close this ticket. Thanks for the review!

@laflannery Thanks for adding the accessibility annotations!

cc: @xiongjaneg

**Closed by thejordanwood** 2024-03-25 14:49 UTC
Labels: VAMC, Facilities, Needs refining, Regional office, Vet Center, UX
