### ISSUE TITLE
Create a QA test plan and regression test plan for Operating Statuses

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#19808] opened 2024-11-06 18:39 UTC
## Description
We will modify Operating Statuses. We need to: 
1. Document how Operating Statuses work today in Production as a regression test plan, to ensure no regressions.
2. Create a test plan for changes in this epic. 

## Testing & QA
**Test plan is started: [#13598 Facility Operating Status expansion test plan](https://docs.google.com/spreadsheets/d/1YUa8ujmnniU8E5VzqnSn8aG9iyOjypzrRazR0nKAVbE/edit?gid=0#gid=0)** (A6 google sheets)

### Scope / Impact analysis
_What, if anything, could break as a result of this change?_

## Acceptance criteria
_ACs should capture expected behavior, to inform test plans. Consider devices, documentation updates including KBs, change management, and [content model](https://prod.cms.va.gov/admin/structure/cm_document) when applicable._

- [x] Regression test plan for Operating Statuses has been created and reviewed for accuracy with engineers & Product, including:
   - [x] Drupal behavior, within reason
   - [ ] FE behavior
- [x] Test plan for this iteration on Operating Statuses is created to cover behavior changes expected for the work

**Comment by laflannery** [comment] 2024-11-15 14:59
Drupal portion is completed I believe. [Asked Christian and Michael ](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19805#issuecomment-2479080248)if they would be able to review.

**Comment by laflannery** [comment] 2024-11-18 16:32
Front end feature testing and Regression testing have been added. I am closing this ticket because from my standpoint this is done but if other folks have any feedback/issues and feel this needs to be reopened, let me know.

**Closed** 2024-11-18 16:32 UTC
Labels: VAMC, Facilities, Needs refining, Regional office, Vet Center, sitewide, Manual QA
