### ISSUE TITLE
CMS Using VBO to update facility status updates all in the filtered results, not just the selected ones

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#11175] opened 2022-10-10 21:58 UTC
## Describe the defect
This was reported by Dave Conlon  and we need to confer with him for the process he used IF we are unable to reproduce it.

## To Reproduce
1. Go to https://prod.cms.va.gov/admin/content/facilities/facility-status
2. Filter by any value (for example: 
3.Select a couple of the results - not all
4. Attempt to changed their status
5. Notice that ALL items where changes, not just the selected. 

## AC / Expected behavior
- [ ] When you filter a set of results on the views bulk operation for facility status, and you select a few facilities from that list to change their status, only the selected facilities should have their status changed.

## Additional context
Add any other context about the problem here. Reach out to the Product Managers to determine if it should be escalated as critical (prevents users from accomplishing their work with no known workaround and needs to be addressed within 2 business days).

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS workstream (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by omahane** [comment] 2022-10-28 22:05
@davidconlon @swirtSJW I tried to reproduce this error on staging, but did not get the results that have been reported. 

- I went to `admin/content/facilities/facility-status`
- I filtered the list.
- I selected 2.
- I changed their operating status.
- Only 2 changes were made.

<img width="1531" alt="Screen Shot 2022-10-28 at 4 50 07 PM" src="https://user-images.githubusercontent.com/766573/198740274-948faa5a-cf5c-455e-96f6-1cc4fc0129cf.png">
<img width="1531" alt="Screen Shot 2022-10-28 at 4 52 23 PM" src="https://user-images.githubusercontent.com/766573/198740295-d743578d-71ce-40e2-ae2c-8ec0130b7074.png">
<img width="1487" alt="Screen Shot 2022-10-28 at 4 52 42 PM" src="https://user-images.githubusercontent.com/766573/198740330-c5caf591-4004-4264-9477-3bf5e13df2d7.png">

Could you let me know if I've missed something?

**Comment by dsinla** [comment] 2022-10-29 03:01
@omahane As a 2nd data point, I spent some time on staging trying to reproduce the error, and had the same experience as you when making edits from /admin/content/facilities/facility-status

Given the mention of views bulk operation, I tried the same exercise at /admin/content/bulk, but the actions I applied to a selected subset of a filtered list were (correctly) executed only on the selected items. I did not see the action applied to all items in the filtered list.

I tried with _Modify field values > COVID status_

<img width="644" alt="Screenshot 2022-10-28 17 51 38" src="https://user-images.githubusercontent.com/62269210/198791196-7a8f319d-9743-4ab1-861e-358f92f758b0.png">
<img width="644" alt="Screenshot 2022-10-28 19 24 47" src="https://user-images.githubusercontent.com/62269210/198791201-73f7bd5b-cbc1-4300-99c6-580e3450a858.png">
<img width="644" alt="Screenshot 2022-10-28 19 25 48" src="https://user-images.githubusercontent.com/62269210/198791386-2c78b11b-150c-470d-8e8c-9e0e2214eb08.png">
<img width="644" alt="Screenshot 2022-10-28 19 25 38" src="https://user-images.githubusercontent.com/62269210/198791252-8a8b3d4d-8704-4711-98a5-fa8c38025f79.png">

..and I tried with _Change the author of the content_ 

<img width="644" alt="Screenshot 2022-10-28 19 26 24" src="https://user-images.githubusercontent.com/62269210/198792264-548bbeca-834c-437a-8898-bed611eb6f7d.png">
<img width="644" alt="Screenshot 2022-10-28 19 26 45" src="https://user-images.githubusercontent.com/62269210/198792362-408cbdc9-050b-4a5e-8017-2123110667e4.png">
<img width="644" alt="Screenshot 2022-10-28 19 27 00" src="https://user-images.githubusercontent.com/62269210/198792470-cd428657-9313-4800-b515-c27d1b638d88.png">

Is it possible this defect may only show on Production?

**Comment by dsinla** [comment] 2022-11-01 17:05
@omahane @dawnpruitt 
Will review on Thursday 11/3 scrum with Dave C

**Comment by omahane** [comment] 2022-11-03 16:24
@dsinla Based on a recent unsuccessful attempt to recreate this issue @davidconlon has suggested we close this.

**Comment by dawnpruitt** [comment] 2022-11-04 10:57
Scrum 11/3: Worked with PO to reproduce. He advised we close this ticket as unable to reproduce/not found.

**Closed by dawnpruitt** 2022-11-04 10:57 UTC
Labels: Defect, ⭐️ Facilities
