### ISSUE TITLE
Editors can choose a field_office option for a Staff Profile that breaks content-release

### ISSUE THREAD

**Issue by omahane** [department-of-veterans-affairs/va.gov-cms#12997] opened 2023-03-17 00:46 UTC
## Describe the defect
When an editor chooses a field_office ("Related office or health care region") option for a Staff Profile that does not have a matching sidebar, content release fails.

## To Reproduce
1. Create a Staff Profile
2. Choose "VHA" as the Related office or health care region
3. Notice that content release fails

## AC / Expected behavior
- [ ] ~I expect if the entity reference of field_office is a VAMC System, then look for a menu. If it is not a system, do not look for a menu~
- [x] Sidebar menu is not linked for `person_profile` pages

## Build Log
[2023-03-16_Build_borked.txt](https://github.com/department-of-veterans-affairs/va.gov-cms/files/10996832/2023-03-16_Build_borked.txt)

 ## Additional context
https://dsva.slack.com/archives/C02VD909V08/p1679001859608059

It's likely that we need to reduce the options in field_office in any content type that uses it, not just Staff Profile. Some research is necessary here.

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS workstream (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [x] `Facilities`
- [ ] `User support`

**Comment by kmariepat-cityfriends** [comment] 2023-03-23 16:47
Grooming Notes:
- This is a content build issue 
- no existing defensive check on the content build step

**Comment by kmariepat-cityfriends** [comment] 2023-03-23 16:56
Next Steps: 
- content build shouldn't break inform CMS teams
- What is the user experience supposed to be for a CMS user, if something is in multiple areas where does that page get built (Spike to determine if we need to defensive about this or not?)

**Comment by jilladams** [comment] 2023-06-01 17:09
Underlying issue here broke content-build again today: https://dsva.slack.com/archives/C0FQSS30V/p1685637612473119. Would be nice to prioritize this if we can.

**Comment by stefaniefgray** [comment] 2023-06-02 00:45
## Related details behind the 6/1/2023 content release failure:

- The editor revised this individual’s Staff Profile and reassigned the “Related office or health care region” field from Iowa City to St. Cloud: https://prod.cms.va.gov/node/11310/revisions/776062/view

- The page now says St. Cloud in the browser task bar, while the URL still says Iowa City.

- The mismatch happened between the "Related office or health care region" field (which the editor should not be able to edit, once published -- see permissions notes and screenshot below) and the right-side menu "Section" field

## Permissions notes:
Per VHA Digital Media, Staff Profile re-assignments (i.e. from VA Atlanta to VA Pittsburgh) need to be run by them and approved first.

Only the VA Drupal CMS Support team should be moving Staff Profiles between VAMC sections, once we’ve received approval to do so.

## Screenshots:

![Screen Shot 2023-06-01 at 2 20 27 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/9059428/34bd192d-58bf-43a4-835b-ea6bbde5969a)

### Here's where you can see the mismatch between St. Cloud in the "Related office or health care region" field and Iowa City in the "Section" field:

![Screen Shot 2023-06-01 at 2 22 19 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/9059428/8e994ea9-bb1e-4468-85cb-6cb3fa58da7f)

**Comment by davidmpickett** [comment] 2023-06-02 16:04
This is a restatement of what others have said before, but just to be clear. There are at least three separate issues here that may need to be resolved:

1. No winnowing logic to remove invalid options from field_office dropdown. Logging in to Staging as justin.hardt@va.gov I can these options that don't seem intended:
 
![Screenshot 2023-06-02 105743](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/71e03bae-9208-4562-93fb-c10bf9d303c1)

2. No validation to check field_office and Section match. (Not that Justin could have selected the correct section anyway.)

![Screenshot 2023-06-02 110107](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/bbf8cb62-26be-435c-9b8c-26e10b65873c)

3. Might want to prevent editors from changing both field_office and section once published and require this to be an admin action since that's the requested process from VHA DM.

**Comment by omahane** [comment] 2023-06-07 14:51
@kmariepat-cityfriends Given the conversation on this ticket, I'd say we still have more refinement to do here.

**Comment by swirtSJW** [comment] 2023-06-14 18:30
Overall, with the constraints on how Staff profiles work, I do not think this is a CMS issue/fault. 
The requirements on staff profiles are varied:

- Staff profiles can be selected for display on any and multiple leadership list pages (COPE)
- Staff profiles only have a page of their own IFF they have a box checked and the bio field is not empty.
   - Only one profile page is built even if the person appears on more than one listing page. 
   - Where the page gets built (the url) depends on the system or office selected on the profile node, which may have no relation to what listing pages the person appears on (which is why we use a back button type link on the FE)
- Related office can assigned to a VAMC systems OR it can be Offices. 
- Sections are not related to field office (can not / should not be winnowed)  Section only determines who can edit the profile.


I think the defect that breaks the build is actually a front end defect.  The front end it making the assumption that if it has a field_office, it must have a system menu and then is looking for a system menu that does not exist.  This needs to be defensive on the FE.  If the entity reference of field_office is a VAMC System, then look for a menu.  If it is not a system, do not look for a menu.

**Comment by swirtSJW** [comment] 2023-06-14 18:48
@davidmpickett called out three things that might need improving:

> No winnowing logic to remove invalid options from field_office dropdown. Logging in to Staging as [justin.hardt@va.gov](mailto:justin.hardt@va.gov) I can these options that don't seem intended:

This was intentional.  Unlike most other things in the VAMC product, this particular content type there is no parity required between field office and field_administration.  A person could be at the VISN level or some other office but the maintenance of their profile could be assigned to an editor at a system because that is where their particular brick and mortar office is.

> No validation to check field_office and Section match. (Not that Justin could have selected the correct section anyway.)

Can't validate and prevent save if parity is not required. (see above)

> Might want to prevent editors from changing both field_office and section once published and require this to be an admin action since that's the requested process from VHA DM.

People change jobs, roles and locations all the time.  Editors ought to be able to account for that without needing admin intervention.

**Comment by davidmpickett** [comment] 2023-06-14 18:56
> Editors ought to be able to account for that without needing admin intervention.

This is a great principal to aspire to, but that does not erase the fact that the VHA has specified they want staff profile changes to be governed and we have not actually implemented that process. IMO this is a product defect.

**Comment by davidmpickett** [comment] 2023-06-14 18:59
> This was intentional.

So editors should be able to select "[Test data] My test office"?

**Comment by swirtSJW** [comment] 2023-06-14 20:06
> So editors should be able to select "[Test data] My test office"?

LOL  That is just instances of an office created by the tests when they run on staging after staging is built.   Tests don't run on prod.

**Comment by swirtSJW** [comment] 2023-06-14 20:12
> This is a great principal to aspire to, but that does not erase the fact that the VHA has specified they want staff profile changes to be governed

Eek.  Governed by who?  I am guessing editorial govern.... not an admin govern. I am guessing ...err hoping this is more like a workflow "ready for approval" thing than a send this over to Facility Team admin for request fulfillment thing.

The other thing we'd have to account for is that this content type is not specific to VHA.

**Comment by davidmpickett** [comment] 2023-06-14 21:34
> > This is a great principal to aspire to, but that does not erase the fact that the VHA has specified they want staff profile changes to be governed
> 
> Eek. Governed by who? I am guessing editorial govern.... not an admin govern. I am guessing ...err hoping this is more like a workflow "ready for approval" thing than a send this over to Facility Team admin for request fulfillment thing.
> 
> The other thing we'd have to account for is that this content type is not specific to VHA.

Per [the KB article](https://prod.cms.va.gov/help/vamc/how-to-edit-or-add-a-staff-profile#undefined), any change of a staff member moving between VAMC health care systems & sections is supposed to be managed via a helpdesk request. This has been the case [since late 2021](https://prod.cms.va.gov/node/6923/revisions/577091/view) based on revision history.

Other key moments in the KB article that indicate the intended product behavior here: 
- "You can only edit a staff profile that is managed by your system - the staff member is primarily located at your health care system"
- "If you don't have an Edit button next to a particular profile, it is managed by a different section."

**Comment by jilladams** [comment] 2023-06-14 23:05
I'm getting lost in the comments sauce here -- am I right on 2 takeaways: 
1. This ticket should convert to become a FE defensive fix that prevents breaking the build? 
2. We need to file a ticket for getting CMS behavior aligned with governance?

**Comment by davidmpickett** [comment] 2023-06-15 02:16
> I'm getting lost in the comments sauce here -- am I right on 2 takeaways:
> 
> 1. This ticket should convert to become a FE defensive fix that prevents breaking the build?
> 2. We need to file a ticket for getting CMS behavior aligned with governance?

I had a detailed comment explaining why I am now not convinced # 2 is needed, but then I clicked a link and lost the draft. In summary the CMS does match governance policy, it's just confusing.

**Comment by davidmpickett** [comment] 2023-06-15 02:37
> * The editor revised this individual’s Staff Profile and reassigned the “Related office or health care region” field from Iowa City to St. Cloud: https://prod.cms.va.gov/node/11310/revisions/776062/view

This is actually not the change that broke Content Release. It's just another very similar error that had a revision published within 10 minutes of the one that broke Content Release. 🤪

https://prod.cms.va.gov/node/7798/revisions/view/706274/776237/split_fields

![screencapture-staging-cms-va-gov-node-7798-revisions](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/4913a246-01c0-4791-ae93-227cfb9b0734)

![screencapture-staging-cms-va-gov-node-11310-revisions-view-706545-776224](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/5dc5da5e-4746-48c6-9c79-040af745c459)

**Comment by swirtSJW** [comment] 2023-06-15 16:32
The reason helpodesk has to be involved in changing system to system is that they can update the alias for the page, no one else can.

**Comment by jilladams** [comment] 2023-06-15 16:37
Breaking build again today: https://dsva.slack.com/archives/C02730UEZPS/p1686846788732199

**Comment by kmariepat-cityfriends** [comment] 2023-06-15 16:38
Next Steps: Check on capacity with @maxx1128

**Comment by jilladams** [comment] 2023-06-20 23:38
From Fri scrum: @maxx1128 has been working on a fix.
From today scrum: in order to test & verify the fix, have to recreate the failure scenario. WIP.

**Comment by maxx1128** [comment] 2023-06-23 21:21
I was able to recreate the failure scenario properly and have left instructions on how to do it locally in the pull request. I wrote a fix and confirmed that it fixed the build locally, so I have put the pull request up for review.

I'm going to be on PTO from 6/26 to 7/7, so if it has enough approval to merge during that time then someone else from Facilities should be good to merge it instead 👍

**Comment by jilladams** [comment] 2023-06-26 21:50
@ryguyk I added you as assignee here just to help us both keep an eye on this til sprint closeout / you move over to AP, since Max is out for the remainder. If you come across concerns during code review, holler, and we can help work out priority among your other sprint tasks re: whether you should iterate the PR over other assigned work, or it can/should wait til Max is back. (fyi @kmariepat-cityfriends )

**Comment by jilladams** [comment] 2023-06-29 15:25
From scrum: 
* We think this fix is a net improvement.
* It does create some tech debt we want to fast follow to fix.
* @ryguyk to create a new ticket to document the IA / architectural questions that have come up out of this PR

**Comment by jilladams** [comment] 2023-06-29 21:07
From 1:1 with Ryan (FYI @kmariepat-cityfriends / @mmiddaugh ): 
* After more debugging here, Ryan determined we cannot just merge the PR as is, it will break rendering the menu on all facility pages. 
* Of the 3 tickets left for Ryan in sprint, his head is deepest in this one already. I've advised him to keep at it to get this fix over the line, in service of preventing breaking content build. 
    *  The 2 tradeoff tickets that might not make it now are #12063 & #12085 

Please advise if any concerns.

**Comment by ryguyk** [comment] 2023-07-05 14:41
This ticket was completed in Sprint 87.

**Closed** 2023-07-05 14:41 UTC
Labels: Defect, VAMC, VA.gov frontend, Facilities
