### ISSUE TITLE
Renew Tugboat Certificate 

### ISSUE THREAD

**Issue by maortiz-27-80** [department-of-veterans-affairs/va.gov-cms#16484] opened 2023-12-19 14:17 UTC
## User Story or Problem Statement
The certificate for tugboat.vfs.va.gov is going to expire in 45 days (February 2, 2024). This certificate must be renewed and installed before it expires.

## Description or Additional Context 
[Link to list of available actions and info](https://vaww.certmgr.va.gov/aperture/certificate/%7B112482ed-d6e5-46c3-8ec2-c019d1a1c926%7D).

## Team
Please check the team(s) that will do this work.

- [X] CMS Team
- [ ] Public Websites
- [ ] Facilities
- [ ] Accelerated Publishing

cc: @BerniXiongA6 @EWashb @ndouglas

**Comment by ndouglas** [comment] 2023-12-19 19:14
Duplicate of #13632.

**Closed by ndouglas** 2023-12-19 19:14 UTC
Labels: Needs refining, CMS Team
