### ISSUE TITLE
Increase traffic gate from 25% to 50% from Virtual Agent Chatbot Team

### ISSUE THREAD

**Issue by ianpsant** [department-of-veterans-affairs/va.gov-cms#8766] opened 2022-04-12 17:03 UTC
### Engineering support for:
- Redirects that have **first been vetted by the Platform Product Support team**. If you are requesting a redirect, please submit the [Redirect Issue Template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=vsp-product-support%2C+ia&template=redirect-request.md&title=Redirect+Request)
- REACT sign-in widgets or feature flags (flipper)
- Other engineering support from the Public Websites Team

**Note:** Apps teams engineers are responsible for flipper implementation related to their products. Our engineers can provide consultation as needed. [Read feature toggle documentation](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/platform/tools/feature-toggles/)

## How to submit your request

- [X] Complete each area of this intake form that applies to your team's needs. Provide as much detail as you can so we can fully understand your request.  
- [X] Post a link to this issue: [#vsa-public-websites](https://dsva.slack.com/channels/vsa-public-websites), and in slack tag @brianalloyd, @kelsonic.    
- [ ] If noted in the guidance below, please schedule any relevant meetings.

### When to submit your request

Please submit all engineering requests **at least 1 full sprint in advance** (so we can work it into our next sprint).

---

## About your app/tool/functionality

**Is this request related to a VA.gov tool? If yes, provide a brief description of the tool or functionality:**  

  - Previously we worked with the Public Websites to implement a react widget that would display a link to the Virtual Agent Chatbot page (https://www.va.gov/contact-us/virtual-agent/) on the Contact Us page to 25% of unauthenticated traffic.
  - We want to increase the percentage of people who see the link from 25% to **50%** for **April 25th release**.
  - The April 25th release is tentative and we'd want to work closely with the Public Websites team to give the Go / No Go on releasing this update for the 25th or whatever the date turns out to be.

**Provide links to any available collateral: **Please link to existing IA requests**, product briefs/outlines, wireframes, prototypes, user research synthesis:** 
  - department-of-veterans-affairs/va.gov-team#36319
  - PR: https://github.com/department-of-veterans-affairs/vets-website/pull/20280

---

## About your support needs
*Please select all that apply, and follow related guidance.*        

### Frontend engineering support 

   
- [ ] **Implementation of REACT sign-in widgets**
   * **Full spec including different states and behaviors:** 
     - < link to spec >
   * **Flipper unique id:** 
     - < unique id >
     
 - [ ] **Support for UAT testing or phased roll out of app/tool landing page**
    * **Full spec including different states and behaviors:** 
      - < link to spec >
    * **Flipper unique id:** 
      - < unique id >

**Note:** Apps teams engineers are responsible for flipper implementation related to their products. Our engineers can provide consultation as needed. [Read feature toggle documentation](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/platform/tools/feature-toggles/)

- [X] **Other**

Increase existing react widget throttle from 25% to 50% of unauthenticated traffic from seeing the link to the Virtual Agent Chatbot.
Example of previous implementation: https://github.com/department-of-veterans-affairs/va.gov-team/issues/36319
      
### Desired/target implementation date

What's the ETA for the app/tool launch or the date when you need this request completed? Our team's capacity will determine which sprint the work falls into.

Monday, April 25

**Note:** As a best practice, PW does not release new products over weekends or holidays. Please plan accordingly. 

---

### About your team

- Team name: Virtual Agent Chatbot
- DEPO product owner: Luciana Morais
- Product manager: Ian Santarinala
- Designer: Patrick Onesty
- FE engineer: Jacob Gacek
- Product/team Slack channel: #va-virtual-agent-public

--- 
#### Acceptance Criteria
- [ ] Convert this request into a Zenhub epic
- [ ] Follow-up with requestor to address any lingering questions/concerns
- [ ] Create epic/tickets as needed for the Public Websites team to implement

#### Definition of Done
* Request ticket is closed and implementation tickets created as needed - **If you have content requests, please fill out the content [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/sitewide-content-intake-form.md)**

**Comment by jilladams** [comment] 2022-04-14 18:15
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VAgov-CMS-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/8766?planning-poker) with ZenHub @ryguyk @allisonlu

**Comment by jilladams** [comment] 2022-04-25 18:22
Per sprint planning: may be as simple as flipper access, request in Platform Support (for PW team members)

**Comment by jilladams** [comment] 2022-05-02 16:08
This is scheduled in our current sprint ending Friday. We are hoping to knock it out early this week and will let you know on ticket once the change is confirmed.

**Comment by jilladams** [comment] 2022-05-04 18:10
I have access to Flipper settings as of today. However, this feature isn't easily identifiable in the list. 

- In issue #36319 the feature is identified as React app data-widget-type="contact-chatbot-cta".
- In the PR, https://github.com/department-of-veterans-affairs/vets-website/pull/20280/files, we have `show_contact_chatbot` as the feature toggle
- In vets-website master branch, this appears on line 94: https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/platform/utilities/feature-toggles/featureFlagNames.js#L94
- However: in the list of Features for flipper, `show_contact_chatbot` doesn't appear, or any other reference to contact chatbot: 
    - Prod: https://api.va.gov/flipper/features
    - Staging: https://staging-api.va.gov/flipper/features

I suspect this is just something I'm unfamiliar with how to find. @ryguyk, any chance you can help me poke around and find it today? 

Unrelated probably but since I poked at it: There are a few other references to virtual agent things, that seem to be unrelated and are all disabled.
https://api.va.gov/flipper/features/virtual_agent_token
https://api.va.gov/flipper/features/virtual_agent_auth
https://api.va.gov/flipper/features/virtual_agent_bot_a

**Comment by jilladams** [comment] 2022-05-04 19:36
Finding: this toggle isn't using Flipper and requires a code change, so reassigning to Ryan.

Slack thread: https://dsva.slack.com/archives/C52CL1PKQ/p1649783390721569

**Comment by ianpsant** [comment] 2022-05-05 16:32
@jilladams @wesrowe After speaking with my Product Owner, if this is still going to be ready this Friday, we'd prefer to release it on Monday, May 9th. Let me know if there are any issues with that. Thanks!

**Comment by allisonlu** [comment] 2022-05-06 22:58
PR opened and approved: https://github.com/department-of-veterans-affairs/vets-website/pull/21002

I'll merge this first thing on Monday so it can go out with the daily deploy.

**Closed** 2022-05-09 15:35 UTC
Labels: ⭐️ Public Websites, vsa-public-websites-intake

**Comment by jilladams** [comment] 2022-06-13 19:32
FYI @allisonlu that Ian flagged via Slack dm that their team needs this live by EOD Thursday latest, in order to have at least one day to monitor prior to the weekend. (Earlier in the week preferred, if possible, but not critical.) Let me know if that poses issues for us.
