### ISSUE TITLE
VBA RO preview observations to address before launch

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#16901] opened 2024-01-18 17:55 UTC
## Description
This is a placeholder ticket to capture questions or comments about VBA RO pilot MVP before launch. Subsequent tickets may need to be stubbed from these observations.

## Preview observations, _resolved as of 3.25.2024_

- The VA benefits hotline number is displayed as VA benefits hotline: 800-827-1000, ext. 4023022840 in the FE and in the data. I'm not entirely sure where the extension came from. There is no extension on the [VBA Regional Offices website](https://www.benefits.va.gov/benefits/offices.asp).  
- Get updates box has a blank spot and is not rendering the "Subscribe to our newsletter" link in the data

## Screenshots

<details> 
<summary> Screenshots of the VA benefits hotline number </summary>

![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/55411834/ad21b4a5-7458-41a5-b42a-5d69320d50e7)

</details>

<details> 
<summary> Get updates screenshots  </summary>

![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/55411834/f9da2807-bc08-4062-b85f-f9c1f8e1ce71)

</details>

**Comment by mmiddaugh** [comment] 2024-01-19 15:39
Not sure if the "Other nearby VA locations" part has been wired yet - the heading renders but no locations are included. 
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/55411834/43f92f27-f42f-42d4-9528-f64fb77cc4a5)

**Comment by mmiddaugh** [comment] 2024-01-19 15:56
I'm not sure this help text is entirely meaningful but it could benefit from a space between to and local in any case. 
<details>
<summary> Screenshot </summary>

<img width="820" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOG5nQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7d9a1868f413b86256f879a9a3706b94c962c172/image.png" alt="image.png" />

</details>

**Comment by mmiddaugh** [comment] 2024-01-19 16:46
@laflannery - Does "Can't find the service you're looking for?" have the correct heading level? I did not expect it to have a jumplink - it seems out of place to assume at the top of the page that I can't find what I am looking for.... 
Perhaps it's because the Services header and service accordions aren't yet present in this preview?
[Preview staging link](http://preview-staging.vfs.va.gov/preview?nodeId=4352)

<details>
<summary> Screenshot </summary>

<img width="394" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd2ZoQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7143fe80d1b4ded91c4ae2286f50eacf21f4c669/image.png" alt="image.png" />
</details>

**Comment by laflannery** [comment] 2024-01-19 17:01
@mmiddaugh So it is but I don't disagree with you about the anchor link, here's my problem:

I originally, based on what I was seeing [from Sketch](https://www.sketch.com/s/891d33ae-152d-471c-ab5d-9aedf89cf6ff), said this should be an H3. Which meant it would NOT show in the "On this page" list. My reasoning was that it was a child of "Other services" which made sense to me:
<img width="496" alt="Screenshot 2024-01-19 at 11 55 02 AM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/106678594/15d130b1-ad7f-4cf7-a306-e3ae61fe3c4a">

However, I did just ask this to be updated to an H2 because [the logic I though was built into this block was not what I thought](https://dsva.slack.com/archives/C0FQSS30V/p1704905199967209?thread_ts=1704833678.355239&cid=C0FQSS30V). This block just shows if it's added into the CMS and when an example page was created a saw an instance that didn't make sense to me - where "Can't find the service you're looking for?" was a child of "Veteran Benefits". To me those two things felt more like siblings, not parent and child, especially if this can show anywhere under any accordion section. That was why I asked for this to change to an H2, the consequence of that is not it's in the "On this page".

Questions:
- Was my sibling vs parent/child relationship decision accurate? Maybe I am misunderstanding and it actually is parent/child regardless of where it shows up.
- If the heading level is correct as an H2, maybe there is a way we can exclude this particular heading from "On this page". We could ask the engineers if that's possible?

Let me know if you want to sync on this because I realize that was a lot of info.

**Comment by mmiddaugh** [comment] 2024-01-30 20:29
@laflannery and I are on the same page about "Can't find what you're looking for" 
- the link is an escape hatch with the same weight as the service categories - which dictates an H2 
- being an H2 means it will get a jump link, even if it's a little awkward 

The good news is that it will can serve Veterans and other beneficiaries who need additional help, whether they realize they need it at the top or bottom of the page.

**Comment by davidmpickett** [comment] 2024-03-28 01:36
> I'm not sure this help text is entirely meaningful but it could benefit from a space between `to` and `local` in any case. (_It may make sense to address this as part of Review error states recommendations and feasibility for VBA content types #16906_)
> 
> Screenshot

We are currently unable to change the interface text in this section. This is a [CMS Team issue](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16452) that would need to be resolved. 

The issue with the spacing seems to be a regression. "to" and the following label are actually entirely separate elements. If you highlight them, you can see there are two overlapping highlights. 

![Screenshot 2024-03-27 at 8 25 11 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/e557b430-dc96-4fc2-97a2-e6631deab909)

They were properly spaced back in December as seen in my screenshot on the linked issue.

![290887746-0fc02e7e-4be1-406c-8381-2899164dfeaa](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/861d307f-2ae2-4814-ae4a-41a19c1056ca)

This regression is not specific to Facilities, as it can be seen in on similar interfaces on Public Websites. For instance, Resources and Support Detail page content type.

![Screenshot 2024-03-27 at 8 26 35 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/dc7e9196-53b9-4060-aa2d-82e449a0fd86)

![Screenshot 2024-03-27 at 8 34 14 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/028dd04e-ede8-4553-9550-da1e5aa63637)

**Comment by mmiddaugh** [comment] 2024-03-29 20:59
see also: "Additional Hours Options" shows as Italics on VBA #17686

**Comment by jilladams** [comment] 2024-04-11 23:13
I'm looking through VBA stuff and came across this ticket for the first time. Can y'all confirm that the intent here is that any feedback out of Editor training sessions comes here for review / to be ticketed? 

If so, I think Dave's comment 2 up is a dangler with no ticket? https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16901#issuecomment-2024244708

In the spirit of simplifying onboarding / expectations for a new PM, how would you feel about us closing this and just cutting new tickets for anything identified during sessions? (@laflannery @mmiddaugh )

**Comment by laflannery** [comment] 2024-04-11 23:23
I'm not actually sure what the original intention of this ticket was here tbh. I personally agree with your idea of just making individual tickets though, I think that's easier than a group ticket approach like this.

**Comment by davidmpickett** [comment] 2024-04-12 00:42
Spun out my comment into a separate ticket so this can close https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17831

**Closed by davidmpickett** 2024-04-12 00:42 UTC
Labels: Facilities, Needs refining, Regional office, product
