### ISSUE TITLE
Injected header: Add linting to prevent potential issues with TeamSites

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#11256] opened 2022-10-19 03:25 UTC
***BLOCKED - We recommend no-op (import components instead) ***

## Description

It was proposed during a recent Post-Mortem that there may be a role for linting to play in preventing breakages of the injected header or footer.

See [comment below](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11256#issuecomment-1284510481). Only do this if you're _not_ planning to do #11260.

`Warning: Please be aware that your changes to the header may break the injected header on TeamSites. Follow proxy-rewrite steps to test the injected header scenario: https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite#local-dev.`

## Acceptance Criteria

- [ ] Review recent postmortems for additional files not owned by PW FE where this warning should ideally be added
- [ ] Implemented eslint rule to watch header/nav-related files for any changes and automatically create a comment on the PR

**Comment by ryguyk** [comment] 2022-10-19 20:02
My first thought is that linting could possibly check for the use of web components in files related to the header. A linting error could trigger when a web component is attempted to be called. This hinges heavily on what is decided with #11260. Such a linting error would not make sense if we end up fetching the web-component library when the header is injected. Together, these two tickets are dependent on a larger, more general question - do we want to allow for the use of web components in the header?

**Comment by wesrowe** [comment] 2023-04-19 18:59
Refined this as a first-step to reduce issues caused by header changes.

**Comment by jilladams** [comment] 2023-05-05 19:56
This ticket is dependent on #11260, which we didn't realize / remember during planning. We have capacity at this point to begin one or the other, so removing this in favor of that ticket.

**Comment by wesrowe** [comment] 2023-06-30 18:02
Team determined (several sprints ago actually) that importing all web components into the injected header would be a performant and more foolproof approach. Closing this as a no-op.

**Closed by wesrowe** 2023-06-30 18:02 UTC
Labels: VA.gov frontend, Blocked, Public Websites, Injected header
