### ISSUE TITLE
Top Task Pages: "Main Phone" field blank on front end for VAMC Medical Records and Register for Care pages

### ISSUE THREAD

**Issue by stefaniefgray** [department-of-veterans-affairs/va.gov-cms#14586] opened 2023-08-01 02:04 UTC
## Describe the defect
As an editor working on **VAMC System Medical Records Office** and **VAMC System Register for Care** pages for my section, I need to add linked **VAMC Facility Non-clinical Service** nodes reflecting the address, hours, and contact info for Medical Records and Register for Care offices at individual facilities.

When adding facility-specific Medical Records and Register for Care office information, there is a checkbox with the option `Use the general facility phone number.` Users also have the option to add additional phone numbers, if needed.

However, the “Main phone” field for each facility isn’t showing up on the published Medical Records and Register for Care pages regardless of whether or not this box has been checked, or whether any additional phone numbers have been added.

## To Reproduce
1. Go to an existing VAMC System Medical Records Office or VAMC System Register for Care node such as https://staging.cms.va.gov/poplar-bluff-health-care/locations/john-j-pershing-veterans-administration-medical-center/register-for-care
2. Click "Edit locations at this facility (opens in a new window)" to taken to where you can edit the associated VAMC Facility Non-clinical Service node for a particular clinic.
3. Expand the "Contact Info" accordion and find the `Use the general facility phone number` checkbox 
4. Check the checkbox
5. Save the page
6. Check out the Preview if on Staging, or if observing this issue on Prod, go to the published page.
7. The "Main Phone" header displays, but the field itself is blank.

## AC / Expected behavior
When the `Use the general facility phone number` checkbox is checked on a VAMC Facility Non-clinical Service featured within a VAMC System Medical Records Office or VAMC System Register for Care node, then the "Main Phone" field should display the main phone number for that facility instead of being blank.

## Screenshots

<img width="360" alt="Screen Shot 2023-07-31 at 2 31 04 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/9059428/f03c7954-74d5-4b47-a1b9-e62a180875e1">

<img width="299" alt="Screen Shot 2023-07-31 at 2 31 23 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/9059428/6bddbd66-acc8-4d97-95ae-29ffd947c467">

 ## Additional context
Should be prioritized since this affects patients seeking access to medical records and registering for care

See Slack thread from #facilities-support: https://dsva.slack.com/archives/C02730UEZPS/p1690835620274939

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS workstream (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [x] `Facilities`
- [ ] `User support`
- [ ] `Accelerated Publishing`

**Comment by stefaniefgray** [comment] 2023-08-01 02:08
Tagging @jilladams and @Dottisea

**Comment by mmiddaugh** [comment] 2023-08-01 20:34
Ryan resolved a similar issue before moving to AP: Inconsistent displays for phone numbers within VAMC health service accordions #13705

**Comment by maxx1128** [comment] 2023-08-03 18:57
I have confirmed through some local testing that the cause is the `fieldPhoneNumber` field is empty (the below screenshot shows the raw data output from my local machine). The component only checks if the "Use the general facility phone number" checkbox has been clicked, but not if there's also a facility phone number that has been selected.

<img width="399" alt="Screen Shot 2023-08-03 at 2 54 49 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/10790736/7c82ad3d-b886-4070-99d8-b5a85daa7683">

I think there are two approaches to fixing this:

1. **If `fieldPhoneNumber` is mandatory,** this is a CMS change. It either needs to be marked as required in the CMS or, if it already is, confirm it's being saved under the correct property name.
2. **If `fieldPhoneNumber` is not mandatory,** this is a front-end change. The template needs to check for both the checkbox being checked and the phone number being present, otherwise, it skips showing the Main Phone section altogether.

**Comment by jilladams** [comment] 2023-08-08 15:25
@maxx1128 to connect with @swirtSJW @omahane async for plan.

**Comment by maxx1128** [comment] 2023-08-08 18:03
> @maxx1128 to connect with @swirtSJW @omahane async for plan.

I have our [async Slack thread for the plan link here.](https://dsva.slack.com/archives/C0FQSS30V/p1691517487415189) cc: @jilladams

**Comment by stefaniefgray** [comment] 2023-08-09 01:17
Thank you everyone! You rock @maxx1128 🎸

**Comment by stefaniefgray** [comment] 2023-08-09 01:17
Will update original reporting editor in https://va-gov.atlassian.net/browse/VAHELP-6187 once resolved

**Comment by mmiddaugh** [comment] 2023-08-09 14:34
This is not unique to this location. It can be observed on Pittsburgh's [Register for care](https://www.va.gov/pittsburgh-health-care/register-for-care/) and [Medical records](https://www.va.gov/pittsburgh-health-care/medical-records-office/) pages.

**Comment by mmiddaugh** [comment] 2023-08-09 16:26
For contrast: [Eastern Kansas](https://www.va.gov/eastern-kansas-health-care/register-for-care/) 

<details>
<summary> does not check the "use facility phone number" option and is behaving as expected </summary>

![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/55411834/8a3f1922-303d-41c1-bc3a-e40e49ce9f1a)

![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/55411834/5376ad4d-e2b6-40c1-aa43-63df99848864)

</details>

**Comment by swirtSJW** [comment] 2023-08-09 17:47
@maxx1128 When the box is checked, to use the main facility number, that number does not live on the non-clinical service entity or on the Medical Records entity, it lives on the facility entity which ought to be in that data through the entity reference on the non-clinical entity in the query (or will need to be added)
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/06efc893-e35d-4ee9-bcaf-22b26d65f4e5)

The other option is to grab it from the full data object that should have all the facilities.

**Comment by jilladams** [comment] 2023-08-16 16:55
Assigning Eli to help finish out QA steps / discussion with Swirt for getting this PR merged.

**Comment by eselkin** [comment] 2023-08-29 14:58
PR: https://github.com/department-of-veterans-affairs/content-build/pull/1661
The QA steps were followed in that PR and merged.
Currently on prod

**Comment by stefaniefgray** [comment] 2023-08-29 18:42
Appears resolved on prod per https://www.va.gov/poplar-bluff-health-care/register-for-care/ and https://www.va.gov/pittsburgh-health-care/register-for-care/

as well as per https://www.va.gov/pittsburgh-health-care/medical-records-office/ and https://www.va.gov/poplar-bluff-health-care/medical-records-office/

Thank you, @eselkin !!!

**Comment by stefaniefgray** [comment] 2023-08-29 18:44
Have notified original reporting editor @ VA Poplar Bluff that this issue is now resolved

**Comment by jilladams** [comment] 2023-08-29 19:21
Closing.

**Closed by jilladams** 2023-08-29 19:21 UTC
Labels: Defect, VAMC, VA.gov frontend, Facilities, Sprint goal
