### ISSUE TITLE
Typography Audit Issue: Injected Header/Footer

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#18087] opened 2024-05-08 21:38 UTC
## Status
**[2024-05-09]** Fran needs to discuss with the DST on if they have options to fix this issue.

## Description
From Phase 1 of the Typography audit, a couple issues were found in the injected Header/Footer that should be looked at:

1. At this point in time, it looks like we have 2 issues; one major and the other minor

- Minor: the spacing between the footer links and the pipes that separate them. Production's spacing is wider than the new version:
**Current Prod**
![Screenshot 2024-05-08 at 4 10 56 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/106678594/5c7ab6d7-d739-4022-9c34-c372f1a7b612)

**Typography PR **
![Screenshot 2024-05-08 at 4 11 00 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/106678594/38c04672-f73a-4ab9-bb87-72e082fe894c)

- Major: everything on the modal has been scaled down on the PR
**Current Prod**
![Screenshot 2024-05-08 at 4 12 57 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/106678594/a08cb206-25d2-4a45-8ba1-a7a3ceb6b4cb)

**Typography PR **
![Screenshot 2024-05-08 at 4 12 46 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/106678594/69ec42fd-a38c-4694-89cd-e8770a26b8e0)
**Video**

https://github.com/department-of-veterans-affairs/va.gov-cms/assets/106678594/4786ae9c-4c99-4cfc-a2b5-8a26dea9e9ce

## Acceptance Criteria
- [ ] Determine path forward on how to resolve
- [ ] Resolve?
- [x] Requires design review

**Comment by randimays** [comment] 2024-05-13 19:14
I took a look at the injected header/footer locally. 

### Solved issues
The typography scaling issue on the VCL modal has been fixed. ✔️ 

### Remaining issues
1. The minor issue for pipe spacing on the footer links is still there; though it really is minor so we can decide as a team whether that needs addressing.
<img width="427" alt="Screenshot 2024-05-13 at 2 04 22 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/19175324/e8fe67cd-4de8-499f-aa22-a62aa41b7b08">



2. Max-width of the modal: because the base font size on Teamsites is smaller than VA.gov, the rem calculation is doing different things. Teamsites has an explicit 10px font size set on the html element, and an explicit 12px font size set on the body tag. This code (https://github.com/department-of-veterans-affairs/vets-website/blob/a00730937731c843d8aeba6d446d97eb369affb0/src/applications/proxy-rewrite/proxy-rewrite-entry.jsx#L115) predates our team, so I'm not sure why this is the case.

**Local** Teamsites:
<img width="400" alt="Screenshot 2024-05-13 at 1 53 42 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/19175324/01fd4a05-979b-4ada-aa14-4256291981b5">

**Prod** Teamsites:
<img width="400" alt="Screenshot 2024-05-13 at 1 53 46 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/19175324/c2c0c52c-0429-4d4c-bca6-dfc64a2dc45d">

**Comment by aklausmeier** [comment] 2024-05-13 20:30
@randimays Injected footer links spacing. This looks fine, no fix needed from a design review standpoint.

**Comment by randimays** [comment] 2024-05-13 20:49
@aklausmeier Here's what the VCL modal looks like on Teamsites at the mobile breakpoint

<img width="320" alt="Screenshot 2024-05-13 at 3 48 36 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/19175324/bc6e02af-95c6-4199-a75c-e356e0803e37">

**Comment by aklausmeier** [comment] 2024-05-13 20:51
Those last two appear to now be centered text instead of left aligned.

**Comment by aklausmeier** [comment] 2024-05-13 20:52
@randimays honestly if we can get those last two to be left aligned in all breakpoints, this ticket looks good from a design review standpoint

**Comment by aklausmeier** [comment] 2024-05-13 21:54
I checked off design review for typography audit only as the text alignment will be addressed in future injected H/F tickets. 

cc @FranECross @jilladams @randimays

**Comment by FranECross** [comment] 2024-05-13 22:58
Note from Randi M in Slack [thread](https://agilesix.slack.com/archives/C05Q7J61NR5/p1715632447144389?thread_ts=1715625917.823179&cid=C05Q7J61NR5): The only issue I see is a VCL modal width issue caused by the 10px/12px font sizes set on Teamsites specifically. I'm not sure it's worth asking DST to open that can of worms to fix it. I think PW can address it in the injected H/F "flattening" work.

[Fran] I agree and am closing this as a no-op.

**Closed by FranECross** 2024-05-13 22:58 UTC
Labels: VA.gov frontend, Needs refining, Public Websites, Injected header
