### ISSUE TITLE
Closer to real time output of ansible log in jenkins

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#1573] opened 2020-04-22 14:42 UTC
The periodic tasks when run by jenkins output their data all at once  for all of them rather than outputing each success in the log in a timely manner.  There is no way to tell how long each task took.

![image](https://user-images.githubusercontent.com/5752113/79995882-c773e700-8485-11ea-8c37-9d0246b1854f.png)

As an engineer I would like to know how long each task took by lookiing at the jenkins console output so that I can assess if there is a problem with any infividual task.

**Comment by indytechcook** [comment] 2020-05-01 14:18
https://stackoverflow.com/questions/61491173/how-to-set-ansible-python-to-unbuffer-output-in-jenkins-pipeline-job#comment108815824_61491173

**Comment by ElijahLynn** [comment] 2020-08-19 17:10
> https://stackoverflow.com/questions/61491173/how-to-set-ansible-python-to-unbuffer-output-in-jenkins-pipeline-job#comment108815824_61491173 (good next steps here)

From above regarding the PYTHON_UNBUFFERED variable:
> Your environment variable is passing through a lot of different pieces, Jenkins, Python, Ansible. I'd make sure that the environment variable is being passed down through the levels faithfully. Find and print it at each level.

**Comment by ElijahLynn** [comment] 2020-08-19 17:21
@olivereri I added this to our next sprint as I think this is going to fall into the category of improvements to developer debugging experience, and I mentioned this briefly the other day.

**Comment by ElijahLynn** [comment] 2020-08-31 20:52
I think a good local test for this is a test.yml playboo with a:
```
sleep 1
echo 'test'
sleep 1 
echo 'test'
# and so on
```

**Comment by ElijahLynn** [comment] 2020-09-15 18:08
Could be a VirtualEnv thing.

**Comment by olivereri** [comment] 2020-09-17 17:23
There doesn't appear to be an official method to support streaming shell/command module output:
https://github.com/ansible/proposals/issues/92
Brian Coca is in the issue discussion and the latest comment is from July 2020 with no updates about adding this feature.

There are some potential work arounds however:
https://github.com/lucasbasquerotto/ansible-live-output-demo
The above runs a shell task and redirects the output to a file, a second task **watch**es the file and polls for updates by a configurable setting to display output.

Near term solution proposal:  If it's possible to break the Composer yaml-tests in separate shell module calls, output should be faster e.g.:
`composer yaml-tests _specificTestName_ --dry-run --no-ansi 2>&1`
`composer yaml-tests phpunit --dry-run --no-ansi 2>&1`

**Comment by ElijahLynn** [comment] 2020-09-17 21:28
> Near term solution proposal: If it's possible to break the Composer yaml-tests in separate shell module calls, output should be faster e.g.:
> `composer yaml-tests _specificTestName_ --dry-run --no-ansi 2>&1`
> `composer yaml-tests phpunit --dry-run --no-ansi 2>&1`

The big shift here would be that DevOps (us) would have to update Ansible every time the test runs changes. With keeping all declarations in a tests.yml file, the application team has full control over what is in here and it is very transparent. 

> There doesn't appear to be an official method to support streaming shell/command module output:
> [ansible/proposals#92](https://github.com/ansible/proposals/issues/92)



That is interesting, because when we run the Ansible tests locally, I _think_ it streams in realtime, or maybe it used to in an earlier version of Ansible. We should test this playbook run locally to see if it streams.

**Comment by ElijahLynn** [comment] 2020-09-17 21:30
But if we did do this, ideally we could see them in Jenkins stages too. It would add extra work to our team over time, updating these etc.

**Comment by ElijahLynn** [comment] 2020-09-17 21:31
I left a comment here https://github.com/ansible/proposals/issues/92#issuecomment-694510674

**Comment by olivereri** [comment] 2020-09-22 18:56
> That is interesting, because when we run the Ansible tests locally, I _think_ it streams in realtime, or maybe it used to in an earlier version of Ansible. We should test this playbook run locally to see if it streams.

The evidence is mounting that this has really never actually worked and must have been something else you observed:
https://serverfault.com/questions/972630/ansible-display-realtime-shell-stdout

**Comment by ElijahLynn** [comment] 2020-09-23 20:47
Hrm, that would be really odd, but is possible! Another engineer and myself did play with this quite a bit after it stopped working on another project, I think around Ansible 2.4.

**Comment by ElijahLynn** [comment] 2020-09-23 20:56
I do see some pretty good reasons this was never supported and will never be supported here https://github.com/ansible/ansible/issues/3887#issuecomment-54672569 by the creator of Ansible. 

In contrast I see some others who suggest they got it working, which contradicts the above (unless I am reading this all wrong). 
https://coderwall.com/p/d5zqla/unbuffered-output-with-ansible-in-jenkins
https://blog.deimos.fr/2016/01/07/ansible-color-and-buffer-fix-on-jenkins/

I think your suggestion of splitting out the test run executions per test suite will make the most sense here. Which I think we will have to do anyways when we parallelize the tests. It will still take a very long time for the Behat suite to run. 

I think we can either convert this issue or close it and create a new one based on your suggestion.

**Comment by olivereri** [comment] 2020-09-28 20:04
I would tend to defer to the reasoning that the creator of Anisble points out.  The two links expressing that streaming output is possible seem pretty weak, considering it hasn't been reproducible. Another group with CI/CD software called Zuul really highlights why I don't think this is possible without significant effort:

> Zuul provides realtime build log streaming to end users so that users can watch long-running jobs in progress. As jobs may be written that execute a shell script that could run for a long time, additional effort is expended to stream stdout and stderr of shell tasks as they happen rather than waiting for the command to finish.
> 
> Zuul contains a modified version of the Ansible command module that starts a log streaming daemon on the build node.
> 
> All jobs run with the zuul.ansible.base.callback.zuul_stream callback plugin enabled, which writes the build log to a file so that the zuul.lib.log_streamer.LogStreamer can provide the data on demand over the finger protocol. Finally, zuul.web.LogStreamHandler exposes that log stream over a websocket connection as part of zuul.web.ZuulWeb.

I'm in favor of closing this since it doesn't sound like the guts of Ansible are geared to support this. The evidence that supports as a possibility doesn't really describe how exactly they are using Ansible either.

**Comment by ElijahLynn** [comment] 2020-09-29 15:47
Agreed on closing for now.

**Closed by ElijahLynn** 2020-09-29 15:47 UTC
Labels: DevOps, Stretch goal
