### ISSUE TITLE
[Events] Facility location: Add NCA facilities, when NCA facilities are migrated to CMS

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#10535] opened 2022-08-30 21:57 UTC
### User story

**AS AN** Facility Editor
**I WANT** to be able to select NCA Facilities (Cemeteries, Monuments)
**SO THAT** I can select their locations from a VA facility list instead of entering the address manually.
**AND** there is a reduced chance of an address being entered with errors, which will cause a poor Veteran/other VA.gov user experience.

### Engineering notes / background

- Facilities team is responsible for pulling address data for NCA Facilities into Drupal. Once it's there, we need to enable these facilities to be findable in the Edit Event UI.
- NCA's are draft nodes: https://prod.cms.va.gov/admin/content?title=&type=nca_facility&moderation_state=All&owner=All
- The filter won't be exposed to the event page## Description
In CMS, on Events > Location > Facility location: this field includes node references to facility content types. NCA facilities are not currently included, and cannot be specified as Event locations. When NCA launches NCA facilities, they should be added to this picker and handled in the Event template.

![Screen Shot 2022-06-15 at 8 42 43 PM](https://user-images.githubusercontent.com/9059428/173980114-faa13e20-c299-4198-bf9e-ea31c7cd86e7.png)

## Additional context 
Previous work in this area to add Vet Centers: 
Backend: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9483, https://github.com/department-of-veterans-affairs/va.gov-cms/pull/10357
Front-end: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10465

## Acceptance Criteria
- [ ] NCA facilities can be specified as an event location (in the entity reference search)
- [ ] Event detail page: when an NCA facility is specified in the CMS, NCA facility address information appears correctly in "Where" 
- [ ] Event list: when an NCA facility is specified in the CMS, NCA facility address information appears correctly in "Where" 
- [ ] Facility page, Events promoted area (e.g. https://www.va.gov/minneapolis-health-care/ ): when an NCA facility is specified in the CMS, NCA facility address information appears correctly in "Where". To appear in this area, the facility must have no Featured event, and Event must be next chronologic event.

**Comment by jilladams** [comment] 2023-04-25 23:16
Ok. My memory per Slack DMs today: when this came up, NCA Facilities weren't migrated enough for this to make sense.  (cc @wesrowe ) 

For PW team reference, state of NCA Facilities is currently ([board](https://github.com/department-of-veterans-affairs/va.gov-cms#workspaces/sitewide-facilities-639f5253e4b702a32376339e/board)): 
* NCA Facilities exist: https://prod.cms.va.gov/admin/content?title=&type=nca_facility&moderation_state=All&owner=All
  * They contain Latitude / Longitude, but not yet street address fields 
* More fields may get migrated: 
  * #13123 
  * #13362 
  * #13340 

This ticket should also be considered in relationship to the bigger questions around consistent experience for how we display locations on an Event at a Facility, related to #13124

**Comment by jilladams** [comment] 2024-04-15 20:54
From PW product sync today: 
* Dave revived the priority for making NCA facilities (Cemeteries) and VBA facilities (Regional Offices + other types) available as Event locations, regardless of whether or not published Drupal nodes are available correlating to those facilities
* DaveC has thoughts around whether or not Drupal should only be referencing Drupal as the source of Facilities data.
  * Could this field reach out directly to APIs for source facility data? Would need to confirm with Lighthouse. 
  * If we change the nature of the field, we need to be mindful of VAMC and Outreach Events impact in the FE, as the Graph QL structure might change, TBD how the changed Drupal field operates, and how address data comes through from the origin to the FE templates, if it's no longer Drupal-stored/formatted data.

@FranECross to consider next steps for prioritizing, relative to other quarterly work / plans for Events V2.

**Comment by FranECross** [comment] 2024-05-31 18:19
I believe we can close this as a dupe of #10536

**Closed by FranECross** 2024-05-31 18:19 UTC
Labels: VA.gov frontend, Drupal engineering, Facilities, Needs refining, Cemeteries, Public Websites, Icebox, Events, NCA
