### ISSUE TITLE
D10 Testing: Billing and Insurance payment link goes to incorrect domain

### ISSUE THREAD

**Issue by maxx1128** [department-of-veterans-affairs/va.gov-cms#14597] opened 2023-08-01 18:43 UTC
## Describe the defect

On the "check your billing, insurance, and payment options" page, the "Pay Options" link goes to a URL at the incorrect domain.

## To Reproduce
1. Go to https://web-kaaijt1fsqp1qasl6a8metonglihfa26.ci.cms.va.gov/portland-health-care/billing-and-insurance/#pay-online-by-phoneor-mail
2. Scroll down to 'Pay online, by phone, or by mail' link
4. Hover over link and see incorrect URL in bottom left of browser screen

## AC / Expected behavior

The link goes to the `va.gov` domain, not the `dev.va.gov` subdomain.

## Screenshots

![](https://user-images.githubusercontent.com/10790736/257262393-978e35a5-66d3-4895-80aa-717ead9d529b.png)

 ## Additional context

This is not currently in production. It was found as part of [the Drupal 10 front-end testing by the facilities team.](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14390)

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [ ] CMS workstream (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [x] `Facilities`
- [ ] `User support`
- [ ] `Accelerated Publishing`

**Comment by edmund-dunn** [comment] 2023-08-03 21:25
@maxx1128 This also appears to be common to tugboat. Verified this in Drupal 9 PR tugboats.

**Comment by mmiddaugh** [comment] 2024-01-02 19:15
Doublechecked this in CMS staging and prod- the link points to a production endpoint
Closing this as it is behaving as expected

<img width="717" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2FTQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1d707c8a8e55535652b381753264018fed683fb7/image.png" alt="image.png" />

**Comment by jilladams** [comment] 2024-01-02 21:06
@xiongjaneg lemme know if you concur, but I'd tend to think of this as CMS team domain, since Edmund concurred it's specific to Tugboat -- I don't think our team feels strongly that we need to have a hand in getting it fixed based on the UX during dev/ testing. If you agree, we can hand off to Berni / Marcia for getting into that backlog.

**Comment by xiongjaneg** [comment] 2024-01-02 21:10
@maortiz-27-80 Submitting to CMS Team for consideration. Also note Michelle's comment that this is on Tugboat, not production.

**Comment by BerniXiongA6** [comment] 2024-01-08 21:26
Hey @ndouglas can you help us get this ticket pre-refined for this current sprint yet? cc: @maortiz-27-80

**Comment by ndouglas** [comment] 2024-01-08 22:47
@BerniXiongA6 @maortiz-27-80 This is a duplicate of #16237, which I already have marked for this sprint -- keeping that one since it's more accurate about the cause, even though this one was first.

**Closed** 2024-01-08 22:47 UTC
Labels: Defect, Needs refining, CMS Team
