### ISSUE TITLE
BE: Add reusable Q&As to Benefit Detail Page content type, using the new runbook

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#10941] opened 2022-09-27 22:50 UTC
### User story

**AS A** Content Editor
**I WANT** to add reusable Q&As to Benefit Detail pages
**SO THAT** Q&As have a single source of truth. 

### Engineering notes / background

Follow the runbook created in #10936. 

## Acceptance criteria

- [ ] Reusable Q&As can be added to Benefit Detail Page nodes
- [ ] Updated runbook with any changes discovered while following it
- [ ] A11y review
- [ ] Product / design review before merge

**Comment by jilladams** [comment] 2023-07-26 00:28
@chri5tia can you confirm you got a11y review? (From ACs)

**Comment by wesrowe** [comment] 2023-07-26 00:39
I verified that it behaves as expected on CMS staging – but I have same question about a11y review

**Comment by laflannery** [comment] 2023-07-26 12:34
I'm having an issue with the display of the modal when it opens, I can only see the top half and I can't get it to scroll into view - is this just me?

![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/106678594/66d9ff73-7f44-4750-9a8c-eaf7f9efc3cf)

**Comment by chri5tia** [comment] 2023-07-26 16:43
@laflannery Can you check a content type that I didn't touch for this ticket to see if you are having the same issue? Can you try the Resources and Support form? Also, can you tell me the approximate size of the browser window or anything else I could use to reproduce the issue?

**Comment by laflannery** [comment] 2023-07-26 18:05
@chri5tia The resources page is doing the same thing for me, on staging and prod. My default browser is Chrome, so that's where I was seeing this issue. However I just tried on FF and Edge and this is correct for both content types:
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/106678594/f85bfac6-36a2-4ece-a7c9-9037f1ccd0e2)

**Comment by chri5tia** [comment] 2023-07-31 01:11
I'm not sure what the next steps are. I am not able to reproduce this on Chrome. Can you tell me what Chrome browser version you are running and the approximate width of the browser window?

**Comment by laflannery** [comment] 2023-08-01 12:26
My chrome is the latest version: Version 115.0.5790.110 (Official Build) (64-bit) and my Browser is 1440px

**Comment by wesrowe** [comment] 2023-08-01 21:20
I will write up the bug Laura observed as a separate ticket since it wasn't introduced by this work. Closing.

**Closed by wesrowe** 2023-08-01 21:20 UTC
Labels: Drupal engineering, Public Websites, Benefit detail page, Q&A
