### ISSUE TITLE
Intermittent connection issues to multiple services through SOCKS

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#4178] opened 2021-02-02 21:14 UTC
## Description

* environment status page is hanging when resuming from sleep. Preview Suspended screen wasn’t showing that the preview is being unsuspended

* pages are not loading intermittently

* Consistent 502 Bad Gateway errors on FE build in demo envs - GraphQL fails

![image](https://user-images.githubusercontent.com/16477724/106663470-fe247500-6560-11eb-890a-40cccf05f3cf.png)

<img width="1039" alt="Screen Shot 2021-02-02 at 1 58 58 PM" src="https://user-images.githubusercontent.com/16477724/106663511-0c729100-6561-11eb-9a4a-739884c0c6de.png">

potentially a TCP level connection issue

could be related to 502 Bad Gateway issues during FE build on demo envs

## Acceptance Criteria

- [ ] connection issues are resolved

## Implementation notes

- triage w/ Ops
- facilitate resolution

**Comment by ElijahLynn** [comment] 2021-02-03 02:21
@olivereri and I have identified the issue, a missing route, and details are in https://dsva.slack.com/archives/CBU0KDSB1/p1612317661227200 (internal), which I triaged to VFS Ops team.

**Comment by ElijahLynn** [comment] 2021-02-04 16:32
> @olivereri and I have identified the issue, a missing route, and details are in https://dsva.slack.com/archives/CBU0KDSB1/p1612317661227200 (internal), which I triaged to VFS Ops team.

This was an issue, which was fixed but that wasn't the cause of this issue and instead it was missing the new subnet in the firewall settings. Manually applied for now and PR here > https://github.com/department-of-veterans-affairs/devops/pull/8463, which was merged and will be in next SOCKS deploy so that manual changes do not get overridden.

**Closed** 2021-02-08 15:57 UTC
Labels: Defect, DevOps, Needs refining, Planned work
