### ISSUE TITLE
PAW: Update markup of questions

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#15210] opened 2023-09-12 13:23 UTC
## Description 
The markup/designs of the PACT Act questions was based on Income Limits (I think) but the markup for radio button groups is different. We can't do it the same because screen readers won't read out the information in the same way.

The current `<va-radio>` component has limitations that make the markup we need not possible. Therefore, we should implement the radio button questions without using  using the component - at least for now and then iterate later when the component is updated.

The basic markup should look like this:
``` 
    <h1 id="form-question">This is the question text</h1> 
    <div id="form-instructions">
       <ul>
         <li>Bahrain</li>
         <li>Iraq</li>
         <li>Kuwait</li>
         <li>Oman</li>
         <li>Qatar</li>
         <li>Saudi Arabia</li>
         <li>Somalia</li>
         <li>The United Arab Emirates (UAE)</li>
         <li>The airspace above any of these locations</li>
       </ul>
     </div>
     <fieldset aria-labelledby="form-question form-instructions">
        <span class="error" role="alert"></span>
        [<va-radio-option> components go here]
     </fieldset>
```
[Link to a Sketch file](https://www.sketch.com/s/b579a8c6-23c8-481f-bbb6-46a36839e217/a/kKLW31r) that could help (this is what we have been using to work with the Forms team and DST)

## Acceptance Criteria
- [ ] H1 heading is outside the fieldset
- [ ] H1 receives focus when navigating between screens/questions
- [ ] Both the H1 and the instructions (bullet list) is read out by screen readers as the label of the fieldset
- [ ] Error is announced when user tried to submit without selecting an answer
- [ ] User can use the arrow keys (up/down OR left/right) to navigate the radio options and they will automatically be selected (They are NOT navigated using the tab)
- [ ] User can use the space bar to select the first option
- [ ] Requires design review
- [ ] Requires accessibility review

## Team
Please check the team(s) that will do this work.

- [ ] CMS Team
- [x] Public Websites
- [ ] Facilities
- [ ] User support
- [ ] Accelerated Publishing

**Comment by jilladams** [comment] 2023-10-25 18:56
Closing as a dupe of https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15268

**Closed by jilladams** 2023-10-25 18:56 UTC
Labels: Defect, Public Websites, accessibility, a11y-defect-2
