### ISSUE TITLE
PM: Lovell launch to dual state 

### ISSUE THREAD

**Issue by dsinla** [department-of-veterans-affairs/va.gov-cms#11930] opened 2022-12-14 00:48 UTC
## Description
When all identified defects are addressed, and when all draft pages are published, we will be in "Dual State", where both the modernized pages exist as "Beta" pages with a banner pointing visitors to the legacy Teamsite pages.
 
Would this essentially be equivalent to "First full publish" for Lovell?
What are the minimum pages required? For instance, would we publish knowing that some Health service detail pages, or some Staff profile pages are still in the works? _Add a column to the site map "Required before publishing to dual state" ?_ 

## Acceptance Criteria
- [ ] Known Lovell-specific defects are addressed
- [ ] The minimum necessary pages are complete and published
- [ ] The banner redirecting to the Teamsite page is in place 

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by davidmpickett** [comment] 2023-02-01 17:59
Closing as duplicate of https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10670

**Comment by davidmpickett** [comment] 2023-02-01 17:59
Closing as duplicate of https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10670

**Closed by davidmpickett** 2023-02-01 17:59 UTC
Labels: Facilities, Needs refining, VA Lovell
