### ISSUE TITLE
FE: Display TRICARE service description for TRICARE facility health services if present, otherwise fall back to currently displayed description.

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#11350] opened 2022-10-26 14:40 UTC
## Description

**UPDATE:** Now that we've merged #11421 we have a TRICARE description field available in the services taxonomy. When displaying a VAMC Facility Health Service page within the Lovell - TRICARE section we want to check for a value in the TRICARE service description and display that value first. If that value doesn't exist display the Description field we are currently using.

![Screen Shot 2022-11-14 at 1 32 38 PM](https://user-images.githubusercontent.com/21045418/201738838-d988db58-9e5d-4218-a881-5b1a0a92b5c8.png)

![image](https://user-images.githubusercontent.com/5752113/198051383-3fd510f1-059f-4c6d-852b-bc142657f4ac.png)

The text from the taxonomy description may contain VA specific text that does not apply to TRICARE so we should check the TRICARE service description for a value first and display it if we find one.

- health_care_service_taxonomy-> field_tricare_description (use if present for TRICARE items)
- health_care_service_taxonomy->description (if the above is not present use this instead)

Pages affected
https://www.va.gov/lovell-federal-tricare-health-care/health-services/
https://www.va.gov/lovell-federal-tricare-health-care/locations/<facility name>

## Acceptance Criteria
- [ ] health_care_service_taxonomy->description is not displayed on /lovell-federal-tricare-health-care/health-services/
- [ ] health_care_service_taxonomy->description is not displayed on /lovell-federal-tricare-health-care/locations/<facility name>
- [ ] Ideally this should be handled by removing the data from the tricare pages, so that a separate clause is not needed on the templates.... however if the display is goofy with empty data, some template work might be needed. (use as a last resort)

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by dsinla** [comment] 2022-11-03 15:58
@swirtSJW  Now that we have new direction from Dave C for TRICAR specific descriptions, would this be closed as No Longer Required?

**Comment by dsinla** [comment] 2022-11-14 18:30
@JayDarnell is this a duplicate of https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11422 ?

**Closed** 2022-11-14 18:36 UTC
Labels: VA.gov frontend, ⭐️ Facilities, Needs refining, VA Lovell

**Comment by dsinla** [comment] 2022-11-14 18:38
Closing as duplicate of #11422
