### ISSUE TITLE
Moderation state dropdown has "Published" selected when editing a published node

### ISSUE THREAD

**Issue by omahane** [department-of-veterans-affairs/va.gov-cms#14488] opened 2023-07-21 20:00 UTC
## Describe the defect
Published content now has the "Published" moderation state selected when editing. 

It appears to affect all content types with moderation.

## To Reproduce
1. Edit an [Event](https://vacms-12252-drupal-10-kaaijt1fsqp1qasl6a8metonglihfa26.ci.cms.va.gov/node/59356/edit) Or any other content type.
2. Scroll down to **Moderation State**.
3. Validate that it says "Change to Published," with "Published" being the selected option in the dropdown

## AC / Expected behavior
Published content has the "Draft" moderation state selected when editing

## Screenshots
![Screenshot 2023-07-19 at 9 42 43 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/766573/49833b95-49a1-4aaa-ad87-7d3a1b736932)

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS workstream (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [x] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`
- [ ] `Accelerated Publishing`

**Comment by swirtSJW** [comment] 2023-07-24 21:16
This is a change to the default behavior in D10 and there is no config to change it to always default to draft, as has been the case for all users of the CMS.

This is likely a change management issue as we have 1000+ editors who have been trained on and gotten use to the way it currently works (all new revisions default to draft) which is safer because it makes all published have to be an intentional change.  We will likely need a communication plan and KB updates/additions.

**Comment by laflannery** [comment] 2023-07-28 12:52
Just Noting that this is a duplicate of #12573

**Comment by jilladams** [comment] 2023-07-31 23:10
Closing bc dupe

**Closed by jilladams** 2023-07-31 23:10 UTC
Labels: Defect, Drupal engineering, Needs refining, CMS Team
