### ISSUE TITLE
CMS-side fix: Events that cross midnight should show the day & date of the event end time

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#9303] opened 2022-06-03 17:09 UTC
## Description
Events list day, date, start time - end time, e.g. `Sun. Aug 14, 2022, 11:30 am – 12:30 am ET`
For events that span midnight they should list day, date, start time - day, date, end time, e.g. `Sun. Aug 14, 2022, 11:30 am – Mon. Aug 15, 2022, 12:30 am ET`

## Assumptions
- CMS-side fix; FE issue will be separate issue
- Similar modification to Drupal module as am/pm fix #9304

## Acceptance Criteria
- [ ] day, date appear on crossing-midnight event end times in recurring events management UI in the CMS

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Platform CMS Team`
- [ ] `Sitewide program`
- [ ] `⭐️ Sitewide CMS`
- [X] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by jilladams** [comment] 2022-06-08 19:12
I noticed this while editing recurrences in the CMS, so we'll need to validate if the frontend presentation is different.

**Comment by wesrowe** [comment] 2022-06-16 17:07
We pulled this into the sprint late (day 9) because Daniel had capacity. It may get finished be EO sprint.

**Comment by dsasser** [comment] 2022-06-16 18:22
@wesrowe @jilladams do you have an example page where this is visible? I'm not seeing these date formats in the recurring events modal, so I'm not sure where I should be looking.

**Comment by jilladams** [comment] 2022-06-16 18:44
We saw this when Ethan had stood up a local instance with local data, so unfortunately: no prod event that pushes down to Staging with that content. A thing that may be a side trail here is: how can we effectively create sample data in lower environments? This is currently mysterious to me. Steve's post yesterday is sort of relatedish? https://dsva.slack.com/archives/C52CL1PKQ/p1655307206343319 But solving that mystery and having it demystified for the team would also be a win. Talking to Ethan may be a good starting point.

**Comment by dsasser** [comment] 2022-06-16 18:55
@jilladams I can recreate the data necessary, but I'm not sure where to test/view the issue at hand. The format `Sun. Aug 14, 2022, 11:30 am – 12:30 am ET` isn't being used on the 'Manage event series' modal, nor on the Event detail page /node/[nid], so I'm not sure where I should be looking.

**Comment by wesrowe** [comment] 2022-06-16 21:02
@dsasser, I think I'm correct in saying this: the issue was really observed on the FE. And I think Steve or Ethan said that Drupal needed an iteration to support the FE. Thoughts?

**Comment by jilladams** [comment] 2022-06-16 21:03
Ah! Ok - that I can help with. Create a new event, and add recurrence. Set event time from 11:30pm - 1am. 
Then in the view of that node, you'll see all the recurrences, e.g. https://staging.cms.va.gov/minneapolis-health-care/events/42754.

So: this fix is for anywhere that the start / end time on an event appear.

**Comment by wesrowe** [comment] 2022-06-16 21:07
@jilladams your screenshots are for lunchtime, not midnight...

**Comment by jilladams** [comment] 2022-06-16 21:09
Right, just an example of where this occurs in terms of placement, not with
proper data. (We dont' have any events matching this midnight use case in
prod or staging.)

**Comment by dsasser** [comment] 2022-06-16 22:55
This is what I'm seeing locally when an event overlaps midnight:
<img width="698" alt="Screen Shot 2022-06-16 at 3 32 16 PM" src="https://user-images.githubusercontent.com/221539/174189839-795e5d63-224e-4835-8290-6c9ab20efd8e.png">
<img width="800" alt="Screen Shot 2022-06-16 at 3 32 54 PM" src="https://user-images.githubusercontent.com/221539/174189859-8c998b96-8519-4be8-90e4-5001de0e26ad.png">

**Comment by dsasser** [comment] 2022-06-17 16:11
This is no longer reproducible. Closing.

**Closed by dsasser** 2022-06-17 16:11 UTC
Labels: Drupal engineering, ⭐️ Public Websites
