### ISSUE TITLE
Spike: Testing with Cypress

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#3706] opened 2020-12-10 20:42 UTC
## Acceptance Criteria
- [ ] 👀 **Needs design review** because the work involves changes to labels or other design elements 
- [ ] 🙈 Can be implemented without consulting design team members
- [ ] Testable_Outcome_X
- [ ] Testable_Outcome_Y
- [ ] Testable_Outcome_Z

## Labels

(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to task)
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [ ] CMS objective (orange)
- [ ] CMS-supported product (black)

**Comment by acrollet** [comment] 2021-01-29 15:30
@oksana-c should we close this as a duplicate of #4109 ?

**Closed** 2021-02-01 15:21 UTC
Labels: Automated testing, Needs refining
