### ISSUE TITLE
Update VA health connect phone number label

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-cms#17749] opened 2024-04-04 17:56 UTC
## Description
To add in Veteran understanding, IVC program leadership has asked for the VA health connect label to be updated to incorporate the Clinical Contact Center

## Tasks
Update VA health connect phone label from` VA health connect` to `VA Health Connect Clinical Contact Center`

- in Facility Locator search results
- in VAMC Location and contact info blocks on VAMC facility pages
- in VAMC Location and contact info blocks on VAMC system pages
- in VAMC Location and contact info blocks on VAMC location pages

## Screenshots

<details>
<summary> Facility Locator search results </summary>

<img width="244" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0UyQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3c271e09c25a552aeb7225dc353d580f0b1a3d00/image.png" alt="image.png" />
</details>

<details>
<summary>VAMC Location and contact info block </summary>

<img width="587" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0kyQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4dfb02a312525e8dc4ee5b2c935776ba63a75cb4/image.png" alt="image.png" />

</details>

**Comment by davidmpickett** [comment] 2024-04-11 23:59
Closing as dupe of #17750

**Closed by davidmpickett** 2024-04-11 23:59 UTC
Labels: Facilities
