### ISSUE TITLE
Placeholder: continuous deployment for CMS

### ISSUE THREAD

**Issue by cweagans** [department-of-veterans-affairs/va.gov-cms#10420] opened 2022-08-24 19:19 UTC
## Description

We should probably look at this at some point. 

## Acceptance Criteria
- [ ] Testable_Outcome_X
- [ ] Testable_Outcome_Y
- [ ] Testable_Outcome_Z
- [ ] Requires design review

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by EWashb** [comment] 2022-12-16 02:45
@TheBoatyMcBoatFace this seems like a dupe of #10981

**Comment by TheBoatyMcBoatFace** [comment] 2022-12-16 15:42
That it is @EWashb. Closing in favor of 
- #10891

**Closed by TheBoatyMcBoatFace** 2022-12-16 15:42 UTC
Labels: Needs refining, Platform CMS Team
