### ISSUE TITLE
URL Change for: Bellevue VA Clinic to Sarpy County VA Clinic

### ISSUE THREAD

**Issue by omahane** [department-of-veterans-affairs/va.gov-cms#18138] opened 2024-05-16 15:58 UTC
### Implementation date
When does this request need to be live:
ASAP

Parent ticket: #18137 

### Instructions for URL redirect
(Note: This issue will be used from initial request through implementation to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track different steps.)
- [x] Notify VA stakeholders as appropriate.
- [x] Link the related facility closure / rename issue.  [#18137](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18137)
- [x] Create a URL redirect in the [devops](https://github.com/department-of-veterans-affairs/devops) repo in `ansible/deployment/config/revproxy-vagov/vars/redirects.yml`
- [x] Add the "Awaiting redirect" flag to the facility node with a revision log message that includes a link to this ticket, preserving the node's current moderation state.
- [x] Redirects deploy daily except Friday at 10am ET, or by requesting OOB deploy (of the revproxy job to prod) in #vfs-platform-support. After deploy, validate that the URL redirect is deployed. (Note: In the event of a facility closure or a name change,  validate that this occurs before making the Lighthouse csv changes.)
- [x] Update this ticket with a comment that the redirect has been deployed.
- [x] Remove the "Awaiting redirect" flag on the facility node with a revision log message that includes a link to this ticket, preserving the node's current moderation state.
- [x]  Notify helpdesk via comment on ticket or Slack message in #cms-support that changes are ready for review.

#### URL Redirect
| Current URL  |  Redirect Destination or New URL |
| ---  |  --- |
| https://www.va.gov/nebraska-western-iowa-health-care/locations/bellevue-va-clinic | https://www.va.gov/nebraska-western-iowa-health-care/locations/sarpy-county-va-clinic |

### 1. Canonical URL change or
**Note: Canonical URL changes do not block the completion of the parent ticket. Once the URL redirect above has been deployed, the value to the Veteran is delivered. This ticket should be kept open until the URL change is verified, except in the case of a removal (as described below).**

### Instructions for canonical URL change
- [x] Verify that the new URL for the facility is published and accessible on VA.gov.
- [x] Update the [CSV in Lighthouse](https://github.com/department-of-veterans-affairs/lighthouse-facilities/blob/master/facilities/src/main/resources/websites.csv) with the changed URL, maintaining the sorted order of the Facility API IDs.
- [x] Create a PR in the [lighthouse-facilities repo](https://github.com/department-of-veterans-affairs/lighthouse-facilities), tagging the Lighthouse team.
- [x] Post a message in the #cms-lighthouse channel in Slack, with an @mention to a Lighthouse team member.
- [x] Add the "Awaiting CSV" flag to the facility node with a revision log message that includes a link to this ticket.
- [x] Validate that the change has deployed by checking that the Facility Locator has been updated with the new url.
- [x] Update this ticket with a comment that the CSV change has been deployed.
- [x] Remove the "Awaiting CSV" flag to the facility node with a revision log message that includes a link to this ticket.

#### URL change example (update with actual ID and URL)
| Facility API ID  |  Full VA.gov URL |
| ---  |  --- |
| vha_636GL | https://www.va.gov/nebraska-western-iowa-health-care/locations/sarpy-county-va-clinic |

**Comment by ian-sears** [comment] 2024-07-19 21:40
Editor replied with clarity today in Jira ticket.
This is indeed to be Sarpy County VA Clinic.

**Comment by ian-sears** [comment] 2024-08-26 16:59
The URL redirect has been deployed. Bellvue now redirects to Sarpy.

**Comment by omahane** [comment] 2024-08-29 17:27
@department-of-veterans-affairs/platform-cms-helpdesk I just put in the redirect PR.

**Comment by omahane** [comment] 2024-09-04 14:48
@department-of-veterans-affairs/platform-cms-helpdesk The redirect has been deployed.

**Comment by ian-sears** [comment] 2024-09-04 23:19
#cms-lighthouse request to update the websites.csv was made
https://dsva.slack.com/archives/C02BTJTDFTN/p1725490925404569
Sarpy County (was bellevue)
vha_636GL,https://www.va.gov/nebraska-western-iowa-health-care/locations/bellevue-va-clinic/
should now be
vha_636GL,https://www.va.gov/nebraska-western-iowa-health-care/locations/sarpy-county-va-clinic/

**Comment by ian-sears** [comment] 2024-09-09 20:34
Not yet updated in the LH csv. Next bus, hopefully :-)
vha_636GL

**Comment by jilladams** [comment] 2024-09-17 22:25
Looks like it's working for me: 
Facility Locator: https://www.va.gov/find-locations/?page=1&address=68046&facilityType=health&serviceType&latitude=41.157431&longitude=-96.042964&radius=10&bounds%5B%5D=-96.792964&bounds%5B%5D=40.407431&bounds%5B%5D=-95.292964&bounds%5B%5D=41.907431&context=Papillion%2C%20Nebraska%2068046%2C%20United%20States

Click on Sarpy, land on https://www.va.gov/nebraska-western-iowa-health-care/locations/sarpy-county-va-clinic/. 

I went ahead and removed the Awaiting CSV flag. Closing.

**Comment by jilladams** [comment] 2024-09-18 21:51
Reopening. @TroyCMSSupport caught something I missed: the markup is still to the Bellevue link, so LH hasn't shipped the CSV update yet. (Which tracks -- Adam typically does close the loop when he makes changes, and hadn't confirmed this change yet.) 

![Screenshot 2024-09-18 at 2 49 53 PM](https://github.com/user-attachments/assets/93e9f04e-663b-4d17-9ce3-49cd9332ad95)

Moving to Awaiting CSV. Nice catch, Troy!

**Comment by TroyCMSSupport** [comment] 2024-09-19 20:06
Seems to be resolved now - Thank you @jilladams and @omahane

**Closed** 2024-09-19 20:06 UTC
Labels: Drupal engineering, Facilities, User support, Redirect request, sitewide, Flagged Facilities
