### ISSUE TITLE
Redirect Request - CPAP Form base URL change - deployed to prod & verified by Fri 9/29 EOD

### ISSUE THREAD

**Issue by JasmineYohannan** [department-of-veterans-affairs/va.gov-cms#15352] opened 2023-09-07 18:08 UTC
# For Mon 10/2 availability, this redirect needs to be complete, merged, deployed and verified in Prod by EOD Fri 9/29 

### Implementation date
When does this request need to be live?
Choose one:
- [ ] On a specific date, connected to a program or publishing requirement. **:**
- [x] Any day prior to a deadline/latest possible date. ****DEADLINE:** 9/29 EOD**
- [ ] Any day after an earliest possible date. **EARLIEST DATE:**
- [x] During a specific date range: **9/18/23 -10/2/23 :***
- [ ] No hard timing requirements, publish when possible.

### Redirects 
current URL | new URL
---  |  ---
https://www.va.gov/health-care/order-hearing-aid-batteries-and-accessories/order-form-2346/  **and all child pages** |  https://www.va.gov/health-care/order-hearing-aid-or-cpap-supplies-form/

### Process, Roles and Responsibilities
- [X] Requesting team: Above information is provided
- [X] Requesting team: All appropriate VA stakeholders are notified as appropriate
- [X] IA: Request is vetted and documented and implementation plan is clear 
- [X] IA: Request is assigned to appropriate team for implementation 
- [ ] Implementation team: Work is complete
- [ ] Implementation team: Validated in production
- [ ] Requesting team: Validates everything is correct in production and closes ticket

**Comment by jilladams** [comment] 2023-09-21 23:25
Question re: timing, @JasmineYohannan - can you clarify what's driving that time window, so our team can keep it in mind? For reference, we'll put this in our next sprint that starts W 9/27, and will need to request an OOB deploy in order to get it out during 9/18/23 -10/2/23 window (since the next natural date it could release would be W 10/4). 

@kristinoletmuskat @mnorthuis - Have added the note re: child pages into the "current URL" area of the ticket -- I think this should be best practices moving forward, to make sure that the ticket body reflects work our team will pick up in future, since it's easy to lose details like that in the comment threads. Thanks!

**Comment by kristinoletmuskat** [comment] 2023-09-22 01:46
@jilladams that sounds great -- we can add that note in future redirect requests.

**Comment by JasmineYohannan** [comment] 2023-09-26 14:59
@jilladams our DLC team wants to start telling Veterans about this functionality starting 10/2, so we wanted to have the redirect done for then.

**Comment by JasmineYohannan** [comment] 2023-09-28 15:48
@jilladams @chriskim2311 as an update - before the redirect happens, we need to make sure the app is actually configured to be accessible via the new URL. that is not currently the case. we’re working on a plan to make this happen, but it will take a few days. cc: @batemapf

**Comment by chriskim2311** [comment] 2023-09-28 16:41
@kristinoletmuskat @JasmineYohannan @jilladams Thank you for the update, Will this delay the release of this redirect? Do we still need it for 10/2? I checked both URLs and they are both not working currently as Jasmine commented above.

**Comment by JasmineYohannan** [comment] 2023-09-28 19:57
@chriskim2311 likely the redirect will be needed to be ready for release midweek rather than Monday cc: @batemapf

**Comment by jilladams** [comment] 2023-09-28 23:02
I had an email update here from @JasmineYohannan saying this would likely need to go out midweek instead, but that's not appearing on ticket anymore. @JasmineYohannan could you clarify timing?

**Comment by JasmineYohannan** [comment] 2023-09-29 13:48
@jilladams @chriskim2311 Confirming that given where things are right now, we will need to push the redirect release to mid-late next week.

**Comment by jilladams** [comment] 2023-10-11 01:28
@JasmineYohannan any updates here?

**Comment by JasmineYohannan** [comment] 2023-10-12 19:26
@kristinoletmuskat is everything okay on the static page end to have this happen?

**Comment by kristinoletmuskat** [comment] 2023-10-13 19:30
Yes we can make this change!

**Comment by chriskim2311** [comment] 2023-10-13 19:54
@kristinoletmuskat Are these authenticated user only pages?

**Comment by kristinoletmuskat** [comment] 2023-10-13 21:19
Yes! You have to sign in to do the form.

**Comment by JasmineYohannan** [comment] 2023-10-17 20:16
@chriskim2311 What time tomorrow will the normal deploy be at? We should be good to go but want to verify a couple of things

**Comment by JasmineYohannan** [comment] 2023-10-17 20:39
@chriskim2311 Can we have the casing be CPAP? (or else revproxy needs to redirect it again from cpap to CPAP).

**Comment by jilladams** [comment] 2023-10-17 22:07
@chriskim2311  I tested based on our discussion  --- right now the lowercase `cpap` resolves to `CPAP`.

| **Input URL** | **Resolves to** |
| -- | -- |
| https://www.va.gov/health-care/order-hearing-aid-or-cpap-supplies-form (with or without / ) | https://www.va.gov/health-care/order-hearing-aid-or-CPAP-supplies-form/introduction  |
| https://www.va.gov/health-care/order-hearing-aid-or-CPAP-supplies-form (with or without / ) |  https://www.va.gov/health-care/order-hearing-aid-or-CPAP-supplies-form/introduction |
| https://www.va.gov/health-care/order-hearing-aid-or-CPAP-supplies-form/introduction |  https://www.va.gov/health-care/order-hearing-aid-or-CPAP-supplies-form/introduction|
| https://www.va.gov/health-care/order-hearing-aid-or-CPAP-supplies-form/introduction |  https://www.va.gov/health-care/order-hearing-aid-or-CPAP-supplies-form/introduction |

**Comment by jilladams** [comment] 2023-10-17 22:07
It looks like this came in via Patrick Bateman here, so is already handled: https://github.com/department-of-veterans-affairs/devops/pull/13533

**Comment by jilladams** [comment] 2023-10-19 00:20
Apologies, just seeing this now. 
@JasmineYohannan are you available in DSVA slack? That might shorten our cycles. I'm gonna start a thread there to help us move fast to get this fixed tomorrow.

**Comment by jilladams** [comment] 2023-10-19 20:18
https://dsva.slack.com/archives/C01K37HRUAH/p1697736620742869?thread_ts=1697674982.893309&cid=C01K37HRUAH
From Patrick Bateman
> hi, sorry folks, been in and out today. tl;dr, everything is fine in its current state and i need to map how i think we should proceed with getting everything to no caps. the problem lies in the fact that both vets-website and revproxy changes are needed (and actually content build too) and since we can’t guarantee deploys of those changes will be perfectly timed, i think we need a temporary state to cover us. will come up with strategy next week and run it by here.

Laura Willwerth confirmed with Patrick that all caps CPAP can stay in prod until any changes. 

This in mind, closing this ticket as complete, and we can create follow up tickets for any additional changes from the current state of things in prod.

**Closed by jilladams** 2023-10-19 20:18 UTC
Labels: VA.gov frontend, Public Websites, Redirect request, non-quarter-prio
