### ISSUE TITLE
FE: Crisis Line Modal (mobile) needs style adjustments

### ISSUE THREAD

**Issue by randimays** [department-of-veterans-affairs/va.gov-cms#16328] opened 2023-12-06 16:00 UTC
## Description

Our VA.gov Crisis Line modal needs some style adjustments on the header (text/close button) to make sure the text does not overlap the button.

Screenshot from Android Galaxy S20 (360px screen width):
<img width="360" alt="Screenshot 2023-12-06 at 10 01 27 AM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/19175324/9808c511-9180-4167-8b1f-7f6e13e00014">

Screenshot from desktop Chrome in responsive mode (407px screen width):
<img width="407" alt="Screenshot 2023-12-06 at 10 01 27 AM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/19175324/1f20f239-44e4-4ecb-ab5e-88f8e8a978f7">

### User story

**AS A** Veteran or other user of VA.gov using a mobile device
**I WANT** to be able to read all text on the VA.gov Crisis Line modal without some text being obscured by the button
**SO THAT** I'm not distracted or frustrated or confused when I open the modal

### Quality / testing notes
- Tested on VA.gov
- Tested on injected header

## Acceptance criteria
**AC1: The X/close button doesn't obscure text when a user is viewing the Crisis Line modal on a the mobile devices mentioned above as well as other mobile devices**

**GIVEN** a Veteran or other user is using a mobile device with screen width mentioned in description and is somewhere on VA.gov
**WHEN** the user opens the Crisis Line modal
**THEN** the x/close button doesn't obscure any text
**AND** pressing the x/close button closes the modal

**AC2: The X/close button displays correct when a user is viewing the Crisis Line modal on a the desktop** 

**GIVEN** a Veteran or other user is using a desktop and is somewhere in VA.gov
**WHEN** the user opens the Crisis Line modal
**THEN** the x/close button doesn't obscure any text
**AND** pressing the x/close button closes the modal

**Comment by FranECross** [comment] 2023-12-20 16:05
Not a priority over other work we have (after conversing with Dave/Jill), because the actual app doesn't exhibit this issue, and the X on browsers isn't isn't heinous enough to prioritize over other work, but is something that a developer can pick up if a sprint is light.  cc @jilladams 

I've confirmed the following:
- iPhone app: has 'Done' instead of an X, and it isn't obscuring anything
- VA.gov on Safari (iPhone) the X partially overlaps the word 'day'
- VA.gov on Chrome (iPhone) the X partially overlaps the word 'day'

**Comment by chriskim2311** [comment] 2024-01-16 21:46
Code has merged pending prod release today

**Comment by chriskim2311** [comment] 2024-01-17 17:11
Verified on prod closing!

**Closed by chriskim2311** 2024-01-17 17:11 UTC
Labels: VA.gov frontend, VA.gov homepage, Public Websites
