### ISSUE TITLE
Cerner: Hard-code Central OH activation of 4 remaining widget types

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#8686] opened 2022-04-07 21:39 UTC
## Description
There are CTA widgets in the unauthenticated va.gov experience that call users to log in. The log in button needs to go to the appropriate EHR system: Cerner (the new EHR) or VistA (legacy system).

[Example](https://www.va.gov/health-care/refill-track-prescriptions/):

![image.png](https://images.zenhubusercontent.com/61a671f5fc46c2a311655f75/19baa992-2c80-4cbb-a03a-6e90e0f76cd3)

"Full" Cerner cut-over for the Central Ohio (aka Columbus) VHA System is scheduled for 4/30. However, Cerner has already been turned on for one type of widget: scheduling and appointment. The remaining widgets remained turned off by a _blocklist_ (exception list) that's hard-coded in the codebase. From a technical perspective, then, much of the cut-over has already been done, and this issue simply calls for this system to be removed from the blocklists.

### Resources
- The Cerner cut-over [runbook](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/teams/vsa/teams/public-websites/cerner.md) has already been followed for CenOH
- Blocklists are in this [index.js](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/platform/utilities/cerner/index.js#L20) file
- [This issue](https://github.com/department-of-veterans-affairs/va.gov-team/issues/35893) in the va.gov-team repo may have more context for this issue. In a [comment](https://github.com/department-of-veterans-affairs/va.gov-team/issues/35893#issuecomment-1091734302) on that issue, Dave expressed a vague preference for __how__ the cut-over is done, please review.

## Testing
The runbook recommends testing with a test user. We need to learn how a widget on an unauthenticated page knows what user is visiting the page. But for testing, please test with (at least) two test users, one associated with the Central OH system and one associated with a legacy (non-Cerner) system.

Ryan and Allison have copies of an email thread with Anthony Diaz (Anthony.Diaz@va.gov) about getting test user logins, along with one-time-use codes to get around MFA.

## Acceptance Criteria
- [ ] Cerner link present for Central OH test user
- [ ] VistA link present for legacy-system test user

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Sitewide program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide crew ` (leave Sitewide unchecked and check the specific team instead)
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [x] `⭐️ Public websites`
  - [ ] `⭐️ Facilities`
  - [ ] `⭐️ User support`

**Comment by jilladams** [comment] 2022-04-11 16:42
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VAgov-CMS-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/8686?planning-poker) with ZenHub @ryguyk @allisonlu

**Comment by jilladams** [comment] 2022-04-14 16:44
@davidconlon  question for you re: this [comment]( https://github.com/department-of-veterans-affairs/va.gov-team/issues/35893#issuecomment-1091734302).  

It turns out the flipper isn't quite granular enough to allow us to remove 4 the blocks on remaining Cerner functions, ship in daily deployment, and use the flipper to enable the cutover on 4/30. Testing is turning out to be a bit trickier than we thought, and the runbook doesn't speak to it much -- Ryan is working through that. 

Bc flipper isn't an option, our understanding re: cutover timing is that we'll need to target the 4/30 daily deployment, instead. Can you confirm that's right / these changes should not reach prod prior?

**Comment by davidconlon** [comment] 2022-04-14 16:53
@jilladams 
Couple things to note: There is no daily deploy on 4/30 (Sat) or 5/1 (Sun) - that's when Cerner is doing their work.
Our work will be to open the proverbial front door (these react widgets) on 5/2 when we have confirmed that they have successfully cut over.
Making this change as part of the 5/2 daily deploy is fine as a result.
I'm going to be OOO on 5/2 so we'll need to make sure to connect you with the right person to say "green light"

**Comment by jilladams** [comment] 2022-04-14 17:21
Perfect, thank you. Helpfully, I'm also on PTO 5/2 (starting 4/22). @wesrowe / @ryguyk  In sprint 57 planning on 4/25, can you all own the action item to make sure we get the contact needed for 5/2 green light?

**Comment by wesrowe** [comment] 2022-04-14 17:31
@jilladams, I can handle the go/no-go comms re 5/2 deployment. Dave to provide the POCs (PsOC?). 
It seems like the cutover/deployment should get its own ticket for tracking, does that make sense to you all?

**Comment by wesrowe** [comment] 2022-04-14 21:00
Created #8772 for 5/2-targeted deployment.

**Comment by ryguyk** [comment] 2022-04-22 19:57
After a good deal of discovery around how things are structured, confirming how things work, and figuring out how to test things, I've determined that the actual code changes to make this happen are quite small.  It's a matter of removing the `757` values in the following code in [this file](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/platform/utilities/cerner/index.js):

```
// Not all Cerner facilities have the same capabilities. These blocklists are
// used to determine which facilities lack certain capabilities.
// Facilities that are Cerner but do not have Cerner prescription features:
export const CERNER_RX_BLOCKLIST = [];
// Facilities that are Cerner but do not have Cerner secure messaging features:
export const CERNER_MESSAGING_BLOCKLIST = ['757'];
// Facilities that are Cerner but do not have Cerner appointment features:
export const CERNER_APPOINTMENTS_BLOCKLIST = [];
// Facilities that are Cerner but do not have Cerner medical records features:
export const CERNER_MEDICAL_RECORDS_BLOCKLIST = ['757'];
// Facilities that are Cerner but do not have Cerner test and lab results
// features:
export const CERNER_TEST_RESULTS_BLOCKLIST = ['757'];
```
Closing this issue in favor of #8772. We'll submit a PR for that issue on the appropriate date.

**Closed by ryguyk** 2022-04-22 19:57 UTC
Labels: Sitewide crew, ⭐️ Public Websites
