### ISSUE TITLE
Publishing custom block results in Error Message - required hidden fields

### ISSUE THREAD

**Issue by TroyA6** [department-of-veterans-affairs/va.gov-cms#15187] opened 2023-09-11 16:40 UTC
## Describe the defect
Saving changes to page: https://prod.cms.va.gov/block/6 results in the following message: 'Please fill out this field', but there is no empty field displayed -- Perhaps the Editorial Workflow / Revision Log field is hidden, as it does not seem to populate correctly.
 
## To Reproduce
1. Go to 'https://prod.cms.va.gov/block/6'
2. Click on 'Publish' in the status section
3. See error

## AC / Expected behavior
When saving changes in any of the three statuses, Editor should be required to complete a Revision Log message, and the changes should be saved successfully.

### Error Message:
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/108767736/12a08e94-52f3-4213-9871-1626df43c1e8)

### Editorial Workflow does not populate:
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/108767736/e2c5a8c8-73c4-467f-8d70-ec4aefc64dec)

 ## Additional context
This is preventing a the page update, which may be time sensitive.

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS workstream (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [x] `Facilities`
- [ ] `User support`
- [ ] `Accelerated Publishing`

**Comment by TroyA6** [comment] 2023-09-11 16:59
Associated JIRA Help Ticket [VAHELP-6355](https://va-gov.atlassian.net/jira/servicedesk/projects/VAHELP/queues/custom/22/VAHELP-6355)

**Comment by ndouglas** [comment] 2023-09-11 17:04
I think this might've been broken by #14842.

If I visit [this preview environment](https://pr14753-kcqw2tduyeeldmgxulxphjyhxf0ymatu.ci.cms.va.gov/block/6), last touched August 16:

![Screenshot 2023-09-11 at 12 58 59 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/1318579/ecae2b39-3f8e-4bcb-85f3-a355a040b446)

then the revision log message field appears as normal:

![Screenshot 2023-09-11 at 1 00 44 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/1318579/156f4d3b-b6e9-47f3-9408-54fd51c0eeaf)

and the block can be saved:

![Screenshot 2023-09-11 at 1 00 56 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/1318579/c949e499-7d06-4d81-a2e4-073b29b8a306)

If we visit a [preview environment from just a few days later](https://pr14867-l2rkuuo23uyrcjlbkqge8wyapdnzp50f.ci.cms.va.gov/block/6):

![Screenshot 2023-09-11 at 1 02 07 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/1318579/b8621336-607f-46ba-a783-55249d9c01ba)

the revision log message field is not displayed:

![Screenshot 2023-09-11 at 1 02 19 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/1318579/8db9b26f-6201-4000-892d-2901d27cb040)

and the block cannot be saved:

![Screenshot 2023-09-11 at 1 02 25 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/1318579/852aee5f-c838-4be6-aa3b-0f14d9f9786b)

**Comment by chri5tia** [comment] 2023-09-13 16:36
This is the code change that exposed the issue by making the hidden field required.

![Screenshot 2023-09-13 at 9 35 49 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/22764938/b1355e00-17f2-40cf-ba60-cdb8e3414bf1)

**Comment by chri5tia** [comment] 2023-09-13 16:43
[15186hotfix.patch](https://github.com/department-of-veterans-affairs/va.gov-cms/files/12600018/15186hotfix.patch)

**Comment by wesrowe** [comment] 2023-09-13 16:49
I'll write a new ticket for PW to address this bug. @chri5tia, is the link above something you have/can put in a PR?

**Comment by wesrowe** [comment] 2023-09-13 16:58
Ticketed to fix #15242. Will pull in this sprint starting today.

**Comment by jilladams** [comment] 2023-09-13 18:29
Tagging this for Public Websites, since Christia had picked this up. @ndouglas and @chri5tia both have PRs in flight, so we need to work out which stays / which is closed as no-op. Christia to follow up with Nate.

**Comment by chri5tia** [comment] 2023-09-13 18:30
https://github.com/department-of-veterans-affairs/va.gov-cms/pull/15243 PR that Nate is looking at.

**Comment by ndouglas** [comment] 2023-09-13 18:31
I don't have a PR in flight, to clarify 🙂

**Comment by chri5tia** [comment] 2023-09-13 18:54
As Nate pointed to, the issue is that the form structure on promo blocks is different than other block types, such as alert.

The fields are so different that I think that this is going to take a little more thought and planning. I would like to go ahead and push the PR that exposes the field and then take some time to plan out and debug the long-term fix as a separate ticket.
<img width="1109" alt="Screenshot 2023-09-13 at 11 53 00 AM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/22764938/2234dc69-89a7-4574-bee8-3acf79818743">
<img width="1117" alt="Screenshot 2023-09-13 at 11 52 56 AM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/22764938/e1278d17-b370-42f7-a1b4-525900b11c6b">

PR is approved and ready to merge.

**Closed** 2023-09-21 04:10 UTC
Labels: Defect, Drupal engineering, Public Websites
