### ISSUE TITLE
SPIKE: Investigate Memcache Performance Issues

### ISSUE THREAD

**Issue by TheBoatyMcBoatFace** [department-of-veterans-affairs/va.gov-cms#11781] opened 2022-12-02 14:56 UTC
# Overview

The site's memcache nodes are experiencing performance variations. The goal is to document how to recreate the issue, investigate the cause, and share the findings. Once findings are finalized, implementation & next steps will be discussed.

## Background

During preparations to [upgrade the site from PHP 7.4 to 8.1](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11345), @ElijahLynn noticed performance regressions. [Upon further investigation](https://github.com/department-of-veterans-affairs/va.gov-cms#issuecomment-1327915651), he discovered that the by replacing the existing memcache nodes with fresh ones, performance greatly improved.

## Why It Matters

Memcache is a system which helps the website respond faster to users. While it is not necessary for the site to operate, it does provide an essential service with regards to user experience.

These speed variations are unusual and, unlikely, but possible, could indicate other site problems.

# Acceptance Criteria

- [ ] **Define Pass/Fail Test Criteria**: What constitutes acceptable node performance?
- [ ] **Define methodology & variables**: Record steps to recreate tests and variables in this story
- [ ] **Results Recorded**: All test results recorded below
- [ ] **Cause discovered and recorded**: The cause of variations is defined and recorded on this ticket
- [ ] **Knowledge Shared**: Once all above steps are completed, the issue/cause is presented to interested parties

### CMS Team

Please check the team(s) that will do this work.

- [ ] `Program`
- [x] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by ElijahLynn** [comment] 2022-12-02 20:41
I am seeing a slowdown on the new nodes from the other day now AND I spun up two new nodes today and they are fast (like the other ones were the other day). So this is all a bit perplexing.

Good news is that Elasticache (memcache) is still the culprit.

I've been looking through config settings to see if there could be anything that looks like it could affect things. I've also tried manual flush_all on the nodes and no luck. Only NEW nodes seem to be fast, and they stay fast for repeated drush cache:rebuild (flush_all) . Something overtime causes them to be slower. Doesn't seem to be a networking thing, although that definitely caused significant increase in response times when they were in different AZs.

I opened an AWS Support Case (by email)
https://console.amazonaws-us-gov.com/support/home#/case/?displayId=11426483301&language=en (edited) 

They replied asking for some network packet captures to both the slow and new cases. Which I am working on now.

**Comment by ElijahLynn** [comment] 2022-12-06 17:35
Good news is that the most recent nodes I created (5&6) are STILL fast, and 3&4 are still slow. I'm going through all of them now individual to see if any individual node is slow and then I can do a packet capture AND Blackfire profile on a single node. I'm really hoping that I can see the issue on an isolated node. If not then that we have an issue with there being multiple nodes in the cluster and the application talking to both of them, so maybe there is a race/timing issue in the app/php code then.

**Comment by ElijahLynn** [comment] 2022-12-14 17:26
Good news and not so good news. Good news is that I found the issue, and the issue isn't with the memcache nodes and everything is fine. Not so good news is that everything is working as expected and I wasted a bunch of time because my testing methodology was bad. 

It was bad because I was changing the IPs of the `CMS_MEMCACHE_NODES` variable that Apache was loading, this is good. But when I was `drush cache:rebuild`ingl, those new IPs were never picked up because they were already loaded into the shell environment I was using and I didn't reload them. This is because `drush` uses the CLI PHP and not the `mod_php` loaded by Apache/httpd. So I was effectively always clearing the cache of nodes 1 & 2 but never the others and therefore getting inconsistent results.

I finally changed my testing methodology to output the ENV and therefore IPs, AND then cleared the cache by doing a curl to the `/flush` endpoint and then doing a request to `/admin/content` with curl as well. This made sure everything was going through Apache. I did this by using the "copy as curl" feature on the network request itself in Chromium/Brave. This created a perfect curl request that I could automate on the CLI, but not using the CLI PHP. 

Here are some of the results on test.staging which has the EC2 instances and RDS in 1C. You can see here a perfect correlation to the network latency introduced by a different availability zone (AZ), in this case 1A. The increase in times correlate perfectly. And all requests over 1C are very consistent. 

![image](https://user-images.githubusercontent.com/1504756/207665087-b4a08507-96c0-4db5-8210-609fc0d2bb80.png)

**Comment by ElijahLynn** [comment] 2022-12-14 17:30
I am closing this ticket. I think we should have another ticket to put the memcache cluster fully into the same AZ to make things faster, yet less reliable in another ticket. We don't have the ASG set to launch multiple instances now, so we really don't have the advanatage of being multi-AZ right now, and I don't see any risk to putting the whole memcache cluster in the same AZ, since a failure in 1C would bring RDS and EC2 down anyways. I'm looking for logical arguments that we should not do this, if I don't hear any objections then I'm going to move forward with this.

**Closed by ElijahLynn** 2022-12-14 17:30 UTC
Labels: DevOps, Research, Platform CMS Team

**Comment by ElijahLynn** [comment] 2022-12-14 17:34
Moved the same-AZ memcache cluster back to this story https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11756.
