### ISSUE TITLE
Remove or Hide Field (approach dependent on field type)

### ISSUE THREAD

**Issue by TroyA6** [department-of-veterans-affairs/va.gov-cms#11248] opened 2022-10-18 21:07 UTC
## Describe the defect
In Drupal CMS Edit mode, the Locations page has a Page Introduction field that is visible and editable, but this content does not appear on va.gov.

## User Story
As a VAMC Drupal CMS Editor, I expect my 'Location' information to appear at the top of my VA health center's Locations page so that Veterans can see quickly how many location options are available to them.

## To Reproduce
1. Go to 'https://prod.cms.va.gov/madison-health-care/locations/' to see the text
2. Go to https://www.va.gov/madison-health-care/locations/ to see that the text field is not displayed as expected

### Text as it appears in Edit mode:
![image](https://user-images.githubusercontent.com/108767736/196541357-25510a6b-202b-433e-87d3-a6e84e425dfc.png)

### Production site view of the same page:
![image](https://user-images.githubusercontent.com/108767736/196541591-866d048b-27d0-4781-857c-d00f9b0f7f98.png)

## Additional context
Some research has been completed regarding this request by Sitewide-Facilities in this Slack https://dsva.slack.com/archives/C0FQSS30V/p1666030927740049

[This ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/25026) might explain that the removal from the FE was intentional.

## Implementation Details
By all appearances, removing the field produces no regressions in Drupal. In fact, the [cron cleans up the data](https://api.drupal.org/api/drupal/core%21modules%21field%21field.module/function/field_cron/10.0.x) on each one run, [50 rows at time](https://api.drupal.org/api/drupal/core%21modules%21field%21config%21install%21field.settings.yml/10).

For that reason, it makes the most sense to remove the field entirely.

## Acceptance Criteria
- [x] It has been determined that this field is purposefully not on the front end 
- [x] IF this is actually a field this should be removed 
- [ ] IF this is a node property then this should be hidden 
- [ ] Any KB article mentioning the field (such as the [About locations content — for VAMCs](https://prod.cms.va.gov/help/vamc/about-locations-content-for-vamcs)) is updated

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by Dottisea** [comment] 2023-02-16 17:54
This was perhaps a regression or was deliberately removed -

**Comment by Dottisea** [comment] 2023-02-16 18:00
11612 is a duplicate assigned to CMS team - talk to erika

**Comment by Dottisea** [comment] 2023-03-01 17:46
The solution is to hide from editorial interface or delete form editorial fields altogether. per Dave C. 3/1/2023

**Comment by maxx1128** [comment] 2023-03-08 20:26
If this was unintentional and needs to be added back, I would put the technical estimate for it at about a **1.** I believe we would just need to put back [the code that was removed here.](https://github.com/department-of-veterans-affairs/content-build/pull/285/files#diff-edf39f0cccb41510d2ab26601689115a1c126d04faa68569dea2de48e255e368L16-L20)

**Comment by omahane** [comment] 2023-03-23 19:23
Changed KB: https://prod.cms.va.gov/node/6795/latest

**Comment by omahane** [comment] 2023-03-23 19:24
@stefaniefgray @TroyA6 Should we remove this KB entirely: https://prod.cms.va.gov/help/va-medical-centers-vamcs/about-locations-content-for-vamcs/how-to-edit-a-locations-list
The only thing it mentions editing is the Page introduction, which we're removing.

**Comment by stefaniefgray** [comment] 2023-03-23 21:05
@omahane We can go ahead and remove it once the introduction portion has been removed

**Comment by omahane** [comment] 2023-03-27 14:55
@stefaniefgray I'll remove it today, after my change merges. Could you or @TroyA6 take a look at the KB change I made?
https://prod.cms.va.gov/node/6795/latest

**Comment by jilladams** [comment] 2023-03-27 22:23
Looks like this got the High Priority flag on accident when switching lanes, so removing it.

**Comment by omahane** [comment] 2023-03-28 13:16
In an abundance of caution, I have archived the KB, instead of deleting it: https://prod.cms.va.gov/help/va-medical-centers-vamcs/about-locations-content-for-vamcs/how-to-edit-a-locations-list

**Comment by omahane** [comment] 2023-03-28 13:37
@stefaniefgray @TroyA6 In light of this [Slack thread](https://dsva.slack.com/archives/C0FQSS30V/p1680009593245629), I have updated the KB to reflect the remaining editorial task: https://prod.cms.va.gov/help/va-medical-centers-vamcs/about-locations-content-for-vamcs/how-to-edit-a-locations-list

**Comment by TroyA6** [comment] 2023-03-28 14:11
@omahane This article looks good to me - @stefaniefgray , what are your thoughts?

**Closed** 2023-03-29 02:02 UTC
Labels: Defect, VAMC, Facilities
