### ISSUE TITLE
Increase Events Test Coverage

### ISSUE THREAD

**Issue by dsasser** [department-of-veterans-affairs/va.gov-cms#14116] opened 2023-06-20 20:40 UTC
## Description
This is a follow-on from https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12932 to create additional tests for missing coverage.

### User story

**AS AN** Event Editor
**I WANT** automated test coverage on my UI
**SO THAT** bugs don't languish until I discover them.

### Engineering notes / background
Tests are lacking for:
- Duplicate events - tests should confirm that duplicate events are not exposed to the FE
- Recurring events - tests should confirm that recurrences get their own "event" object in the event listing
- Online events - tests should confirm that online events display correctly ("where" should not have an address, but display "This is an online event".
- Active events - See https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10307

## Acceptance criteria

- [ ] tests confirm that duplicate events are not exposed to the FE
- [ ]  tests confirm that recurrences get their own "event" object in the event listing
- [ ] tests confirm that online events display correctly ("where" should not have an address, but display "This is an online event".
- [ ] Active events - See https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10307
- [ ] Test coverage should be at least 80%

**Comment by randimays** [comment] 2023-12-22 17:34
# Pull requests
Both are in review as of 12/22

vets-website PR: https://github.com/department-of-veterans-affairs/vets-website/pull/27257
content-build PR: https://github.com/department-of-veterans-affairs/content-build/pull/1842

## Unit tests
The goal was to get at least 80% unit test coverage (in vets-website) as possible, but we aren't able to achieve this due to shadow DOM limitations (preventing us from being able to click buttons / simulate behavior in a unit test).

Here's a before & after of coverage averages on `main` versus the new test branch:

|         | Statements | Branches | Functions | Lines |
| ------- | ------ | ----- | --- | --- |
| `main`  |    63%    | 57%      | 68%  |63% |
| new branch |     71% (+8%)   | 76% (+19%)      |70% (+2%) |71% (+8%) | 

### Before (`main`)
<img width="1448" alt="Screenshot 2023-12-21 at 5 16 21 PM" src="https://github.com/department-of-veterans-affairs/vets-website/assets/19175324/0dbc054c-ee36-4975-b44c-d1ab7e19f032">

### After (new branch)
<img width="1442" alt="Screenshot 2023-12-21 at 5 15 36 PM" src="https://github.com/department-of-veterans-affairs/vets-website/assets/19175324/7388a17c-2260-4d31-a88a-0d8b648d804e">

## Cypress tests
I would've liked to add Cypress tests in vets-website to cover the Events functionality we couldn't hit through a unit test, but the Events app is a widget in vets-website, not a complete application. This means Cypress tests are not run (as it doesn't have a static page container). We aren't able to add them in content-build either because content-build is only the container for the Events search & results widget and won't have that information when running in CI.

**Comment by jilladams** [comment] 2023-12-29 19:06
For end of sprint: 
* Content-build PR merged
* vets-website PR: https://github.com/department-of-veterans-affairs/vets-website/pull/27257 needs FE COP approval from Plat
* The unit tests / Cypress notes re: coverage are super helpful, Randi, thanks. It seems like there isn't anything here we could ticket for next steps shy of deciding to convert Events to a full application. I could see this becoming a weird thing if we shipped something new and Events related that required the Collab Cycle for some reason -- we'd become launch blocked due to these stats. Do you think there's any value in surfacing the situation, though, to Platform, for consideration re: the requirements for 80% coverage?

**Comment by randimays** [comment] 2024-01-02 16:35
@jilladams All PRs have merged now. I am going to verify functionality in the search widget to guard against regressions and then this ticket will be closed.

I'm not sure why Events isn't currently an application, but is Public Websites going to continue owning this application for the foreseeable future? If we are, I'd recommend we convert to a full vets-website application. We still may not be able to hit 80% test coverage because of the shadow DOM limitations, though.

**Comment by jilladams** [comment] 2024-01-02 16:49
Discussed with Randi, she'll ticket that idea.

**Comment by randimays** [comment] 2024-01-02 17:52
@jilladams @FranECross New ticket for creating an application in VW for Events: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16594. Noting here that we will still have unit testing gaps covering meaningful code in Events. We can cross that bridge with Platform if need be, but likely need to confirm with Dave about product ownership going forward.

**Comment by randimays** [comment] 2024-01-02 21:54
`vets-website` and `content-build` tests have been merged in. Verified correct functionality (no regressions) in staging and prod. Closing!

**Closed by randimays** 2024-01-02 21:54 UTC
Labels: VA.gov frontend, Public Websites, Events
