### ISSUE TITLE
Hidden fields preventing saving a node

### ISSUE THREAD

**Issue by VanessaLuxen** [department-of-veterans-affairs/va.gov-cms#4753] opened 2021-03-22 13:19 UTC
This ticket has come from a request to the help desk from Randi H because she is unable to save after changing the governance on a draft page of an R&S article. It doesn't give an error message but it doesn't do anything when she clicks the save button. She was able to change it on one node but can't on any others. Help Desk was able to replicate this issue. Kaise as our Tier 2 support was able to determine that this is due to required hidden fields on the form. Randi said this is not urgent as they are not ready to put all of this information in the form yet but will need to be completed soon.  

prod.cms.va.gov/node/15603/edit

Relates to this Jira ticket: https://va-gov.atlassian.net/jira/servicedesk/projects/VAHELP/queues/custom/22/VAHELP-545

**Comment by kevwalsh** [comment] 2021-03-29 01:31
@VanessaLuxen This looks like it may be a duplicate of #4633 which was created by @ndouglas ... that one contains some of the original messaging from the user. Any way you can verify if this is the same issue?

**Comment by VanessaLuxen** [comment] 2021-03-29 13:59
@kevwalsh It may be the same base issue but this was about 2 different help desk tickets. This is for Jira ticket https://va-gov.atlassian.net/jira/servicedesk/projects/VAHELP/queues/custom/22/VAHELP-545 that came in on March 19 from Randi. 

Ticket #4633 is for Jira ticket https://va-gov.atlassian.net/jira/servicedesk/projects/VAHELP/queues/custom/11/VAHELP-501 that was also a help desk request from Randi but it was from March 11. 

Let me know if I can provide more info on either of these.

**Closed** 2021-04-23 12:09 UTC
Labels: Defect, Needs refining, Product Support Team, User Feedback
