### ISSUE TITLE
BE: After hard launch, deprecate old homepage Drupal elements

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#11921] opened 2022-12-12 22:02 UTC
If/When the new Homepage design (/new-home-page) is launched to actually load on VA.gov, we can deprecate old homepage elements / logic for elements that no longer show on the homepage. These include: 

1. Home page Top tasks blocks MENU: https://prod.cms.va.gov/admin/structure/menu/manage/homepage-top-tasks-blocks
  - These are the 4 big tiles of links
2. Promos entityqueue 
  - On OldHP, pulls in the 3 blocks at the bottom: Pact, Pathfinder, VAntage
3. Homepage hub list fields on Benefit Hub Landing Page content type: https://prod.cms.va.gov/node/3071/edit -- blocked by #11968 and hard launch
    * Hub label
    * Hub teaser text 
    * 
<img width="1105" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/4054752/f1a1504e-94a4-4486-8053-f7da7cf0c272">

## Acceptance criteria

- [ ] Confirmed no other content uses Home page top tasks menu, and then removed it (or raised awareness it is used elsewhere)
- [ ] Homepage [promo entityqueue](https://prod.cms.va.gov/admin/structure/entityqueue/home_page_promos) – confirmed it's not used elsewhere, then removed it (or raised awareness it is used elsewhere)
- [ ] Homepage [Benefit hub entityqueue](https://prod.cms.va.gov/admin/structure/entityqueue/home_page_hub_list) –  confirmed it's not used elsewhere, then removed it (or raised awareness it is used elsewhere)
- [ ] ~~Homepage-related fields in [Ben Hub landing page content type](https://prod.cms.va.gov/node/3071/edit) –  confirmed it's not used elsewhere (FE task, see preceding ticket), then removed it (or raised awareness it is used elsewhere)~~ _#13955 found that this content is used elsewhere_
  - [ ] ~~Hub label field~~
  - [ ] ~~Hub teaser text~~
- [ ] Removed CMS feature flag FEATURE_HOMEPAGE_V2

**Comment by dsasser** [comment] 2023-06-22 19:36
@jilladams @wesrowe FYI there are going to be necessary FE changes in content-build that need to precede the Drupal changes.

Removing menus and entityqueues without removing the related graphql queries (and related code using those queries) in content-build would result in content-build failing ungracefully (a timeout will occur eventually) during build/realease.

This does not change the overall complexity such that we need to shuffle any other sprint work, but it does change how we need to release the work. Namely: the content-build PR I'm working on needs to be merged and released before Drupal work can get merged in.

**Comment by dsasser** [comment] 2023-06-22 19:53
FE content-build PR: https://github.com/department-of-veterans-affairs/content-build/pull/1615

**Comment by dsasser** [comment] 2023-06-23 18:36
BE va.gov-cms PR: https://github.com/department-of-veterans-affairs/va.gov-cms/pull/14147

**Comment by dsasser** [comment] 2023-06-27 21:34
# Mid-Sprint Status Update 6/27/23

The FE work has been merged and deployed to production.
The BE PR is up but a graphql test is failing due to an error that I'm working to resolve.

The error occurs during content fetching from Drupal, but provides no indication as to the root cause.
```
| GetNodePage__slice7 | 2s | 25 pages |
| GetNodePage__slice8 | 2s | 25 pages |
| GetNodePage__slice9 | 2s | 25 pages |
| GetNodePage__slice2 | 2s | 25 pages |
| GetNodePage__slice3 | 2s | 25 pages |
| GetNodePage__slice11 | 3s | 25 pages |
| GetNodePage__slice1 | 2s | 25 pages |
Error: HTTP error: 500: Internal Server Error
    at Object.query (/var/lib/tugboat/docroot/vendor/va-gov/content-build/src/site/stages/build/drupal/api.js:135:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RetryOperation._fn (/var/lib/tugboat/docroot/vendor/va-gov/content-build/node_modules/p-retry/index.js:50:12)
Failed to pipe Drupal content into Metalsmith!
/var/lib/tugboat/docroot/vendor/va-gov/content-build/src/site/stages/build/plugins/download-assets.js:11
  throw up;
  ^

Error: HTTP error: 500: Internal Server Error
    at Object.query (/var/lib/tugboat/docroot/vendor/va-gov/content-build/src/site/stages/build/drupal/api.js:135:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RetryOperation._fn (/var/lib/tugboat/docroot/vendor/va-gov/content-build/node_modules/p-retry/index.js:50:12) {
  attemptNumber: 11,
  retriesLeft: 0
}
error Command failed with exit code 1.
```
 As of yet I don't think this will impact getting this across the line by sprint close, but will update here if that changes.

**Comment by jilladams** [comment] 2023-06-28 00:12
BLESS.

**Comment by dsasser** [comment] 2023-06-28 17:46
> The BE PR is up but a graphql test is failing due to an error that I'm working to resolve.

Fortunately this turned out to be a Tugboat glitch. The BE PR has now been approved and merged.

**Comment by dsasser** [comment] 2023-06-30 22:26
Verified in prod

<img width="1525" alt="Screenshot 2023-06-30 at 3 25 55 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/221539/046810d3-bc8f-4097-bd3e-bbb00325c359">

**Closed** 2023-06-30 22:25 UTC
Labels: Drupal engineering, VA.gov homepage, Technical debt, Public Websites
