### ISSUE TITLE
Document GovDelivery integrations with VA.gov CMS

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#4595] opened 2021-03-08 03:01 UTC
Currently adding this to #1392 epic but another epic may be more appropriate. 

## User Story or Problem Statement

As a CMS user or team member, I want to understand the relationships between Drupal and GovDelivery for the following functionality

1. Sending emails - what content is eligible to be pushed to Veterans by VA.gov CMS
2. Content release - when, why, and how does GovDelivery trigger one?
3. Managing links where Veterans can subscribe to GovDelivery

## Acceptance Criteria

Documentation is clear for 
- [x] Developers working on GovDelivery integration
- [x] CMS editors adding content 
- [ ] CMS editors managing govdelivery subscription URLs
- [ ] Content release engineers working on automated content release cycles.

**Comment by oksana-c** [comment] 2021-03-08 11:57
this is a dupe of #1361 , but I'll close the old one, since is looks like this new issue covers more than docs for engineers.
I can see a good use case for a user guide here. What do you think @kevwalsh?

Also linking to the lucidchart **"Content-only deploy architecture"** which @swirtSJW pointed out has details around GovDelivery integration - https://lucid.app/lucidchart/d413a48c-02ae-483e-8c44-812dedb0de76/edit?shared=true&page=3VS3b-25UGW-#

**Comment by kevwalsh** [comment] 2021-03-08 16:34
Yep on user guide and possibly a few places in the UI, which could potentially link out to the user guide. 

* `VAMC system` content type. 
* `VAMC system operating status` content type
* `Situation update` paragraph type (part of the VAMC system operating status)

**Comment by swirtSJW** [comment] 2021-11-04 21:44
This diagram should be reproduces as part of this.  The diagram is outdated, but shows the general idea.
![image](https://user-images.githubusercontent.com/5752113/140424346-c2626728-2cb1-4906-aa5d-a1fbdd428a53.png)

This PR kicks off the documentation but is not specific enough to tick all the ACs on this issue.   I think some of the ACs related to end users should be in a knowledge base article.

**Comment by Agile6MSkinner** [comment] 2024-12-27 20:39
This item is stale and likely obsolete. Closing.

**Closed by Agile6MSkinner** 2024-12-27 20:39 UTC
Labels: Enhancement, VAMC, Facilities, Needs refining, Documentation, sitewide
