### ISSUE TITLE
PHP Exception  Database error

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#2905] opened 2020-09-11 19:56 UTC
## Description
I am seeing a bunch of these at deploy time
![image](https://user-images.githubusercontent.com/5752113/92967222-dbc17c00-f446-11ea-8531-232bce0c16df.png)

Text
```
Exception: Database error: SQLSTATE[HY000] [14] unable to open database file in SimpleSAML\Store\SQL->__construct() (line 63 of /var/www/cms/docroot/vendor/simplesamlphp/simplesamlphp/lib/SimpleSAML/Store/SQL.php).
```

They are coming through on various paths and always on the same user.  User 1
User | axcsd452ksey

## Acceptance Criteria
* Testable_Outcome_X
* Testable_Outcome_Y
* Testable_Outcome_Z

**Comment by ElijahLynn** [comment] 2020-09-11 20:03
Duplicate of https://github.com/department-of-veterans-affairs/va.gov-cms/issues/2570

**Comment by indytechcook** [comment] 2020-09-23 14:22
Closing since it's a duplicate

**Closed by indytechcook** 2020-09-23 14:22 UTC
Labels: DevOps
