### ISSUE TITLE
Unpublished Content showing in Outdated Content Tool

### ISSUE THREAD

**Issue by productmike** [department-of-veterans-affairs/va.gov-cms#13697] opened 2023-05-12 17:46 UTC
## Defect Description
Issue here: https://dsva.slack.com/archives/CT4GZBM8F/p1683830188937019

Steps to Reproduce: TBD

## User Expectation
As an editor, I expect that anything that displays in the Outdated Content tool to be published content and actionable, so that content visible to the VA users are updated. If hidden from VA user view, I should not be focusing my efforts on updating that content.

**Comment by EWashb** [comment] 2023-08-31 02:43
Confirming above assumption that we should not show unpublished content in the outdated content audit.

**Comment by ndouglas** [comment] 2023-10-31 14:36
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VAgov-CMS-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/13697?planning-poker) with Zenhub @edmund-dunn @JunTaoLuo @tonytaylor

**Comment by ndouglas** [comment] 2023-11-01 12:11
This is a duplicate of #13982.

**Closed by ndouglas** 2023-11-01 12:11 UTC
Labels: Defect, Drupal engineering, CMS Team
