### ISSUE TITLE
[CMS COLLAB CYCLE INTAKE] Public Websites, Benefit Content Model Hardening

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#12257] opened 2023-01-18 00:36 UTC
### What type of request are you making?

- [ ] Update to an existing CMS feature (including product iterations, updating DS components or page layouts and nav changes)
- [X] New CMS feature (New content types, DS components, workflows or products)
- [ ] Content audit (either one time audits or resuable tools)
- [ ] Change Management review (for any visible changes to the CMS, workflow or content model)
- [ ] Other

### Please choose the team that is requesting the Collab Cycle kickoff.

Public Websites

### When did/will you start working on this product/feature?

Q3 2022

### When will your feature need to launch?

Target Q1 2023

### Are you doing research with VA.gov users or editors?

No

### Will your work involve changes to...?

CMS content model, CMS features that span multiple products or work streams

### Please add a link to your product outline issue.

TBD

### Additional Information

A few notes on the origin of this, and previous effort:
- Danielle T is driving the thought on this strategy, sketched out the MVP, owns the content itself, etc.
- In Q4 2022, Danielle provided a spreadsheet of all VA benefits, and Dave Pickett is scheduled to get that into Airtable as a "draft content model" in Sprint 76, started 1/17/23
- Expected first consumers of the new content model will include Benefit Hubs and Chatbot

### Notify the Sitewide CMS team of this ticket in the cms-support Slack channel.

- [X] I acknowledge that I must notify `#cms-support` after submitting this issue.

**Comment by jilladams** [comment] 2023-02-23 17:01
Hello old friends. We did a kickoff for this and the output was: come back when you have a design. 

And now, thanks to the efforts of @davidmpickett and @chri5tia (and @wesrowe !), we have a map of the plan => https://docs.google.com/spreadsheets/d/1gP6x-QLFRrJlLWdCEE1COAZXU-kRRmFKSc0sIlc_tyM/edit#gid=0 

Dave has also reviewed this a bit with @timcosgrove along the way for Drupal insights. 

Our next step is to take it to Dave C and Danielle T for review. But: we would like to verify with you all that you have no changes / critical feedback, before we do. I'd like to schedule a meeting to over it -- @EWashb @dawnpruitt and @swirtSJW I think the 3 of you should be there. Anyone else?

**Comment by jilladams** [comment] 2023-02-23 17:32
JK, we need to knock out #12731 for schema.org implications first, _then_ will schedule review with y'all.

**Comment by jilladams** [comment] 2023-03-24 21:28
Closing as a dupe of https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9912

**Closed by jilladams** 2023-03-24 21:28 UTC
Labels: CMS Team
