### ISSUE TITLE
WYSWIG Link has no internal link autocomplete

### ISSUE THREAD

**Issue by omahane** [department-of-veterans-affairs/va.gov-cms#14489] opened 2023-07-21 20:23 UTC
## Describe the defect
When in a WYSIWYG, creating a link does not offer an autocomplete option for finding internal content.

## To Reproduce
1. Go to an [Event](https://vacms-12252-drupal-10-kaaijt1fsqp1qasl6a8metonglihfa26.ci.cms.va.gov/node/59356/edit)
2. Select some text in the **Full event description**
3. Click the Link button in the toolbar
4. Validate that you don't have an autocomplete field for finding internal content to which to link

## AC / Expected behavior
When creating a link, an autocomplete should allow the editor to find internal content by typing words in the content title.

## Screenshots
![Screenshot 2023-07-21 at 1 52 25 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/766573/d7fdbf7d-a5b0-47e1-b23d-48298e643bed)

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS workstream (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

### Team
Please check the team(s) that will do this work.

- [x] `CMS Team`
- [ ] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`
- [ ] `Accelerated Publishing`

**Comment by laflannery** [comment] 2023-07-28 12:53
Duplicate of #12564

**Comment by tonytaylor** [comment] 2023-07-31 19:27
I was able to get a working URL autocomplete field:
![20230731--1420](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/607178/f1d1df7d-0d87-4523-ae65-c29fef4e98de)

**Comment by edmund-dunn** [comment] 2023-08-02 15:50
This has been fixed and merged into the D10 branch.

**Closed by edmund-dunn** 2023-08-02 15:50 UTC
Labels: Defect, Drupal engineering, Needs refining, CMS Team
