### ISSUE TITLE
Resources and Support: allow editors to choose what categories are shown on main landing page 

### ISSUE THREAD

**Issue by aklausmeier** [department-of-veterans-affairs/va.gov-cms#18464] opened 2024-07-05 15:26 UTC
## Status
**[2024-07-29] [Fran]** Amanda and Michelle weighed in after Daniel presented to options. The decision was made to go with the hard-coded option. Fran updated the ticket. 
**[2024-07-25] [Daniel]** Daniel [unpacked](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18464#issuecomment-2251159228) the engineering aspects and discovered some risks and options
**[2024-07-24] [Fran]** Dave Picket indicated that this needs to go through refinement. I've removed the 8 points and added the Needs refining tag.
**[2024-07-23] [Fran]** Amanda mentioned that a decision needs to be made as to how this will be implemented. I commented with questions to Dave Picket and Daniel S.
**[2024-07-23] [Fran]** Per Michelle M, targeting Sprint 9, if possible.

## Background
With the new Family Member and Caregiver Benefit Hub being published, the [Resources and Support landing page](https://www.va.gov/resources/) should accommodate showing this Hub topic and related articles without it being hidden or pushing down the Health care topics to the truncated/hidden area. 

Resources and support will be undergoing a future redesign but in the interim, we need a way to show this topic with a light lift for an MVP solution.

## Description 

<img width="400" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWU1QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f13caa0d2f6e1aef39396a86163000448083ca81/Screenshot%202024-07-05%20at%209.36.34%20AM.png" alt="Screenshot 2024-07-05 at 9.36.34 AM.png" />

Drupal [editing screen](https://prod.cms.va.gov/node/8296/edit) shows listed in user-specified order. FE is alphabetical with exception of first and last ones, and truncated to limit to 6 categories. 
<img width="400" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBKzI1QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d187fa53c0e578d63f4bb6f695f55cb61e63d80f/Screenshot%202024-07-05%20at%2012.56.09%20PM.png" alt="Screenshot 2024-07-05 at 12.56.09 PM.png" />

**Some potential options:**

- remove "show all topics" button and no longer hide topics
- allow editor to rearrange order of topics, not dependent on an alphabetic order

## Decisions
**Hard-Coded Conditional (fastest, but with tech debt):**  Points 3️⃣
- Add a conditional that checks if the page is /resources (there is another part of the codebase doing exactly this) and
  - Renders all the categories
  - Removes the show all categories button

Note that Daniel has confirmed that the conditional option won't change the sort order, we'll leave the existing sorting behaviors intact so as not to cause regressions or unexpected bugs.

## Acceptance criteria
- [x] New topic has capability of being shown without hidden content shown after button is clicked 
- [x] Sort order is preserved
- [x] Test the happy and unhappy paths to ensure no unintended issues arise
  - [x] Need to determine which paths to test.
- [ ] Per comments below, update "Go to all articles" links for each category to be more descriptive:
  - [ ] Go to all articles about VA account and profile
  - [ ] Go to all articles about decision reviews and appeals
  - [ ] Go to all articles about disability
  - [ ] Go to all articles about education and training
  - [ ] Go to all articles about health care
  - [ ] Go to all articles about other topics and questions 
- [x] Design review
- [x] Accessibility review

**Comment by aklausmeier** [comment] 2024-07-05 18:56
New concern came up during discussions with Mikki and Danielle, stubbed ticket for consideration, hoping it might be a quick/light lift. Let me know if you have any questions.

cc @FranECross @Agile6MSkinner

**Comment by FranECross** [comment] 2024-07-09 22:09
Moved to Next Refinement for review by engineers/Amanda next week. cc @aklausmeier

**Comment by aklausmeier** [comment] 2024-07-23 20:40
@FranECross @Agile6MSkinner This is pointed but not clear on which solution will be implemented. I suggested a few options but was hoping an engineer could refine to inform best solution to move forward with an MVP solution and hopefully lighter lift.

**Comment by FranECross** [comment] 2024-07-23 21:49
@dsasser @davidmpickett We'd like, if possible, to pull this ticket into the sprint tomorrow, but as Amanda indicates above some thought needs to go into what the implementation will actually be. Do you want this to be a Spike, that you can either then implement using this ticket, if the Spike efforts isn't that big, or attempt to refine before tomorrow's meeting? Apologies for this late question, but when I saw it was pointed, I thought the path forward had already been determined.

**Comment by davidmpickett** [comment] 2024-07-23 22:23
I don't think we should skip the normal refinement process on this. Doesn't seem like there's been any engineering feasibility / lift conversation yet. IMO, SPIKEs should be reserved for complicated technical investigations. I think this just needs clarity on what the requirements are so that the right technical implementation can applied. 

1. Display Family Member Benefits category on R&S landing page in position (x)
   - Probably entirely FE work, might only be 3 points
2. Allow CAIA editors to control order of topics on R&S landing page
   - Requires Drupaling in addition to FE, is that MVP?

**Comment by FranECross** [comment] 2024-07-23 22:32
I imagine the points should be removed and Needs refining tag should be added? I (and I think Michelle) thought it was ready to go. Thanks again!

**Comment by mmiddaugh** [comment] 2024-07-24 12:45
> Display Family Member Benefits category on R&S landing page in position (x)

Yes, the goal is to make the new Family Member Benefits category visible but not at the risk of bumping another category out of view and not necessarily dictating position. 

I'm guessing there might be other low lift options here. 
- If the number of visible categories is currently limited, could that limit be removed? If so, what would be the outcome?
- What would be the outcome if the "Show all topics" button were removed?

@aklausmeier

**Comment by aklausmeier** [comment] 2024-07-24 14:55
@FranECross I provided 2 options in the ticket, an engineer should weigh in on which one is the lightest lift and move forward OR suggest an even lighter lift solution. 

> Some potential options:

- > remove "show all topics" button and no longer hide topics
- > allow editor to rearrange order of topics, not dependent on an alphabetic order

If removing the "Show all topics" button and showing all hubs on landing page is the lightest lift, that is my preference.

**Comment by jilladams** [comment] 2024-07-24 18:04
Assigned to @FranECross for follow up / refinement, and moved to top of Next Refinement.

**Comment by dsasser** [comment] 2024-07-25 18:34
## Engineering Pre-finement notes:

The categories are coming back from GraphQL in the order that they are arranged in the UI, but they are ultimately being re-arranged by a liquid filter [formatVaParagraphs](https://github.com/department-of-veterans-affairs/content-build/blob/66b830fb6c86129957394ef83a6fa720a01562ce/src/site/filters/liquid.js#L55) before being rendered.

The filter re-orders the categories, placing 'VA account and profile' first, 'Other topics and questions' last, then everything else alphabetically.

⚠️ The challenge here is that this filter is being used not only by Basic Landing Pages but also any entity that uses the corresponding paragraph type, Lists of Links. So any change we do to the filter could affect other pages if we are not careful.

On the FE, the template affected is the [basic_landing_page.drupal.liquid](https://github.com/department-of-veterans-affairs/content-build/blob/main/src/site/layouts/basic_landing_page.drupal.liquid#L40). This template hands over the rendering of the categories to the  [lists_of_links.drupal.liquid](https://github.com/department-of-veterans-affairs/content-build/blob/main/src/site/paragraphs/lists_of_links.drupal.liquid) liquid template, which leverages the formatVaParagraphs filter.

<details>

<summary>formatVaParagraphs liquid filter</summary

```javascript

  liquid.filters.formatVaParagraphs = vaParagraphs => {
    const FIRST_SECTION_HEADER = 'VA account and profile';
    const LAST_SECTION_HEADER = 'Other topics and questions';

    // Derive the first and last sections.
    const firstSection = _.find(
      vaParagraphs,
      vaParagraph =>
        vaParagraph.entity.fieldSectionHeader === FIRST_SECTION_HEADER,
    );
    const lastSection = _.find(
      vaParagraphs,
      vaParagraph =>
        vaParagraph.entity.fieldSectionHeader === LAST_SECTION_HEADER,
    );

    const otherSections = _.filter(
      vaParagraphs,
      vaParagraph =>
        vaParagraph.entity.fieldSectionHeader !== FIRST_SECTION_HEADER &&
        vaParagraph.entity.fieldSectionHeader !== LAST_SECTION_HEADER,
    );

    return [
      firstSection,
      // Other sections is sorted alphabetically by `fieldSectionHeader`.
      ..._.orderBy(otherSections, 'entity.fieldSectionHeader', 'asc'),
      lastSection,
    ];
  };

```

</details>

<details>

<summary>Graphql query</summary


```graphql
fragment listsOfLinks on ParagraphListsOfLinks {
    entityId
    fieldSectionHeader
    fieldVaParagraphs {
      entity {
        entityBundle
        ... on ParagraphListOfLinks {
          fieldSectionHeader
          fieldLink {
            title
            url {
              path
            }
          }
          fieldLinks {
            title
            url {
              path
            }
          }
        }
      }
    }
  }

query MyQuery {
      nodeQuery(
        limit: 25
        offset: 0
        sort: { field: "nid", direction:  ASC }
        filter: {
        conditions: [
          { field: "status", value: ["1"], enabled: true },
          { field: "type", value: ["basic_landing_page"] },
          { field: "nid", value: "8296"}
        ]
      }) {
        entities {
          ... on NodeBasicLandingPage {
            fieldContentBlock {
              entity {
                entityBundle
                ... listsOfLinks
              }
            }
          }
        }
      }
}

```

</details>

## Possible Solutions

### Hard-Coded Conditional (fastest, but with tech debt)

Add a conditional that checks if the page is /resources (there is another part of the codebase doing exactly this) and
- Renders all the categories
- Removes the show all categories button

### Drupal Field (more complex, but more adaptable)

Add a Drupal boolean field to Paragraph to control display of the categories. This would include:
- A new Drupal boolean field to the lists_of_links paragraph. A single checkbox which indicates that all categories should be displayed. (Drupal engineering)
- Checking this box in the Drupal /resources node (Content)
- Adding the new field to the GraphQL query
- Adapting the liquid filter to accommodate the new field. If set, the categories will all be rendered and there will be no 'Show all topics' button.

**Comment by FranECross** [comment] 2024-07-25 18:44
@dsasser Thanks so much for the research and prefinement notes. Are you able to swag estimates for the two options above? I [messaged](https://dsva.slack.com/archives/C03LFSPGV16/p1721933036649009) Michelle in Slack (for when she's back on Monday) asking her to review.

I do see in the description this note, and wonder if the hard coded is the fastest/least effort if that would be the way to go, and then a different, adaptable solution be implemented during the redesign?: "Resources and support will be undergoing a future redesign but in the interim, we need a way to show this topic with a light lift for an MVP solution."

cc @aklausmeier @jilladams

**Comment by dsasser** [comment] 2024-07-25 18:49
@FranECross 

> Are you able to swag estimates for the two options

Hard-coded FE: 3
Drupal Field: 8

**Comment by FranECross** [comment] 2024-07-26 14:38
Amanda responded in the [Slack thread](https://dsva.slack.com/archives/C03LFSPGV16/p1721935924119929?thread_ts=1721933036.649009&cid=C03LFSPGV16): My vote is the hard-coded, lightest lift but would like Michelle to weigh in on Monday.

**Comment by FranECross** [comment] 2024-07-29 17:57
@Daniel Sasser Updating ticket with Slack question from [Michelle](https://dsva.slack.com/team/U03GNFJ7WG5)
 I assume adding the conditional will not change the existing sort order, which is 'VA account and profile' first, 'Other topics and questions' last, then everything else in alpha order. Can you confirm?
I agree with hard-coded approach (but if the sort order is affected, we may need to add a separate task to restore the order)

**Comment by dsasser** [comment] 2024-07-29 18:32
> @daniel Sasser Updating ticket with Slack question from [Michelle](https://dsva.slack.com/team/U03GNFJ7WG5) I assume adding the conditional will not change the existing sort order, which is 'VA account and profile' first, 'Other topics and questions' last, then everything else in alpha order. Can you confirm? I agree with hard-coded approach (but if the sort order is affected, we may need to add a separate task to restore the order)

@FranECross @mmiddaugh yes the conditional option won't change the sort order, we'll leave the existing sorting behaviors intact so as not to cause regressions or unexpected bugs.

**Comment by FranECross** [comment] 2024-07-29 18:37
Thanks so much, @dsasser . I've updated the ticket with a Decision section, noting the hard-coded decision, and added "Sort order is preserved." to the AC for posterity. So you consider this ready for the Ready pipeline, or do you want to look at it one more time in refinement this week?

**Comment by randimays** [comment] 2024-08-05 16:51
Pulling into sprint 9 as stretch.

**Comment by randimays** [comment] 2024-08-06 15:22
This will carry over to sprint 10. Adding and testing on the Resources & Support landing page was straightforward, but it is not clear where else this component is used, so I'm working on adding test data into a Tugboat.

**Comment by randimays** [comment] 2024-08-06 20:53
I made the changes for the R&S landing page ✔️ But I'm stuck on how to check the Lists of Links component on other pages (the version with max 6 categories).

@davidmpickett and @omahane helped me discover that Benefit Hub Detail Pages can use Lists of Links. I added test data in a Tugboat to these pages:

- https://web-w4azz2khpzdi53uymp1gxkpi0fbqdlqu.demo.cms.va.gov/housing-assistance/home-loans/how-to-request-coe
- https://web-w4azz2khpzdi53uymp1gxkpi0fbqdlqu.demo.cms.va.gov/change-direct-deposit

But the test data doesn't show up in the web view. I looked at the Metalsmith data to see what was coming through and it's missing content:
<img width="265" alt="Screenshot 2024-08-06 at 3 30 38 PM" src="https://github.com/user-attachments/assets/9fa6b4c1-a2a6-46c0-af94-dc7a47ef8a57">

Here's what that same data looks like on R&S landing page:
<img width="525" alt="Screenshot 2024-08-06 at 3 30 44 PM" src="https://github.com/user-attachments/assets/e0509299-8a19-4e93-93dd-ae0085b8f183">

This is a GraphQL issue, so I looked at the [query for lists of links](https://github.com/department-of-veterans-affairs/content-build/blob/main/src/site/stages/build/drupal/graphql/paragraph-fragments/listsOfLinks.paragraph.graphql.js). The only place this query used is in the [BasicLandingPage GraphQL](https://github.com/department-of-veterans-affairs/content-build/blob/a1010cca611685de00a2a34d0818f2fbc436e698/src/site/stages/build/drupal/graphql/nodeBasicLandingPage.graphql.js#L26). The `basic_landing_page` template in content-build only maps to one page: R&S landing page.

Noteworthy CMS warning:
<img width="600" alt="Screenshot 2024-08-05 at 2 35 21 PM" src="https://github.com/user-attachments/assets/9ca2da2f-2797-4105-9b29-006c895223c2">

@dsasser (@jilladams, @FranECross): Is it safe to say that we can remove the truncation / "show all" button from the Lists of Links component? It doesn't look like there is another public-facing use case for it other than R&S landing page.

**Comment by FranECross** [comment] 2024-08-06 21:52
@randimays I would love to defer to @dsasser and/or @jilladams, since they have so much more historical knowledge. My knee-jerk is to say 'yes'.

**Comment by randimays** [comment] 2024-08-08 16:39
@dsasser to your point from scrum: it is possible to add this content type to Benefit Hub detail pages, but considering the `Resources and support or User Guides only!` messaging: is it possible to remove this content type from those pages so no one can try to add it?

**Comment by dsasser** [comment] 2024-08-08 18:21
> @dsasser (@jilladams, @FranECross): Is it safe to say that we can remove the truncation / "show all" button from the Lists of Links component? It doesn't look like there is another public-facing use case for it other than R&S landing page.

> @dsasser to your point from scrum: it is possible to add this content type to Benefit Hub detail pages, but considering the Resources and support or User Guides only! messaging: is it possible to remove this content type from those pages so no one can try to add it?

@randi great [discovery](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18464#issuecomment-2272132968)!

B.L.U.F.:  I suggest we do as Randi is recommending, and remove the truncation / "show all" button from the Lists of Links component.

My thought for the fast version when originally refining this ticket was to just use a conditional  check for the `/resources` path such as what is done [page.js](https://github.com/department-of-veterans-affairs/content-build/blob/2ae2d915509bf876cf2c4deb2fd07413ced476d0/src/site/stages/build/drupal/page.js#L530). Which admittedly is not ideal and pretty ugly. 

I looked at all current uses of the lists_of_links paragraph (some nodes use the same paragraph type multiple times, but we only list unique instances below):

| Node Type | Uniqe Count |
|--------|--------|
| Landing Page `basic_landing_page` | 1 |
| Centralized Content `centralized_content` | 1 | 
| CMS Knowledge Base Article `documentation_page`  | 9 |

Landing Page
There is only one Landing Page with a `lists_of_links`, which is the landing page for the Resources and Support home page at [/resources](https://www.va.gov/resources/). This is the primary page we want to affect.

Centralized Content
The only node using `lists_of_links` is an archived 404 page, so this page never gets built by content-build, and so changing the behavior of the component would have no affect here.

CMS Knowledge Base Article
These are not rendered on VA.gov, so changing the content-build behavior would have no affect.

**Comment by randimays** [comment] 2024-08-08 18:35
Thank you @dsasser for looking into this! I'll remove the truncation from the Lists of Links component.

**Comment by randimays** [comment] 2024-08-12 13:52
@FranECross 

In PR reviews, @laflannery asked if we could update the "Go to all articles" links on R&S landing page categories to be specific to each category since the links as-is are duplicative. [See #2 in her comment](https://github.com/department-of-veterans-affairs/content-build/pull/2226#issuecomment-2283987160).

Note that these are editor-managed fields in Drupal, so we can change them now and they have the ability to change them back. But if/when editors add new categories they will have our new pattern to follow.

This would require a change in prod Drupal that would then propagate to lower environments over the next day or so. The FE work for this ticket is already complete.

Are you OK with us making those link text updates as part of this ticket?

**Comment by randimays** [comment] 2024-08-12 13:55
@laflannery For those proposed link text updates, here's what I'm assuming we'd use (the last one I'm not sure about):

- Go to all VA account and profile articles
- Go to all burials and memorials articles
- Go to all decision reviews and appeals articles
- Go to all disability articles
- Go to all education and training articles
- Go to all health care articles
- Go to all life insurance articles
- Go to all pension articles
- Go to all other topics and questions articles

**Comment by laflannery** [comment] 2024-08-12 14:05
The last one could be "Go to all articles about other topics and questions" which makes a bit more sense to me. 

And if we did want to follow the same pattern we could flip the other ones:
- "Go to all articles about health care"
- "Go to all articles about VA account and profile"
- "Go to all articles about education and training"
- etc.

But I don't have a preference on that either way.

**Comment by FranECross** [comment] 2024-08-12 18:28
> @FranECross
> 
> In PR reviews, @laflannery asked if we could update the "Go to all articles" links on R&S landing page categories to be specific to each category since the links as-is are duplicative. [See #2 in her comment](https://github.com/department-of-veterans-affairs/content-build/pull/2226#issuecomment-2283987160).
> 
> Note that these are editor-managed fields in Drupal, so we can change them now and they have the ability to change them back. But if/when editors add new categories they will have our new pattern to follow.
> 
> This would require a change in prod Drupal that would then propagate to lower environments over the next day or so. The FE work for this ticket is already complete.
> 
> Are you OK with us making those link text updates as part of this ticket?

@randimays I am okay with you making the link text changes. Should I or will you be stubbing the drupal ticket? Thanks!

**Comment by randimays** [comment] 2024-08-12 19:01
@FranECross I think we can make those changes as part of this ticket; we can just add ACs. I'll do that now.

**Comment by randimays** [comment] 2024-08-13 16:58
The category truncation has been removed, and the link text has been updated and validated successfully in production. Closing as complete!

**Closed by randimays** 2024-08-13 16:58 UTC
Labels: VA.gov frontend, Resources and support, Public Websites, sitewide
