### ISSUE TITLE
Notices related to log revision message requirement on vet center content.

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#5433] opened 2021-05-24 17:20 UTC
**Describe the defect**
When editing a Vet Center CAP I see the following message
![image](https://user-images.githubusercontent.com/5752113/119384274-72129680-bc92-11eb-867d-fc00422f9fac.png)

```
Notice: Undefined index: field_nearby_vet_centers in _va_gov_vet_center_require_revision_message() (line 622 of modules/custom/va_gov_backend/va_gov_backend.module).
Warning: Invalid argument supplied for foreach() in _va_gov_vet_center_require_revision_message() (line 622 of modules/custom/va_gov_backend/va_gov_backend.module).
```

This need to properly defend against an assumed index `field_nearby_vet_centers` or other indexes

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information if relevant, or delete):**

**Additional context**
Add any other context about the problem here. Reach out to the Product Managers to determine if it should be escalated as critical (prevents users from accomplishing their work with no known workaround and needs to be addressed within 2 business days).

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS objective (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Core Application Team`
- [x] `Product Support Team`

**Comment by EWashb** [comment] 2023-02-24 16:50
@swirtSJW since you were just doing this work- is this still happening? I don't think so and if not we can close this.

**Comment by davidmpickett** [comment] 2023-04-20 21:03
@swirtSJW review if this is still an issue

**Comment by davidmpickett** [comment] 2024-07-01 23:08
Was not able to reproduce. Closing

**Closed by davidmpickett** 2024-07-01 23:08 UTC
Labels: Defect, Facilities, Needs refining, Vet Center, crew-sitewide, sitewide
