### ISSUE TITLE
Facility name change: From Columbus VA Clinic to Robert S. Poydasheff VA Clinic

### ISSUE THREAD

**Issue by TroyA6** [department-of-veterans-affairs/va.gov-cms#10607] opened 2022-09-01 21:16 UTC
## Intake
- Submitter: Rhonda Albo @ VA Central Alabama
- [x] If the submitter is an editor, send them the link to the CMS Knowledge Base (KB) article on facility basic data for their product (VAMC or Vet Center). Let them know that facility changes can take between 75 days and 4 months after submitting a request, according to VAST administrators.
- [x] Other stakeholders to include on updates, if any: Rhonda Albo

Original Jira ticket: https://va-gov.atlassian.net/browse/VAHELP-4551

Link to facility: https://www.va.gov/central-alabama-health-care/locations/robert-s-poydasheff-va-clinic/

## Acceptance criteria

- [x] The H1 title change comes from Lighthouse to Drupal.
- [x] Coordinate with Facilities team to create a [redirect request](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/new?assignees=&labels=Redirect+request&template=redirect-request-facility-url.md&title=Redirect+Request+for%3A+%3Cinsert+facility+name%3E)
- [x] CMS engineer locates the newly renamed VAMC Facility (https://prod.cms.va.gov/admin/content/bulk) Search by new name
- [x] CMS engineer updates URL alias for this facility
- [x] CMS engineer resaves this facility
- [x] CMS engineer makes bulk alias changes to facility service nodes. (https://prod.cms.va.gov/admin/content/bulk?type=health_care_local_health_service)
- [x] CMS engineer bulk saves fixed titles to facility service nodes. (https://prod.cms.va.gov/admin/content/bulk?type=health_care_local_health_service)
- [x] CMS engineer updates menu title for facility
- [x] CMS engineer updates Alt text for facility image, if relevant.
- [x] CMS engineer updates Meta description (TBD: some backwards compatibility for SEM, by including something like ", formerly known as [previous name]".
- [x] CMS engineer edit facility node and remove flag `Changed name` then save node.
- [ ] HD notifies editor and any other stakeholders.
</details>

## CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [x] `⭐️ User support`

**Comment by stefaniefgray** [comment] 2022-09-08 21:20
## Pages that have been transferred from Columbus to Poydasheff:
- https://prod.cms.va.gov/central-alabama-health-care/locations/robert-s-poydasheff-va-clinic
- https://prod.cms.va.gov/central-alabama-health-care/locations/robert-s-poydasheff-va-clinic/physical-therapy-occupational-therapy-and-kinesiotherapy
- https://prod.cms.va.gov/central-alabama-health-care/locations/robert-s-poydasheff-va-clinic/prosthetics-and-rehabilitation
- https://prod.cms.va.gov/central-alabama-health-care/locations/robert-s-poydasheff-va-clinic/telehealth
- https://prod.cms.va.gov/central-alabama-health-care/locations/robert-s-poydasheff-va-clinic/optometry
- https://prod.cms.va.gov/central-alabama-health-care/locations/monroe-county-va-clinic/patient-advocates
- https://prod.cms.va.gov/central-alabama-health-care/locations/robert-s-poydasheff-va-clinic/podiatry
- https://prod.cms.va.gov/central-alabama-health-care/locations/robert-s-poydasheff-va-clinic/radiology
- https://prod.cms.va.gov/central-alabama-health-care/locations/robert-s-poydasheff-va-clinic/audiology-and-speech
- https://prod.cms.va.gov/central-alabama-health-care/locations/robert-s-poydasheff-va-clinic/social-work
- https://prod.cms.va.gov/central-alabama-health-care/locations/robert-s-poydasheff-va-clinic/women-veteran-care

## Pages that have NOT been transferred over -- am confused about why they're filed under /jackson-health-care/ when they are all assigned to VA Central Alabama

- [ ] https://prod.cms.va.gov/jackson-health-care/locations/columbus-va-clinic/laboratory-and-pathology
- [ ] https://prod.cms.va.gov/jackson-health-care/locations/columbus-va-clinic/pharmacy (Archived)
- [ ] https://prod.cms.va.gov/jackson-health-care/locations/columbus-va-clinic/mental-health-care-0 (Archived)
- [ ] https://prod.cms.va.gov/jackson-health-care/locations/columbus-va-clinic/my-healthevet-coordinator
- [ ] https://prod.cms.va.gov/jackson-health-care/locations/columbus-va-clinic/primary-care-0

^^ **IMPORTANT:** The fact that the URL says Jackson Health Care but the assignment says VA Central Alabama may be a _mistake_

These health services may actually be associated with the Columbus VA Clinic in Mississippi: https://prod.cms.va.gov/jackson-health-care/locations/columbus-va-clinic

Need to find out which one they are supposed to be linked to

**Comment by stefaniefgray** [comment] 2022-09-08 21:44
Just asked VA Central Alabama and VA Jackson about the Columbus/Columbus URL and naming discrepancies described above -- see: 
- https://va-gov.atlassian.net/browse/VAHELP-4775
- https://va-gov.atlassian.net/browse/VAHELP-4776

**Comment by stefaniefgray** [comment] 2022-09-09 02:10
@JayDarnell @christianmburk

**Comment by stefaniefgray** [comment] 2022-09-09 03:46
**Update:**

VA Jackson has confirmed that the URLs on the following pages are **wrong** and that these VAMC Facility Health Services belong to VA Central Alabama and the Robert S. Poydasheff VA Clinic:

 https://prod.cms.va.gov/jackson-health-care/locations/columbus-va-clinic/laboratory-and-pathology
 https://prod.cms.va.gov/jackson-health-care/locations/columbus-va-clinic/pharmacy (Archived)
 https://prod.cms.va.gov/jackson-health-care/locations/columbus-va-clinic/mental-health-care-0 (Archived)
 https://prod.cms.va.gov/jackson-health-care/locations/columbus-va-clinic/my-healthevet-coordinator
 https://prod.cms.va.gov/jackson-health-care/locations/columbus-va-clinic/primary-care-0

**Comment by JayDarnell** [comment] 2022-09-09 20:46
This facility health service is also listed as part of the Robert S Poydasheff family but has the wrong URL: 

https://prod.cms.va.gov/central-alabama-health-care/locations/monroe-county-va-clinic/patient-advocates

**Comment by JayDarnell** [comment] 2022-09-09 20:49
All 6 items above have been resaved with proper URLs

**Comment by stefaniefgray** [comment] 2022-09-23 23:25
@JayDarnell Thank you, Jay! 

Per the author: "There is a Monroe County VA Clinic 619GE and it has no relation to  Robert S. Poydasheff VA Clinic. Robert S. Poydasheff VA Clinic is in Muscogee County not Monroe County"

Just asked in https://va-gov.atlassian.net/browse/VAHELP-4775 about the Monroe County URL, waiting on editor response

**Comment by stefaniefgray** [comment] 2023-04-20 23:21
See https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13393

**Comment by stefaniefgray** [comment] 2023-04-20 23:21
Reopening because Facility Flag for "New Facility" must be removed once URL redirect request is complete: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13393

**Comment by stefaniefgray** [comment] 2023-05-05 23:14
Redirect confirmed! Closing

**Closed by stefaniefgray** 2023-05-05 23:14 UTC
Labels: VAMC, Facilities, User support, Change request
