### ISSUE TITLE
SAML logged-in user getting logged out and work lost.

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#1027] opened 2020-02-21 15:48 UTC
## Background 

[See Slack message](https://dsva.slack.com/archives/CDHBKAL9W/p1582235071113200?thread_ts=1582235071113200&cid=CDHBKAL9W) from @jenniferlee-dsva on February 20.

To do 
* 

Questions to look at
* session length
* where data is stored 
* audit how many users are logging in with PIV vs drupal user/password
* enforce PIV? 

Possible solutions, depending on the problem
* Patch drupal module?
* move data storage?

**Comment by howardbrande** [comment] 2020-02-21 15:51
Initial slack thread when issue was reported: https://dsva.slack.com/archives/CDHBKAL9W/p1582235071113200

**Comment by swirtSJW** [comment] 2020-02-21 15:51
Related #1023

**Comment by howardbrande** [comment] 2020-02-21 15:52
Additional slack thread between @howardbrande @swirtSJW and @ElijahLynn 
https://dsva.slack.com/archives/CT4GZBM8F/p1582235346448300

**Comment by ElijahLynn** [comment] 2020-02-28 19:32
I was able to stay logged in during yesterdays deploy while logged in with my PIV card on my GFE. I suspect this is because I may have had the admin role OR because one of my roles assigned to me is set to allow local login. I noticed I had a SESS* (Drupal/SQL) cookie and also a SAML* cookie which we suspected is stored in the SQLite DB. 

I will reproduce next by changing the role of my user to be just an editor.

**Comment by ElijahLynn** [comment] 2020-02-28 20:15
I just removed my `administrator` role and added `content_admin` and `content_publisher` to match the account of the user who reported this. I still have the same cookies. PROD deploy is coming up in 60 minutes and I am logged in to see if I can reproduce for today's deploy.

**Comment by ElijahLynn** [comment] 2020-02-29 00:54
I stayed logged in today when logged into SAML via the PROD deploy and could not reproduce this issue. I wonder if maybe the issue was related to the Drupal core update 8.8 the other day? 

Next steps would be to restore a backup to a lower environment and test the release on that environment but without doing a deploy and just running the steps manually without wiping the database.

**Comment by ElijahLynn** [comment] 2020-03-12 15:40
We could not reproduce this so we are putting this back in the backlog/icebox for now.

**Closed** 2020-04-13 16:41 UTC
Labels: Defect, DevOps, Needs grooming, ⭐️ Infrastructure
