### ISSUE TITLE
Semantic heading hierarchy in rich text fields

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#1968] opened 2020-06-04 20:23 UTC
## User Story or Problem Statement

There are 

The CMS doesn't always know where the content will be displayed, especially when content is displayed in multiple places, so we can't prescribe headings. 

Editors don't know how to write semantic headings, and decoupled makes this even harder. 

Limited html does not allow headings and sidesteps this semantic heading issue, but is limiting in many circumstances. 

## Acceptance Criteria
- [ ] TBD

## Implementation steps
<optional>

**Comment by EWashb** [comment] 2022-07-26 16:29
@laflannery thoughts on repurposing this ticket for some of the heading issues you found in the VAMC audit?

**Comment by laflannery** [comment] 2022-07-26 16:49
I think that would be fine, I think there are other issues out there (i.e. 4798) that are basically duplicates of this issue so we can use this for another purpose

**Comment by laflannery** [comment] 2023-06-14 18:28
Closing this as a duplicate of [#9571](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9571)

**Closed by laflannery** 2023-06-14 18:28 UTC
Labels: Needs refining, CMS Team, accessibility
