### ISSUE TITLE
Determine if our govdelivery implementation is affected by upcoming change.

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#3439] opened 2020-11-09 23:08 UTC
GovDelivery (Granicus) is making some changes to their API.   We need to assess these changes and see if they affect our implementation  of https://www.drupal.org/project/govdelivery_bulletins

Here is the notification from gov delivery:

```
Important Security Updates for API and TMS Services
Monday, November 23rd, 2020: Granicus will be deprecating the TLS 1.1 cipher security suites for all API services and TMS in accordance with FedRAMP authorization requirements and NIST recommended best practices.

This upgrade may impact the ability of your application to successfully connect to these services. Please use the information below (or provide the information below to the team that manages your API connections) to ensure continued connections between your application and the govDelivery application after 6:00 AM ET.

Following this change, API calls made to the govDelivery and TMS applications using TLS 1.1 or lower will no longer be successful.

Planned System Maintenance Date/Times:
Monday, November 23rd at 6:00am ET (11:00am BST)
Impacted Applications and Services:
Web Services/APls for the Communications Cloud Production environment via api.govdelivery.com
Targeted Messaging Service (TMS) Production Environment - used by organizations triggering messages directly from their own systems into Granicus via
tms.govdelivery.com
Web Services/APls for the Communications Cloud Stage Environment via stage-api.govdelivery.com
Targeted Messaging Service (TMS) Stage Environment - used by organizations triggering messages directly from their own systems into Granicus via stage-tms.govdelivery.com

You can test the future cipher suite configuration using the endpoints below. These endpoints are configured to represent what cipher suites the standard endpoints will allow after the change this afternoon. Please note, these endpoints are only intended for testing the updated cipher suite and it is not required or recommended to update your application to use these endpoints permanently. 

NOTE:  Please be aware that the testing endpoints are live and calls made to them could impact production data. We recommend using a read-only command (such as List Sent Bulletins for API calls) when verifying connectivity against the new cipher suites.

govDelivery API Users:

https://fcs-stage-api.govdelivery.com for our stage environment.
https://fcs-api.govdelivery.com for our production environment.
TMS Users:

https://fcs-stage-tms.govdelivery.com for our stage environment.
https://fcs-tms.govdelivery.com for our production environment.
If your agency employs a firewall to allow calls to be made, you will need to update your settings to allow access to the additional IP addresses for the "FCS" endpoints:

209.134.144.0/24
66.117.61.0/24
69.5.91.0/25
Supported Versions of TLS 
The list of supported cipher suites as of November 23rd are listed below:

TLSv1.2 256 bits ECDHE-RSA-AES256-GCM-SHA384
TLSv1.2 256 bits ECDHE-RSA-AES256-SHA384
TLSv1.2 256 bits ECDHE-RSA-AES256-SHA
TLSv1.2 256 bits AES256-GCM-SHA384
TLSv1.2 256 bits AES256-SHA256
TLSv1.2 256 bits AES256-SHA
TLSv1.2 128 bits ECDHE-RSA-AES128-GCM-SHA256
TLSv1.2 128 bits ECDHE-RSA-AES128-SHA256
TLSv1.2 128 bits ECDHE-RSA-AES128-SHA
TLSv1.2 128 bits AES128-GCM-SHA256
TLSv1.2 128 bits AES128-SHA256
TLSv1.2 128 bits AES128-SHA

```

----

If we are unaffected, notify Jeff B.    If we are affected, create ticket describing what we needs to be changed to keep gov delivery working and notify Jeff B.

**Comment by ElijahLynn** [comment] 2020-11-10 07:07
Looks like we are forcing 1.2 in at least one place, so we know the libraries/dependencies support it:

https://github.com/department-of-veterans-affairs/va.gov-cms/blob/8d2ca1762ec1b60d7a9c28a45e7d0bc01497bf13/docroot/modules/custom/va_gov_build_trigger/src/Service/BuildFrontend.php#L132-L135

**Comment by acrollet** [comment] 2020-11-17 18:42
This has been tested working from dev.cms.va.gov:

<img width="438" alt="Screen Shot 2020-11-17 at 11 41 22 AM" src="https://user-images.githubusercontent.com/101649/99432822-ef1b1880-28c9-11eb-9fe7-1c062fe7f7be.png">

**Comment by oksana-c** [comment] 2020-11-20 17:38
@acrollet, from you last comment I understand that we're unaffected by the change described in the ticket, you have confirmed that our govdelivery integration is working for the CMS and no follow up is required. If my understanding is correct, we can close this ticket.

**Comment by acrollet** [comment] 2020-11-20 17:39
@oksana-c confirmed!

**Comment by oksana-c** [comment] 2020-11-20 17:57
Thanks @acrollet ! 

@JeffBarnesUSDS , upcoming GovDelivery Security Updates for API and TMS Services will not affect the CMS functionality dependent on GovDelivery service ✅

**Closed** 2020-11-23 14:44 UTC
Labels: Core Application Team, Unplanned work
