### ISSUE TITLE
Update Drupal UI for Mental health phone number in VAMC Facility content type

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#17862] opened 2024-04-16 13:20 UTC
## Status

1. Decide how to format / break down the work in #17861
2. Update the formatting of this ticket to mirror that

## User stories
As an Editor, I want to list the fastest way for a Veteran to reach my department including navigating phone trees with multiple selections required. (Example in the wild: [Corpus Christi Mobile Clinic multi-extension MH #](https://dsva.slack.com/archives/C0FQSS30V/p1715101439584939).) 

As a Veteran, I want phone numbers to be accessible and tappable so that I can dial easily from mobile. 

As a DS owner, I want as many phone numbers as possible to use the Design System va-telephone component. 

## Background
Currently the Mental health phone number field in the VAMC Facility content type is using the Telephone number field type. This is a single field for the editor to enter the phone number information as well as any applicable extension information.  However, phone numbers and extensions require specific formatting in order to meet VA guidelines and to display and function properly on the FE. 

## Description
In order to make it easier for editors to enter their phone number correctly, we want to convert this single Telephone number field to use the Phone paragraph type field, which uses separate fields for the phone and extension.

### Additional Notes
- Please hide the **Label** field so that this is not available to editors, we do not need this because we are going to just keep the hardcoded label on the FE
- Add help text for paragraph field:

```[tasklist]
### Acceptance Criteria
- [x] Mental Health phone number field on VAMC Facility content type uses the Phone paragraph type
- [x] Label field is hidden in Drupal UI
- [x] Add help text on the Mental health phone number field (that will now be using the paragraph type):
```
**HELPTEXT:**
  > Enter the number Veterans should call to access mental health services at your facility. If your facility doesn't offer these services, enter the most appropriate system number. This number will be displayed everywhere your facility appears across VA.gov. View guidelines for editing VAMC facilities (opens in a new tab)

```[tasklist]
### Drupal - Field Migration
- [x] Script is written to migrate VAMC Facility Mental health phone numbers from field to paragraph.  Can use https://www.drupal.org/project/codit_batch_operations.
- [x] Cardinality for phone_number paragraph type on  VAMC Facility content type is set to 1
- [x] 'Label' field on phone_number paragraph type is hidden on VAMC Facility content type Node:Edit
- [x] Current`field_phone_number` is hidden but not removed
- [x] Update phone number audit view to display phone paragraph type field AND the Telephone number type field (in order to compare values before and after migration)
- [x] Migration is tested and validated
- [x] This field is pushed to Lighthouse. Update the Facility push for VAMCs to Lighthouse to include the new field in the payload. Send a test push.
  - [ ] Reach out to Adam Stilton in the #cms-lighthouse channel to request they verify the push was received by Lighthouse in their Sandbox environment.
- [x] Manual Code review
- [x] CMS PR is created and approved but not merged
```

**Comment by laflannery** [comment] 2024-05-07 17:14
From [this slack thread](https://dsva.slack.com/archives/C0FQSS30V/p1715101439584939), there was an instance of an editor adding an incorrectly formatted phone number - they added `855-864-0516press2thenpress5` into the single phone field. The question this has raised is if there is a way to chain extensions and have them dial correctly. Eli suggested that it might be `tel:8558640516,2,5` but we aren't positive. We also aren't sure if the component supports multiple extensions

**Comment by eselkin** [comment] 2024-05-07 17:20
We aren't even sure if we can provide one extension with a comma already in it to the va-telephone component.

**Comment by laflannery** [comment] 2024-05-07 17:24
One extension works when passed properly into the component, using the props as they should be used. 

I have confirmed that chained extensions does not work then the href is formatted as `href="tel:XXXXXXXXXX,X,X` I need to do more research into if this is even possible - regardless of using the component or not because I'm not sure it is

**Comment by eselkin** [comment] 2024-05-07 17:25
The comma equates to like a 1-2 second pause. But if the system doesn't operate quickly enough then no amount of commas work.

**Comment by davidmpickett** [comment] 2024-07-17 17:58
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VAgov-Sitewide-Product-Team-6645154188a81a1f7a0a9464/issues/department-of-veterans-affairs/va.gov-cms/17862?planning-poker) with Zenhub @dsasser @jv-agile6 @omahane

**Comment by omahane** [comment] 2024-08-07 16:16
What about migrating content? I'm not seeing that in the ACs.

**Comment by jilladams** [comment] 2024-09-17 15:44
PR in progress will target integration branch.

**Comment by jilladams** [comment] 2024-09-30 18:44
I moved this to Complete Pending Integration, since the PR is merged into the integration branch. 
@omahane pls add notes re: status with lighthouse, when you get a chance.

**Comment by omahane** [comment] 2024-09-30 21:53
I have asked LH to confirm that they can receive the new number correctly.

Their validation notwithstanding, a comparison of the queue items from staging the PR env of the integration branch confirms that the data is identical:

![Image](https://github.com/user-attachments/assets/eb55f6fc-d5f4-47c2-a269-4ed2b4a234d2)

**Comment by omahane** [comment] 2024-10-01 13:39
This morning (1 Oct 2024), Adam confirmed the successful receipt of the mental health phone number from the integration branch PR env.

https://dsva.slack.com/archives/C02BTJTDFTN/p1727732511160679

**Comment by jilladams** [comment] 2024-11-26 17:02
Launched in production today.

**Closed by jilladams** 2024-11-26 17:02 UTC
Labels: VAMC, Drupal engineering, Facilities, sitewide, ghp-deploy, points-8
