### ISSUE TITLE
Fetch lat/long from event's referenced facility, else perform forward lookup from Mapbox

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#9620] opened 2022-06-29 16:09 UTC

**Comment by davidmpickett** [comment] 2023-05-24 20:26
@jilladams @wesrowe This can probably be closed as a duplicate of https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13222

**Closed** 2023-05-24 23:00 UTC
Labels: Drupal engineering, Facilities, Public Websites, Events
