### ISSUE TITLE
Q&A: Add report in CMS for all page-specific Q&As for Content team

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#15142] opened 2023-09-07 18:35 UTC
### User story

**AS A** Content Editor
**I WANT** to be able to see all the page-specific (non-reusable) Q&As in the CMS
**SO THAT** I can get organized to reduce dupes, confusion, etc.

### Engineering notes / background
Form page could appear somewhere like: `admin/content/qa` and be Titled: "Page-specific Q&As".

## Acceptance criteria

- [x] Gathered column desires from Danielle/CAIA
- [x] Made report available in CMS, with columns:
  - Page-specific Q&A Question (not the group)
  - page title of the node where Page-specific Q&A appears (as a link?)
  - link to node where the Q&A appears if possible
  - Section of the node (in order to see its Benefit hub )
- [ ] ~Request CAIA feedback in #sitewide-content-accessibility-ia channel using prod CMS link~ - migrated to #15891

**Comment by wesrowe** [comment] 2023-09-07 23:43
@DanielleThierryUSDSVA – @davidconlon proposed in refinement today that CAIA would find it helpful to have a report in the CMS that pulls up all the page-specific (non-reusable) Q&As in the system into a single audit view. Assuming that sounds useful to you...
- What columns/fields would need to be present to make the report useful?
- Is there an example of another report that meets similar needs?

**Comment by DanielleThierryUSDSVA** [comment] 2023-09-13 02:29
Hi @wesrowe. Great questions. I think this would likely be useful, yes. I can't think of an example of a similar report. I think we'd want to have the benefit hub and page title or node to help categorize them and locate them on the pages.

**Comment by chri5tia** [comment] 2023-10-20 14:56
## Update 10/19/23

The implementation of non-reusable Q&A is a bit complex and inconsistent between nodes. I may end up needing to create different views for the different nodes that use this. I made a breakthrough in understanding the shape of the data that I should be able to use to finish building the view.

**Comment by chri5tia** [comment] 2023-10-24 17:04
## Update 10/24/23
This view is ready to go but only contains content on Campaign Landing Pages. I am trying to find other places where Page-specific Q&A is used.

**Comment by chri5tia** [comment] 2023-10-24 22:28
## Ride-along engineering notes that you can ignore

The only two content types that have the page-specific q&a enabled in config for the main content block are:

- page (Benefit Detail Page)
- health-care-region-detail-page

![Screenshot 2023-10-24 at 3 18 27 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/22764938/41c2e3d3-616d-48c5-aaa5-eb24de65eef9)
![Screenshot 2023-10-24 at 3 18 06 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/22764938/aec72542-25b3-443b-97fb-467a62007b7e)

Other places, not via the main content block:

- Campaign landing pages: added to view-based report

**Comment by chri5tia** [comment] 2023-10-25 17:36
## 10/25/23 Status and Points of Clarification
CAIA confirmed that a bulk of non-reusable Q&A content is in R&S. Rich text and other non-templated paragraph types were used for q&a and other content. R&S, as of 3 years ago or more, has not had the page-specific q&a enabled, only reusable.
There is not a way to generate a report for Resource & Support Q&A content because there is not a way to distinguish that type of content. 

Adding page/benefit detail page content to the report.

**Comment by jilladams** [comment] 2023-10-25 18:20
Note from sprint planning: 
Because Main Content > Rich text and Main Content > Accordion group are so generic, the eng lift to find a way to report specifically on ones that were used on R&S for Q&A. 

There are 81 published R&S articles: https://prod.cms.va.gov/admin/content?title=&type=support_resources_detail_page&moderation_state=All&owner=All. The baseline assumption here should likely be that CAIA needs to review all 81 for any use of paragraphs that were made into Q&As, and migrate that content into reusable Q&As. (Or: they may have a cause to make page-specific Q&As, which would be a new requirement and need to be exposed on R&S.)

**Comment by chri5tia** [comment] 2023-10-25 19:25
And here is the view: https://cms-80d0prfrxp0pohhtro3rzzrlo2bjdxih.ci.cms.va.gov/admin/content/qa

**Comment by jilladams** [comment] 2023-10-25 20:57
@chri5tia I don't see any Benefit Detail Pages coming up in that view. Did you end up adding them? If so, does that just mean there are no existing Page specific Q&As on them right now?

**Comment by chri5tia** [comment] 2023-10-26 14:49
@jilladams Hmm, I definitely thought I was seeing them during testing. I don't see my test content coming up in the view on the tugboat so I'll see what got missed. Thanks for pointing this out!

**Comment by chri5tia** [comment] 2023-10-26 16:25
@jilladams I pushed a fix and the environment is rebuilding. Can you evaluate the report before I reach out to CAIA? Thank you again!

**Comment by jilladams** [comment] 2023-10-26 17:51
PR question about the UX here, with the full content blocks included: https://github.com/department-of-veterans-affairs/va.gov-cms/pull/15833#issuecomment-1781551073

**Comment by chri5tia** [comment] 2023-10-26 20:31
@jilladams @thejordanwood 
There are two views to look at to make a determination for which one you want to use.

https://cms-80d0prfrxp0pohhtro3rzzrlo2bjdxih.ci.cms.va.gov/admin/content/qa
Pro: Shows each individual question, looks clean and compact. 
Con: The same node will be listed for each question.

https://cms-80d0prfrxp0pohhtro3rzzrlo2bjdxih.ci.cms.va.gov/admin/content/qa_group
Pro: Shows all the whole group of questions for each node
Con: The field rows are huge.

**Closed** 2023-11-01 20:58 UTC
Labels: Drupal engineering, Public Websites, backend, Q&A
