### ISSUE TITLE
Design updated Operating Status presentation for FE

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#19806] opened 2024-11-06 18:32 UTC
### Scope / Impact analysis
_What, if anything, could break as a result of this change?_
_Engineer should assess this when approaching PR._

## Acceptance criteria

- [ ] Design review
- [ ] A11y review

**Comment by davidmpickett** [comment] 2024-11-06 18:50
Dupe of https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19804

**Closed by davidmpickett** 2024-11-06 18:50 UTC
Labels: Design, Facilities, Needs refining, sitewide, UX
