### ISSUE TITLE
Locations Page 'PAGE INTRODUCTION' Field Appears in CMS Edit Mode, but is hidden on Published Page

### ISSUE THREAD

**Issue by TroyA6** [department-of-veterans-affairs/va.gov-cms#11612] opened 2022-11-16 16:26 UTC
## To Reproduce
1. Go to [https://prod.cms.va.gov/madison-health-care/locations](https://prod.cms.va.gov/madison-health-care/locations)
2. View (or edit) the text in the PAGE INTRODUCTION text field
3. Publish the page
4. See the 'missing' field - the text field in the Edit mode does not appear on the published page in production [https://www.va.gov/madison-health-care/locations/](https://www.va.gov/madison-health-care/locations/)

## AC / Expected behavior
The Editor's expectation is that the text entered in the PAGE INTRODUCTION field should appear on the production site/page, similar to the Health Services Page Introduction field.

## EDIT MODE PAGE INTRODUCTION FIELD WITH CONTENT
![image](https://user-images.githubusercontent.com/108767736/202229296-5e96ff34-3997-4edf-9a0e-24429dfbc758.png)

## PRODUCTION VIEW OF THE SAME PAGE - PAGE INTRODUCTION CONTENT IS HIDDEN
![image](https://user-images.githubusercontent.com/108767736/202229583-f5cd4f76-d9a2-450a-ab11-e70a8eb247bb.png)

## Health Services (Page displays 'Page Introduction' content as expected)
![image](https://user-images.githubusercontent.com/108767736/202230926-b7b88e5d-4013-43f9-9cf4-c0aaeb42e09a.png)

 ## Additional context
There has been some discussion in SLACK regarding this issue - [https://dsva.slack.com/archives/C01K37HRUAH/p1664481254295809](https://dsva.slack.com/archives/C01K37HRUAH/p1664481254295809)

Jira Ticket: [https://va-gov.atlassian.net/jira/servicedesk/projects/VAHELP/queues/custom/12/VAHELP-4894](https://va-gov.atlassian.net/jira/servicedesk/projects/VAHELP/queues/custom/12/VAHELP-4894)

## Desktop (please complete the following information if relevant, or delete)
 - OS: Windows 10/11
 - Browser Chrome, Edge
 - Version 

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [ ] CMS workstream (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [x] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by stefaniefgray** [comment] 2022-12-13 23:52
@TheBoatyMcBoatFace Here's a Platform ticket team ticket that fell through the cracks -- not sure what to do with it at this time? cc: @EWashb 

Original Jira ticket from 9/29/2022 where this issue was reported by VA Madison: https://va-gov.atlassian.net/browse/VAHELP-4894

**Comment by TheBoatyMcBoatFace** [comment] 2022-12-14 00:12
> 

Thanks for flagging @stefaniefgray. I'll bring it up with the team at SCRUM tomorrow.

**Comment by stefaniefgray** [comment] 2023-01-20 18:40
@EWashb Resurfacing this ticket from https://va-gov.atlassian.net/browse/VAHELP-4894 -- what shall we do with it?

**Comment by stefaniefgray** [comment] 2023-03-13 20:58
@laflannery @dawnpruitt (for when she returns) Hi -- not sure what to do with this one! Original Jira ticket is still open. 

Doesn't seem like a priority, but it has sort of fallen between the cracks in the meantime. What should we do with this?

**Comment by laflannery** [comment] 2023-03-13 21:11
@stefaniefgray This appears to be a duplicate of #11248 which has been refined by the Facilities team, I'm going to close this (as it is a facilities task not CMS)

**Closed by laflannery** 2023-03-13 21:11 UTC
Labels: Defect, Needs refining, Platform CMS Team, CMS Team
