### ISSUE TITLE
Featured Lovell events and stories that should show on both systems not showing on either system home page

### ISSUE THREAD

**Issue by omahane** [department-of-veterans-affairs/va.gov-cms#13615] opened 2023-05-04 18:30 UTC
## Describe the defect
Stories in the Lovell Federal health care umbrella system that should show on the homepage of the Lovell TRICARE and Lovell VA systems are not.

## To Reproduce
1. Write a story
2. Choose "Lovell Federal health care: Stories" in **Where should the story be listed?**
3. Check "Featured" on the story
4. Publish the story
5. Look for story on either homepage: 

- https://www.va.gov/lovell-federal-health-care-va/
- https://www.va.gov/lovell-federal-health-care-tricare/

## AC / Expected behavior
A stories section should be populated with featured stories.

## Screenshots
![Screen Shot 2023-05-04 at 1 24 00 PM](https://user-images.githubusercontent.com/766573/236295051-e8ec9580-6ed3-4e80-9c31-60151596a9c8.png)

## Slack discussion
https://dsva.slack.com/archives/C0FQSS30V/p1683224452110549

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS workstream (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [x] `Facilities`
- [ ] `User support`

**Comment by swirtSJW** [comment] 2023-05-05 14:46
This is a duplicate of https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11941

**Comment by jilladams** [comment] 2023-05-05 15:25
Note from scrum: not urgent today, shouldn't pull into sprint.

**Comment by jilladams** [comment] 2023-05-05 15:26
Closing as dupe of https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11941

**Closed as completed by jilladams** 2023-05-05 15:26 UTC
Labels: Defect, sitewide, Facilities, Needs refining
