### ISSUE TITLE
Knowledge Transfer for NextJS

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-cms#16058] opened 2023-11-08 16:54 UTC
## Description
This is a placeholder for the tasks related to knowledge transfer from AP team to Facilities engineers

**Comment by jilladams** [comment] 2024-06-27 22:10
Closing as a dupe of #16865 now that megateam has this under a single effort / epic.

**Closed by jilladams** 2024-06-27 22:10 UTC
Labels: Drupal engineering, Epic, Facilities, sitewide
