### ISSUE TITLE
[SPIKE] [Breadcrumb title case issue] Some breadcrumbs are displaying in Title Case instead of Sentence case as they should

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#19972] opened 2024-11-26 22:37 UTC
## Description

Randi Hecht reported in [Slack](https://dsva.slack.com/archives/C52CL1PKQ/p1723819948404999) some time ago an issue wherein breadcrumbs are displaying in Title Case instead of Sentence case as they should.

Amanda K looked into this:
This is more of the v3 breadcrumbs not respecting the H1 styling and incorrect capitalization and it is clearly a Drupal defect.
Which has also been identified in other places. ([Fran 2024-11-26] We believe the H1 styling has been corrected)

[Events: Inconsistent breadcrumb capitalization](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12326) (this one appears to be in the facility page level, not event)

[[Other - Accessibility] Inconsistent breadcrumb capitalization on Lovell](https://github.com/department-of-veterans-affairs/va.gov-team/issues/64850)

When AP updated to V3 breadcrumbs, this issue was resolved. Since this issue involves an important sign in page and across Drupal products, not just events (current AP priority), a product question remains, should a team prioritize a fix in content build since the timing of a full AP rollout is TBD? (edited)

## Additional Information

We are pursuing a fix in content build because this affects more than just Events. As part of this ticket, the engineer should determine if this would more accurately be a fix that the CMS team should make, or if the PW or Facilities team can push ahead and fix.

### User story

**AS A** Veteran, their caregiver, family member or survivor
**I WANT** a consistent look and feel across all of VA.gov
**SO THAT** I'm not distracted by different styles, and also so that I don't lose confidence in VA.gov providing a good and accurate experience

### Examples 
Examples below show  breadcrumbs **not** matching H1 case (breadcrumb is title case; H1 page title is sentence case), as well as one that is correct.

**Resources & Support Examples with issue**
- Breadcrumb is title case; H1 page title is sentence case: https://www.va.gov/resources/signing-in-to-vagov/
  - Breadcrumb is title case: Signing **In To** VA.gov
  - Actual H1 page title is sentence case: Signing **in to** VA.gov
- UR:; H1 page title is sentence case: https://www.va.gov/resources/managing-your-vagov-profile/
  - Breadcrumb is title case: Managing **Your** VA.gov **Profile**
  - Actual H1 page title is sentence case: Managing **your** VA.gov **profile**

**Events Examples with issue**
- Breadcrumb is title case; H1 page title is sentence case: https://www.va.gov/west-palm-beach-health-care/events/64425/
  - Breadcrumb is title case: Free Legal **Services Are Back In Partnership With** Legal Aid of Palm Beach County!
  - Actual H1 page title is sentence case: Free Legal **services are back in partnership with** Legal Aid of Palm Beach County!
- Breadcrumb is title case; H1 page title is sentence case: https://www.va.gov/palo-alto-health-care/events/68666/
  - Breadcrumb is title case: Medical **Outreach For** Veterans - Santa Cruz Veterans Memorial Building
  - Actual H1 page title is sentence case: Medical **outreach for** Veterans - Santa Cruz Veterans Memorial Building

**Example of correct breadcrumb using sentence case - matching H1**
- Bread matches H1, including case: https://www.va.gov/palo-alto-health-care/
  - Breadcrumb is correct (sentence case matches H1 page title): VA Palo Alto health care
  - H1 page title: VA Palo Alto health care

## Acceptance criteria
_ACs should capture expected behavior, to inform test plans. Consider devices, documentation updates including KBs, change management, and [content model](https://prod.cms.va.gov/admin/structure/cm_document) when applicable._

- [ ] Breadcrumbs should match the H1, including matching case e.g. if the H1 page title is sentence case, then the breadcrumb should be sentence case. See examples above.
  - [ ] Determine cause of the sporadic issue of Title Case breadcrumbs vs. Sentence case
- [ ] Determine if CMS team should actually be providing the fix
  - [ ] if so, notify Jill Adams/Fran Cross/Michael Skinner so they can communicate with Grace K
- [ ] OR, If this can be fixed by PW or Facilities team, create ticket for the fix
- [ ] Fran/Michael/Jill to close the loop with Randi Hecht in Slack [here](https://dsva.slack.com/archives/C52CL1PKQ/p1723819948404999)

**Comment by jilladams** [comment] 2024-12-04 17:16
Marked as a 2 pointer based on the idea that it's really a SPIKE for root cause, and we won't know how to fix til we know how / where it's broken.

**Comment by dsasser** [comment] 2024-12-17 14:42
Hi @FranECross, I’m a bit confused about the goal and scope of this issue. The user story doesn’t have any clear goals, and the ACs don’t have any detailed expectations either. It’s also a bit overwhelming because I have to dig into a lot of different issues or slack conversations. I’m not sure if I’m missing something obvious, but I’m having a hard time figuring out what’s useful from those tickets. I’ll bring this up in the 16th minute to see if we can clear things up.

**Comment by FranECross** [comment] 2024-12-17 21:25
@dsasser I've updated the ticket:

- deleted info that is confusing/no longer applies
- added examples where the issue still occurs and where it is correct
- updated AC

**Comment by dsasser** [comment] 2024-12-24 22:04
## Findings
Most breadcrumbs on the FE use the Drupal provided breadcrumbs. In Drupal, the Easy Breadcrumb module has a setting, Transformation mode, that transforms the final output based on its configuration. Currently it is set to "Capitalize the first letter of each word in the segment", so if a breadcrumb is managed by Easy Breadcrumb, all words will be capitalized. There is a 'none' option, which we would use in order to not affect the capitalization of breadcrumbs. This capitalization doesn't apply for breadcrumbs managed by other breadcrumb builders, such as by Menu Breadcrumb. Changing this configuration is simple and would take minimal effort.

## How Breadcrumbs are Assembled
In Drupal, breadcrumbs are assembled based on the route of the current page, contextual information, and breadcrumb builders. Breadcrumbs are provided by the core Breadcrumb service, which relies on a pipeline of breadcrumb builders to assemble and modify the breadcrumb trail.

### Breadcrumb Builders
These are plugins that define how breadcrumbs are assembled for specific scenarios. Breadcrumb builders implement the BreadcrumbBuilderInterface.

The VA.gov CMS has the following Breadcrumb Builders:

- System (core, priority 0). Applies to all routes. Builds path-based breadcrumbs.
- Taxonomy (core, priority 1002). Applies only to Taxonomy Terms. Provides a custom taxonomy breadcrumb builder that uses the term hierarchy
- Menu Breadcrumb (contrib, priority 1010). Applies to any path that is in a Menu. Provides a builder that builds breadcrumbs based on Menu placement and hierarchy.
- Easy Breadcrumb (contrib, priority 1003). Applies to all paths. Updates the core system breadcrumb to include the current page title. The module also comes with additional settings that are common features needed in breadcrumbs.
- Translation Management Core (contrib, priority 101). Applies to TMGMT Job Item routes. Builds breadcrumbs for Translations Management Core job items.

### Breadcrumb Pipeline:
Breadcrumbs are constructed in the following order:

1. Route Parents: Drupal traverses the hierarchy of the current route and its parent routes to determine the basic breadcrumb structure.
2. Breadcrumb Builders: Any active breadcrumb builders are invoked. These builders can add, remove, or override breadcrumbs in the trail.

The BreadcrumbManager service loops through all breadcrumb builders and invokes the _first_ builder that applies to the current request. In case of the VA.gov CMS, this results in the following process order:

1. Menu Breadcrumb
2. Easy Breadcrumb
3. Taxonomy
4. Translation Management Core
5. System

## SPIKE Examples

| Path | Problem | Cause |
| -------- | ------- | ------ |
| [/resources/signing-in-to-vagov/](https://www.va.gov/resources/signing-in-to-vagov/) | Breadcrumb in title case | Easy Breadcrumb transformation |
| [/resources/managing-your-vagov-profile/](https://www.va.gov/resources/signing-in-to-vagov/resources/managing-your-vagov-profile/)| Breadcrumb in title case | Easy Breadcrumb transformation |
| [/west-palm-beach-health-care/events/64425/](https://www.va.gov/west-palm-beach-health-care/events/64425/) | Breadcrumb in title case | Easy Breadcrumb transformation |
| [/events/68666/](https://www.va.gov/events/68666/) | Breadcrumb in title case | Easy Breadcrumb transformation |
| [/palo-alto-health-care/](https://www.va.gov/palo-alto-health-care/) | No problem | N/A |

**Comment by dsasser** [comment] 2024-12-24 22:04
@FranECross FYI ^

**Closed** 2024-12-24 22:04 UTC
Labels: Drupal engineering, Facilities, Public Websites, sitewide, Breadcrumbs

**Comment by jilladams** [comment] 2024-12-26 18:34
@dsasser I added these notes to the [Breadcrumb content model documentation](https://prod.cms.va.gov/admin/structure/cm_document/note/126/breadcrumbs). Could you review that and just make sure I didn't get anything wrong? (Can edit directly to fix if I did)

**Comment by jilladams** [comment] 2024-12-26 18:38
Created https://github.com/department-of-veterans-affairs/va.gov-cms/issues/20179 to implement the change to Easy Breadcrumb settings.
