### ISSUE TITLE
Events default timezone appears to default to user's timezone, not NY/ET

### ISSUE THREAD

**Issue by erogray** [department-of-veterans-affairs/va.gov-cms#3717] opened 2020-12-11 17:59 UTC
Jean Orzechowicz (Jean.Orzechowicz@va.gov) showed us that when you create an event (e.g. on https://staging.cms.va.gov/node/add/event) the default timezone in the select box says "default: America/New_York" but when that default option is used, the timezone actually used for the event is _her_ user timezone (Central Time). I've verified this by trying with different users: ET users get ET, CT users get CT. If you choose a specific timezone option _other_ than the default option, it does set correctly.

One potential fix might be to change that option text to read something like "default: my time zone".

**Comment by kevwalsh** [comment] 2020-12-11 19:05
Hmm, we had made an explicit decision to _not_ set default time zone based on user's time zone, until we had time to do some research (#2578) in that problem space but apparently we got it anyway!

I see a few options, there may be others.

1. Roll with it: update the UI (for the datetime fields on events and situation updates to make it more clear that it defaults to the user's time zone. 

![Manage_form_display___VA_gov_CMS](https://user-images.githubusercontent.com/643678/101943377-f972be80-3bb8-11eb-8e93-8d7a41bfd6ff.jpg)

2. Fix the bug with the contrib module, so that it behaves as expected, and defaults to ET as expected. 

![Manage_form_display___VA_gov_CMS](https://user-images.githubusercontent.com/643678/101943464-1909e700-3bb9-11eb-86be-87c595dc67ac.jpg)

3. Fight it: Set all users to use ET, and hide the time zone selector on the user profile for now, to prevent users from setting their time zone to, say, PT or CT, until a time that we can work on this.

**Comment by ndouglas** [comment] 2020-12-15 19:03
`smart_date` uses `''` to represent this "Site default" value.

`''` is stored to and retrieved from the database when no override is provided.  When this `''` value is retrieved and Drupal formats it, this default value will be replaced with `date_default_timezone_get()`, which return the user's timezone (see \Drupal\system\TimeZoneResolver).

1. So if you save it with a user whose timezone is set to CT, then view it, the date will be displayed in CT.
2. If you then change your timezone to MT, it will be displayed in MT.
3. If you save it as a user whose timezone is CT, then view it as a different user whose timezone is MT, it will be displayed in MT.

I think this is a result of an outdated/incorrect understanding of the date system by the `smart_date` developers.  I think this change was made to `smart_date` around the same time that Core's use of `date_default_timezone_set()/_get()` changed.  But I'm not sure it ever worked as intended.

I don't think there's a clean way of formatting the date according to the server timezone with the existing date formatters, on which `smart_date` relies heavily, so I'm not sure this option makes sense as implemented.  It's definitely described in a different way than how it actually seems to work.  I'm a bit surprised this issue hasn't been raised yet.  Looking at the issue where this was committed, there does not seem to be a lot of discussion of this particular option, so maybe it just slipped through.

I think that this would lead to two action items:

1) open an issue for `smart_date` to work around this in some way or, failing that, remove the option
2) set the default value here to America/New York explicitly

2) is the most expedient approach to our particular problem.  1) might be a big can of worms but seems an important issue to raise.

**Comment by oksana-c** [comment] 2020-12-18 14:58
@ndouglas thanks for the summary and opening an issue for smart dates contrib.

I agree that the option (2) is the most feasible way to proceed. Then we'll spend more time exploring the problem space in the issue Kevin linked to.
> set the default value here to America/New York explicitly 

also pasting Kevin's screenshot here for reference 
![Manage_form_display___VA_gov_CMS](https://user-images.githubusercontent.com/643678/101943464-1909e700-3bb9-11eb-86be-87c595dc67ac.jpg)

let's do it!

**Closed** 2020-12-21 17:34 UTC
Labels: Defect, Helpdesk & support, Planned work
