### ISSUE TITLE
PAW: QA artifact (for Staging Review)

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#16442] opened 2023-12-14 20:01 UTC
Draft exists, need to refresh and prep it for Staging Review: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/pact-act-wizard/engineering/testing-qa.md

## ACs
- [ ] QA artifact is updated, reviewed and ready for Staging Review and added to body (as noted in the Platform guidance: _You are free to provide this information to Governance Team in whatever format is most convenient..._ https://github.com/department-of-veterans-affairs/va.gov-team/issues/60582

**Comment by FranECross** [comment] 2023-12-14 22:58
@randimays @jilladams Is the existing test plan both a Regression Test Plan and a 'regular' Test Plan? I ask because the Platform Governance guidance indicates we need both. as well as the E2E tests and unit test coverage (which we have).

![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/147188767/eb2e6ff6-73e9-4a7c-b751-6fe4f4a4907b)

**Comment by randimays** [comment] 2023-12-15 15:36
@FranECross The unit tests and end-to-end tests in place for the PACT Act wizard cover all of the functionality of the application. Those are automatically run before any code is merged. We also do manual testing in the review instance before merging. We are covered!

**Comment by FranECross** [comment] 2023-12-15 15:57
@randimays Wonderful! Thanks so much for the information.

**Comment by jilladams** [comment] 2023-12-18 23:50
i merged the PR for the artifact, and this is ready to close, IMO. I'll let you do the honors if you agree, @FranECross

**Comment by FranECross** [comment] 2023-12-18 23:54
Excellent @jilladams ! Thank you and I do agree. Closing!

**Closed by FranECross** 2023-12-18 23:54 UTC
Labels: VA.gov frontend, Public Websites, PACT Act Wizard
