### ISSUE TITLE
SPIKE: Renaming a Vet Center splits content across multiple workbench Sections

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#15583] opened 2023-10-06 18:57 UTC
## Describe the defect
A Vet Center's common name should match its section name. However, when a Vet Center is renamed, the Section name does not automatically update, the two can stay not-matched. 

Example: 
* "Dr. Cameron McKinley Department of Veterans Affairs Veterans" was renamed to "Prescott Vet Center" in 2021: https://prod.cms.va.gov/node/3785/revisions/view/573869/595976/visual_inline
* Vet Center is named "Prescott Vet Center" still
* Old section still exists named "Dr. Cameron McKinley Department of Veterans Affairs Veterans" - https://prod.cms.va.gov/taxonomy/term/1041/edit
  - Governs the Prescott Vet Center node
  - no users assigned to this section
* Newer section exists named "prescott-vet-center" - https://prod.cms.va.gov/section/vha/vet-centers/prescott-vet-center
  - Governs all other nodes related to Prescott (services, location list, outstation, etc.) as well as the users

This causes confusion for Editors in production today (clearly).

This will be true for VBAs as well.

## Screenshots

<details><summary> Prescott Vet Center Section governs everything _but_ Prescott Vet Center </summary>

![screencapture-prod-cms-va-gov-section-vha-vet-centers-prescott-vet-center-2023-10-06-13_37_28](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/5f9dec1b-8b2b-44f7-9f32-9bd275a1d01b)

</details>

<details><summary> Dr-Cameron-Mckinley Section governs just Prescott Vet Center </summary>

![screencapture-prod-cms-va-gov-admin-content-2023-10-06-13_46_51 (1)](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/fc723633-c349-4f82-819f-79987e0fdba6)

</details>

<details><summary> Users assigned to the two sections </summary>

![screencapture-staging-cms-va-gov-admin-people-2023-10-06-13_44_35](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/ec1700a0-9b84-4fe9-8319-5ed791966fb4)

![screencapture-staging-cms-va-gov-admin-people-2023-10-06-13_44_16](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/185577b2-81ee-4acc-81a0-98b7251c4457)

</details>

## To Reproduce
1. Compare [prod.cms.va.gov/admin/content?title=&type=All&moderation_state=All&owner=1041](prod.cms.va.gov/admin/content?title=&type=All&moderation_state=All&owner=1041)
2. to [prod.cms.va.gov/admin/content?title=&type=All&moderation_state=All&owner=741](prod.cms.va.gov/admin/content?title=&type=All&moderation_state=All&owner=741)

## AC / Expected behavior
- [x] Vet Center sections are named properly and content is assigned to the correct sections 
- [x] When a Vet Center is renamed, the Section name is updated to match the Vet Center name.
- [x] The Vet Center [runbook-vet-center-name-change.md](https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/.github/ISSUE_TEMPLATE/runbook-vet-center-name-change.md) is updated to reflect how Section name change occurs -- via automation / code, or via manual steps that have to be performed
- [x] #11628 is updated with decisions / findings that can be applied to VBA
- [ ] Finalize plan with Product for how to manage Vet Centers moving forward / ticket if needed

### Updating the Event Subscriber
The code to set the flag during name changes is being called in `entityUpdate()`, which is in `va_gov_vamc/src/EventSubscriber/VAMCEntityEventSubscriber.php`.

This function already returns a `bool` if the flag gets set. We are not using this return value at present. We could use it to determine whether to call a new function that does a field check, comparing the title of the Vet Center (and VBA) to the name of the Section term. If different, we can determine the best course for a fix.

### Updating the migration process
The migration itself creates a term in the `field_administration` area of this this migration config: `va_gov_migrate/config/install/migrate_plus.migration.va_node_facility_vet_centers.yml` It's possible that a new plugin for this would be a better idea. After all, if we can update the term with the new name instead of creating a new one, I think that would be preferable.

**Comment by xiongjaneg** [comment] 2024-02-22 18:12
@xiongjaneg move the first AC or look for the related ticket/epic

**Comment by jilladams** [comment] 2024-08-16 21:01
@davidmpickett when we say "splits" in the title here - we don't have any idea how that happened, right? It wasn't automagical as far as we know? (Like: a new Prescott Section term got added after name change, and sub pages got put into it. Or we think some of it happened automatically?)

**Comment by Agile6MSkinner** [comment] 2024-08-19 20:29
@omahane Please add details to aid in working this.

**Comment by davidmpickett** [comment] 2024-08-19 21:54
> @davidmpickett when we say "splits" in the title here - we don't have any idea how that happened, right? It wasn't automagical as far as we know? (Like: a new Prescott Section term got added after name change, and sub pages got put into it. Or we think some of it happened automatically?)

_I_ don't understand how it happened, but @omahane might. Looking at the revision history for the terms, some changes were done by Anonymous (not verified). I suspect that may be the fingerprint of an automated process. Maybe the CMS Migrator doesn't leave it's name on the revision history for Terms (because Terms didn't used to have revision history)?

![Screenshot 2024-08-19 at 4 48 22 PM](https://github.com/user-attachments/assets/fd3fa468-8d9d-4942-ae14-7111547c6d7d)

![Screenshot 2024-08-19 at 4 48 42 PM](https://github.com/user-attachments/assets/4ff57f93-9873-480d-8903-05e5bd89236c)

Either way, the organization of the content across the two sections has only gotten messier since I first created this ticket.

**Comment by omahane** [comment] 2024-08-20 13:33
These steps to reproduce don't actually describe how to reproduce this issue. Instead, it shows the outcome of the process. I need to look at this some more to determine what's actually happening.

**Comment by omahane** [comment] 2024-08-20 13:38
> > @davidmpickett when we say "splits" in the title here - we don't have any idea how that happened, right? It wasn't automagical as far as we know? (Like: a new Prescott Section term got added after name change, and sub pages got put into it. Or we think some of it happened automatically?)
> 
> _I_ don't understand how it happened, but @omahane might. Looking at the revision history for the terms, some changes were done by Anonymous (not verified). I suspect that may be the fingerprint of an automated process. Maybe the CMS Migrator doesn't leave it's name on the revision history for Terms (because Terms didn't used to have revision history)?
> 
> Either way, the organization of the content across the two sections has only gotten messier since I first created this ticket.

The steps to reproduce on this ticket don't actually describe how to reproduce this issue. Instead, it shows the outcome of the process. I need to look at this some more to determine what's actually happening. But I also think that when a Vet Center Name changes that we should immediately change the section, until a programmatic fix is made. While I don't know for sure, I suspect that leaving the old section is problematic.

**Comment by omahane** [comment] 2024-09-03 12:23
Having manually cleaned these up, I'm now not sure that I did it the right way.

Here's the issue I see:
- The name of the center was changed by a [congressional act in 2014](https://www.congress.gov/113/plaws/publ138/PLAW-113publ138.htm).
- "Dr. Cameron McKinley Department of Veterans Affairs Veterans Center" is the official name of the vet center, according to the API:
<img width="742" alt="Screenshot 2024-09-03 at 7 10 44 AM" src="https://github.com/user-attachments/assets/ba6c648e-927b-46f8-a845-b51c5c38ea72">

- The center was not renamed officially but only had the common name changed in the CMS.

The CMS URL uses the common name:
- https://prod.cms.va.gov/prescott-vet-center

The VA.gov URL uses the common name
-  https://www.va.gov/prescott-vet-center

The services use the common name in the title of the service and the URL:
- "Prescott Vet Center - Couples and family counseling"
-  https://prod.cms.va.gov/prescott-vet-center/service/prescott-vet-center-couples-and-family-counseling

Should the Section, then, by the common name or the official name?

**Comment by omahane** [comment] 2024-09-03 20:19
Conversation about this Slack: https://dsva.slack.com/archives/C0FQSS30V/p1725372002021899

**Comment by omahane** [comment] 2024-09-03 21:03
> Should the Section, then, by the common name or the official name?

The Section must be based on the official name, as that is the only one that is in the API. The rest of the data, including services name and URL can use the common name.

**Comment by omahane** [comment] 2024-09-04 15:46
Correction, the migration process is **currently** using the Vet Center name to generate a new Section term and assigning the new Vet Center to it. It also creates a new Section during the migration when the Vet Center name changes, essentially blindly making a new term because no term like it currently exists, given that the facility name is different, and thus the term that is created is different.

The way VBA works, however, is that it assigns a default_value ("VBA Facilities", term id 191), which means that on change there's no term created and no new Section assigned. We could do the same thing with Vet Center.

That way, we could then manually create a Section from the common name, assign the facility to it, without concern that the next migration would create a new Section all over again. When the [required services for new Vet Centers](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19070) code is working once more, this will mean a bulk edit of services after the new Section is created and assigned to the facility. We could, however, on update of Vet Center, run a check to see if the Section has changed from the default, at which point we change the section of all associated services.

**Comment by jilladams** [comment] 2024-09-04 16:51
@omahane to schedule a short follow up with @mmiddaugh @Agile6MSkinner to finalize plan for VBA & Vet Centers, and map out next steps.

**Comment by omahane** [comment] 2024-09-13 14:22
At the Sitewide UX sync, it was decided that we should no longer create the Vet Center section on creation, as we currently do. Instead we will follow the model of VBA, adding them to the "Vet Centers" (term id 190). I will create a ticket to describe this change.

**Comment by omahane** [comment] 2024-09-13 14:35
#19204 will resolve the persistent issue that is identified in this ticket.

**Closed by omahane** 2024-09-13 14:35 UTC
Labels: Defect, Drupal engineering, Facilities, Vet Center, sitewide
