### ISSUE TITLE
VAMC non-clinical services have required fields that are not applicable to them

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#17967] opened 2024-04-25 21:03 UTC
## Describe the defect
With the new update to Service Locations, the VAMC non-clinical service type in Drupal has required fields that are not applicable to this content type nor does any of this information display on the front end. This creates a poor editor experience because of the steps explained below:

## To Reproduce
1. Go to a non-clinical service on the SL Tugboat, [example](https://pr-xptmfsnjoodldn85nzgkrgljqtfbz24b.ci.cms.va.gov/nebraska-western-iowa-health-care/locations/north-platte-va-clinic/register-for-care)
2. Click on the 'Edit' tab
3. Scroll down, add a Revision log message and try to save the content
4. If this is the first time this particular node has been edited since the updated fields have been added, you will see an error message indicating that there are 4 errors:
![Screenshot 2024-04-25 at 4 57 55 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/106678594/fd737e06-3787-4588-b640-0c85b01b6fac)
5. This is because these are all new, required fields but they have no content yet.
6. The editor will need to select options and/or add content for these fields before being able to save this node
7. However, these particular fields do not apply to non-clinical services. Also, even if I do happen to select options other than "No" for these fields, nothing shows on the Front End site.

This makes for a frustrating editor experience because we are preventing them from saving their content with non-applicable fields.

## AC / Expected behavior

- [ ] The user experience for non-clinical services has been adjusted
- [ ] There are no regressions for the UI on VAMC Facility health services
- [ ] There are no regressions on the UI on VBA Facility health services

 ## Additional context
A possible, quick and dirty solution, could be to update the migration to default the non-clinical services to the null option for these particular fields. This could potentially alleviate some of the frustration here and not impact the planned launch timeline. A longer-term solution could then be discussed for post-launch.

**Comment by jilladams** [comment] 2024-04-25 22:00
@omahane this ticket is the topic Laura brought up at the end of UX sync today. I would love to get your thoughts: 

1. She suggested data migration updates to set null values for the non-clinical services, to fix this UX. Does that seem light or heavy? 
2. We talked on the call about the fact that these fields from the Service Location paragraph will likely _never_ matter for non-clinical services. They'll be exposed in this location on Drupal, but won't map to anything in FE templates. Laura and I _think_ it's true that the paragraph type is one size fits all, and we can't hide these fields on non-clinical services. Could you confirm that, or correct us if that's wrong, if you know? 

cc @davidmpickett @aklausmeier

**Comment by davidmpickett** [comment] 2024-04-25 22:22
Rather than updating the migration I had proposed handling this as a bulk update https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17515

**Comment by davidmpickett** [comment] 2024-04-25 22:28
I would suggest closing this as dupe of 17515 and continuing this conversation there. It’s the same core issue and already has additional screenshots and notes on limitations

**Comment by jilladams** [comment] 2024-04-25 22:32
Thanks, Dave. Closing.

**Closed by jilladams** 2024-04-25 22:32 UTC
Labels: Defect, Drupal engineering, Facilities, Needs refining, UX
