### ISSUE TITLE
"NaN" displayed in va-number-input under multiple scenarios

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#14975] opened 2023-08-25 16:47 UTC
## Describe the defect
If a user enters characters in the `va-number-input` field and then deletes them, instead of a blank input they see the string `NaN`. Scenarios:
- delete or backspace button
- triggering form validation – e.g., by trying to submit an alpha character or number outside of allowed range (0-100)

## To Reproduce
1. Go to https://staging.va.gov/health-care/income-limits/
2. start the flow by clicking "check current income limits"
3. enter a valid zip and press continue
4. On the Dependents screen, enter any alphanumeric character
5. Use any method to delete it
6. See `NaN` appears in the input

## AC / Expected behavior

- Same steps but no `NaN` appearance

## Screenshots
<img width="223" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/4054752/76ee0280-ff56-41e8-be6c-64b697acbc0a">

 ## Additional context
Add any other context about the problem here. Reach out to the Product Managers to determine if it should be escalated as critical (prevents users from accomplishing their work with no known workaround and needs to be addressed within 2 business days).

## Desktop (please complete the following information if relevant, or delete)
Easily reproduced on desktop and mobile.

**Comment by randimays** [comment] 2023-08-25 17:44
This was caused by some recent changes to the DS component for `va-number-input` (the React binding version). It is stricter with regard to the number format it requires. We had some logic updating the value of the field that wasn't thoroughly handling when the field is blank, thus trying to convert nothing into a number.

Will be putting up a PR for this shortly.

**Comment by randimays** [comment] 2023-08-28 13:43
Verified in staging. Closing!

**Closed by randimays** 2023-08-28 13:43 UTC
Labels: Defect, VA.gov frontend, Public Websites, Income limits app
