### ISSUE TITLE
[AP] Search bar in mobile header has incorrect styling

### ISSUE THREAD

**Issue by randimays** [department-of-veterans-affairs/va.gov-cms#19409] opened 2024-10-04 17:13 UTC
## Description

On ~400px width screens, the search bar in the mobile header has incorrect styling.

AP URL: https://dev.va.gov/lovell-federal-health-care-va/events/72662/

<img width="400" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNTBrQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5c68839baa7d818cdef72c0da34bc34912bbd482/Screenshot%202024-10-04%20at%2012.12.45%20PM.png" alt="Screenshot 2024-10-04 at 12.12.45 PM.png" />

Prod URL: https://va.gov/lovell-federal-health-care-va/events/72662/

## Acceptance criteria
- [ ] Search bar on mobile matches production visually and functionally
- [ ] Search bar on table matches production visually and functionally
- [ ] Search bar on desktop matches production visually and functionally

**Comment by jilladams** [comment] 2024-10-08 18:25
Dupe of https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19410, not sure why there are 2, but the other has comments and more assignees, so closing this one.

**Closed by jilladams** 2024-10-08 18:25 UTC
Labels: Defect, VA.gov frontend, Needs refining, Accelerated Publishing, sitewide
