### ISSUE TITLE
Implement consistent characters remaining pattern across all forms

### ISSUE THREAD

**Issue by rachel-kauff** [department-of-veterans-affairs/va.gov-cms#2472] opened 2020-07-28 22:26 UTC
## User Stories

As a user, I'd prefer a consistent experience for text that tells me how many characters I can input into a field.

## Acceptance criteria 

- [ ] Audit character limit fields [@rachel-kauff ]
- [ ] Develop a character limit help text pattern and document in [GDrive Design System directory](https://drive.google.com/drive/folders/1XEw8PZOauwLESDeNlsCV-FCWyznhnfXQ) [@rachel-kauff ]
- [ ] All fields identified in the audit are updated w/ new help text pattern [engineer]

**Comment by davidmpickett** [comment] 2024-01-16 22:17
Closing as duplicate of #16659

**Closed by davidmpickett** 2024-01-16 22:17 UTC
Labels: Drupal engineering, CMS experience, Needs refining, UX writing, CMS design system, CMS Team
