### ISSUE TITLE
Redirect Request: Vet Center pages live the week of 1/22/23

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-cms#12407] opened 2023-01-27 19:52 UTC
### Instructions
- Requests must be submitted **AT LEAST** 2 weeks in advance.  Some requests take a significant amount of time and coordination to implement, so start the process as soon as you know you will need one. 
- This issue will be used from initial request through implementation to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track differnt steps.
- It is your responsibility to notify VA stakeholders as appropriate.  

### Type of request
- [ ] We are retiring or taking down a page and need to redirect the URL (complete redirect section)
- [ ] We are changing the URL of an existing page (complete redirect section)
- [ ] We need a custom vanity URL (complete vanity URL section)

### Implementation date
When does this request need to be live?
Choose one:
- [ ] On a specific date, connected to a program or publishing requirement. **DATE:**
- [ ] Any day prior to a deadline/latest possible date. **DEADLINE:** 
- [ ] Any day after an earliest possible date. **EARLIEST DATE:**
- [ ] During a specific date range: ***EARLIEST DATE TO LATEST DATE:***
- [ ] No hard timing requirements, publish when possible.

### Redirects 
Current URL  |  Redirect Destination or New URL
---  |  ---
www.va.gov/find-locations/facility/vc_0736V | https://www.va.gov/springfield-mo-vet-center/
https://www.va.gov/directory/guide/facility.asp?ID=5914&dnum=All | https://www.va.gov/springfield-mo-vet-center/
https://www.va.gov/directory/guide/keystaff.cfm?id=5914 | https://www.va.gov/springfield-mo-vet-center/
www.va.gov/find-locations/facility/vc_0402V | https://www.va.gov/detroit-vet-center/
https://www.va.gov/directory/guide/facility.asp?ID=6189&dnum=All | https://www.va.gov/detroit-vet-center/
https://www.va.gov/directory/guide/keystaff.cfm?id=6189 | https://www.va.gov/detroit-vet-center/
www.va.gov/find-locations/facility/vc_0414V | https://www.va.gov/st.-louis-vet-center/
https://www.va.gov/directory/guide/facility.asp?ID=495&dnum=All | https://www.va.gov/st.-louis-vet-center/
https://www.va.gov/directory/guide/keystaff.cfm?id=495 | https://www.va.gov/st.-louis-vet-center/
www.va.gov/find-locations/facility/vc_0206V | https://www.va.gov/parma-vet-center/
https://www.va.gov/directory/guide/facility.asp?ID=5447&dnum=All | https://www.va.gov/parma-vet-center/
https://www.va.gov/directory/guide/keystaff.cfm?id=5447 | https://www.va.gov/parma-vet-center/
www.va.gov/find-locations/facility/vc_0234V | https://www.va.gov/toledo-vet-center/
https://www.va.gov/directory/guide/facility.asp?ID=5670&dnum=All | https://www.va.gov/toledo-vet-center/
https://www.va.gov/directory/guide/keystaff.cfm?id=5670 | https://www.va.gov/toledo-vet-center/
www.va.gov/find-locations/facility/vc_0415V | https://www.va.gov/milwaukee-vet-center/
https://www.va.gov/directory/guide/facility.asp?ID=580&dnum=All | https://www.va.gov/milwaukee-vet-center/
https://www.va.gov/directory/guide/keystaff.cfm?id=580 | https://www.va.gov/milwaukee-vet-center/

### Vanity URLs 
Vanity URL  |  Landing page
---  |  ---
requested URL | landing page URL

**Link to campaign landing page request issue:**

### Process, Roles and Responsibilities
- [ ] Requesting team: Above information is provided
- [ ] Requesting team: All appropriate VA stakeholders are notified as appropriate
- [ ] IA: Request is vetted and documented and implementation plan is clear 
- [ ] IA: Request is assigned to appropriate team for implementation 
- [ ] Implementation team: Work is complete
- [ ] Implementation team: Validated in production
- [ ] Requesting team: Validates everything is correct in production and closes ticket

**Comment by dsasser** [comment] 2023-02-09 16:28
PR for review: https://github.com/department-of-veterans-affairs/devops/pull/12534 (contains both #12407 and #12288 redirects.

**Comment by dsasser** [comment] 2023-02-14 17:02
Done but waiting for the weekly Wednesday deploy to verify.

**Comment by dsasser** [comment] 2023-02-17 18:41
Tested the redirects and received the following:

```bash
✅ Correct redirect from  https://www.va.gov/find-locations/facility/vc_0736V to https://www.va.gov/springfield-mo-vet-center/
❌ Incorrect redirect from  https://www.va.gov/directory/guide/facility.asp?ID=5914&dnum=All to https://www.va.gov/find-locations/?facilityType=vet_center
❌ Missing redirect from  https://www.va.gov/directory/guide/keystaff.cfm?id=5914 to https://www.va.gov/springfield-mo-vet-center/
✅ Correct redirect from  https://www.va.gov/find-locations/facility/vc_0402V to https://www.va.gov/detroit-vet-center/
❌ Incorrect redirect from  https://www.va.gov/directory/guide/facility.asp?ID=6189&dnum=All to https://www.va.gov/find-locations/?facilityType=vet_center
❌ Missing redirect from  https://www.va.gov/directory/guide/keystaff.cfm?id=6189 to https://www.va.gov/detroit-vet-center/
✅ Correct redirect from  https://www.va.gov/find-locations/facility/vc_0414V to https://www.va.gov/st.-louis-vet-center/
❌ Incorrect redirect from  https://www.va.gov/directory/guide/facility.asp?ID=495&dnum=All to https://www.va.gov/find-locations/?facilityType=vet_center
❌ Missing redirect from  https://www.va.gov/directory/guide/keystaff.cfm?id=495 to https://www.va.gov/st.-louis-vet-center/
✅ Correct redirect from  https://www.va.gov/find-locations/facility/vc_0206V to https://www.va.gov/parma-vet-center/
❌ Incorrect redirect from  https://www.va.gov/directory/guide/facility.asp?ID=5447&dnum=All to https://www.va.gov/find-locations/?facilityType=vet_center
❌ Missing redirect from  https://www.va.gov/directory/guide/keystaff.cfm?id=5447 to https://www.va.gov/parma-vet-center/
✅ Correct redirect from  https://www.va.gov/find-locations/facility/vc_0234V to https://www.va.gov/toledo-vet-center/
❌ Incorrect redirect from  https://www.va.gov/directory/guide/facility.asp?ID=5670&dnum=All to https://www.va.gov/find-locations/?facilityType=vet_center
❌ Missing redirect from  https://www.va.gov/directory/guide/keystaff.cfm?id=5670 to https://www.va.gov/toledo-vet-center/
✅ Correct redirect from  https://www.va.gov/find-locations/facility/vc_0415V to https://www.va.gov/milwaukee-vet-center/
❌ Incorrect redirect from  https://www.va.gov/directory/guide/facility.asp?ID=580&dnum=All to https://www.va.gov/find-locations/?facilityType=vet_center
❌ Missing redirect from  https://www.va.gov/directory/guide/keystaff.cfm?id=580 to https://www.va.gov/milwaukee-vet-center/
```

This indicates that the redirects which include query string parameters are not worked as expected. Some of them are incorrectly redirecting to https://www.va.gov/find-locations/?facilityType=vet_center while others are missing a redirect entirely.

**Comment by dsasser** [comment] 2023-02-21 18:44
> Tested the redirects and received the following:
> 
> ```shell
> ✅ Correct redirect from  https://www.va.gov/find-locations/facility/vc_0736V to https://www.va.gov/springfield-mo-vet-center/
> ❌ Incorrect redirect from  https://www.va.gov/directory/guide/facility.asp?ID=5914&dnum=All to https://www.va.gov/find-locations/?facilityType=vet_center
> ❌ Missing redirect from  https://www.va.gov/directory/guide/keystaff.cfm?id=5914 to https://www.va.gov/springfield-mo-vet-center/
> ✅ Correct redirect from  https://www.va.gov/find-locations/facility/vc_0402V to https://www.va.gov/detroit-vet-center/
> ❌ Incorrect redirect from  https://www.va.gov/directory/guide/facility.asp?ID=6189&dnum=All to https://www.va.gov/find-locations/?facilityType=vet_center
> ❌ Missing redirect from  https://www.va.gov/directory/guide/keystaff.cfm?id=6189 to https://www.va.gov/detroit-vet-center/
> ✅ Correct redirect from  https://www.va.gov/find-locations/facility/vc_0414V to https://www.va.gov/st.-louis-vet-center/
> ❌ Incorrect redirect from  https://www.va.gov/directory/guide/facility.asp?ID=495&dnum=All to https://www.va.gov/find-locations/?facilityType=vet_center
> ❌ Missing redirect from  https://www.va.gov/directory/guide/keystaff.cfm?id=495 to https://www.va.gov/st.-louis-vet-center/
> ✅ Correct redirect from  https://www.va.gov/find-locations/facility/vc_0206V to https://www.va.gov/parma-vet-center/
> ❌ Incorrect redirect from  https://www.va.gov/directory/guide/facility.asp?ID=5447&dnum=All to https://www.va.gov/find-locations/?facilityType=vet_center
> ❌ Missing redirect from  https://www.va.gov/directory/guide/keystaff.cfm?id=5447 to https://www.va.gov/parma-vet-center/
> ✅ Correct redirect from  https://www.va.gov/find-locations/facility/vc_0234V to https://www.va.gov/toledo-vet-center/
> ❌ Incorrect redirect from  https://www.va.gov/directory/guide/facility.asp?ID=5670&dnum=All to https://www.va.gov/find-locations/?facilityType=vet_center
> ❌ Missing redirect from  https://www.va.gov/directory/guide/keystaff.cfm?id=5670 to https://www.va.gov/toledo-vet-center/
> ✅ Correct redirect from  https://www.va.gov/find-locations/facility/vc_0415V to https://www.va.gov/milwaukee-vet-center/
> ❌ Incorrect redirect from  https://www.va.gov/directory/guide/facility.asp?ID=580&dnum=All to https://www.va.gov/find-locations/?facilityType=vet_center
> ❌ Missing redirect from  https://www.va.gov/directory/guide/keystaff.cfm?id=580 to https://www.va.gov/milwaukee-vet-center/
> ```
> 
> This indicates that the redirects which include query string parameters are not worked as expected. Some of them are incorrectly redirecting to https://www.va.gov/find-locations/?facilityType=vet_center while others are missing a redirect entirely.

The cause of this was identified [here](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12288#issuecomment-1435348218) and a subsequent [PR](https://github.com/department-of-veterans-affairs/devops/pull/12579) was created to correctly use redirects_by_query for parameter based redirects.

**Comment by jilladams** [comment] 2023-02-22 20:43
That fix verified all but 3 of these -- it looks like the request for `https://www.va.gov/st.-louis-vet-center/` is in invalid url and should not include the ., so should be `https://www.va.gov/st-louis-vet-center/`. Noting, and I can prob get a PR up EOD for that fix, that Daniel could review, if he doesn't get to it first.

**Comment by jilladams** [comment] 2023-02-22 23:18
OOB deploy requested: https://dsva.slack.com/archives/CBU0KDSB1/p1677107410355259

**Comment by jilladams** [comment] 2023-02-23 16:36
St Louis fix verified in prod, closing.

**Closed by jilladams** 2023-02-23 16:36 UTC
Labels: VA.gov frontend, Public Websites, Sitewide IA

**Comment by stefaniefgray** [comment] 2023-03-10 17:25
Milwaukee Vet Center entry on Facility Locator still goes to https://www.va.gov/find-locations/facility/vc_0415V instead of to https://www.va.gov/milwaukee-vet-center/

Is this something our team can help fix? @dsasser @jilladams 

Slack thread in #facilities-support: https://dsva.slack.com/archives/C02730UEZPS/p1674245972931099
Jira ticket: https://va-gov.atlassian.net/browse/VAHELP-5385

**Comment by jilladams** [comment] 2023-03-10 17:33
@stefaniefgray https://www.va.gov/find-locations/facility/vc_0415V redirects to https://www.va.gov/milwaukee-vet-center/ for me, both with and without trailing slash. I don't really understand the description in the JIRA ticket here: 
> Our Milwaukee Vet Center has a comprehensive Drupal page:
[Milwaukee Vet Center | Veterans Affairs (va.gov)](https://www.va.gov/milwaukee-vet-center/)

> However, when you click on “Vet Center” from our VAMC “Locations” page ([Milwaukee Vet Center | Veterans Affairs (va.gov)](https://www.va.gov/find-locations/facility/vc_0415V)), you don’t see that page: instead it is just the generic Vet Center page. I couldn’t find any way in Drupal to replace this or even insert a link to the Vet Center’s comprehensive page.

Could you help me with the steps to repro how you're starting from which page, what you're clicking, to get the page with no redirect? Happy to zoom if that's easiest

**Comment by stefaniefgray** [comment] 2023-03-14 01:23
@jilladams Hi! The issue detailed by the editor in the original request is resolved, which is good. The editor was initially concerned about the link to the Milwaukee Vet Center listed on the VA Milwaukee "Locations" page.

However, if you search for the Milwaukee Vet Center on the Facility Locator lookup tool ( https://www.va.gov/find-locations/ ), the link still goes to https://www.va.gov/find-locations/facility/vc_0415V instead of to https://www.va.gov/milwaukee-vet-center/

Here's a screenshot showing the URL that appears when I hover my mouse over the Milwaukee Vet Center's title link:

<img width="1225" alt="Screen Shot 2023-03-13 at 7 21 34 PM" src="https://user-images.githubusercontent.com/9059428/224867947-735b5fe9-74d0-4b74-848e-9d9ba4696cda.png">

Is this something that our team can fix?

**Comment by jilladams** [comment] 2023-03-14 17:00
Ah, interesting! So if you click that, the URL does redirect and correctly land on https://www.va.gov/milwaukee-vet-center/. But: I see your point and have confirmed that for all the vet centers listed in this ticket with new redirects, the old URL shows in the Facility locator. For other Vet Centers that have been redirected in prior months, the new URL is used. I _suspect_ this may be a caching thing somewhere, but: we'll need to confirm with the Facilities team. I will ping in their channel.

**Comment by jilladams** [comment] 2023-03-14 17:05
https://dsva.slack.com/archives/C0FQSS30V/p1678813495215149
