### ISSUE TITLE
[BLOCKED] [Discharge Upgrade Wizard] Remove old DUW code - DUPE

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#19532] opened 2024-10-17 20:35 UTC
## Description

After the new Discharge Upgrade Wizard has been validated in production and sufficient time has passed to ensure there are no issues, the old DUW code needs to be removed.

Note that the redirect should still remain in place even with the old code gone, because the URL for the intro page and other pages do not match the old DUW's URLs.

### User story

**AS A** PO/PM who manages Discharge Upgrade Wizard
**I WANT** the old DUW code to be removed
**SO THAT** we have clean code and less tech debt.

### Scope / Impact analysis
_What, if anything, could break as a result of this change?_
_Engineer should assess this when approaching PR._

### Roles / assignments
_After functional testing, code review, accessibility review, and design review can happen in parallel._
- [ ] **Functional testing:** @FranECross testing of the new DUW to ensure no impacts due to this code removal.
- [ ] **Code review:** 
- [ ] **Design review:** N/A
- [ ] **Accessibility review:** N/A
- [ ] **Product acceptance:** Fran Cross

## Acceptance criteria
_ACs should capture expected behavior, to inform test plans. Consider devices, documentation updates including KBs, change management, and [content model](https://prod.cms.va.gov/admin/structure/cm_document) when applicable._

- [ ] Old DUW code that has no impact on the new DUW has been removed
- [ ] Regression testing of new DUW has occurred and passed
- [ ] Impact analysis is filled out and QA test plan is updated accordingly
- [ ] Does this product have an existing regression test plan?
	- [ ] Yes, link: TBD

**Comment by jilladams** [comment] 2024-12-10 22:44
Closing as a dupe of https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19539, since that one is in Refined & Ready and has points.

**Closed by jilladams** 2024-12-10 22:44 UTC
Labels: Needs refining, Technical debt, Blocked, Public Websites, sitewide, Discharge upgrade wizard
