### ISSUE TITLE
I.L. FE: Add Edit capability to Review Info screen

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#13587] opened 2023-05-03 19:33 UTC
### User story

**AS A** Veteran
**I WANT** to use an "edit" link on the Review screen to directly edit zip or dependents fields without seeing intervening screens en route
**SO THAT** I can handle it with minimal cognitive load.

### Quality / testing notes
- [x] End-to-end tests for edit capability for Zip and Dependents exist and pass
- [x] Unit tests for clicking Edit on the Review screen exist and pass

## Acceptance criteria

- [x] Design and layout is as designed on both desktop and mobile
- [x] Clicking edit link by Zip takes me directly to the Zip Code screen
- [x] Clicking continue from the Zip screen returns me directly to the Review info screen, where my new input is visible
- [x] Clicking edit link by Dependents takes me directly to the Dependents screen
- [x] Clicking continue from the Dependents screen returns me directly to the Review info screen, where my new input is visible
- [x] Requires design review

**Comment by wesrowe** [comment] 2023-05-17 22:24
@randimays, this is one that needs your eye on testing ACs and possible re-estimation.

**Comment by randimays** [comment] 2023-05-18 16:49
Added a couple of testing ACs and updated estimate from 3 to 5.

**Comment by randimays** [comment] 2023-05-25 15:43
PR is up for review.

**Comment by randimays** [comment] 2023-05-31 17:46
Received all necessary engineering code reviews. Waiting on @thejordanwood to have a look before we merge.

**Comment by thejordanwood** [comment] 2023-05-31 19:48
@randimays It looks like this functions the way it should. I have a couple of design notes:

- I believe the input field size should be smaller for zip code and dependents. I found this example on the [health care application form](https://www.va.gov/health-care/apply/application/id-form). It should be the same size as the social security number input field. 
- The continue and back buttons aren't working correctly for me on mobile screen sizes. [The design documentation]( https://design.va.gov/components/button/button-pair#mobile-behavior) says this about mobile behavior: "At and after the [small-screen breakpoint](https://design.va.gov/foundation/breakpoints#names-and-values) the buttons left align and revert to a natural width (i.e. as wide as they need to be to accommodate their label) with the secondary button continuing to appear before the primary button."

**Comment by randimays** [comment] 2023-06-01 15:26
@thejordanwood 

- Input field size: https://dsva.slack.com/archives/C01DBGX4P45/p1685631756942529. I asked Platform about this and they are currently working on adding the ability to customize width on the text and number inputs. Right now this isn't available for the latest iteration of inputs, so I can't change the width of them yet.
- Continue & back buttons: https://dsva.slack.com/archives/C01DBGX4P45/p1685632575158909. I asked Platform about this one too and they said the current behavior is the intended behavior of the VaButtonPair component. We aren't able to achieve the look in the design comp. There may be examples of this in other parts of the site / other forms but I think as those migrate to newer versions of design system components they will all end up looking like this out of the box.

**Comment by thejordanwood** [comment] 2023-06-01 15:38
@randimays Thanks for checking with Platform! If that's the case, then this is fine with me from a design standpoint.

**Comment by wesrowe** [comment] 2023-06-02 20:35
flow works well for me. I defer to discussion above on design particulars.

**Comment by randimays** [comment] 2023-06-05 13:46
Flow validated in staging; closing as complete.

**Closed** 2023-06-05 13:46 UTC
Labels: VA.gov frontend, Public Websites, Income limits app
