### ISSUE TITLE
Spike: Research what code sets the user object's LOA property (AskVA)

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#9573] opened 2022-06-23 18:24 UTC
## Description

The Ask widget uses Level of Access (LOA) data from the user object. This issue is to find out how this property is set on login, to enable the recommended implementation below. The notes below are from the preceding discovery issue, #9140.

### Implementation note
Dave and Claudio discussed how best to change the code. They determined that the best approach would be to **find where the `loa` parameter is currently set on the user object and add logic there for the new params** (rather than change the logic in the widget itself). Rationale: this would make it more likely that any other widget that leverages the loa parameter could go on functioning as expected after the change by login.gov.

## 9140 Discovery Results
- The `AskVA` widget is included into landing pages via `src/site/layouts/landing_page.drupal.liquid`
- The `loa` value is provided by a Redux Store to this React component (AskVA widget) as a React property.
- **AskVA Widget**: "src/applications/static-pages/ask-va/components/App/index.js"
   - Once the widget receives the `loa` React property, the template will fetch the URL based on the `loa` value during each component render.
   - **Production URLs** for `loa` value:
     - Equals `=== 1`: `'https://ask.va.gov/unauthenticated'`
     - Greater or equal to `>= 2`: `'https://eauth.va.gov/isam/sps/saml20idp/saml20/logininitial?PartnerId=https://prod-va-gov-sso.portals.va.gov/ava/SSO/Metadata/'`
     - Default (any other value):  `'https://ask.va.gov'`
   - **Development URLs** for `loa` value:
     - Equals `=== 1`: `'https://dvagov-veft-qa.dynamics365portals.us/unauthenticated'`
     - Greater or equal to `>= 2`: `'https://sqa.eauth.va.gov/isam/sps/saml20idp/saml20/logininitial?PartnerId=https://iam-ssoe-sqa1-veis.devtest.vaec.va.gov/ava/SSO/Metadata/'`
     - Default (any other value):  `'https://dvagov-veft-qa.dynamics365portals.us/'`

### Learnings from meeting 6/17/22

New values to accommodate in code:
There is currently logic in the VA.gov react widget to send visitors with LOA ≥ 2 to a different experience.
Login.gov will provide two other parameters (but not LOA): both IAL and AAL fields will need to be ≥ 2 for visitors to be sent to the same experience mentioned above.

## Acceptance Criteria
- [ ] ready to implement

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by jilladams** [comment] 2022-07-05 22:18
@wesrowe this is the ticket Dave flagged in sprint planning today, as maybe being a dupe of #9140. It looks like Claudio documented how LOA works and the files it touches. I don't have a working memory of why we still have this ticket - do you? Were there specific outstanding pieces we need to figure out, that you know of / heard about from Claudio? Or is this safe to close and next step is just to do the work in #9567?

**Comment by wesrowe** [comment] 2022-07-05 22:24
Not a dupe – in #9140 Claudio only looked at the widget itself and how it changes its behavior based on the `loa` parameter. This ticket is to find out how the `loa` parameter is set by the app, so that we can add the new login.gov inputs to that logic. (It was partly/mostly Dave's idea to handle it that way, "globally," rather than just altering the widget.)

**Comment by wesrowe** [comment] 2022-07-22 19:43
Ryan found code that might already be handling these new properties in vets-api – code was added 9 months ago by Derek Brown. I reached out to him via Slack to see if we need to do anything more.

**Comment by wesrowe** [comment] 2022-07-25 15:48
update: Derek did that work for Lighthouse: 
>Good morning, I am actually with the Lighthouse team so the LOA properties that are set as part of the Lighthouse OAuth token validation service do not apply to [VA.gov](http://va.gov/) sessions.
The [#vsp-identity](https://dsva.slack.com/archives/CSFV4QTKN) channel might be the right place for this question as I'm not sure how LOA is tracked for [VA.gov](http://va.gov/).

**Comment by ryguyk** [comment] 2022-07-26 18:33
https://dsva.slack.com/archives/CSFV4QTKN/p1658848123081279

It appears that this is nothing we need to be concerned about. After authenticating with login.gov, when our code grabs the `loa` value, that value will already have been calculated from login.gov `ial` and `aal` values (actually, just `ial` directly, since `aal` refers to MFA, and login.gov always requires MFA).

We should not have to do anything further.

**Comment by jilladams** [comment] 2022-07-26 21:50
Wes has a note to let Dave know that this is dusted, and the threads make sense. Good to close this out.

**Closed** 2022-07-27 14:25 UTC
Labels: VA.gov frontend, ⭐️ Public Websites
