### ISSUE TITLE
RCA: VA forms are incorrectly showing up in VBA and VACO sections

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#9469] opened 2022-06-15 15:48 UTC
## Describe the defect

Certain Section listings are showing certain content that they shouldn't. 

Content Manager views built based on Section permissions are showing content with a different Section. 
e.g. VBA section view is showing Forms content with the Octo Section.

## User story
As an editor
I want to see only content that I can edit, in my editor views
so that I don't mess with things I can't / shouldn't touch. 

## To Reproduce
1. Go to [VBA](https://prod.cms.va.gov/section/vba)
2. See Forms listed 
3. Go to [VACO](https://prod.cms.va.gov/section/vaco)
4. See Forms listed

For a specific example form: 
1. Go to [VBA](https://prod.cms.va.gov/section/vba), Filter by Content Type = VA Form
2. Click through to a listed Form, e.g. https://prod.cms.va.gov/node/5714/edit
3. Under Section, see Section is OCTO > Sitewide > Forms

## Screenshots

**Forms appear in VBA section**
<img width="1285" alt="VBA___VA_gov_CMS" src="https://user-images.githubusercontent.com/643678/173870491-c06ed72f-5539-4762-b844-cb486e82a2b8.png">

**Section listed on example form**
<img width="303" alt="Screen Shot 2023-02-16 at 11 53 18 AM" src="https://user-images.githubusercontent.com/85581471/219473325-fa9eefe0-62c5-4ec8-be6a-5bbc7a37b9f1.png">

 ## Additional context
Not sure if this Forms specific, or a canary for something else that's going on. 

When we import from Forms DB, we receive/set a "Form Administration" field that corresponds to the area where these forms are appearing for VBA / VACO. That _could_ be implicated somehow.

## ACs
- [ ] Root cause analysis
- [ ] Determine path forward and cut new ticket

### CMS Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [X] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

**Comment by msbtterswrth** [comment] 2022-06-15 16:24
I found this [related d.o issue](https://www.drupal.org/project/taxonomy_entity_index/issues/2030089). Doesn't seem to be a d8 patch for this issue yet.

**Comment by swirtSJW** [comment] 2022-06-15 17:30
Raised this with module maintainers here https://civicactions.slack.com/archives/C0ASJ7C8P/p1655313649513379

**Comment by swirtSJW** [comment] 2022-06-15 17:36
Sadly they are both foggy on the issue.  So we will have to contribute a patch.

**Comment by EWashb** [comment] 2023-02-16 04:46
@jilladams PW has forms, right? I would like to remove our label and add to your backlog

**Comment by jilladams** [comment] 2023-02-16 19:51
Good call, updated - fyi @wesrowe

**Comment by wesrowe** [comment] 2023-02-16 21:39
Assigned to @dsasser for pre-refinement review.

**Comment by jilladams** [comment] 2023-02-21 21:38
Suspicion: The forms that are appearing incorrectly in these views have that Administration assigned as the Form Administration, from the Forms DB CSV import. I think this may be implicated. 

Example: 
* VBA content manager view: https://prod.cms.va.gov/section/vba
* Shows Form 21P-0571: https://prod.cms.va.gov/node/6089/edit
* Which has Form Administration = VBA set

Backend Refinement: 
* This is where in the code we map the Forms DB Form Administration to a Taxonomy term: https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_node_form.yml
  * Investigation should start with how those terms / vocabularies line up with Sections (or don't), to see if this has anything to do with it

Keeping the 5 estimate (more than a day, less than a week), and can timebox the effort to root cause.

Pulling into sprint for @chri5tia  since she has capacity. Goal is to get to root cause and then double check if 5 sufficient for the fix as well.

**Comment by jilladams** [comment] 2023-02-23 17:30
Ticket was added to sprint opportunistically. However, #12731 is a new ticket with higher priority re: quarterly goals, so: ejecting this, pulling that one in instead.

**Comment by wesrowe** [comment] 2023-03-09 16:43
@jilladams, we're pulling this into sprint 79 opportunistically.

**Comment by dsasser** [comment] 2023-03-10 20:35
## Root cause analysis:

VA Forms have two "administration" fields:

1. "Form Administration"
    a. Machine name: `field_va_form_administration`
    b. Field type: entity_reference.
    c. Referencing "Section" taxonomy terms (parents only, using entity reference selection View administration_section)
2. "Section"
    a. Machine name: `field_administration`
    b. Field type: entity_reference
    c. Referencing "Section" taxonomy terms. Statically set to term id 196 (OCTO -> Sitewide content team -> Forms) for all forms

What this reveals is that VA Forms content has two entity reference fields which map to the same Vocabulary: Sections.

In the View controlling the display of section content (eg: /section/vba), a contextual filter (an argument to the query) is being added which joins data from the `taxonomy_entity_index` database table. This table collects mappings from entities (nodes in this case) to taxonomy terms. Because we are mapping two fields to the same Vocabulary in VA Forms, there will always be two entries for each of the form nodes:

![Screenshot 2023-03-10 at 10 00 54 AM](https://user-images.githubusercontent.com/221539/224392807-0fda8cb8-ae3f-4aaf-ba07-c0954f36c4aa.png)

Due to the query settings for the View (distinct, and aggregated), only one result is displayed for each node, which has a side-effect of masking the underlying problem.

## Possible solutions (in no particular order)

### Don't use an entity_reference field for "Form Administration"
This solution would essentially be to replace the existing 'field_va_form_administration' field, which is an entity reference field, with some other type of field that doesn't reference the same Section vocabulary as the 'field_administration' field.

One type of field we could use is a 'List (select)' field. In this scenario, the select list would be populated with a copy of the root level Section terms. Because it isn't an entity reference field, the taxonomy tables used in the View would not return two instances for the same node.

Side effects with this approach:

- Field name could change, which would cause any GraphQL queries using the old field name to break. This means the query Lighthouse uses to populate the Forms API would need to be altered. Further complicating this is the fact that, graphQL will return the 'key' of the value, rather than the 'label'. For our example node, 5714, this would result in the value '1' to be returned from GraphQL, rather than the expected 'VBA'.
- Forms audit views would need to be updated to replace the field and any related filters.
- A migration from old field -> new field would need to be written.
- Keeping parity between the select field and the Section parent terms would need to be handled. This could be done in an allowed_values_function callback.

### Views query alter
Performing a Views query alter to limit results using a field name. This would alter the query by filtering on the 'taxonomy_entity_index.field_name' column, limiting results to results with the fieldname 'field_administration' (or excluding fields with the name 'field_va_form_administration'.

Side effects with this approach:

- "hides" logic, making it more difficult to troubleshoot in the future.
- Introduces tech debt.
- Is rather "fast" to develop, in terms of the other options.

### Views filter
Ideally, we could filter out certain fields from the section listings by way of configuration in Views. This would require one of several possible solutions, including either adding a field filter (no such filter is provided by the taxonomy_entity_index module), enhancing the existing argument code to do such filtering (probably not recommended as this would also hide the filtering logic)

Side effects with this approach:

- It might be the most difficult/time consuming to write
- It can be committed back to the community as a patch to the taxonomy_entity_index module.
- No hiding of the logic
- Doesn't affect any other content types
- No assumed tech debt

**Comment by jilladams** [comment] 2023-03-10 21:34
Backend refinement: 
- Also discussed: could we swap the taxonomy field to just be a list field with the same machine name. Have to provide a key/value pair, and GraphQL just wants to send a key. Has a GraphQL impact, and Lighthouse impact. So no. 

So: Option 3 wins. This ticket may stay a 5 or may become an 8 in the end.

**Closed** 2023-03-10 21:46 UTC
Labels: Defect, Drupal engineering, Find a form, Public Websites
