### ISSUE TITLE
FE: Featured stories and events should show on the appropriate Lovell system page

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#11941] opened 2022-12-14 16:16 UTC
A story or event assigned to the parent (umbrella) system: Lovell federal health care and also set as featured does not show up as a featured story/event on the home page for either subsystem: Lovell - VA, or Lovell - TRICARE

For other VAMCs this is limited to 1 or 2? Boston is a good example where 2 stories are showing

##### Acceptance Criteria 
- [x] I expect when a published story has the Featured checkbox selected, the following occurs:
   - [x] If it is set to be listed on "Lovell Federal health care: Stories", it shows on both Lovell VA and Lovell TRICARE systems pages
   - [x] If it is set to be listed on "Lovell Federal VA health care: Stories", it shows on the Lovell VA system page only
   - [x] If it is set to be listed on "Lovell Federal TRICARE health care: Stories", it shows on the Lovell TRICARE system page only
   - [x] I expect the maximum number of featured stories we will show is 2 (**note**: this is already implemented at a template level).
- [x] Update https://prod.cms.va.gov/help/vamc/how-do-i-feature-a-story-on-my-sites-homepage to add a Lovell footnote to explain the logic for featuring / umbrella / lower level
- [x] Update https://prod.cms.va.gov/help/vamc/creating-content-for-lovell-federal-health-care for logic re: umbrella updates

<img width="1693" alt="Screenshot 2022-12-15 at 1 36 02 PM" src="https://user-images.githubusercontent.com/21045418/207941613-749059e7-ff5e-49bf-900b-b884a5e9536e.png">

<img width="854" alt="Screenshot 2022-12-15 at 1 36 24 PM" src="https://user-images.githubusercontent.com/21045418/207941634-d01b3510-a04e-443c-9cf4-6485b3f8c3a0.png">

<img width="731" alt="Screenshot 2022-12-15 at 1 41 37 PM" src="https://user-images.githubusercontent.com/21045418/207941646-1694ee77-8146-48ad-a71a-a490f79259f8.png">

**Comment by omahane** [comment] 2022-12-15 19:07
@JayDarnell I see you edited this issue. I was looking at it, too. Do you think the following is accurate:


As a Lovell editor, I would like to feature a story on 
- both Lovell VA and Lovell TRICARE systems pages
- Lovell VA system page only
- Lovell TRICARE system page only

# Acceptance Criteria
- When a published story has the Featured checkbox selected
  - If it is set to be listed on "Lovell Federal health care: Stories", it shows on both Lovell VA and Lovell TRICARE systems pages
  - If it is set to be listed on "Lovell Federal VA health care: Stories", it shows on the Lovell VA system page only
  - If it is set to be listed on "Lovell Federal TRICARE health care: Stories", it shows on the Lovell TRICARE system page only
- The "1st" or "2nd" order setting is honored

**Comment by JayDarnell** [comment] 2022-12-15 19:25
That looks good @omahane - I just verified that featured stories placed directly on either subsystem do show up. So it looks like this ticket needs to get the items posted to the parent (umbrella) system working and to verify the order setting is honoured. 

<img width="1766" alt="Screenshot 2022-12-15 at 2 23 04 PM" src="https://user-images.githubusercontent.com/21045418/207949184-fe5c097e-0384-4a51-84ce-3415e8fc874f.png">

<img width="1779" alt="Screenshot 2022-12-15 at 2 23 23 PM" src="https://user-images.githubusercontent.com/21045418/207949207-08bc137c-f69c-4a35-b29c-a709385f8f87.png">

**Comment by omahane** [comment] 2022-12-15 19:59
Can we try to publish the "Both" story and rebuild to see what shows?

**Comment by JayDarnell** [comment] 2022-12-15 20:30
I tried the both story first and it didn't work @omahane

**Comment by Dottisea** [comment] 2023-01-30 20:19
On hold for now

**Comment by jilladams** [comment] 2023-05-05 15:25
Closing as dupe of https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13615

**Comment by kmariepat-cityfriends** [comment] 2023-05-08 15:51
discuss if this changes priority of this epic: #11401

**Comment by mmiddaugh** [comment] 2023-05-08 18:07
Let's please update KB articles as needed on this (related to workarounds or other info to support editors)

**Comment by kmariepat-cityfriends** [comment] 2023-05-23 15:10
Review of KB Notes:
- @TroyA6 will update a screenshot and publish after

**Comment by kmariepat-cityfriends** [comment] 2023-05-23 15:13
Next steps: update old content in the following KB:
-  https://prod.cms.va.gov/help/vamc/how-do-i-feature-a-story-on-my-sites-homepage
-

**Closed** 2023-05-23 15:17 UTC
Labels: Defect, VAMC, VA.gov frontend, Facilities, VA Lovell
