### ISSUE TITLE
Static Data Files: Add documentation

### ISSUE THREAD

**Issue by ryguyk** [department-of-veterans-affairs/va.gov-cms#9199] opened 2022-05-23 15:30 UTC
## Description
See #8199. The process for generating static data files needs more complete documentation.

**Comment by swirtSJW** [comment] 2022-05-24 21:24
Closing this as duplicate of https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8203

**Closed by swirtSJW** 2022-05-24 21:24 UTC
Labels: Needs refining, Program
