### ISSUE TITLE
[Certificate Alert] Remove PDF Cert Expiration Alerts (end-of-usefulness)

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#11520] opened 2022-11-08 23:26 UTC
## Description
Per Beth Potts, we should remove the alert implemented in this [ticket](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10956).

## Acceptance Criteria
- [x] Remove alert code
- [x] Remove flipper control logic & flipper itself, `pdf_warning_banner`
- [x] Create Platform support request to remove flipper from the UI, e.g. https://dsva.slack.com/archives/CBU0KDSB1/p1725555324327549
  - [x] Verify flipper is no longer present in the [UI](https://api.va.gov/flipper/features)
- [x] Update Product Guide and submit to Contact Center team (#vsp-contact-center-support in DSVA slack)
  - [x] Submitted to Contact Center via their intake ticket
  - [x] Uploaded document to Gihub in the Content Center folder in that Product's file hierarchy

**Comment by wesrowe** [comment] 2023-10-04 16:43
@chriskim2311 or @randimays, can one of you please confirm that the code for the PDF certificate alert has indeed been removed?

**Comment by randimays** [comment] 2023-10-04 17:56
@wesrowe Per [this PR](https://github.com/department-of-veterans-affairs/content-build/pull/1426/files), the content-build PDF certificate alert was removed. That was a form-specific alert.

There is a more general alert for all forms in vets-website where we updated the copy in [this PR](https://github.com/department-of-veterans-affairs/vets-website/pull/23051/files), and that alert still exists.

**Comment by wesrowe** [comment] 2023-10-05 18:04
I had banner blindness. here it is on prod: 
<img width="222" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/4054752/fcaea780-c498-418f-b649-ea074cefa239">

**Comment by wesrowe** [comment] 2023-10-05 18:05
Sync topic: We should connect with Dave, he may refer us to CAIA.

**Comment by FranECross** [comment] 2023-12-06 21:52
Added to Prod sync meeting on 12/13

**Comment by jilladams** [comment] 2024-09-05 17:00
@SnowboardTechie as this is your first PR to roll through I think, holler if you have any questions about process for code review > merge > deploy > verification, etc., to get this to closure. 

Also FYI that I added an AC. There's a weird phenomenon around flippers, for your reference: our code changes will persist. BUT, the Flipper UI (https://api.va.gov/flipper/features) will continue to display the flipper. This is because "flipper cleanup" is done by a sidekiq job that has a bug in it that was wantonly enabling / disabling flippers in Production when it ran, which is... bad. So: Platform team hasn't been able to root cause the bug, and instead have just disabled the Sidekiq job that would otherwise run regularly and remove any flippers from the UI that have been removed in code. As a result, we have to ask them to run one-offs to clean up removed flippers. An example you can follow, once your code deploys: https://dsva.slack.com/archives/CBU0KDSB1/p1725555324327549

**Comment by SnowboardTechie** [comment] 2024-09-05 17:17
@jilladams Thank you for that! I will follow up with that request once the PR is merged. 

I was wondering about the last step "Update Product Guide and submit to Contact Center team (#vsp-contact-center-support in DSVA slack)" what is this product guide piece that requires updating? Is there an example I could follow here as well?

**Comment by jilladams** [comment] 2024-09-05 22:51
What a great question! Didn't even notice that. FYI @FranECross we'll need to figure out if that's still necessary. I _think_ what happened here is that because the PDF cert change went through the Collab Cycle when it originally shipped way back when, the copy was included in our notes to VA's support team / chatbot folks, etc. And that AC means: remove that reference from the product guide that the Contact Center people use, once it's out of the UI.  That's normally a PM task.

(@wesrowe any chance you remember if I have that right?  And/or know how we could find the Product Guide that got sent to Contact Center? I haven't ever dealt with those.)

**Comment by wesrowe** [comment] 2024-09-05 23:43
@jilladams @FranECross, Jill is generally right about what a product guide is. I _probably_ left the Word doc version in the PW sharepoint folders somewhere. But you can also just ask the Contact Center Team for it. 

FSYA I have since learned that the Profile team keeps all the old versions of their product guide in a folder on github – a useful practice.

**Comment by FranECross** [comment] 2024-09-06 16:31
@wesrowe @jilladams I found the product guide on one of the other tickets linked to the epic, updated it, and will share with the content team in their Slack channel, and will mark that done on the ticket. Thanks ya'll! cc @SnowboardTechie

**Comment by FranECross** [comment] 2024-09-06 16:36
As an aside, it looks like they're requesting that product guides be in word docs, and the one we have for this is a PowerPoint slide. I'll convert to a word doc, and then will submit a ticket for them to replace the existing with the new.

**Comment by FranECross** [comment] 2024-09-06 19:54
@SnowboardTechie Product Guide has been updated and submitted via a [ticket ](Contact Center Review for Sitewide Public Websites- Find a Form (aka Find a VA Form) #92362)to the Contact Center (per their instructions). I've marked that off on the AC. cc @jilladams

**Comment by jilladams** [comment] 2024-09-09 16:49
This got auto closed by PR, but not all ACs are complete yet. Reopening and moving to Prod Verification.

**Comment by SnowboardTechie** [comment] 2024-09-09 16:52
PR merged and request to remove flipper has been submitted to platform support [here](https://dsva.slack.com/archives/CBU0KDSB1/p1725900598448809). I will update once they have completed the request and I can confirm the flipper is no longer in the dashboard.

**Comment by SnowboardTechie** [comment] 2024-09-09 21:07
Platform support found this feature flipper was still available in the vets-api itself so I have opened a PR to remove the last remaining piece before they will be able to remove this from the admin dashboard.

**Closed** 2024-09-12 14:47 UTC
Labels: VA.gov frontend, Technical debt, Find a form, Public Websites, sitewide, non-quarter-prio
