### ISSUE TITLE
Bulk user import: Users are not imported as blocked on BRD

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#4275] opened 2021-02-11 18:34 UTC
## Problem statement

During the last bulk user import on prod, all users were created as Active and received account activation email. 
Users should have been created as Blocked on Prod and received "Welcome (waiting approval)" email.

## Acceptance Criteria
- [x] users are imported as blocked on BRD environments
- [ ] users that are imported as blocked receive "Welcome (waiting approval)" email instead of account activation email

potential follow-up https://github.com/department-of-veterans-affairs/va.gov-cms/issues/4270

**Comment by ElijahLynn** [comment] 2021-02-16 16:17
When testing this, note that Tugboat has an SMTP intercept feature and all emails sent _should_ be available in the Tugboat UI, see screenshot:
![image](https://user-images.githubusercontent.com/1504756/108090438-77c36500-702f-11eb-80fe-8285659eced9.png)

**Comment by acrollet** [comment] 2021-02-17 21:23
@oksana-c @xiongjaneg On investigating this issue, I've determined that the emails are not being sent during the import process, but when the account is later edited and activated, at which time the [Account Activation](https://prod.cms.va.gov/admin/content-models/users) email is sent.

One can confirm by cross-referencing the timestamps on Vanessa Luxen's [account history](https://prod.cms.va.gov/user/1685/history) and the [email that was sent to her](https://dsva.slack.com/archives/CT4GZBM8F/p1613054660386900?thread_ts=1613051593.372200&cid=CT4GZBM8F). I've also just confirmed this myself by importing [my own VA account](https://prod.cms.va.gov/user/1693) - it was imported as blocked, and I haven't received an email after 15 minutes.

I also cross-referenced the timing on the [email sent to Christopher Durney](https://dsva.slack.com/archives/CT4GZBM8F/p1613577883264800?thread_ts=1613576753.262900&cid=CT4GZBM8F) and it matches up with when the account was manually activated.

Regarding the AC to send the "Welcome (waiting approval)" email, that email's wording references accounts that are self-created by users. (That option isn't enabled on the CMS) Do we want to update the wording and send that email? If so we should rope @rachel-kauff into this discussion :-)

**Comment by xiongjaneg** [comment] 2021-02-17 21:34
Hmmm, this surprises me since the only action I took after importing into prod was to block users. However, if bulk import in prod is acting as expected with blocked status and not sending any emails, that's the desired action for our workflow. When bulk importing users into prod for training purposes, we don't want them to know. We only send emails when the training demo environment has been refreshed and their training accounts are activated.

**Comment by acrollet** [comment] 2021-02-17 21:37
@xiongjaneg yeah, I was surprised too, my assumption was that the issue was with the import, not with you! I'm wondering if the issue is actually with the user edit form or bulk operations... Perhaps next time you need to import users we can screenshare and maybe start with one user and confirm the behavior together?

**Comment by xiongjaneg** [comment] 2021-02-17 21:42
Sounds good. I'll let you know when I get the next list from Stan. Sometimes having extra eyes just makes things work magically well.

**Comment by acrollet** [comment] 2021-03-03 22:45
@xiongjaneg does https://github.com/department-of-veterans-affairs/va.gov-cms/issues/4248#issuecomment-790087977 mean that we can close this issue out? Thanks! :-)

**Comment by xiongjaneg** [comment] 2021-03-03 22:52
@acrollet Just for my own paranoia, I'm going to do one more test with yours and Vanessa's VA emails and then I'll close it out tomorrow. Thanks!

**Comment by acrollet** [comment] 2021-03-03 22:55
@xiongjaneg awesome, thanks! :-)

**Comment by xiongjaneg** [comment] 2021-03-03 22:59
The Acceptance Criteria should be the following:
 - [ ] users are imported as blocked on BRD environments
 - [ ] users that are imported as blocked in prod **don't get any message** (at least for training purposes, they shouldn't know they've been added to prod, we refresh the training environment to add them there, and then help desk sends a separate email with training instructions)

**Comment by xiongjaneg** [comment] 2021-03-03 23:07
@acrollet @VanessaLuxen I deleted your Va email accounts then re-imported them as blocked with the same permissions VAMC editors would have. As long as you didn't receive any emails, we're good to go on this issue.

**Comment by VanessaLuxen** [comment] 2021-03-04 14:40
@xiongjaneg I did not receive an email.

**Comment by acrollet** [comment] 2021-03-04 14:41
@xiongjaneg I need to do the PIV exemption dance before I can check, I'll work on it later today...

**Comment by xiongjaneg** [comment] 2021-03-06 13:57
Verified that test users didn't receive automated email when their blocked accounts were imported.

**Closed** 2021-03-06 13:57 UTC
Labels: Core Application Team, Defect, Planned work
