### ISSUE TITLE
When editing an existing event, the duration field is wrong

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#3496] opened 2020-11-16 19:01 UTC
**Describe the defect**

**To Reproduce**
1. Create an event that is 2 hours long /node/add/event (you can use the duration field)
2. edit the event
3. the duration field goes back to 1 hour

**Expected behavior**
1. the duration field should reflect he actual duration, not revert to 1 hour. 

**Screenshots**
![image](https://user-images.githubusercontent.com/643678/99295893-f67fea80-2813-11eb-8524-399effb4fa0f.png)

**Comment by swirtSJW** [comment] 2020-11-16 19:35
The issue is related to a missing bit of data on the migration.  These work fine when all he data is present.     Since it is part of the migration, we are fixing it in that ticket .

I am closing this one.

**Closed by swirtSJW** 2020-11-16 19:35 UTC
Labels: Content forms, Defect
