### ISSUE TITLE
SPIKE: Mental Health Numbers

### ISSUE THREAD

**Issue by kmariepat-cityfriends** [department-of-veterans-affairs/va.gov-cms#13785] opened 2023-05-22 15:59 UTC
As an editor of mental health numbers, I need to specify the primary mental health phone number for a facility 

I expect this is structured as single source of truth, don't want another field that uses the same phone number under the service. just putting a phone number on the facility could create duplication 
no divergence between facility health service number 

We have a mental health service where editors put in phone numbers AND we want a field to designate the primary health number AND we don't want editors to maintain numbers in two different places

Right now we know not every facility has a mental health number, it is not a required service. Working with office of mental health need to determine if it's a required field.

FE Notes:
- already a spot on the front end for mental health (may need updated queries to pull the correct number)
- need CM that number is no longer coming from lighthouse (they are now responsible) 

##### Acceptance Criteria
- [x] I expect that at least 2 approaches are proposed for implementing the following user story `As an editor of mental health numbers, I need to specify the primary mental health phone number for a facility` note that we do not divergence between facility health service number 
- [x] consider that FE changes may be needed based on approach 
- [x] Note that this data will have to be pushed to Lighthouse, keep this in mind while working through solutions 
- [x] I expect Blake on CMS team is consulted (and ask thoughts on expectation for reviewing and partnering on this work, use collab cycle?)
- [x] I expect that the approaches are reviewed with the team and PO (meeting scheduled to get complete AC)

**Comment by kmariepat-cityfriends** [comment] 2023-05-22 16:01
This will not be deployed ahead of change management plan, that will be in place before the code is merged

**Comment by kmariepat-cityfriends** [comment] 2023-05-22 16:02
maybe starting with a spike, using editorial flipper

**Comment by kmariepat-cityfriends** [comment] 2023-05-22 16:04
How and when and what do we need to worry about in terms of collisions, how do we pair this with other comms

**Comment by mmiddaugh** [comment] 2023-05-22 21:55
In addition to the facility location information, mental health service accordion, and Facility Locator search results, the mental health number also appears on the system level mental health care coordinator page, i.e. [VA Wilmington health care > Health services > Mental health care ](https://www.va.gov/wilmington-health-care/health-services/mental-health-care/) page (not just within the accordion)

**Comment by kmariepat-cityfriends** [comment] 2023-05-25 17:03
The approaches determined in this card will be reviewed and validated with editors (talk further about approcah and resources needed for this)

**Comment by kmariepat-cityfriends** [comment] 2023-05-25 17:07
@kmariepat-cityfriends to make a new card to audit KB articles where this is mentioned

it is known to be mentioned in the `basic facility info` article 

ask VHA DM what they are concerned

**Comment by mmiddaugh** [comment] 2023-06-07 16:20
Most recent information informed by a conversation with the Office of Mental Health 

- We have support for moving toward CMS as a single source of truth
- There _may_ be a need to default to a Clinical contact center phone number if no mental health number is available (Clinical contact center numbers are assigned at a VISN level and are partially present in CMS. They would need a label to differentiate them from a local facility number for Veteran understanding)

**Comment by swirtSJW** [comment] 2023-06-16 14:46
## Option 1

**Comment by swirtSJW** [comment] 2023-06-16 14:46
## Option 2

**Comment by swirtSJW** [comment] 2023-06-16 15:56
Every facility gets the field-mental-health-phone from the migration from the FacilityAPI from the entry phone[mental_health_clinic]    Out of the 1,324 vha facilities, 871 (66%) have mental_health_clinic numbers, so 66% of the facilities in the CMS have this value.
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/f118b7af-8cd0-41ef-abce-46e69529cf28)

So the question is, should we stop grabbing that value from the FAPI and just let the facility edit that value from this point forward?

**Comment by swirtSJW** [comment] 2023-06-16 22:02
@kmariepat-cityfriends In hindsight I think this AC is a bit misplaced (I know I am the one that misplaced it).  

> I expect Blake on CMS team is consulted (and ask thoughts on expectation for reviewing and partnering on this work, use collab cycle?)

I think it is too early to bring CMS team or Blake into this until **after** we pick one of the two paths and refine the chosen path more.  They need more refining because there is still some uncertainty on the business logic behind all this.

**Comment by swirtSJW** [comment] 2023-06-16 22:05
>  I expect that the approaches are reviewed with the team and PO

@kmariepat-cityfriends & @jilladams  I think we are far enough along on this that I can explain the possible approaches to our product owner(s) and the team.  So we are good to go for a meeting.

**Comment by jilladams** [comment] 2023-06-20 15:28
@kmariepat-cityfriends 2 things here, from scrum discussion: 
1. We need to review the proposals here (options 1 & 2) to get final clarifications from VHA DM on which way to go. Maybe also Lighthouse.
2. For VHA DM sync, is it possible to move the standing agenda / notes doc into the Team folder so we can all access / add to it?

**Comment by mmiddaugh** [comment] 2023-06-20 15:42
@swirtSJW and I discussed the above questions live - posting answers here for our future selves

- Q: Should we stop grabbing that value from the FAPI and just let the facility edit that value from this point forward? Or do we have low confidence in the values coming from the Facility API and we want to start with a blank slate?
  - _A: For the most part, Jay's earlier analysis revealed a few discrepancies between the mental health number at the facility level and those at the mental health service level so we should be able to use existing numbers as a starting point_
- Q: Would this value be required for every facility (editor can't save without it?) There was mention higher up about the possible need for a fallback number
    - _A:  We should confirm this with VHA DM_
- Q: You mentioned higher up about there being a number that was at the VISN level (Clinical contact center) that might need to be a fallback. Is this something you envision living at the system level?
    - _A: The Clinical contact center number previously mentioned is also known as VA health connect (which is already a concept in Drupal for the VISNs in which it is available). Given it is not widely available, it probably isn't a viable option as a default for most VISNs and could be theoretically be entered by editors if desired. Otherwise, we're not expecting other system level numbers of this sort to be needed._

One additional note: we're expecting Mental health service availability and phone numbers to be confirmed during the planned health service validation process. We need to learn more from VHA DM about the timing of this initiative.

**Comment by jilladams** [comment] 2023-06-20 21:43
@swirtSJW can you confirm re: the AC on talking to Blake about this ticket? Is that done and the VHA DM check is all that's left?

**Closed** 2023-06-21 13:25 UTC
Labels: Drupal engineering, Facilities

**Comment by mmiddaugh** [comment] 2023-06-28 22:28
@swirtSJW @kmariepat-cityfriends I'm wondering about the need to make it clear to editors in the interface that the phone number entered into the mental health facility field will be the one pushed to Lighthouse and therefore available in Facility Locator search results and possibly elsewhere in the ecosystem

**Comment by davidmpickett** [comment] 2023-08-31 22:12
My very official wireframe of a possible interface for adding to VAMC Facility

![20230831_170239](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/89cbd28a-2c96-40c3-9cc9-011dedba2fba)

Very official explanation of interaction

1 - would check for instance of Mental Healthcare service at this facility. If found, display all associated phone numbers and let editor pick one (simpler version, pick the first phone number from the first service location)

2 - populate this field with data from a new field on VAMC system that indicates 1 fallback mental health number per VAMC system

3 - lets editor put in a different phone number that is specific to facility and different from previous two options. Could we prepopulate this field with existing data from Lighthouse to give editors a starting point?

**Comment by davidmpickett** [comment] 2023-08-31 22:16
This is very much in line with [option 2](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13785#issuecomment-1594815334) proposed by @swirtSJW, but more transparent to the editors about choosing between possible sources.

**Comment by mmiddaugh** [comment] 2023-08-31 23:15
Can we simplify even more to this ->Prepopulate the field with the phone number from the first service location in Mental health and make it editable. 

I think this solves Jill's question about what to do with new facilities because it requires the presence of the mental health service, right?
