### ISSUE TITLE
Investigate potential caching defect on user perms service.

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#5521] opened 2021-06-04 18:25 UTC
**Describe the defect**
There are fleeting instances where a user sees options as though they were limited for another user.   A cache clear resolves the issue, potentially just for that user and for that instance in time.

![image](https://user-images.githubusercontent.com/5752113/120846744-926b0c80-c540-11eb-83f0-8fef633ed030.png)
![image](https://user-images.githubusercontent.com/5752113/120846820-a878cd00-c540-11eb-956a-87f0569a443e.png)

**To Reproduce**
reproducing this is part of the challenge and the investigation.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information if relevant, or delete):**

**Additional context**
Add any other context about the problem here. Reach out to the Product Managers to determine if it should be escalated as critical (prevents users from accomplishing their work with no known workaround and needs to be addressed within 2 business days).

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Defect")
- [x] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [ ] CMS objective (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Core Application Team`
- [x] `Product Support Team`

**Comment by kevwalsh** [comment] 2021-06-07 12:59
This may be a dupe of #5025, but this may have more info.

**Closed** 2021-06-07 14:34 UTC
Labels: Defect, Needs refining, Product Support Team, invalid-duplicate
