### ISSUE TITLE
BE Spike: Add Magichead collapse functionality during initial creation of a new Section

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#14534] opened 2023-07-26 03:49 UTC
### User story

AS A Content Editor adding a new "magichead" Section to a Benefits Taxonomy term,
I WANT to be able to collapse the new Section (and any other Sections) without saving first (which is a workaround)
SO THAT I can use drag-and-drop to adjust Section depths (which is much more difficult when they're not collapsed)

### Current behavior

In the [Tugboat](https://cms-sszuuulgluyv7apczcgnke3zom2tnz5x.ci.cms.va.gov/) where we've been doing testing (as of July 25), there is no collapse or collapse-all option in the UI during Edit mode.

Note: During internal testing the collapse buttons were present for Edit mode, but they were never present for initial "Add" (creation) of a new term.

### Engineering notes / background

Per discussion in refinement on 7/27:
- The button options on a newly-create Section are controlled by the Paragraph module/UI that we're using. Modifying would be a huge lift since there's so much under-the-hood with "collapse" functionality.
- Recommended alternative approach: try adding a new/custom button that applies a CSS class to simply make the row much less tall, or JS functionality, but doesn't attempt the complex stuff of an actual collapse button

## Acceptance criteria

Timebox: 3 points (~1 day), come up for air

- [ ] Tried the approach of adding a "collapse-ish" button that is present when first creating a magichead (Eligibility Overview) Section
- [ ] Reviewed UX with PM and decided whether it would be viable
- [ ] Ticketed next steps, if any

**Comment by dsasser** [comment] 2023-09-15 16:34
# Update 9/15/23

I have attempted two methods leveraging contributed modules which come at the problem in different ways: client-side javascript, and Paragraphs field widgets. Neither has worked unfortunately. Both seem like valid paths to continue to work through, however I'm currently favoring the Paragraph field widget over the javascript method. The "stable" paragraph field widget is already used in many places in the CMS, so editors will be familiar with it.

<details>
<summary>Trying the (stable) paragraphs field widget</summary>

Magichead is leveraging the field widget provided by Entity Reference Hierarchy, which itself is inheriting 99% of it's code from the Paragraphs module 'classic' field widget.

It seemed natural, then, to pursue the other field widget provided by Paragraphs, which provides the collapse, collapse all, and many other functions.

This widget provides the collapse and collapse all functions we have seen in other areas of the CMS that use paragraphs. Some of the options it provides:

![Screenshot 2023-09-15 at 8 51 16 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/221539/0732e9dc-d6b2-40aa-a4ab-dcb76ac35cfa)

The default UI for magichead:

![Screenshot 2023-09-15 at 8 54 42 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/221539/82483de8-239c-41d2-be43-743211ac8ae4)

The collapse button is visible, and functional. However, the 'depth' field is missing from the table, and items cannot be nested. 

I tried to add the depth field without enhancing the Paragraphs widget, and the result is less than desirable. Not only are the depth fields visible, but the tabledrag behavior is completely broken in every way:

![Screenshot 2023-09-15 at 9 00 30 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/221539/cf9e3e8b-9cd7-459d-aa3b-cd879e9be664)

I spent a day attempting to correct these issues, but did not succeed. Each problem solved created at least one new issue. This is contributed to the fact that the Paragraphs module code is vast and difficult to navigate. However, I'm confident that with sufficient time, we could get this working.

</details>

<details>
<summary>A Javascript solution</summary>
We could provide client-side javascript solution which doesn't touch any of the existing Paragraphs code. I found that this was [attempted back in 2018](https://github.com/AmazeeLabs/paragraphs_collapsible/commits/8.x-1.x) in a module called [Paragraphs Collapsible](https://www.drupal.org/project/paragraphs_collapsible).

I dropped this into our codebase, but the javascript is not functional because it is making assumptions that are no longer true (it is attempting to target markup that isn't on the page).

To pursue this, I would need to rewrite the entire script.

</details>

**Comment by dsasser** [comment] 2023-09-21 02:53
> @dsasser, have you completed the spike, in terms of timebox? If so, are we ready to ticket the follow-up implementation? I'm curious what your estimate would be to get past the issues you encountered.

I want to take another crack at it tomorrow, which I think still fits within the original timebox. As of now, I don't have a strong idea of the effort involved, but I definitely will before sprint end.

**Comment by dsasser** [comment] 2023-09-22 19:01
# SPIKE Results

With some modifications, we can leverage the existing Paragraphs field widget (referred to as 'Paragraphs (stable)' in the CMS UI). This field widget provides the collapse feature out-of-the-box, among other features should we choose to use them. The field widget is the primary field widget used for many of our Paragraphs fields across the CMS, so it will cause no need for additional user training.

The overall effort will be a **5**, depending on UX/product review outcomes.

These screenshots show the out-of-the-box behavior of the field widget in the magichead context:

New term without a magichead item:
![Screenshot 2023-09-22 at 11 29 40 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/221539/9438095d-c592-43c4-bac6-78afad72a786)

Adding a new magichead item:
![Screenshot 2023-09-22 at 11 29 51 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/221539/399a3070-6973-4744-9581-baa966303e14)

Collapsing a new magichead item:
![Screenshot 2023-09-22 at 11 30 09 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/221539/a10ba3ba-cdc4-4403-accf-3e43227387a8)

<details>

<summary>Implementation Details</summary>

To implement the new widget, we will need to:

- Create a new field widget class in Entity Reference Hierarchy Paragraphs. This should be committed back to the community. This class should inherit from `ParagraphsWidget` from the Paragraphs module. The `entity_reference_hierarchy_paragraphs_preprocess_field_multiple_value_form` function will need to be modified to take into account the extra row added to the table. Specifically, anywhere `$variables['table']['#rows'][$key]` is used, we need to add 1 to the $key: `$key + 1`. The code should be aware of which field widget is being used, and make the correct decision based on this. See [this branch](https://github.com/department-of-veterans-affairs/va.gov-cms/tree/VACMS-14534-magichead-collapse) for changes I made during the spike.
- Create a new magichead field widget, which inherits from the new widget created from above. This widget exists to add our custom depth field limitation, as well as form error handling.
- Address any UX concerns
- Resolve regressions noted below

</details>

<details>

<summary>Regressions</summary>

Using this widget does regress some things:

- The tree lines no longer appear. This is expected, since the existing css is targeting markup for the existing field widget. Modifying the css should be minimal effort.
- When depth field errors are encountered, our custom javascript that displays the error message for only the offending table is affecting all tables on the form. This, in turn, is turning on 'Show row weights' for the entire site, which is not expected. This too should be minimal effort to resolve.
</details>

## Next Steps

- Meet w/ UX and PM to review findings. Scheduled for Monday 9/25 at 2:00 Pacific.
- Create tickets based on that conversation

**Closed** 2023-09-26 15:42 UTC
Labels: Drupal engineering, Public Websites, backend, VA Benefits Taxonomy
