### ISSUE TITLE
SE: Drupal Upgrade

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-cms#11614] opened 2022-11-16 17:51 UTC
## Description
Drupal 9.5 is going to be released [soon](https://www.drupal.org/project/drupal/releases/9.5.0-rc1), presumably.

Drupal 9.5 is the deprecated-code-friendly equivalent to Drupal 10, which will be released about the same time.

## Acceptance Criteria
- [x] We've upgraded from Drupal 9.4 to 9.5, along with the relevant dependencies.

**Comment by EWashb** [comment] 2022-11-16 19:08
Let's think through which version and run all of the regression testing.

**Comment by EWashb** [comment] 2022-11-16 19:09
check runbooks for minor vs. major around upgrades.

**Comment by EWashb** [comment] 2023-07-25 02:27
@productmike @BerniXiongA6 are we tracking these items as a part of our D10 upgrade? I'm afraid these items have fallen through the cracks since we have more than one Drupal Upgrade Epic. Seems high priority to look at these associated tickets.

**Comment by productmike** [comment] 2023-07-25 15:34
@EWashb It's a good call out. The best way to approach this at this point would be to treat these as specific test cases for the team to run through and either close out or shift to the active epic. Part of the ongoing testing is for the team to group each week to review the entered defects. Thinking I can include this list as part of the review too.

cc: @BerniXiongA6

**Comment by productmike** [comment] 2023-07-28 15:53
Closing this epic in favor of #14410

**Closed by productmike** 2023-07-28 15:53 UTC
Labels: Epic, Needs refining, CMS Team, Quality Assurance
