### ISSUE TITLE
[VA Benefits Taxonomy] Add new 'Application process' field to 'How to Apply' section

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#18163] opened 2024-05-20 16:31 UTC
## Status
**[2024-08-12] [Dave]** Updating ticket based on 1on1 convo with Michelle
**[2024-08-08] [Fran]** Meeting scheduled for Tues, 8/13 to discuss this.
**[2024-07-31] [Fran]** Fran to schedule a meeting with Michelle, Dave P, and Daniel to discuss further. 
**[July 24, 2024]** per [slack thread](https://dsva.slack.com/archives/C06S9DADEUB/p1721835249015599) @mmiddaugh will be reaching out to stakeholders for clarification

## Description
In order to help Veterans, their caregivers, and family members navigate applying for benefits, we need to provide guidance on nuances of when and how to use different forms that are linked to a Benefit.

For instance, for programs like dental care where you apply by filling out the health care Form 10-10EZ (which is the full healthcare form, not just for dental), we understand it might not be obvious to the user/Veteran that they need to fill out the 10-10EZ form for that benefit.

The current Benefit Taxonomy build allows for connecting multiple Forms to a benefit, but doesn't have any place to add context abut those forms.

![how_to_apply](https://github.com/user-attachments/assets/daa1356a-3dbc-4b0e-98a4-9dd569202277)

### User story

**AS A** Veteran, their family member or caregiver who is reviewing how to apply for benefits
**I WANT** to clearly understand what I need to do and/or fill out in order to apply
**SO THAT** I can quickly and with minimum frustration apply for benefits.

## Content modeling considerations

We allow for linking VA Forms nodes to VA Benefit terms. Once linked, any information about the Form could also be displayed in any context the Benefit is.

### Content that belongs on the VA Form content type

These fields are **out-of-scope** for this ticket, just providing them as examples of stuff that is definitely Form-specific and not Benefit-specific

**Form versions**
- Link to online tool
- PDF form
- Alternate language version of form
- Related forms

**Ways to apply**
- How to apply online
- How to apply by mail
- How to apply in person
- How to apply by fax
- How to apply by phone

### Why is the 'When to use this form' field on VA Form not enough?

One extant field on the Form type that could theoretically be pulled through to Benefits once Forms are linked is the 'When to use this form' field. 

<img width="809" alt="Screenshot 2024-08-13 at 10 22 14 AM" src="https://github.com/user-attachments/assets/dce759a5-9b62-45a3-a79a-eed66999fefd">

One of the main questions that needs to be resolved before this ticket moves forward is what would we add on the Benefit side that is meaningfully different from the content that exists in this field.

### VA dental care = Multiple benefits with 1 form
VA health care and VA dental care are separate benefits that share an application form, [10-10EZ](https://www.va.gov/find-forms/about-form-10-10ez/)

The `When to use this form` field describes the primary use case of health care:
> Use VA Form 10-10EZ if you’re a Veteran and want to apply for VA health care. You must be enrolled in VA health care to get care at VA health facilities or to have us cover your care at a community care provider (an approved non-VA provider).  

Trying to add a note about dental care into that field might distract from the primary focus. Pulling through a description that focus on health care to show in the dental care context could be confusing. 

### Disability benefits = 1 benefit with mutiple forms
Disability benefits has a lot of different forms. Here are just three that might be considered on first application.

- Optional & BEFORE primary = [Intent to file](https://www.va.gov/find-forms/about-form-21-0966/)
- Required & Primary form = [Disability claim](https://www.va.gov/find-forms/about-form-21-526ez/)
- Optional & WITH primary [Supplemental form for mental health condition](https://www.va.gov/find-forms/about-form-21-0781/) 
https://www.va.gov/find-forms/about-form-21-8940/

The Intent to file form `When to use this form`
> Use VA Form 21-0966 if you’re still gathering information to support your claim, and want to start the filing process. Submitting an intent to file can secure the earliest possible effective date for any retroactive payments you may be eligible to receive.

The primary form `When to use this form`
> Use VA Form 21-526EZ when you want to apply for VA disability compensation (pay) and related benefits.

The optional form's `When to use this form`
> Use VA Form 21-0781 if you’ve been diagnosed with a mental health condition related to a traumatic event during your military service, and you want to apply for related benefits or services.
> 
> As of June 28, 2024, we’ve discontinued the Statement in Support of Claim for Service Connection for PTSD Secondary to Personal Assault (VA Form 21-0781a). We previously used this form to get more information to support claims for posttraumatic stress disorder (PTSD) related to personal assault. We’ve combined this form into a new PDF version of the Statement in Support of Claimed Mental Health Disorder(s) Due to an In-Service Traumatic Event(s) (VA Form 21-0781). You can download the updated PDF form on this page. 
> 
> These are some examples of mental health conditions:
> 
> Posttraumatic stress disorder (PTSD)
> Major depressive disorder
> Generalized anxiety disorder
> Bipolar disorder
> Traumatic events during your military service can include any of these types of events:
> 
> Combat events, like engaging in combat with enemy forces, experiencing fear of hostile military or terrorist activity, serving in an imminent danger area, or serving as a drone aircraft crew member
> Sexual assault or harassment (also known as military sexual trauma or MST)
> Traumatic personal events, like physical assault, battery, robbery, mugging, stalking, or harassment by a person who wasn’t part of an enemy force, or domestic abuse or harassment by a partner 
> Other traumatic events, like getting into a car accident, witnessing a natural disaster, working on burn ward or graves registration, witnessing the death, injury, or threat to another person or to yourself, that was caused by something other than a hostile military or terrorist activity, or experiencing or witnessing friendly fire that occurred on a gunnery range during a training mission
> Note: This form is optional. But if you’re submitting a claim related to a mental health condition, this form could help with your claim. We’ll use the information you provide to help identify records and other evidence to support your claim.

## Proposal

- Add a new limited rich text field to the VA Benefit Taxonomy in the How To Apply section
- **Field type**: Text (formatted, long)
- **Text format**: Rich Text Limited
- **Character limit**: Unlimited
- **Required**: No (for now)
- **Machine name**: field_va_benefit_app_process
- **Label**: "Application process"
- **Help text**: "Briefly describe the benefit application process, including which form(s) are required or optional."
- **Position:** After 'Preparing to apply' and before 'How to get help' 

## Acceptance criteria

- [ ] Update the How to Apply section(s) with new field
- [ ] Content Admins can fill out the new field when editing a term in VA Benefit taxonomy

**Comment by mmiddaugh** [comment] 2024-07-15 19:51
@FranECross @davidmpickett I will get clarity on this request during a meeting with Danielle and Randi H on 7/24

**Comment by mmiddaugh** [comment] 2024-07-30 22:31
@davidmpickett, the original intent of this request was to add fields for the options (and instructions) by which a Veteran can apply, such as applying online with the digital form, downloading the form and mailing it, getting assistance with the application by phone or in person, etc. 

But does "how to use this form to apply" content belong to the form or to the benefit? How might we connect the form and benefit? If we are able to add these options/instructions into the model, they might also be used in other templates, such as the "About this form" template or elsewhere. 

**Other details**
The model should not expect all options for all benefits or forms. 
<details>
<summary> Summary of my quick analysis across 7 different forms/benefits </summary>

- online application x 7
- applying by phone (or more accurately, getting help filling out the form by phone) x 1
- applying by mail (by downloading the form and mailing it) x 7
- applying in person (by getting help filling out the form in person or by filling it out in advance and submitting it in person) x 5
- applying with the help of a trained professional x 4 (related: through a lender x 1)
- applying by fax x 1
- uploading a downloaded application x 1
</details>
--- 
There is a need to delineate the form used to apply vs other related forms (and the details which are available about those forms should be different) 

Let's chat about this when you return and consider the best approach and next steps

**Comment by FranECross** [comment] 2024-07-31 16:00
Thanks, @mmiddaugh ! I'll get a meeting on the calendar with you, Dave, me and Daniel Sasser (to keep him in the loop). cc @dsasser

**Comment by davidmpickett** [comment] 2024-08-05 16:03
Bit of historical context here. We discussed these issues back in February 2023. Here's a [relevant portion of the decision log](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/structured-content/benefits-content-model/decision-log.md#intersection-with-the-forms-content-model-used-by-the-find-a-form-product).

> But does "how to use this form to apply" content belong to the form or to the benefit? How might we connect the form and benefit?

Dave Conlon's opinion was that this type of information should be connected to the Form content model rather than the Benefit content model. 

> There is a need to delineate the form used to apply vs other related forms (and the details which are available about those forms should be different)

I had proposed a field for "Related VA Forms Guidance", but according to the decision log: "MVP will not have a new field; editors will look at "when to use" field in Forms content model and determine if this separate field will be needed." This is an example of what that field looks like on the VA Form content type:

![Screenshot 2024-08-05 at 10 44 36 AM](https://github.com/user-attachments/assets/e668534b-d40d-44f7-b68e-6ab918d9dbfd)

> Summary of my quick analysis across 7 different forms/benefits

FYI I did a slightly deeper audit last year

[VA Benefit Content Model Taxonomy spec.xlsx](https://github.com/user-attachments/files/16500076/VA.Benefit.Content.Model.Taxonomy.spec.xlsx)

- Does this require an application?
  - Apply
  - Apply for pre-requisite
  - Apply with pre-requisite
  - Possible extra form
  - Intent to file
  - Enroll
  - Auto-enroll
  - How to get
  - Closed
- Forms for applying
  - Do forms need to be modeled separate from benefits?
  - Link to pdf
  - Link to online form
  - Multiple forms = Primary & supplemental
  - Multiple forms = Different forms for different audiences
  - Multiple forms = This is really two benefits
- How to prepare (evidence)
  - This is likely to be blobby
  - “Preparing to apply” of how to apply
  - “Prepare” section of Apply now pages
  - Sometimes have to look at the PDF
- Ways to apply
  - How to apply online
  - How to apply by mail
  - How to apply in person
  - How to apply by fax
  - How to apply by phone
  - How to apply with help from a professional
- How to get help with your application
  - This is separate from applying with help from a professional

**Comment by davidmpickett** [comment] 2024-08-12 21:20
@FranECross FYI - @mmiddaugh and I talked through some of the content modeling considerations for this ticket in a 1on1 meeting today. I just updated the ticket to better reflect our current thinking. I can walk through that background in the meeting tomorrow and then we can talk about options for implementation direction.

**Comment by jv-agile6** [comment] 2024-09-05 15:14
Took assignment of ticket and moved to in-progress.

**Comment by jv-agile6** [comment] 2024-09-05 20:05
Created new branch - VACMS-18163-BenefitsTaxonomy-NewApplicationProcess-field-HowtoApply 
Pulled fresh DB - ● λ ddev pull va --skip-files -y

**Comment by jv-agile6** [comment] 2024-09-05 21:04
Added 

- config/sync/field.field.taxonomy_term.va_benefits_taxonomy.field_application_process.yml

- config/sync/field.storage.taxonomy_term.field_application_process.yml

Commit -m "VACMS-18163: added rich text field to VA Benefits taxonomy"

**Comment by jv-agile6** [comment] 2024-09-11 20:49
updated QA steps on pull request. Sent slack message to @davidmpickett for his 👀 on it before review

**Comment by jv-agile6** [comment] 2024-09-12 17:15
Recieved feed back from @davidmpickett on QA to incorporate into ticket before PR.

"When writing QA steps, it's best to focus on recreating the end user experience and detailing the steps a user would take to interact with the new functionality, rather than where an admin could go to verify the config.
(
So you'd probably want to have the steps point to [va_benefits_taxonomy/overview ](https://pr19127-hydi1bigqwffplm36wq4lr9av81xbcsc.ci.cms.va.gov/admin/structure/taxonomy/manage/va_benefits_taxonomy/overview)
[11:52](https://dsva.slack.com/archives/D079PMD7Z1Q/p1726159931617309)

and then explain the steps to edit a Term and verify that the new field is functioning as intended.

It looks like the "Application process" field is currently disabled on the Form Display. That means editors wouldn't actually be able to interact with the field"

**Comment by jilladams** [comment] 2024-09-17 15:48
Ready for PR, needs QA steps added from a user perspective.

**Comment by jv-agile6** [comment] 2024-09-20 13:26
One more code review before pull request now that QA has been completed. Goal is to have this accomplished by EOD

**Comment by jv-agile6** [comment] 2024-09-27 18:55
Resolving failures in PR tests.
- va/tests/cypress — Failure
Required
- va/tests/status-error — Failure
Required

**Comment by jv-agile6** [comment] 2024-09-27 19:00
![Image](https://github.com/user-attachments/assets/16a9a16d-b48e-4239-9cc8-e3119b939030)

**Comment by jv-agile6** [comment] 2024-10-09 15:49
A rebasing effort had polluted branch with commits outside of AC.  Resolved rebase by creating and new branch [VACMS-18163-BenefitsTaxonomy-NewApplicationProcessField-HowtoApply]. Resolved config conflicts, committed solution 

> core.entity_form_display.taxonomy_term.va_benefits_taxonomy.default
> core.entity_view_display.taxonomy_term.va_benefits_taxonomy.default
> field.field.taxonomy_term.va_benefits_taxonomy.field_field_va_benefit_app_proce
> field.storage.taxonomy_term.field_field_va_benefit_app_proce

and pushed branch. Drafted PR and added testing steps.  PR is failing 2 Cyperess tests
![Image](https://github.com/user-attachments/assets/6f803dc6-35f0-4063-80b3-54d626f7cf9e)

Spec                                              Tests  Passing  Failing  Pending  Skipped  
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ ✖  platform/media.feature                   14:16        8        7        1        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✖  platform/text_validation.feature         05:12        2        1        1        -        - │

**Comment by jv-agile6** [comment] 2024-10-09 20:58
Pull Request finalized. Awaiting approval to merge.

**Comment by jv-agile6** [comment] 2024-10-10 20:57
Branch has been merged

**Comment by jilladams** [comment] 2024-10-10 23:37
Congrats, @jv-agile6 ! Once it's up in production, please tag @FranECross or I to take a look for product acceptance, and we can close! WOO!

**Comment by jilladams** [comment] 2024-10-15 20:42
Visible in prod CMS! Go team. 
![Image](https://github.com/user-attachments/assets/80d849fc-3c76-4602-b5e7-ad5e2c7a5b26)

**Closed by jilladams** 2024-10-15 20:42 UTC
Labels: Drupal engineering, Content strategy, Public Websites, sitewide, VA Benefits Taxonomy, Drupal Site Building
