### ISSUE TITLE
[V1 & 3 Components] Homepage full width banner not using uswds component

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#18895] opened 2024-08-09 18:52 UTC
## Description
Jamie Gibbs noted that she's seeing a banner (the full width banner) in [prod](https://va.gov/) right now on the home page and it's not using the USWDS version of the component (it has a uswds prop set to false).

<img width="1438" alt="Screenshot 2024-08-09 at 1 27 59 PM" src="https://github.com/user-attachments/assets/7d9f651e-a727-45d6-8672-5de1454a1105">

Jill A checked the existing V3 epics and noted that we don't have the full width banner addressed in either.

### User story

**AS A** PO/PM for Public Websites products
**I WANT** to implement available V1 or V3 components in features & products currently under Public Websites management where components aren't currently being used
**SO THAT** all PW products are in alignment with the current component version
**AND** Veterans and other users have a consistent experience throughout VA.gov tools and information

## Acceptance criteria
- [ ] Full width banner is using the V3 component
- [ ] Promo banners are also using the V3 component
- [ ] verify/review the E2E tests
- [ ] check desktop and mobile
- [ ] a11y review

**Comment by jilladams** [comment] 2024-08-09 19:02
Since I couldn't find an older ticket where we addressed Promo Banners either (which show up above the footer when there is one) I added that to the ACs here as well. Can decide in refinement if that makes sense or should actually be a separate ticket.

**Comment by jilladams** [comment] 2024-08-09 20:57
Jami noted: 
> Just a head's up that I'm digging into this a little more because it seems like it might actually be the va-banner web component internals that are adding the uswds flag to its child component. If that's the case, your team won't be able to change that (and I apologize for any false alarm!) but I'm looking into it with our team in our [deprecation PR](https://github.com/department-of-veterans-affairs/component-library/pull/1268).

**Comment by randimays** [comment] 2024-08-12 14:05
I checked all instances of `uswds` in our code in content-build and none of them are set to `"false"`. Laura confirmed that the `uswds="false"` is also showing up in DST's Storybook, indicating that the web component code is the root cause somehow. Screenshot below is from Storybook:

<img width="285" alt="Screenshot 2024-08-12 at 9 03 51 AM" src="https://github.com/user-attachments/assets/3d57cc46-2dab-4ac9-812e-8b7ca73c727d">

Closing this as a no-op since we'll pick up any fix from DST's updates. We can always reopen if we find that is not the case.

**Closed by randimays** 2024-08-12 14:05 UTC
Labels: VA.gov frontend, Public Websites, sitewide, V3 Components
