### ISSUE TITLE
Investigate google map destination link issue.

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#11496] opened 2022-11-07 21:19 UTC
## Description
There is at least one issue with google maps not leading to the right direction.
There are two links to google maps on a Vet Center Page.  One is a link, and one is a link on a map image
![image](https://user-images.githubusercontent.com/5752113/200417637-ef87e84c-3edb-4dcf-a950-7cf44b386a12.png)

1. The text link uses **only the first line** and seems to **missing the state** from the address field -[template](https://github.com/department-of-veterans-affairs/content-build/blob/d75175c1fa4846d00129297ed5695b4420762876/src/site/includes/vet_centers/address_phone_image.liquid#L40)-
   -Link 1 works as it should https://maps.google.com/?saddr=Current+Location&daddr=1821%2022nd%20Street,%20West%20Des%20Moines,%2050266 results in "1821 22nd St, West Des Moines, IA 50266"
2. The image link comes from mapbox and is rendered using [this template](https://github.com/department-of-veterans-affairs/content-build/blob/f7bafff44f67aea4cffa94ee343d31bbd8784231/src/site/includes/image_and_static_map.liquid#L11)
   - The link from mapbox has both the line 1 and line 2 of the address so "Suite 115" is included.
   - The presence of the suite seems to result in the address being "redirected" to a different zip code. 
   https://maps.google.com/?saddr=Current+Location&daddr=1821%2022nd%20Street,%20Suite%20115,%20West%20Des%20Moines,%20IA%2050266 results in "1821 S 22nd St # 115, West Des Moines, IA 50061" which is wrong.

- Node [Des Moines Vet Center](https://prod.cms.va.gov/des-moines-vet-center)
- Web: [Des Moines Vet Center](https://www.va.gov/des-moines-vet-center/)
- CMS support ticket https://va-gov.atlassian.net/browse/VAHELP-5039

## Acceptance Criteria
- [ ] Solution for the fix is determined
- [ ] Issue for the fix is created

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by swirtSJW** [comment] 2022-11-07 21:53
A bit of testing shows that the suite is the problematic element.  Doing a google search for "1821 22nd Street, Suite 115, West Des Moines, IA 50266" 
![image](https://user-images.githubusercontent.com/5752113/200423050-fab41def-6792-4ed9-92b8-91d4c0d153cb.png)


While a search for "1821 22nd Street, West Des Moines, IA 50266"
Gets you to the right spot
![image](https://user-images.githubusercontent.com/5752113/200423275-b6771f83-dbae-4134-bb3e-beca57612f00.png)

**Comment by swirtSJW** [comment] 2022-11-08 16:00
Now in this particular case, the error is caused by the suite 115 entry from address line 2.  However, I think it is likely that in other cases the link may end up wrong because line 2 is NOT included.  Though it would be interesting to see if we can find other cases where there is data in line 2 and that we end up with either a pass or a fail on the map link

**Comment by stefaniefgray** [comment] 2022-11-19 05:36
"So a follow up from this morning discussion during the call for Outreach staff in District 3.  

Today I checked the created website pages through CMS for VC 405 and the directions lead to a still incorrect location, directing people that use that link on the page to travel to a South 22nd Street in West Des Moines.  

So now the map displays correct city but wrong part of the city.  

This is also an issue on the current location page the VA website has posted. There should not be a S or E in the street address. So maps page is back to identifying the previous incorrect address for our location using the map link.  

The map link written with text works fine. 

Correct address is 1821 22nd Street, Suite 115, West Des Moines, IA 50266.  

Our concern is when we have new Veterans seeking our location and having an expectation that the programmed technology works.  "

**Comment by stefaniefgray** [comment] 2022-12-07 19:36
@swirtSJW @dsinla Troy and I discussed this issue today -- here's what we want to find out. Please let us know if this is appropriate, thanks!

### Questions:
**1. Is Lighthouse storing the Des Moines Vet Center's location as a plain-text street address that is being geocoded by Google Maps, or as lat/long points?**

We would like to reach out to Lighthouse (as well as VAST, if any locational data is stored within it) to be able to view how the location of this facility is stored on their end.

(I have a background in GIS and strongly suspect that the street address is being stored improperly in Lighthouse and/or VAST and that Google Maps is geocoding it incorrectly as a result).

Since the "correct" address lacks the suite number and state, this issue seems related to these factors. 

The suite number (especially if it's added as a pound sign, etc.) or lack of state (Iowa), might be affecting how Google Maps geocodes the address and determines the correct latitude and longitude points.

Latest Jira ticket: https://va-gov.atlassian.net/browse/VAHELP-5085

**2. What is the best way for the VA Drupal CMS Helpdesk to communicate with the Lighthouse team in the future about similar issues?**

Should we be emailing them at api@va.gov or reach out through alternate means to speak with someone directly?

**Comment by swirtSJW** [comment] 2022-12-21 19:13
This is not really a lighthouse issue or a VAST issue.  It is a google maps issue.  We are building the map and the link on the front end from the same data, the address that is in the CMS.  

**1821 22nd St, West Des Moines, IA 50266** - ends up in the right spot
**1821 22nd St,  Suite #115, West Des Moines, IA 50266**  does not and even bumps you to a new zip code  
![image](https://user-images.githubusercontent.com/5752113/208984970-f771da46-a9e7-42e0-acb7-2bad979b5814.png)

**Comment by swirtSJW** [comment] 2022-12-21 19:26
The facility api that uses lat lon directly is correct 
![image](https://user-images.githubusercontent.com/5752113/208987094-f8a91c9d-6cb8-4e44-9fd8-fd1cb3fef258.png)
This is not a VAST / Facility API problem.

**Comment by stefaniefgray** [comment] 2022-12-21 19:46
Could be disconnect between Mapbox + Google Maps

**Comment by swirtSJW** [comment] 2022-12-21 21:59
@stefaniefgray and I looked into this  quite extensively and ruled out that this is NOT

- facility API / vast data issue
- CMS data issue
- Not a va.gov FE issue

This is a one-off abnormality in Google maps that for one specific suite number redirects 

-  [1821 22nd St, Suite 115, West Des Moines, IA 50266](https://maps.google.com/?saddr=Current+Location&daddr=1821%2022nd%20Street,%20Suite%20115,%20West%20Des%20Moines,%20IA%2050266) REDIRECTS TO 1821 E 22nd St #115, Des Moines, IA 50317  (completely different town and zip code

Yet a search that differs by only one suite number do not redirect and work just fine.
- [1821 22nd St, Suite 114, West Des Moines, IA 50266](https://maps.google.com/?saddr=Current+Location&daddr=1821%2022nd%20Street,%20Suite%20114,%20West%20Des%20Moines,%20IA%2050266) 
- [1821 22nd St, Suite 116, West Des Moines, IA 50266](https://maps.google.com/?saddr=Current+Location&daddr=1821%2022nd%20Street,%20Suite%20116,%20West%20Des%20Moines,%20IA%2050266)

**Comment by stefaniefgray** [comment] 2022-12-22 01:49
Have started quest to get in contact with the Google Maps team -- will try calling during business hours tomorrow

**Comment by swirtSJW** [comment] 2022-12-22 16:10
Thanks @stefaniefgray.  Do you want me to leave this ticket open for tracking google contact or should I close this as done on the dev part?

**Comment by swirtSJW** [comment] 2022-12-22 17:02
@stefaniefgray Most likely to get this looked into, somebody that has access to the phone number on the google map listing will have to claim that business.   Then they can initiate changes.
![image](https://user-images.githubusercontent.com/5752113/209187650-f8dbf1b6-ab92-4659-a2de-9ea20781292e.png)

They have to be able to answer that phone because that is the one that googlebot will call when they try to claim that business.

**Comment by stefaniefgray** [comment] 2023-02-17 02:17
Emailed folks at Google who were recommended as contacts by Dave C; location briefly changed on the "bad" link to another random cornfield (this time, on the _southwest_ side of the greater Des Moines area)

Asked them to fix this -- now the "bad" Google Maps link goes back to the original incorrect location

Need to reach back out once more, and will ask editor to perform steps listed above for claiming location on Google Maps

**Comment by stefaniefgray** [comment] 2023-03-13 20:59
Issue is confirmed as having been fixed on the Des Moines Vet Center homepage by the editor who originally reported it

@swirtSJW Can this ticket be closed?

**Closed** 2023-03-20 20:10 UTC
Labels: Defect, VA.gov frontend, Facilities, Vet Center
