### ISSUE TITLE
Update tugboat host to use version 20 of Docker 

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-cms#6223] opened 2021-08-24 15:53 UTC
## Description

Follow up from #6216.

## Acceptance Criteria
- [ ] Testable_Outcome_X
- [ ] Testable_Outcome_Y
- [ ] Testable_Outcome_Z
- [ ] Requires design review

**Comment by ndouglas** [comment] 2022-01-19 12:26
Confirmed this morning that this is still a thing:

```
sh-4.2$ docker version
Client:
 Version:           19.03.13-ce
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46
 Built:             Mon Nov  2 19:22:46 2020
 OS/Arch:           linux/amd64
 Experimental:      false
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.40/version: dial unix /var/run/docker.sock: connect: permission denied
```

**Comment by cweagans** [comment] 2022-01-19 21:23
Closing in favor of https://github.com/department-of-veterans-affairs/va.gov-cms/issues/7667 since there is some other discussion/info there.

**Closed by cweagans** 2022-01-19 21:23 UTC
Labels: DevOps, Needs refining, Platform CMS Team, tugboat
