### ISSUE TITLE
[Discharge Upgrade Wizard] (#7) FE: Review Answers Page

### ISSUE THREAD

**Issue by chriskim2311** [department-of-veterans-affairs/va.gov-cms#16916] opened 2024-01-18 23:29 UTC
## Description
Ticket 7

### User story

**AS A** Veteran
**I WANT** to be see Review my answers before submitting to see my results
**SO THAT** I make sure I did not make any mistakes in my answers.

## Engineering notes:

- Add Review Answers page
- Create route for that
- Display conditions ("decision tree") for this question
- review the existing content for typos
- Add edit links for each answered question
- allow deep dive to that question (under certain conditions)
- regression: can't deep dive to question normally
- Redux store for answer storage
- Form error handling
- Testing: Cypress tests
- Testing: Unit tests (for display conditions logic)

## Acceptance criteria
- [ ] Converted to subtask pattern (one question per page; in this case, review your answers)
- [ ] Content changes made
- [ ] A11y review
- [ ] Design review

### Existing Text

Review Your Answers
 
If any information below is incorrect, update your answers to get the most accurate information regarding your discharge situation. 

### Updated Text (not all text is updated; but I included all text to reduce confusion):

Review your answers
 
If any information here is wrong, you can change your answers now. This will help us give you the most accurate instructions.

**Comment by chriskim2311** [comment] 2024-05-01 00:52
This is still in progress with changes coming from the PR review.

**Comment by randimays** [comment] 2024-05-01 21:50
@FranECross @laflannery @thejordanwood Based on this Slack thread: https://dsva.slack.com/archives/C52CL1PKQ/p1714598022469959?thread_ts=1714591633.627719&cid=C52CL1PKQ updating the ACs here for only adding the Edit links on the Review page, but they won't have any functionality yet. In a future ticket, we will consider how we want to handle edits for a dynamic flow (maybe dipping into Jeana's team's research/work).

**Comment by randimays** [comment] 2024-05-06 16:42
Updates from scrum (tacking onto the post above): we will need UX research on how to handle edits because in most cases, the flow after the edited question will change. Our existing paradigms for editing form flows are currently being researched by at least Jeana's team, so we may be part of the effort to finalize an approach.

From an accessibility perspective: @laflannery pointed out that the Edit links are not up to standard. We decided to address this after the UX research is complete.

@FranECross confirmed we don't have a hard deadline, and it probably makes sense to pick up the UX research portion at the end of May or beginning of June when Chris returns and DUW work resumes.

**Comment by randimays** [comment] 2024-05-07 14:59
Verified successfully in staging. Closing!

**Closed by randimays** 2024-05-07 14:59 UTC
Labels: VA.gov frontend, Public Websites, Discharge wizard
