### ISSUE TITLE
Addresses in rich text fields

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#1966] opened 2020-06-04 20:21 UTC
As an editor, i want to add an address with structured content to my rich text field.

**Comment by swirtSJW** [comment] 2023-01-18 22:11
I am not sure who is asking for this feature.   Would likely be a plugin for ckeditor.

**Comment by EWashb** [comment] 2023-01-19 00:06
Agreed @swirtSJW. I'm going to add CKEditor 5 as a blocker to this. I don't know where this ask is coming from either, and I have not heard this myself.

**Comment by laflannery** [comment] 2023-04-07 14:19
Closing as this looks like a duplicate of #3950

**Closed by laflannery** 2023-04-07 14:19 UTC
Labels: Drupal engineering, Content forms, Content model, Needs refining, UX writing, CMS Team
