### ISSUE TITLE
"Abbreviation" button is now in WYSIWYG

### ISSUE THREAD

**Issue by omahane** [department-of-veterans-affairs/va.gov-cms#14539] opened 2023-07-26 18:41 UTC
## Describe the defect
There's an "Abbreviation" button in the WYSIWYG toolbar.

## To Reproduce
1. Add an event: /node/add/event
2. Scroll down to **Full event description**
3. Validate that the "Abbreviation" button is present

## AC / Expected behavior
No "Abbreviation" button is showing.

## Screenshots
![Screenshot 2023-07-26 at 1 31 26 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/766573/db13b1c4-017f-4d15-b1ec-9588703bff64)

 ## Additional context
It's possible this is an intentional addition, and I missed that fact. But if not, well, can we excise it?

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS workstream (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [x] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`
- [ ] `Accelerated Publishing`

**Comment by laflannery** [comment] 2023-07-28 12:56
This is a purposeful addition - we have/are notifying VHA and Vet Center stakeholders about this change and have the change management documentation regarding why this was done [here](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/cms/product-outlines/ckeditor)

We also have updated the [KB article](https://prod.cms.va.gov/node/34036/latest) regarding the CKEditor and it's functions in prep for these changes and it will be published once D10 launches

**Comment by laflannery** [comment] 2023-07-28 14:07
We would want what you have in 1 - so that folks have a way to get the full name of the acronym if they need to remember.

**Comment by jilladams** [comment] 2023-09-29 22:23
@laflannery sounds like this could be closed as no-op / intended behavior?

**Comment by laflannery** [comment] 2023-10-02 11:36
Yep

**Closed by laflannery** 2023-10-02 11:36 UTC
Labels: Defect, Needs refining, Public Websites
