### ISSUE TITLE
Content audit: VCL phone number in built site

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#9699] opened 2022-07-05 20:37 UTC
## Description

Find everywhere that the Veteran Crisis Line phone number appears, so that we can update it everywhere in a future sprint. Document URL as well as what type of change it would be (eg, hard-coded).

Note: related to CMS-based audit for VCL number: #9696

## Acceptance Criteria
- [ ] document appearances of VCL number

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by jilladams** [comment] 2022-07-05 20:44
We think there's overlap if we search generated pages and will find the same CMS references Lynn found. Goal is to find hard-coded references.

**Comment by jilladams** [comment] 2022-07-06 23:07
@allisonlu note that we forgot to set sprint goals in sprint planning. Dave confirmed in Slack after the fact that this should be one. Updated on ticket.

**Comment by allisonlu** [comment] 2022-07-07 20:10
## vets-website (5 instances)

## Telephone component:

I couldn't find this component on the actual website, so I'm thinking it might be in an authenticated questionnaire page. 
- Link to file: https://github.com/department-of-veterans-affairs/vets-website/blob/0d38b0e6edd941d0ae691d8ad77503adf6c251fd/src/applications/health-care-questionnaire/shared/components/footer/NeedHelpSmall.jsx

### Links:

Virtual Agent page: see h2 **Before you start** > expand "How to get help if you're in crisis...", there is a link to the VCL number
- Link to file: https://github.com/department-of-veterans-affairs/vets-website/blob/021dd082c86301c17e099c790ba21be9b89d1ea5/src/applications/virtual-agent/components/page/Disclaimer.jsx

Footer: see most-right column **In crisis? Talk to someone now**, there is a link to the Veterans Crisis Line modal. 
- Link to file: https://github.com/department-of-veterans-affairs/vets-website/blob/0d38b0e6edd941d0ae691d8ad77503adf6c251fd/src/platform/site-wide/va-footer/components/CrisisPanel.jsx

VA Secure Messaging page: see h2 "**Can I use secure messaging for medical emergencies or urgent needs?**", there is a link to the VCL number.
- Link to page for non-Cerner users: https://github.com/department-of-veterans-affairs/vets-website/blob/0d38b0e6edd941d0ae691d8ad77503adf6c251fd/src/applications/static-pages/health-care-manage-benefits/secure-messaging-page/components/UnauthContent/index.js
- Link to file for Cerner users: https://github.com/department-of-veterans-affairs/vets-website/blob/0d38b0e6edd941d0ae691d8ad77503adf6c251fd/src/applications/static-pages/health-care-manage-benefits/secure-messaging-page/components/AuthContent/index.js


## content-build (1 instance)

This doesn't appear on any public page. It seems like this file is used for end-to-end testing for Vet Centers.
- Link to file: https://github.com/department-of-veterans-affairs/content-build/blob/f7bafff44f67aea4cffa94ee343d31bbd8784231/src/site/layouts/tests/vet_center/template/fixtures/vet_center_data.json

**Comment by jilladams** [comment] 2022-07-08 21:11
I'm wondering if/why we need Dave's review? We can log these for the update when 988 is real / make an implementation ticket for the changes in this 988 epic. Do we have uncertainty around whether this is good info or not? 

My vote would be: if @allisonlu is high confidence, we could go ahead and close.

**Comment by wesrowe** [comment] 2022-07-08 21:42
I could have phrased it differently – we can close with an FYI to Dave 
in case he wants to review.

**Comment by kevwalsh** [comment] 2022-07-11 15:27
For y'alls awareness: Facilities team is working on a script (#9714) to update all the CMS database. We _hope_ to have this ready on July 18th to run post deploy, but AFAIK there's no reason to coordinate timing on changes in CMS, vs changes in hard-coded instances, since both phone numbers will work indefinitely.

**Comment by wesrowe** [comment] 2022-07-11 15:42
> to run post deploy

@kevwalsh, can you clarify what "deploy" means – is July 18th the go-live date for the new phone number? It's our understanding that the old phone number will work for a little while; we don't have an issue yet for implementing our cutover... Sounds like some coordination/context setting would be a good idea.

**Comment by jilladams** [comment] 2022-07-11 16:23
And in either case: I think this ticket is now closeable?

**Comment by kevwalsh** [comment] 2022-07-12 18:20
> Sounds like some coordination/context setting would be a good idea.

@wesrowe i don't think we need close coordination on timing here.  

On the CMS content side of things, our original ACs specifically mentioned that we didn't need to coordinate timing across instances in the CMS-managed content. We were considering getting folks in the field to make these changes one by one. We've moved to a single script approach to updating CMS managed instances, but it doesn't need to be timed with the changes to hard-coded instances. 

> And in either case: I think this ticket is now closeable? 

Not sure if that's a question for me, but my gut says yes.

**Comment by jilladams** [comment] 2022-07-15 15:33
@davidconlon confirmed in Slack DM today with me/Wes that we should do our updates to the findings here in Sprint 63. Closing this as complete, and stubbed a new ticket we need to flesh out: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9797

**Closed by jilladams** 2022-07-15 15:33 UTC
Labels: VA.gov frontend, Needs refining, ⭐️ Public Websites
