### ISSUE TITLE
VA facilities can be saved as Event locations, but disappear from the "Where:" field on the live site.

### ISSUE THREAD

**Issue by stefaniefgray** [department-of-veterans-affairs/va.gov-cms#9647] opened 2022-06-30 01:28 UTC
## Describe the defect
As a VAMC Editor, I would like to add an Event to my site that is hosted at a VAMC facility. (Real life example: VA Bedford is hosting an Event at the Haverhill VA Clinic.)

When adding the Event location after selecting "At a VA Facility," I am able to choose a VAMC location such as the Haverhill VA Clinic and can save it to the Event.

However, once the Event page is published to the live site, the facility name vanishes from the "Where:" field. This appears to be a front-end defect.

## To Reproduce

1. While adding or editing a VAMC Event page, select **Location type = At a VA facility**
Link: https://prod.cms.va.gov/node/add/event

2. Within the “Facility Location” field, type the name of a VAMC facility and select it from the dropdown menu that follows.

3. Publish the page to the live site. The "Where:" field is left blank on the live version of the Event page.

## AC / Expected behavior
I expect to see the saved Event location listed in the "Where:" field on published Event pages.

## Screenshots
![Screen Shot 2022-06-29 at 7 23 03 PM](https://user-images.githubusercontent.com/9059428/176572705-cfe1b51f-c011-47a3-a093-8b496001b0c2.png)

![Screen Shot 2022-06-29 at 7 01 00 PM](https://user-images.githubusercontent.com/9059428/176572722-3feacc92-e01d-42bc-a88a-d9b438822bf2.png)

![Screen Shot 2022-06-29 at 7 01 15 PM](https://user-images.githubusercontent.com/9059428/176573228-99df7c55-4d29-4d43-a43c-486b376c16c1.png)

 ## Additional context
See related Event location issue: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9483

Original Jira ticket: https://va-gov.atlassian.net/browse/VAHELP-4383

## Live examples where this is happening across multiple VAMCs:
- **VA Bedford:** 
     - https://prod.cms.va.gov/bedford-health-care/events/47391
     - https://www.va.gov/bedford-health-care/events/47391/
     
- **VA Loma Linda:** 
     - https://prod.cms.va.gov/loma-linda-health-care/events/47421
     - https://www.va.gov/loma-linda-health-care/events/47421/
     
- **VA Tuscaloosa:** 
     - https://prod.cms.va.gov/tuscaloosa-health-care/events/47418
     - https://www.va.gov/tuscaloosa-health-care/events/47418/

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS workstream (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by kevwalsh** [comment] 2022-06-30 04:26
i think this is a dupe of #9442

**Closed** 2022-06-30 17:16 UTC
Labels: Defect, invalid-duplicate, ⭐️ Facilities, Needs refining
