### ISSUE TITLE
[POC] Evaluate maintaining current BRD on Amazon Linux 2

### ISSUE THREAD

**Issue by jkalexander7** [department-of-veterans-affairs/va.gov-cms#7013] opened 2021-11-19 21:30 UTC
## User Story or Problem Statement

As a CMS engineer, I want to explore the technical feasibility of maintaining the existing BRD system on Amazon Linux 2, so that we can evaluate adopting this solution for the Drupal CMS.

## Acceptance Criteria

- [x] Confirm a test instance of the tool is up and running
- [x] Get a test instance of the CMS up on the tool
- [x] Evaluate the tool against the decision criteria with details on why the scores were set
- [x] Document findings within ticket 

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [x] `Platform CMS Team`
- [ ] `Sitewide CMS Team`

**Comment by ElijahLynn** [comment] 2021-12-06 17:06
Note: we may need to get the base image updated too as I thought that was where the internal certs were applied.

**Comment by olivereri** [comment] 2021-12-15 18:23
# Document Findings WIP

## Overall Finding
It was possible to modify the current BRD Platform, Build portion to use AL2 as well as modify for use for Drupal.  This work built on top of previous work to incorporate AL2.  Deployment portion also needed some modifications. Within in a sprint it was possible to demonstrate that Drupal can be built and deployed on AL2. 

* Work was previously done by Platform OPs to modify Build process to use Amazon Linux 2.
  * CIS Benchmark configured AL2 AMI no longer exists.
  * CIS Offers an official hardened AL2 AMI for use.
  * Vanilla AL2 works as well.

**Comment by indytechcook** [comment] 2021-12-17 15:12
We had a call about this and here is the outcome:

> We seemed to reach a consensus (no objections) to moving forward with upgrading the existing BRD to use Amazon Linux 2 and pause on further POC and research of new systems. This includes pausing the migration to Argo + GHA at this time. We estimate the remaining lift to be 2 engineers working for another 2-3 sprints to upgrade BRD to AL2. We understand this comes with the responsibility of eventually maintaining Jenkins after Operations has migrated other projects off of it to Argo, and we want to accept that responsibility.
This will solve our current security need to upgrade from PHP 7.3 to 7.4 and allow us to easily go to PHP 8 as well. Then we can enable the horizontal scaling across availability zones for greater stability. This should handle the needs of CMS for the forseeable future without needing to migrate to new tooling, which could take a considerable amount of time to achieve feature parity. We discussed incrementally moving to using containers with the support that BRD already has for containers (1 container per instance).
Then we can free up all that developer migration time and focus on getting our tests running faster (parallelized), likely move Tugboat (Docker Swarm) onto BRD (work is already done but was paused due to sunsetting of Jenkins), getting logs into and migrating to DD GovCloud, and getting Blackfire on-prem up and running to prevent performance regressions from being merged (keep the CMS fast, and make it faster).
Please add anything you feel needs clarifying or was missed. 

**Needed Follow ups:**

- [ ] Decision document created and presented to PO
- [ ] Planning and Issue created in Github for implementation.

**Closed** 2021-12-17 20:25 UTC
Labels: DevOps, Platform CMS Team

**Comment by olivereri** [comment] 2022-01-03 17:16
https://techviewleo.com/install-php-7-on-amazon-linux/
