### ISSUE TITLE
PHP notice from tablefield contrib module

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#1564] opened 2020-04-21 21:53 UTC
## Description

Address php notice coming from tablefield contrib module. Contribute patch back to DO

![image (18)](https://user-images.githubusercontent.com/16477724/79917668-25ea8800-83e8-11ea-9561-ce4587d3a389.png)

## Acceptance Criteria
* notice is gone, no regressions

**Comment by acrollet** [comment] 2020-11-03 18:20
I was not able to reproduce this issue. It looks like this was fixed in #2572, closing. I also updated the associated [d.o. issue](https://www.drupal.org/project/tablefield/issues/3163841).

**Closed by acrollet** 2020-11-03 18:20 UTC
Labels: Drupal engineering, Technical debt
