### ISSUE TITLE
Improve Editorial Experience for VAMCs 

### ISSUE THREAD

**Issue by kmariepat-cityfriends** [department-of-veterans-affairs/va.gov-cms#13962] opened 2023-06-01 15:52 UTC
- More action based rather than trying to navigate different content types 
- More specific titles for content types 
- How do we leverage the editorial interface to encourage good habits 
- Should we be considering a button `View your site's performance" / "View your analytics"
- How do you measure the outcomes you are trying to achieve and what are those outcomes

**Comment by jilladams** [comment] 2023-06-23 20:01
Closing as dupe of #5413

**Closed** 2024-10-25 23:04 UTC
Labels: VAMC, Drupal engineering, Epic, Facilities, CMS design, sitewide, jpa-1
