### ISSUE TITLE
[Events] FE Events templates not loading header/footer / all event data when VA Location > Location information is missing

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#17424] opened 2024-03-05 23:13 UTC
## Description
When the user opens the event for VA ECHCS Colorado Springs Walk-in Flu Shot Clinic on the websites  it does not display all of the information that has been entered in Drupal. It looks like the same error is happening to some other events as well, not all events. 

Reported by Support / VAMC editor: https://dsva.slack.com/archives/C52CL1PKQ/p1709679995868159

Event node: https://prod.cms.va.gov/eastern-colorado-health-care/events/66168/
FE Event page: https://www.va.gov/eastern-colorado-health-care/events/66168/

FE page is missing header, footer, event metadata after "When"/date info. 

### Other affected Event(s)
VA ECHCS Patient Tele-Town Hall- April - https://www.va.gov/eastern-colorado-health-care/events/65547
Event Node: https://prod.cms.va.gov/node/65547/edit

## Acceptance Criteria
- [ ] All event information entered in Drupal should display to users when they're viewing the event(s)
- [ ] Header and footer load on events pages
- [ ] Requires design review
- [ ] Requires accessibility review

**Comment by jilladams** [comment] 2024-03-05 23:26
Noting that on both the listed nodes, the Event says it's at a VA Location, but a location wasn't entered. Not clear yet if that's the problem, or needs to be a separate ticket. If that's not the root cause here once we know, will need to ticket it.

**Comment by chriskim2311** [comment] 2024-03-06 00:24
FE needs to update logic to account for the footerNav div not being present when trying to render the VAFooter content(vets-website). When this event in the CMS was created with bad data we most likely failed in the event.drupal.liquid template and did not render the footer.html(content-build) at the end of the template. 

When the startVAFooter function tried to populate the footer div that was not rendered we saw the undefined error on prod. 
![VA_Eastern_Colorado_Health_Care___VA_ECHCS_Colorado_Springs_Walk-In_Flu_Shot_Clinic___Veterans_Affairs](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/42885441/d843e40f-dbaa-4dfd-a866-a37753a4833a)

Main fix would be to not allow for the bad data to be released on prod. But we can account for the missing footer div in the startVAFooter function in vets-website.

**Comment by jilladams** [comment] 2024-03-07 19:36
Dave made the judgment call: Public Websites will work on fixing #17426, but will leave this issue for later. Moving to "transfer to other teams" pipeline, assuming that will end up with IIR.

**Comment by randimays** [comment] 2024-04-30 16:50
If we make it to vets-website code with a broken content-build template (due to missing Drupal data), the problem exists in content-build and/or Drupal. Most likely, we don't need to make changes in vets-website.

We have a ton of null checks in the events template (CB), but it's hard to tell where the events template broke exactly because the original issue is fixed and I'm not sure we can reproduce it (@dsasser?). Because the events template broke part of the way through executing the code, it skipped over the bottom of the template where the footer is inserted. But the show must go on: vets-website code started executing and tripped when the footer div was missing.

In my opinion, we should carefully consider where we implement error handling / fallbacks. For instance, if we're missing Drupal data that breaks the header or footer, we can't simply prevent those from rendering as a fail-safe as this is not an acceptable Veteran experience. We need to fix the problem where it originates (as code to the offending code as possible).

I could be missing some nuance in this ticket about expectations and requirements, but it doesn't seem to me like there is any front end action to be taken here.

**Comment by FranECross** [comment] 2024-06-04 18:20
Closing per Randi's comment above.

**Closed by FranECross** 2024-06-04 18:20 UTC
Labels: Defect, VA.gov frontend, Needs refining, Public Websites, Events

**Comment by jilladams** [comment] 2024-06-04 18:28
Noting: Drupal work was done to prevent us from being able to end up in this state again, under https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17426. 

However, that Drupal change won't work until the CMS Team is able to resolve https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17896

So: this might happen again in the meantime. The fix is to have the Editor add the missing Location data.
