### ISSUE TITLE
CMS-driven Footer Megamenu: Create/Populate Footer Menu

### ISSUE THREAD

**Issue by chri5tia** [department-of-veterans-affairs/va.gov-cms#11438] opened 2022-11-03 13:41 UTC
## Description
- Populate existing footer menu in CMS: `footer`
https://va-gov-cms.ddev.site/admin/structure/menu/manage/footer
- Use links and structure as they already exist on va.gov. The code for the URLs and hierarchy is in `content-build/src/platform/static-data/{} footer-links.json`
  - Do _not_ include Language Assistance section
  - Do not include Col 4 of top section (Contact Us plus VCL)

[Mural](https://app.mural.co/invitation/mural/vagov6717/1668126089949?sender=u907f83e01e35bb04de6f8139&key=dd1afd5d-3cd7-4d0c-9aff-26e3308b2ec3) with analysis of the differences between Desktop and Mobile

## Language assistance links
This is powered by a React component, so will not be included in initial drupalizing. Ticketed for separate consideration later: #11492 
 
## Acceptance Criteria
- [ ] Initial categories: Section 1, ~Section 2: Language Assist,~ Section 3 (see screenshot and note)
- [ ] Section 1 Links 
  - [ ] _**Note: Do not include Column 4 (Contact Us plus VCL) in this ticket**_ 
  - [ ] Hierarchy – Each column of links is under a parent link, and links are sub-menu under that
  - [ ] Parent link's link text is the header/title of the column (eg "Veteran programs and services" for Col 1), with no link/href
- [ ] Requires design review

![Screen Shot 2022-11-03 at 6.38.13 AM.png](https://images.zenhubusercontent.com/62a38e72cce4cadccd3c8d3f/7bd8ba7e-63cb-45d6-a450-2882015e5598)
Note: Label "Section" is not official/subject to change after design review

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by chri5tia** [comment] 2022-11-08 03:08
@jilladams @wesrowe Something I didn't think about. Typically menu links are part of content, so these links should be added on prod and not in a code config. I want to confirm that the expectation here is that: 
- [x] the footer is available on prod 
- [ ] the footer links are added on prod

**Comment by chri5tia** [comment] 2022-11-08 16:33
Code changes that the new cypress test applies to:
https://github.com/department-of-veterans-affairs/va.gov-cms/pull/10574/files

**Comment by jilladams** [comment] 2022-11-08 18:04
Confirming: menu links should go in on Prod. We need to first confirm (per scrum discussion) that the existing Footer menu isn't exposed in any front-end code. We don't want new links showing up on prod front-end where they're not expected.

**Comment by jilladams** [comment] 2022-11-08 18:58
Updated body to add notes that Language selector links don't need to go into this menu.

**Comment by chri5tia** [comment] 2022-11-10 00:31
https://github.com/department-of-veterans-affairs/content-build/blob/main/src/platform/static-data/footer-links.json

**Comment by wesrowe** [comment] 2022-11-10 00:59
Link to [DSVA slack thread](https://dsva.slack.com/archives/C52CL1PKQ/p1668035722276659) where we discuss some enhancements that may be necessary to the Drupal data model. Changes depend on the FE architecture design.

Things the FE probably needs to know, based on json file in comment above:
- column
- href
- title
- order - should be captured by drupal's `weight`
- target ("" or "_blank")
- rel (eg noopener, noreferrer)

Additional things the FE _may_ need to know:
- additional classes – e.g., VCL is a `<button>`  with added classes
- data-show - eg VCL also has this
- aria-label - eg TTY: 711 
- `label` - the json file uses this for items that (I think) are the first item in Column 4 under a sub-header. So the `label` string is used as a sub-header above the link specced in that particular json object. E.g., "Call us" is the `label` for the 800-number link.

**Comment by wesrowe** [comment] 2022-11-10 23:22
Notes:
- Adjust ACs to 3 col + rail
- 
- Talk to content designer (Pickett) about Col 4, aria-labels
  - Col headers: Parent-level links will not have links/hrefs
  - Order of 3 cols will be determined by order in drupal
- Inform Pickett about 3-menu approach
- Document rationale in this ticket
  - Col 4 may need extra attributes in 
- Be cognizant of:
  - Injection
  - Mobile differences (drupal doesn't need to know)

Injection complications:
- Injection currently relies on 2 pieces:
  - json file – a single file for both header and footer is created (very simply) during content build
  - react component – since the column 1-3 headers are hard-coded in the existing react component, moving to drupal will require some modification of the react component that gets injected
- Options
  - 1 – use drupal to reconstruct the exact same footer-json file during content build, thus preserving injection architecture
  - 2 – do something with drupal that may be better for modernized VAgov but may also have more impact on injection architecture (ie, changing number of files, file names, etc)

**Comment by jilladams** [comment] 2022-11-14 22:40
@wesrowe @ryguyk @chri5tia we need to make sure #11482 keeps up with outcomes here so if someone like Bryan or Josh implement, they have everything they need in one place. I took a pass today, based on our last convo, but we should plan to go through it in refinement when this ticket is done just to confirm it lines up with where we land here.

**Comment by chri5tia** [comment] 2022-11-15 17:04
Footer done, primarily. I need to comb over and double-check everything. The Footer Rail will be done today.
https://prod.cms.va.gov/admin/structure/menu/manage/footer

**Comment by laflannery** [comment] 2022-11-17 16:21
@wesrowe @jilladams I think I may have found a bug with this footer:

On the Drupal CMS login page, in the footer, I am now seeing this:
![image](https://user-images.githubusercontent.com/106678594/202499754-d3b9c504-bf04-4f5d-a5ab-b38db562f6dc.png)
Whereas before I used to have actual footer links (I know one of them was VA Design system because there is an old screenshot [in this ticket](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9915))

I looked in the CMS UI and found the [Footer menu here](https://prod.cms.va.gov/admin/structure/menu/manage/footer) and noticed that there are links set as Old/Disabled, however those are the correct links that should be showing on the Login page.  The new text that is showing is the top level column text.  Could someone take a look at this?

**Comment by chri5tia** [comment] 2022-11-17 16:41
@laflannery Thanks for catching this! Fixed.
Now we know what the `footer` menu is being used for and that it is, in fact, being used somewhere.

**Comment by chri5tia** [comment] 2022-11-17 16:48
Team, I am thinking we should create a new footer for the CMS log in page, called `footer_cms`. And then userp the `footer` for the purpose we planned. (In lieu of creating a new footer with a more confusing machine name.)

**Comment by jilladams** [comment] 2022-11-17 18:05
That seems reasonable to me, and please make sure the menu "Description" gets updated for both, to make sure it's clear what the menus are doing, and in which context they appear in the front end. 

e.g. 
Footer = VA.gov footer, columns 1-3
Footer Bottom Rail = VA.gov footer, bottom-most menu below VA logo
footer_cms = CMS footer menu, appears on CMS login page

**Comment by chri5tia** [comment] 2022-11-18 23:15
Done.

https://prod.cms.va.gov/admin/structure/menu/manage/footer
https://prod.cms.va.gov/admin/structure/menu/manage/va-gov-footer
https://prod.cms.va.gov/admin/structure/menu/manage/footer-bottom-rail

**Comment by jilladams** [comment] 2022-11-18 23:38
@chri5tia I fixed up some ordering in the menus where they didn't match what's live in the va.gov front-end today. Otherwise looks good with just a couple notes for cleanup: 

1. https://prod.cms.va.gov/admin/structure/menu/item/11539/edit?destination=/admin/structure/menu/manage/va-gov-footer --  we need to confirm that entering the path this way will work correctly when passed through to the front-end. The relative path could be problematic when the header is injected into sites that don't have va.gov as domain. Probably best to just update to add the full domain, unless you had reasons not to?

2. https://prod.cms.va.gov/admin/structure/menu/manage/va-gov-footer includes column 4, which we excluded from scope in the ACs. Pls delete those.

3. https://prod.cms.va.gov/admin/structure/menu/manage/footer - need to delete the disabled links here as cleanup.

**Comment by chri5tia** [comment] 2022-11-19 00:39
Thanks Jill! I meant to go back and address those.

**Comment by chri5tia** [comment] 2022-11-21 16:30
Reopening this ticket. Creating the new menu and populating it with links without pushing the config to prod first has caused issues. I removed the menu and will recreate once the PR merges.

**Comment by chri5tia** [comment] 2022-11-24 00:18
This is done.
https://prod.cms.va.gov/admin/structure/menu/manage/va-gov-footer

**Comment by chri5tia** [comment] 2022-11-24 00:19
@jilladams in lieu of a code push, let me know if this is good to close.

**Comment by jilladams** [comment] 2022-11-28 21:35
Looks good, only question from me is re: relative / node links. Not sure if entry like this pointing to the node will work out to point to the correct URLs per environment (show Staging links on Staging, etc)? Can we tell via GraphQL what URL will get sent through to the front-end? I'm guessing it builds the URL at build time based on the env?  These 4 are set up this way:

* https://prod.cms.va.gov/admin/structure/menu/item/11570/edit?destination=/admin/structure/menu/manage/va-gov-footer 
* https://prod.cms.va.gov/admin/structure/menu/item/11573/edit?destination=/admin/structure/menu/manage/va-gov-footer 
* https://prod.cms.va.gov/admin/structure/menu/item/11580/edit?destination=/admin/structure/menu/manage/va-gov-footer
* https://prod.cms.va.gov/admin/structure/menu/item/11581/edit?destination=/admin/structure/menu/manage/va-gov-footer

**Comment by jilladams** [comment] 2022-11-28 22:25
Confirmed with Christia: these should build HREFs relative to the build env, and we can confirm with front-end when they implement via #11482 . Closing.

**Closed by jilladams** 2022-11-28 22:25 UTC
Labels: Drupal engineering, Needs refining, ⭐️ Public Websites
