### ISSUE TITLE
Determine if there are any regressions based on incorrect info in KB article 

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#10493] opened 2022-08-29 13:28 UTC
## Background
potentially Edit "How to edit a VAMC System homepage" KB article
The [current article](https://prod.cms.va.gov/help/vamc/how-to-edit-a-vamc-system-homepage) could use some updates to clarify content

## Suggested Updates

- For Step 11, do all the editors know where to find the information they need for the GovDelivery fields or should we include this? Update the KB article to reflect this 
- Should the VA Health Connect and Records System be discussed even though the editor can’t change it? a regular editor can't change this 

## Acceptance Criteria
- [x] I expect the KB article is updated to reflect the necessary changes as discussed above in suggested updates
   - [x]  For Step 11, do all the editors know where to find the information they need for the GovDelivery fields or should we include this? Update the KB article to reflect this 
   - [ ] ~Should the VA Health Connect and Records System be discussed even though the editor can’t change it? a regular editor can't change this~  - THis inofrmation was not part of this article at the time I reviewed it.  It must have been removed prior.
- [x] Article is reviewed by Sitewide CMS
- [x] Article is reviewed by Helpdesk
- [x] Article posted to KB https://prod.cms.va.gov/help/vamc/how-to-edit-a-vamc-system-homepage

**Comment by kmariepat-cityfriends** [comment] 2023-03-23 17:18
Make a separate issue for this because the, need to make a new pattern because you can no longer get ids for vet center on facility locator 
- For Step 10, there is no mention of how to find the facility ID in order to add it into one of these fields.  In case this is not be obvious for all editors, it should perhaps be added here

**Comment by kmariepat-cityfriends** [comment] 2023-03-29 14:29
New and separate issue is here: https://app.zenhub.com/workspaces/sitewide-facilities-639f5253e4b702a32376339e/issues/gh/department-of-veterans-affairs/va.gov-cms/13108

**Comment by swirtSJW** [comment] 2023-04-04 20:19
Nobody is allowed to create new system pages.  Only admins 
![image](https://user-images.githubusercontent.com/5752113/229910951-74d8cbbc-e727-4b25-b17f-216ab3c80f77.png)

**Comment by kmariepat-cityfriends** [comment] 2023-04-06 15:45
@swirtSJW is your comment signaling that this card doesn't need to be done? or just a note to yourself?

I'm asking because I see you assigned it to yourself but its not in progress

**Comment by swirtSJW** [comment] 2023-04-10 15:38
@laflannery I made the mistake of publishing the first one, so had to follow suit with the others.
We can always revert if you object to what I added.

https://prod.cms.va.gov/node/15102/revisions/view/761031/762255/visual_inline

**Comment by swirtSJW** [comment] 2023-04-10 15:44
> @swirtSJW is your comment signaling that this card doesn't need to be done? or just a note to yourself?

@kmariepat-cityfriends 
It was mainly a note to myself.   There was concern in the earlier writing of this issue that there were regressions created by people following the directions for creating a system.   So this was to establish that  no editors other than true admins can create a system page.  Once it is created, they can only edit certain fields.   The article is now true as to only addressing fields that they can edit.

> I'm asking because I see you assigned it to yourself but its not in progress
Either a zenhub slipup  (it sometimes fail when I tell it to do two things like assign myself and change the pipeline),  OR  my own brain slippped a cog.  Sorry for the confusion.

**Comment by TroyA6** [comment] 2023-04-10 20:06
@swirtSJW @kmariepat-cityfriends @laflannery @stefaniefgray - Thank you Swirt -- this looks good - The only part I cannot confirm is the GovDelievery account piece... I don't have access to that - @stefaniefgray will you review as well? Thanks!

**Comment by stefaniefgray** [comment] 2023-04-11 16:14
@swirtSJW @kmariepat-cityfriends @jilladams Looks good! 👍

**Closed** 2023-04-11 22:03 UTC
Labels: Knowledge Base, Facilities
