### ISSUE TITLE
Code validation of upgrade to PHP 7.4

### ISSUE THREAD

**Issue by jkalexander7** [department-of-veterans-affairs/va.gov-cms#7582] opened 2022-01-13 15:52 UTC
## User Story or Problem Statement

PHP 7.3 will be end of life December 2021. Upgrade to PHP 7.4 is needed prior to making updates to BRD system with AL2.
Previous upgrade: (https://github.com/department-of-veterans-affairs/va.gov-cms/issues/1004)

## Acceptance Criteria

- [x] All modules are compatible with PHP 7.4
- [x] There are no new PHP notices when running CICD tests 
- [x] Upgrade tugboat, lando, and ddev to PHP 7.4

**Comment by jkalexander7** [comment] 2022-01-13 18:41
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VAgov-CMS-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/7582?planning-poker) with ZenHub @amponce @cweagans @ElijahLynn @indytechcook @ndouglas @olivereri @timcosgrove

**Comment by cweagans** [comment] 2022-01-13 18:49
https://www.php.net/manual/en/migration74.incompatible.php may be useful to you.

**Comment by indytechcook** [comment] 2022-01-13 19:00
Code Compatibility test: docker run --rm -v $(pwd):/app vfac/php7compatibility 7.4 -d memory_limit=1G

**Comment by indytechcook** [comment] 2022-01-13 19:02
Reading down the thread, https://github.com/department-of-veterans-affairs/va.gov-cms/issues/1004 was originally a 7.4 ticket and we did all the code combability checks and fixes then.  It shifted to 7.3 when we had issues with drush and devshop.

**Comment by indytechcook** [comment] 2022-01-13 19:04
PHPStan version check: https://phpstan.org/config-reference#phpversion

**Comment by cweagans** [comment] 2022-01-19 00:53
In the Tugboat config, there's a reference to #6216 which may prevent us from immediately upgrading Tugboat to PHP 7.4. @ElijahLynn do you know if we've upgraded our Tugboat Docker version from 19 to 20? I see #6223 is still open - I guess that was a followup?

**Comment by ndouglas** [comment] 2022-01-19 12:29
Confirmed that the host is still running Docker 19:

```
sh-4.2$ docker version
Client:
 Version:           19.03.13-ce
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46
 Built:             Mon Nov  2 19:22:46 2020
 OS/Arch:           linux/amd64
 Experimental:      false
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.40/version: dial unix /var/run/docker.sock: connect: permission denied
```

**Comment by ndouglas** [comment] 2022-01-19 15:09
I ran `phpstan analyze` with the PHP version set to 7.4 (thanks, Neil!) and other options unchanged and no errors were reported.

<img width="492" alt="Screen Shot 2022-01-19 at 8 49 00 AM" src="https://user-images.githubusercontent.com/1318579/150143402-e60bad9a-3773-40d9-900e-629f1752115b.png">

I commented out the excluded tests and included contrib modules:

<img width="336" alt="Screen Shot 2022-01-19 at 8 56 05 AM" src="https://user-images.githubusercontent.com/1318579/150144709-5aaa267d-d7a5-4f78-b10f-3460960996eb.png">

and reran:

<img width="473" alt="Screen Shot 2022-01-19 at 8 55 45 AM" src="https://user-images.githubusercontent.com/1318579/150144793-1295202d-a7b1-4e14-b181-60b8c3a1549f.png">

This was a little noisier:

<img width="210" alt="Screen Shot 2022-01-19 at 8 57 56 AM" src="https://user-images.githubusercontent.com/1318579/150145021-66868f1a-28d3-464b-b203-8401b6a04b7e.png">

Most of these were for unknown methods and properties on objects, which is a consequence of idiomatic Drupal development.  I ignore them!

<img width="390" alt="Screen Shot 2022-01-19 at 9 17 27 AM" src="https://user-images.githubusercontent.com/1318579/150148546-52118675-3473-4351-89d5-8a7c607c0caf.png">

and that cuts the errors almost in half.

<img width="214" alt="Screen Shot 2022-01-19 at 9 18 06 AM" src="https://user-images.githubusercontent.com/1318579/150148645-8113270d-a918-4096-be8a-4b3dc3c18628.png">

I scanned for "deprecated" but all results were of three groups:
- deprecated in Drupal 8.x/9.x, removed in 10.0.0
- deprecated in Symfony 4.x
- deprecated in PHPUnit 

I didn't find any references to deprecations in PHP itself.  Looking at the [7.4 deprecations](https://www.php.net/manual/en/migration74.deprecated.php), this makes sense -- none jump out at me as things I've seen in our codebase.  

(and some things like [nested ternary conditionals, given PHP <= 8.0.0's unconventional associativity](https://www.php.net/manual/en/language.operators.comparison.php#language.operators.comparison.ternary) would definitely jump out at me)

I also reviewed the baseline file and observed that none of its listed errors could confound detection of any new issues with PHP 7.4.

This is just a first step, of course, but so far I haven't turned up any issues.

**Comment by ndouglas** [comment] 2022-01-19 16:55
The issue mentioned above with Alpine and PHP 7.4 might not be relevant since the Tugboat PHP container does not use Alpine, but Debian.  Unless I'm missing something.

**Comment by ndouglas** [comment] 2022-01-24 15:24
@indytechcook I think it's sufficient to close it.  I have a PR open for the actual code updates for Tubgoat/Lando/DDEV, but they're trivial obv.

**Comment by indytechcook** [comment] 2022-01-24 15:33
I had thought we had a follow up issue to actually make the change in tugboat/lando/ddev but it's actually an AC on this issue :)

**Closed** 2022-01-27 16:54 UTC
Labels: DevOps, Platform CMS Team
