### ISSUE TITLE
UX Design | Support Cross-product Testing

### ISSUE THREAD

**Issue by productmike** [department-of-veterans-affairs/va.gov-cms#14427] opened 2023-07-19 13:13 UTC
## User Story / Task
Coming out of the cross-team sync on D10 test planning on 7/18, we need to ensure we provide space to support testing.

## Acceptance Criteria
- [x] Drupal team, UX, PM, DM meet to review CMS components ([mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/vagov6717/1646745279937/9a5570c420939d84e875e8334fd73073e3a3971b?fromVisitorModal=true&sender=ub3a2c2a4de441f561d452324)) to determine our expectations on which are core vs. product.
- [x] UX Design calls out specific design consistency concerns and helps determine how we should address.
- [ ] Any UX Design request from downstream product is responded to.

**Comment by productmike** [comment] 2023-07-24 20:05
Sure thing, feel free to post here, grab time on the calendar or slack 'em :)  @BlakeOrgan @BerniXiongA6

**Comment by EWashb** [comment] 2023-07-25 02:30
#12560 is an example of UX review items that @BlakeOrgan will likely be interested in. Please take a look at this epic for an already-tested list of UX items: #11614

**Comment by productmike** [comment] 2023-07-25 15:14
Thanks @EWashb

**Comment by BlakeOrgan** [comment] 2023-08-01 20:05
I used [this spreadsheet](https://docs.google.com/spreadsheets/d/1v5vc4PS1WxzctjK-qrulEL3BrVXhcTmV7VcRzin_oj4/edit?usp=sharing) to track and compare what's currently on Prod to the D10 test environment on the [VA.gov Claro Admin Theme](https://prod.cms.va.gov/admin/appearance/styleguide/vagovclaro) page. This page gives a good overview of many different elements that are used across the CMS. The notes section contains questions and suggestions based on each of these individual items, but only items marked as failing will need to be addressed as part of the D10 update.

The majority of the UI elements saw no visual difference. Some items such as the ones listed below looked different in the D10 version, but are actually an improvement from what is on currently on Prod

**UI Improvements in D10**
- Single checkboxes and checkbox groups now have proper spacing between the checkbox and the description and checkboxes are properly left aligned
- Radio selects now have proper spacing between the selection point and the description and are properly left aligned.
- "Forms, details" and "Forms, vertical tabs" dropdown arrows are now properly aligned with the label of the dropdown.
- The blue bar that shows progress within the progress bar now properly fits within the confines of the bar.

**UI Regressions in D10**

The items marked as failed in the spreadsheet are listed below along with an explanation of the visual regressions.

- Rich Text and Rich Text Limited
    * Italic has been removed. This was intentional.
    * Linky has been removed when adding links. This is a regression.
    * Numbered lists should align with bulleted lists. 
    * "Start at" number dropdown was added to numbered lists. Do we want to keep this addition? Will including it as part of the update introduce any problems down the line? What's the use case for starting a numbered list at a number other than 1? 
    * Styling of the horizontal rule is different. 
    * Styling when clicking source has a different icon, but I think it's an improvement over what's currently in Prod. Why do we allow for them to edit the source code? Seems like an opportunity for them to unintentionally mess things up since our CMS is headless and the end result might be displayed in different ways.
    * The styling of quote is different. There are no quotation marks that denote that this is a quote like what's currently on Prod. I would consider this a regression IMO.
    * We still allow them to specify heading levels, however, on Prod it is labeled "Format" and on D10 it is labeled "Paragraph" or whatever the current styling is set as. Heading levels are a different font in D10 than on Prod. Why are we allowing them to set their own heading levels in the RTE? It seems like it opens a lot of opportunities for skipped heading levels. I think we should limit them from doing that. 
    * There are more styles in the D10 Dropdown. Could introducing these additional styles present problems down the line? 
    * The styling of the existing "Address Block" style is different between Prod and D10.
    *  "Abbreviation was added to the RTE. What is this addition intended to be used for? Should we keep it? Would adding it present future problems down the line? 
    * Do we allow editors to switch between text formats using the "Text format" dropdown? I feel like admins should be determining what type of text input we are presenting to our editors and not let them switch on their own. 
    * The question mark icon next to "About text formats' link is not AA accessible and should be on the left of the text.
* “Filter tips, short” and “filter tips, long” seem to be documentation around the RTE and would need be changed to document any updates made as part of the RTEs.
* Unordered inline lists with links
    * The spacing between items shrunk in the D10 version. Spacing between items should be 24px
* Menu tree
    * Is this supposed to reflect the structure of the menu as it displays in the UI?
    * Differences start happening around "appearance" when going down the list.

**Closed by BlakeOrgan** 2023-08-01 20:05 UTC
Labels: CMS Team, CMS design

**Comment by EWashb** [comment] 2023-08-01 23:04
@BlakeOrgan thank you for this thoughtful write-up.

@productmike we need to make sure to include Blake's feedback in the testing documents. He found a lot of things that should be discussed and rated prior to launch.
