### ISSUE TITLE
Update St Croix Vet Center to new USVI section; archive St Thomas Vet Center - Awaiting Redirect

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-cms#17847] opened 2024-04-15 15:15 UTC
> We expect to learn about a new Vet Center in the USVI. This new location will require changes for two existing locations and likely communication with two or more editors will be necessary. 
> - The [St. Croix Vet Center Outstation](https://prod.cms.va.gov/san-juan-vet-center/st-croix-vet-center-outstation) (vc_3071OS) will move from the San Juan section to the new USVI Vet Center section. The editor will also likely change. 
> - The [St. Thomas Vet Center Outstation](https://prod.cms.va.gov/san-juan-vet-center/st-thomas-vet-center-outstation) (vc_3072OS) should be deactivated by VAST and will need to be archived. It's unclear if these two changes will come through VAST at the same time. 

# Facility closure: `vc_3071OS`
## Intake
- [x] What triggered this runbook? (Flag in CMS, Help desk ticket, Product team, RCS Central Office)
Trigger: BOLO from Michelle. St Croix has now come through the API with a new API ID (`vc_3081OS`). 

- [x] Link to associated help desk ticket (if applicable)
Help desk ticket: [VAHELP-8146](https://va-gov.atlassian.net/browse/VAHELP-8146)

- [x] Name of submitter (if applicable)
Submitter: Barb Kuhn

- [x] Contact the Vet Center editor and send them a link to the operating status KB article. If the facility has not closed yet and we can provide lead-time, the editor should change the Facility status to "Facility notice" and provide information in the Facility Status additional information about when the facility will permanently close.
- [x] When the facility has already closed - including if we were unable to give the aforementioned lead time- the editor should change the Facility status to Closed and provide information in the Facility Status additional information that the facility has permanently closed as of DATE.
   - Vet Center Mobile autoarchive when they are removed from the facilty API.  No action required.
   - Vet Center Outstations autoarchive when they are removed from the facilty API.  No action required.
- [x] After 30 days of the facility being closed AND that the facility has been removed from the Lighthouse Facilities API, we can then archive the facility.
KB articles: <insert_kb_article_links>

- [x] Link to facility in production:
Facility CMS link: [https://prod.cms.va.gov/san-juan-vet-center/st-croix-vet-center-outstation](https://prod.cms.va.gov/san-juan-vet-center/st-croix-vet-center-outstation)
Facility API ID: vc_3071OS

#### CMS help desk steps
**Note: If the help desk is waiting on information from the facility staff or editor, add the "Awaiting editor" flag to the facility with a log message that includes a link to this ticket. Remove the flag when the ticket is ready to be worked by the Facilities team. Be sure to preserve the current moderation state of the node when adding or removing the flag.**
- [x] 1. Become aware that the facility is no longer on the Facility API (typically, via a Flag, but this may come in as a helpdesk ticket).
- [x] 2. Create a [URL change](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/new?assignees=&template=runbook-facility-url-change.md&title=URL+Change+for%3A+%3Cinsert+facility+name%3E) to redirect the from the URL of the facility to be closed to the URL of its parent system and to remove the old canonical link. We need this because the Outstation is moving to a new section. 
vc_3071OS,https://www.va.gov/san-juan-vet-center/locations/#st-croix-vet-center-outstation  -- whichever API ID stays alive needs to be updated to point to the new link on USVI
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19781

#### Drupal Admin steps (CMS Engineer or Help desk)
_Help desk will complete these steps or escalate to request help from CMS engineering._
- [x] 4. Drupal Admin bulk unpublishes the nodes.
- [ ] 5. Drupal Admin removes the Section.
- [x] 6. Drupal Admin edits facility node by removing the flag `Removed from source`, sets moderation state to archived, and saves the node.

#### CMS Help desk (wrap up)
- [x] 7. Help desk notifies editor and any other stakeholders.

# New facility: `vc_3081OS`

## Description
Use this runbook if: a Vet Center, Mobile Vet Center, or Vet Center Outstation is flagged as New, OR if an existing facility is flagged as New with a new Facility API ID.  
- This may also occur when an Outstation is promoted to main Vet Center or if an existing Mobile Vet Center is reallocated to a different Vet Center 

## Intake
- [x] What triggered this runbook? (Flag in CMS, Help desk ticket, Product team, VHA Digital Media)
Trigger: <insert_trigger>

- [ ] Link to associated help desk ticket (if applicable)
Help desk ticket: <insert_help_desk_link>

- [ ] Name of submitter (if applicable)
Submitter: <insert_name>

- [ ] If the submitter is an editor, send them links to any relevant KB articles for the Vet Center product.
KB articles: <insert_kb_article_links>

- [ ] Link to facility in production:
Facility CMS link: <insert_facility_link>
Facility API ID: <insert_facility_API_ID>

### New Vet Center
[@TODO: KB ARTICLE FOR ADDING VET CENTERS - SEE runbook-vamc-facility-new]

#### CMS help desk steps
**Note: If the help desk is waiting on information from the facility staff or editor, add the `Awaiting editor` flag to the facility** with a log message that includes a link to this ticket. Remove the flag when the ticket is ready to be worked by the Facilities team. **Be sure to preserve the current moderation state of the node when adding or removing the flag.**

**If a Mobile Vet Center:**
- [ ] Confirm the Vet Center to which it belongs and and set the "Main Vet Center location" field. The parent location may be derived by the Facility ID.
- [ ] Follow up with Barb Kuhn/RCS Central office to let her know we've identified this new Mobile unit and confirm the District, Vet Center Director, and Outreach Specialist (names/email addresses) who will be responsible for updates
- [ ] Contact the Vet Center editor to remind them to (1) add a photo of the Mobile Vet Center and then they can publish when ready and (2) remind them that if this Mobile Vet Center is used by any other facilities to communicate with those Vet Center editors

**If a Outstation:**
- [x] Become aware that the new facility is now on the Facility API (typically, via a Flag).
- [x] Confirm the Vet Center to which it belongs and set the "Main Vet Center location" field. The parent location may be derived by the Facility ID.
- [x] Follow up with Barb Kuhn/RCS Central office to let her know we've identified the new Outstation and confirm the District, Vet Center Director, and Outreach Specialist (names/email addresses) who will be responsible for updates
- [x] Contact the Vet Center editor to remind them to (1) add a photo of the Outstation
- [x] If the new Outstation replaces a CAP, the editor should consider updating the operating status for the CAP to direct Veterans to the new location with “as of” date and set a reminder on the calendar to archive the CAP 30 days after the new location has opened   

**If a Vet Center:**
- [ ] Become aware that the new facility is now on the Facility API (typically, via a Flag).
- [ ] Check with Readjustment Counseling Services to (1) confirm what district the Vet Center belongs, (2) identify the Vet Center Director and Outreach Specialist (names/email addresses), (3) confirm the new location isn't a replacement for an existing Outstation
- [ ] In [Sections taxonomy](https://prod.cms.va.gov/admin/structure/taxonomy/manage/administration/overview), move the Vet Center Section to the appropriate district.
- [ ] Create account access as directed by RCS. If editors are new to Drupal, create accounts with editor rights only for Vet Center Director and Outreach Specialist so that they cannot publish on their own.
- [ ] Contact Vet Center Director and Outreach specialist to onboard for training [@TODO write sample email - SEE runbook-vamc-facility-new] **Note: this should include instructions for adding content and preparing for publishing and RCS Central Office should be included as CC**
- [ ] Add flag `Awaiting editor` to this facility. Note: This is now blocked until RCS Central office approves.
- [ ] **Once approved by RCS Central Office as complete, proceed to Drupal Admin publishing steps**

**Drupal Admin steps**
- [x] Bulk publish the nodes and facility.
- [x] Contact Lighthouse via Slack at #cms-lighthouse channel that this facility requires a canonical link in the following format (replacing the placeholder data with the actual API Id and VA.gov URL):
  - `vc_3081OS,https://www.va.gov/us-virgin-islands-vet-center/st-croix-vet-center-outstation/`
- [x] Add the "Awaiting CSV" flag to the facility node with a revision log message that includes a link to this ticket.
- [x] Let Help desk know this has been done, if not done by Help desk.

#### Wait (days or weeks, potentially)
- [ ] After the canonical link has been added to the websites.csv and you have confirmation from Lighthouse that the CSV has been deployed, validate that the change has deployed by checking that the Facility Locator has been updated with the new url.
- [ ] Update this ticket with a comment that the CSV change has been deployed.
- [ ] Edit facility node and remove `New facility` and "Awaiting CSV" flags with a revision log message that includes a link to this ticket.
- [ ] Let Help desk know this has been done, if not done by Help desk.

#### CMS Help desk (wrap up)
- [ ] 11. Upgrade the Vet Center Director and Outreach Specialist accounts to the publisher role for that Vet Center.
- [ ] 12. Notify editor and any other stakeholders.

[VAHELP-8146]: https://va-gov.atlassian.net/browse/VAHELP-8146?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by jilladams** [comment] 2024-10-24 16:49
The new vet center was handled here, in this dupe ticket: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19102

But: we haven't handled St Croix yet.

**Comment by jilladams** [comment] 2024-10-24 16:53
Per @ian-sears : 
* No news on St Thomas
* St Croix came through LH last night as a new facility with a new API ID: vc_3081OS. We need to confirm which (old vs new) should be published and moved under USVI, and which should be archived. That is a Barb question. Helpdesk will follow up.

**Comment by ian-sears** [comment] 2024-10-24 21:14
Update from Barbara Kuhn.
We are activating (filling out and Publishing) vc_3081OS.
Then Redirects to it from the older vc_3071OS
Then archiving of vc_3071OS

**Comment by ian-sears** [comment] 2024-11-05 00:26
@jilladams @omahane I worked to untablge the above, focussing on the St. Croix Vet Center Outstation, and have become very confused.
If possible, we should meet to clarify, as the above blends (3) facilities into this one GitHub ticket and has become difficult to advance. I believe the work has been done, however.

**Comment by ian-sears** [comment] 2024-11-06 00:45
@omahane  Please disregard my above confusion.
We've filed the Lighthouse CSV request to
ADD: vc_3081OS,https://www.va.gov/us-virgin-islands-vet-center/#st-croix-vet-center-outstation/
and REMOVE: vc_3071OS,https://www.va.gov/san-juan-vet-center/locations/#st-croix-vet-center-outstation
Slack request here: https://dsva.slack.com/archives/C02BTJTDFTN/p1730765512022909

Christian, please set up a redirect, as requested by Barbara Kuhn above in this ticket FROM the vc_3071OS Outsation TO the new vc_3081OS.
(I did not think we actually DO use redirects for Outstations, however I leave that to you, as Barbara did request that above.)

**Comment by ian-sears** [comment] 2024-11-07 20:06
@omahane  @jilladams --

When you have some time, could you please Create a URL redirect in the [vsp-platform-revproxy](https://github.com/department-of-veterans-affairs/vsp-platform-revproxy) repo in template-rendering/revproxy-vagov/vars/redirects.yml

[FROM] https://www.va.gov/san-juan-vet-center/locations/#st-croix-vet-center-outstation/
     [TO] https://www.va.gov/us-virgin-islands-vet-center/#st-croix-vet-center-outstation/

Please alert Helpdesk @department-of-veterans-affairs/platform-cms-helpdesk when this step has been completed.

**Comment by ian-sears** [comment] 2024-11-27 18:48
Closing asw all resolved.
St. Croix Vet Center Outstation redirect from sJ St.Croix is complete.
CSV is in place and resolves on facility API.
SJVCOS is archived (redirects successfully yo the USVI St. Croix Vet Center Outstation as intended.
Editor has been notified.
All is complete.

**Closed by ian-sears** 2024-11-27 18:48 UTC
Labels: VA.gov frontend, Drupal engineering, Facilities, Vet Center, User support, Change request, sitewide, Flagged Facilities, ghp-backlog
