### ISSUE TITLE
Error when sorting by moderation state

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#13840] opened 2023-05-25 16:43 UTC
## Describe the defect
In the CMS, when trying to sort the view by Moderation State, I am getting an error.

## To Reproduce
1. Go to the main [content view](https://prod.cms.va.gov/admin/content)
2. Click on Moderation State at the top of the content table
3. See error

## AC / Expected behavior

- [ ] The content table should reload sorted by moderation state

## Additional context
The other available sorting (Title, Section, etc.) works correctly for the view

I did this in a Tugboat environment and got this error if it helps:

> The website encountered an unexpected error. Please try again later.

```
Drupal\Core\Database\DatabaseExceptionWrapper: Exception in Content[content]: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'moderation_state' in 'order clause': SELECT "node_field_data"."langcode" AS "node_field_data_langcode", "users_field_data_content_lock"."langcode" AS "users_field_data_content_lock_langcode", "content_lock"."timestamp" AS "content_lock_timestamp", "content_lock"."entity_id" AS "content_lock_entity_id", "node_field_data"."nid" AS "nid", "users_field_data_node_field_data"."uid" AS "users_field_data_node_field_data_uid", "users_field_data_content_lock"."uid" AS "users_field_data_content_lock_uid" FROM "node_field_data" "node_field_data" INNER JOIN "users_field_data" "users_field_data_node_field_data" ON node_field_data.uid = users_field_data_node_field_data.uid LEFT JOIN "content_lock" "content_lock" ON node_field_data.nid = content_lock.entity_id AND content_lock.entity_type = :views_join_condition_0 LEFT JOIN "users_field_data" "users_field_data_content_lock" ON content_lock.uid = users_field_data_content_lock.uid WHERE "node_field_data"."type" IN (:db_condition_placeholder_1) ORDER BY ""."moderation_state" ASC LIMIT 25 OFFSET 0; Array ( [:db_condition_placeholder_1] => full_width_banner_alert [:views_join_condition_0] => node ) in main() (line 19 of index.php).
```

### Team
Please check the team(s) that will do this work.

- [x] `CMS Team`
- [ ] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

**Comment by ndouglas** [comment] 2023-05-31 12:46
I think this is a dupe of #12559.

**Closed by ndouglas** 2023-05-31 12:46 UTC
Labels: Defect, Needs refining, CMS Team
