### ISSUE TITLE
Audit usage of vets-website styles from content-build

### ISSUE THREAD

**Issue by randimays** [department-of-veterans-affairs/va.gov-cms#18365] opened 2024-06-20 20:26 UTC
## Description
There are some CSS classes in `vets-website` stylesheets that are referred to / used in `content-build`. We are not sure how much this occurs; engineers first noticed it while doing web component upgrades. 

This ticket is to find all of the places where `content-build` is using styles from `vets-website` and assess risk of styles or functionality breaking if those styles are removed from `vets-website`.

### Engineering notes / background
Beth Potts discovered a style bug with icons on Benefit Hub landing pages that resulted from an engineer removing a file containing the `inline` class from `vets-website`. Slack thread for context: https://dsva.slack.com/archives/C52CL1PKQ/p1718906568437409

## Acceptance criteria
- [ ] All usages of vets-website classes in content-build are identified in ticket comments
- [ ] Review findings with PM for decision on next steps (e.g. ticket to fix them, or wait til AP, etc)

**Comment by jilladams** [comment] 2024-08-14 21:58
dupe of #18765

**Closed by jilladams** 2024-08-14 21:58 UTC
Labels: VA.gov frontend, Facilities, Needs refining, Public Websites, sitewide
