### ISSUE TITLE
[V1 or 3 Components] Implement available components for Campaign Landing Pages

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#17179] opened 2024-02-09 00:19 UTC
## Description

The Design team is releasing a Typography update (sometime in March), which means that the PW team needs to upgrade any of our products where components aren't currently being using, but a V1 or V3 component is available.

If the updates aren't made prior to the Typography update, there's a chance that Veteran-facing issues may occur.

Example pages:

- [Sign in securely with Login.gov](https://www.va.gov/initiatives/sign-in-securely-with-logingov/)
- [How Veterans can register to vote](https://www.va.gov/initiatives/vote/)

## Elements that are not using components that should be

1. Links: are not using a component but should be using the [v1 component](https://design.va.gov/components/link/)
   - This should be used everywhere possible, including content inside accordions
   - We also want to make sure we are using the proper variant of the links (i.e [Active link](https://design.va.gov/components/link/#active), [Channel](https://design.va.gov/components/link/#channel), etc.) so the styles remain the same
2. Telephone
   - The V1 [component](https://design.va.gov/components/telephone) is not being used anywhere but should be

### User story

**AS A** PO/PM for Public Websites products
**I WANT** to implement available V1 or V3 components in features & products currently under Public Websites management where components aren't currently being used
**SO THAT** all PW products are in alignment with the current component version.
**AND** Veterans and other users have a consistent experience within VA.gov

## Acceptance criteria
- [ ] Links are using V1 component, with proper variant when necessary
- [ ] Telephone is using the V1 component
- [ ] other features display correctly
- [ ] verify/review the E2E tests
- [ ] check desktop and mobile
- [ ] a11y review

**Comment by laflannery** [comment] 2024-03-15 14:16
@chriskim2311 I just found this ticket and I'm pretty sure it's a duplicate of the one [you are already working on](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17178). The only thing that is different is the AC (this mentioned the testing). Should we close this one?

**Comment by FranECross** [comment] 2024-03-27 17:27
Close per comment above.

**Closed** 2024-03-27 17:27 UTC
Labels: VA.gov frontend, Public Websites, V3 Components
