### ISSUE TITLE
FE: Screen readers need guidance on pronouncing "VA" in breadcrumbs

### ISSUE THREAD

**Issue by ryguyk** [department-of-veterans-affairs/va.gov-cms#12302] opened 2023-01-20 17:17 UTC
## Description
It is a known issue (see [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/4507) and [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/20238)) that screen readers struggle with "VA". As such, it is our understanding that "VA" was removed in most cases from breadcrumbs because they are such a prominent feature at the top of the page that could cause Veterans who use screen readers to become confused.

With Lovell, though, we are knowingly introducing "VA" into breadcrumbs. The linked issues above are concerned with solving this problem on a wider basis, but such solutions appear difficult at best. This issue is to handle this in the more isolated context of this Lovell-specific instance of "VA" appearing in breadcrumbs.

## Acceptance Criteria
- [ ] When "VA" ,as it means "Veterans Affairs" only, appears in a breadcrumb the screen reader correctly reads it

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by laflannery** [comment] 2023-02-20 21:57
I just retested this with NVDA and there was no issue on any instance of VA (breadcrumb, page title, news release titles, link in switcher).  I can't test with Voiceover because I need public link but if someone with a Mac wants to try (or I can get someone to do it tomorrow for me) but I'm not convinced this is an issue anymore - or at least not anything that would be serious/launch-blocking

**Comment by maxx1128** [comment] 2023-02-22 16:49
I checked this issue out with VoiceOver and a Mac and confirmed that the instances of VA on this Lovell page (navigation, links, plain text) were all properly read by VoiceOver as the two letters in the acronym. I agree that at the very least this isn't blocking, and is likely not an issue anymore either.

<img width="1171" alt="Screen Shot 2023-02-22 at 11 47 37 AM" src="https://user-images.githubusercontent.com/10790736/220698353-e5f40a80-cf84-4d8a-886b-62b66b2fea81.png">

**Comment by Dottisea** [comment] 2023-02-23 16:52
Convo with Laura Flannery - this is seemingly not happening anymore (can't be reproduced)  so putting the ticket in the icebox in case the issue reoccurs.

**Comment by mmiddaugh** [comment] 2024-01-02 15:55
Closing as this appears to be resolved

**Closed by mmiddaugh** 2024-01-02 15:55 UTC
Labels: VAMC, VA.gov frontend, Facilities, VA Lovell, Breadcrumbs

**Comment by laflannery** [comment] 2024-01-02 16:09
@mmiddaugh The issue with "VA" is not with VoiceOver or NVDA but with JAWS. We still don't have an answer to how, or even if, we should solve this yet however. Would you want to keep this open for the JAWS issue?
