### ISSUE TITLE
Menu Link update possibly not clearing graphql cache

### ISSUE THREAD

**Issue by indytechcook** [department-of-veterans-affairs/va.gov-cms#4354] opened 2021-02-17 18:54 UTC
## Description

During a content deploy there was an error hitting the graphQL request due to missing menu entities.  We need to verify that the menu entites are adding cache tags to the query.

Randi reported deleting 2 menu links before this issue started to occur.

## links
* [internal] https://dsva.slack.com/archives/CDHBKAL9W/p1613585283207000
* [internal] https://dsva.slack.com/archives/CT4GZBM8F/p1613585644290200
* http://jenkins.vfs.va.gov/job/builds/job/vets-website-content-vagovprod/825/console

## Logs:

Build Log Error:
```
 [
   {
     message: 'Internal server error',
     category: 'internal',
     locations: [ [Object] ],
     path: [ 'nodeQuery', 'entities', 9, 'entityUrl', 'breadcrumb' ]
   }
 ]
 Error: GetNodeSupportResourcesDetailPage resulted in errors
     at parallelQuery (/application/src/site/stages/build/drupal/****.js:224:17)
     at processTicksAndRejections (internal/process/task_queues.js:93:5)
     at async Promise.all (index 5)
     at async Object.getAllPagesViaIndividualGraphQlQueries (/application/src/site/stages/build/drupal/****.js:271:7)
     at async getContentViaGraphQL (/application/src/site/stages/build/drupal/metalsmith-drupal.js:162:19)
     at async loadDrupal (/application/src/site/stages/build/drupal/metalsmith-drupal.js:231:7)
     at async Ware.<anonymous> (/application/src/site/stages/build/drupal/metalsmith-drupal.js:275:20)
 Failed to pipe Drupal content into Metalsmith!
 /application/src/site/stages/build/index.js:284
     if (err) throw err;
              ^
 
 Error: GetNodeSupportResourcesDetailPage resulted in errors
     at parallelQuery (/application/src/site/stages/build/drupal/****.js:224:17)
     at processTicksAndRejections (internal/process/task_queues.js:93:5)
     at async Promise.all (index 5)
     at async Object.getAllPagesViaIndividualGraphQlQueries (/application/src/site/stages/build/drupal/****.js:271:7)
     at async getContentViaGraphQL (/application/src/site/stages/build/drupal/metalsmith-drupal.js:162:19)
     at async loadDrupal (/application/src/site/stages/build/drupal/metalsmith-drupal.js:231:7)
     at async Ware.<anonymous> (/application/src/site/stages/build/drupal/metalsmith-drupal.js:275:20)
 error Command failed with exit code 1.
```

Drupal Watchdog error:

```
Drupal\Component\Plugin\Exception\PluginNotFoundException: Plugin ID 'menu_link_content:4a204faa-aa3d-4e41-82a9-bf554d7ce18f' was not found. in Drupal\Core\Menu\MenuLinkManager->getDefinition() (line 206 of /var/www/cms/docroot/core/lib/Drupal/Core/Menu/MenuLinkManager.php).
```

## Acceptance Criteria
- [ ] 👀 **Needs design review** because the work involves changes to labels or other design elements 
- [ ] 🙈 Can be implemented without consulting design team members
- [ ] Testable_Outcome_X
- [ ] Testable_Outcome_Y
- [ ] Testable_Outcome_Z

**Comment by indytechcook** [comment] 2021-02-18 13:22
I wasn't able to reproduce this locally.  A few things I tried:

* Made sure my settings.php files had caching enabled.
* Ran the vets-website build to prime caches and verified the `cache_graphql_resutls` table had items.
* Deleted the menu link entity `474` which is the id for`4a204faa-aa3d-4e41-82a9-bf554d7ce18f`
* Re-ran the front end build.

I also tried deleted random menu items and wasn't able to reproduce the issue.

When I searched the cache table for results with menu link cache tags I did find 4 records with the `menu_link_content_list` tag.  This tag would correspond to any menu link entity change.  I did not figure out which queries these cache items were for.

cids:
```
cid
ccid:1d6eac9bc646885c52805f49f990070838711eace8d44973c1458cba5bb77cbf
ccid:5e4a0322039f4817ecea9a616463b3328a39123459610c3409e98bc1c3ef2ad3
cid:1d6eac9bc646885c52805f49f990070838711eace8d44973c1458cba5bb77cbf:[languages:language_content]=en:[languages:language_interface]=en:[languages:language_url]=en:[user.permissions]=cac985ecca48b3331e4f7ef6f4c0287783e85096182f17e478221e01490d1a2b
cid:5e4a0322039f4817ecea9a616463b3328a39123459610c3409e98bc1c3ef2ad3:[languages:language_content]=en:[languages:language_interface]=en:[languages:language_url]=en:[url.site]=http://va-gov-cms.lndo.site:[user.nodesDvwh-q_0_koiQua9uCOjzEaaeWNv9BawT0So7hq1jE
```

**Comment by oksana-c** [comment] 2021-03-01 18:20
closing since we weren't able to reproduce. Will reopen if the same defect comes up again.

**Closed by oksana-c** 2021-03-01 18:20 UTC
Labels: Core Application Team, Defect, Drupal engineering, Needs refining, Stretch goal
