### ISSUE TITLE
PM: Share with VHA DM

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#12987] opened 2023-03-16 15:30 UTC
## Description
Raised here in Staging Review: https://github.com/department-of-veterans-affairs/va.gov-team/issues/54292

**How to Reproduce**

- Go to https://www.va.gov/lovell-federal-health-care-va/contact-us/ and hover over the links under Patient help and resources. See that they go to VA and TRICARE pages.
- Go to https://www.va.gov/lovell-federal-health-care-tricare/health-services/mental-health-care/ and hover over links under Other Resources. See that some of them to to VA pages.
- Go to https://www.va.gov/lovell-federal-health-care-tricare/health-services/returning-service-member-care/ and hover over links under Other Resources. See that some of them to to VA pages.
- Go to https://www.va.gov/lovell-federal-health-care-tricare/work-with-us/ See that all links go to VA side
- Go to https://www.va.gov/lovell-federal-health-care-va/dav-vans-transportation-for-veterans/ and look at link under Arrange a Ride. See that link goes to TRICARE side

**Expected behavior**

Any dual-published content that contains a link to either sub system always checks the URLs and changes them during the split process

## Acceptance Criteria
- [ ] I expect that the below AC are completed within a timebox that reflects the size on this card
- [ ] I expect that every case and circumstance leading to this behavior is explored based off of the examples provided above (where all the links can possibly live)
- [ ] I expect it is determined if this is a front or back end solution 
- [ ] I expect solution options are presented to solve the implementation AC as described here:  I expect that any link that goes to a page within a Lovell system page that is dual published needs to go to its respective system

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

**Comment by davidmpickett** [comment] 2023-04-13 03:55
@kmariepat-cityfriends @swirtSJW 
Is this still blocked? It's not clear what was blocking this from proceeding, but maybe it had something to do with the URL alias issue that just got resolved.

**Comment by kmariepat-cityfriends** [comment] 2023-04-13 14:34
@davidmpickett wish I put a reason here, I don't know why it was originally blocked or if it's unblocked but thanks for highlighting. I will show in refinement today and see what the rest of the team knows.

**Comment by davidconlon** [comment] 2023-04-13 16:31
Doing this one-at a time comment.

**Contact Us** - Should not be a dual-publish page (I don't think) but we should work with VHA DM and Lovell to understand, in particular, how FOIA requests are handled, Fraud reporting is handled, Patient care safety issues reporting, etc. because right now we're specifying "VA's processes" and DoD/Tricare may have a different processes and we will be looking to harden this page for VA facilities in the future.

**Comment by davidconlon** [comment] 2023-04-13 16:53
**DAV Van**s - I think we need to validate this with Lovell, but I don't think DAV serves DoD folks. They serve only Veterans. But could be confirmed via VHA DM.

**Comment by davidconlon** [comment] 2023-04-13 16:57
**Work with us** - Sooo, as a person looking for a job, does it matter whether I jump between DoD and VA sides? Arguably this entire sub-section might be a dual-publish thing so that it's relative links? it's weird.
But really the content editors likely need to see where they are linking to? I'm not sure it actually matters - probably should confirm with Lovell via VHA DM. That someone looking for a job jumps between sites if they are looking for a job with the Federal Gov't or if there are different hiring streams is really I think what we need to understand.

**Comment by davidmpickett** [comment] 2023-04-17 20:29
@davidconlon Given that most of these seem to be content strategy issues to be discussed with VHA DM and Lovell, does that mean this ticket shouldn't be a blocker for Full State?

Will you be initiating conversation with VHA DM, or should @kmariepat-cityfriends?

**Comment by davidconlon** [comment] 2023-04-18 15:39
@davidmpickett @kmariepat-cityfriends I haven't really been involved in the discussions around Lovell with VHA DM. This may be a topic for the support synch next Tues?

**Comment by kmariepat-cityfriends** [comment] 2023-04-26 14:13
Closing this card, all dual published locations were communicated to VHA DM

**Closed** 2023-04-26 14:14 UTC
Labels: VAMC, Facilities, Blocked, VA Lovell

**Comment by kmariepat-cityfriends** [comment] 2023-04-27 18:22
Archive the https://www.va.gov/lovell-federal-health-care-va/dav-vans-transportation-for-veterans/
