### ISSUE TITLE
[Search] Correct [lastmod] date on XML sitemap

### ISSUE THREAD

**Issue by mnorthuis** [department-of-veterans-affairs/va.gov-cms#16333] opened 2023-12-06 17:40 UTC
## Status
[2024-04-23] Dave Conlon and Erika Washburn have asked that the PW team prioritize this item. _Note that Mikki closed [[Search] Sitemap should correctly indicate the last modified date of content]_( https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16380) as a dupe.

## BLUF
It currently appears as though every entry in the xml sitemap is being updated/generated with a new [lastmod] date each time any update is made to the sitemap.   Only the URL that was updated should have an updated [lastmod] date reflected in the xml sitemap so that search engines can identify which pages have updates and prioritize them to reindex.  

See comments for additional context and information.

## User Story or Problem Statement
As a Veteran, when I search for VA content, I need search results to include the newest content and reflect updated copy and content in results.

As a search engine, I need to know which pages have been recently updated so I can prioritize them in my limited crawl budget to ensure updates are reflected in search results. 

## Impacts of this issue:
With every URL having an updated [lastmod] date, search engines are trying to crawl the entire site each time, which means:
- old pages are being continually crawled for no reason, wasting limited crawl budget
- pages that have updated H1s, descriptions, and/or meta data are not being updated in search results
- new pages are being missed/not crawled and are not indexed

This is critical when new pages and updates can reflect urgent new or updated information. 
This was discovered when we updated content and an H1 on a pension payment rates page for the new year, and search results were still reflecting the page title as last year's rates several days later. 

## Requirements
A CMS page's (only; not assets or content from other repos) entry in the sitemap should indicate its last-modified date, so that crawlers can identify updated content and index it.

## Background & implementation details

- W3C compliant datetime formats: https://www.w3.org/TR/NOTE-datetime
- General information about Sitemap structure: https://www.sitemaps.org/protocol.html
- Search.gov sitemap.xml expectations: https://search.gov/indexing/sitemaps.html
- Sitemap is created in Content Build here: https://github.com/department-of-veterans-affairs/content-build/blob/main/src/site/stages/build/plugins/create-sitemaps.js#L11

## Acceptance criteria
- [ ] Sitemap draws the `lastmod` value from `field_last_saved_by_an_editor` if it is available on the content
- [ ] Sitemap draws the `lastmod` value from the `changed` property if `field_last_saved_by_an_editor` is not available
- [ ] `lastmod` is formatted in a W3C-compliant datetime format
- [ ] `changefreq` and `priority` are removed

**Comment by swirtSJW** [comment] 2023-12-06 18:49
copied from [slack thread](https://dsva.slack.com/archives/C03LFSPGV16/p1701887694177479?thread_ts=1701874581.107499&cid=C03LFSPGV16)
There is a level of complexity here that is often overlooked.   Determining the "last updated" of a page on [VA.gov](http://va.gov/) is not as simple as it sounds.  Example:
[VAMC system services page](https://www.va.gov/pittsburgh-health-care/health-services/) it is one node in the CMS that may only get updated once every 6 months or more, but it is made of of content from hundreds of service pages that may have been updated as recently as today.    The updated date should ideally reflect the most recently update node that feeds that page, not the node that is that page.   Similar is true for all the listing pages like events or press releases.  The listing pages themselves are almost never updated, but the items in the list are updated more often.

**Comment by EWashb** [comment] 2023-12-11 22:15
The issue above is especially problematic for sitemap cataloging/crawling on search.gov.

**Comment by EWashb** [comment] 2023-12-11 23:10
Additional discovery needs to be done regarding the search results/crawling results per search engine. @mnorthuis do you have an idea of how long a crawl currently takes on search.gov or any other search engines? Does the lastmod date on the XML sitemap 

@maortiz-27-80 for the CMS Team's work on the this- Additional discovery should be considered on the linkages between URL and the lastmod date and potentially other factors that could be logged for lastmod such as our "last touched by an editor" field. Lastmod date is not a good indicator of current content on the site. At any point, the sitemap will show the current date as the lastmod date since content-build rebuilds the entire site instead of incrementally. I suggest we make this a discovery ticket to determine how we can make the lastmod date be more correct.

**Comment by EWashb** [comment] 2023-12-12 18:39
Did confirm with IA that setting a less frequent interval on lastmod scanning for search.gov would not be appropriate because search.gov cannot always complete a full scan and could introduce additional delays from the cataloging and IA perspective.

**Comment by EWashb** [comment] 2024-02-22 19:22
Currently blocked due to A6 team transition and Oddball onboarding.

**Comment by EWashb** [comment] 2024-04-04 15:17
Related to #16380

**Comment by FranECross** [comment] 2024-04-23 18:23
This ticket may be a dupe of 16380 and should be closed or adjusted accordingly if so.

**Comment by mnorthuis** [comment] 2024-04-23 19:07
Closed issue #16380 and keeping this issue.

**Comment by FranECross** [comment] 2024-04-23 19:55
@dsasser I moved the AC/notes we'd added to 16380 (closed by Mikki today as a dupe) to this ticket, added the 5 timeboxed points, and am moving to Ready for consideration in the upcoming sprint.

**Comment by dsasser** [comment] 2024-05-06 16:55
## Status Update 5/6/24

Some questions/concerns have surfaced while working this issue. In the interest of BLUF, I propose we do the following:

1. Scope this issue to CMS pages only (not assets or content from other repos)
2. Add the logic that this issue suggests: to coalesce a last updated value from `field_last_changed_by_an_editor` or `changed`.
3. Create a ticket to add the 'field_last_changed_by_an_editor' field in GraphQL to all nodes and use that in the sitemap.

### Scope
This issue doesn't specify that the scope should/should not be limited to CMS detail pages. All pages, wether coming from the CMS or not, end up in the sitemap (eg: va.gov-cms markdown files). Only the CMS provided pages are within our control, so I would recommend we limit the testing/scope of this issue to pages that derive from CMS content.

### Last Modified on Existing Pages
Existing detail pages (eg: https://staging.va.gov/disability/eligibility/illnesses-within-one-year-of-discharge/) have a 'Last modified' date near the footer. This is being rendered from the `last-updated.drupal.liquid` liquid template, and picks the first value it finds based on the following logic:

- Use the 'lastupdate' field, if set
- Use the 'git_lastupdate' field, if set
- Use the 'changed' field, if set

I can't find any uses of the 'lastupdate' and 'git_lastupdate' values, so ostensibly the 'changed' field is the only value being used currently. However, according to issue ACs, we should be using the `field_last_saved_by_an_editor` field, or `changed` if not present.

> Sitemap draws the lastmod value from field_last_saved_by_an_editor if it is available on the content
> Sitemap draws the lastmod value from the changed property if field_last_saved_by_an_editor is not available

What I want to ensure is that the value represented as the 'Last updated' date on the live detail page should also match the sitemap's date. We can either update this value on the live page to reflect the new value, or we can change the ACs on this ticket to use the 'changed' date in the sitemap that we are already displaying on the detail page.

### GraphQL
The `field_last_saved_by_an_editor` field isn't being returned in the GraphQL queries currently. In order to bring it in, we'll need to update every graphql query that feeds a page in the sitemap to include this field.

**Comment by dsasser** [comment] 2024-05-06 17:42
The current 'Last updated' value on display on live pages is coming from the 'changed' field on the node. eg:

![Screenshot 2024-05-06 at 10 39 51 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/221539/831f4ece-3084-4755-89f0-e44ff14e5bcf)

**Comment by FranECross** [comment] 2024-05-06 17:51
@dsasser Thanks for all this info, and please see notes below:

- Please go ahead and change the AC as you indicate above
- I'll edit/add a note to the Description limiting the scope of this issue to CMS pages only (not assets or content from other repos)

**Comment by dsasser** [comment] 2024-05-07 19:13
@FranECross I created this [ticket](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18065) to track updating the graphql queries.

**Comment by FranECross** [comment] 2024-05-07 20:45
Thanks, @dsasser !  I added AC to the new story and moved it to Next Refinement.

**Comment by jilladams** [comment] 2024-05-08 15:48
From mid-sprint review: Review Instance getting up for testing is the main work remaining here, Platform issue. Review will be to compare the Prod and RI sitemaps to confirm parity.

**Comment by dsasser** [comment] 2024-05-09 16:32
From scrum: As [Steve originally pointed out](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16333#issuecomment-1843500259), the true "last modified" date of some content is difficult to determine. We need to ticket a spike/discovery to determine if/how we want to approach that. @FranECross we are approaching platform CMS territory here, I think.

**Comment by dsasser** [comment] 2024-05-13 16:36
Verified on prod:

![Screenshot 2024-05-13 at 9 35 41 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/221539/319748d7-0d2b-4057-aacb-961c362cd217)

**Closed by dsasser** 2024-05-13 16:36 UTC
Labels: Defect, Drupal engineering, Public Websites, CMS Team, Sitewide IA
