### ISSUE TITLE
Saipan Benefits offices have no representation in Facility Locator

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#12112] opened 2022-12-23 18:14 UTC
## Description
As a VA beneficiary in the Northern Mariana Islands, I want to find information about VA benefits offices located in Saipan by using the Facility Locator on VA.gov.

Searching for VA Benefit offices in this area yields no results:
![saipan.png](https://images.zenhubusercontent.com/62acf41e5be34fcdb6c44c0b/c67b8980-aedb-4d65-be60-d08706471d81)

Currently the information about the Saipan benefit offices is only listed on the front page of the [Honolulu Region Office teamsite](https://www.benefits.va.gov/honolulu/)

![honolulu.png](https://images.zenhubusercontent.com/62acf41e5be34fcdb6c44c0b/319e4d46-eca8-4b19-898c-f0425dea7e94)

## Acceptance Criteria
- [ ] Testable_Outcome_X
- [ ] Testable_Outcome_Y
- [ ] Testable_Outcome_Z
- [ ] Requires design review

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by davidmpickett** [comment] 2022-12-23 18:40
The narrow issue here is resolving this for Saipan. 

The broader issue here is understanding the scope of the use case for representing locations where VA benefit services are offered that are not official VA facilities

**Comment by swirtSJW** [comment] 2022-12-23 22:10
This looks like the case of having a VBA representative/provider assigned to a VHA facility, but no facility reference in VAST.

**Comment by swirtSJW** [comment] 2022-12-23 22:11
https://dsva.slack.com/archives/C0FQSS30V/p1671820889216669?thread_ts=1671819668.766879&cid=C0FQSS30V

**Comment by swirtSJW** [comment] 2022-12-23 22:23
Since this is all coming from "Sandy's Database that @davidconlon is maintaining  it may just be that it was never added and needs to be.

**Comment by JQuaggles** [comment] 2022-12-23 23:19
I don't think this is a FL locator issue though, but rather that this location is not a permanent facility and just what seems like 1 person? If you look at say Newington Regional Office, they have a benefits office located at the Medical Center (according to their current website) (West Haven VA Medical Center, 950 Campbell Ave. (BLDG 1, RM G197) West Haven, CT 06516) - but it is not considered a satellite office where it would appear within Facility Locator. Whereas Providence actually has a listing for the Benefits Satellite Office at the Providence VAMC. 

So it's not just unofficial VA locations, but also other VA locations where they potentially have a benefits office there that might be missing from FL?

Seems like as we look at VBA Facilities pages, it might be good to discuss these types of things too. We want to make sure there is consistency.

**Comment by davidconlon** [comment] 2022-12-27 19:11
@JQuaggles - @swirtSJW is correct.
There is going to misalignment between what is on the teamsite pages and what is in 'Sandy's' database until we replace the DB with Drupal.
We performed a data call last year but that does not mean that the data is current in either the database or the website.
I also note that the website Last updated: December 16, 2022 so the request to add this content to Sandy's DB may not have occurred yet.

Regardless, the path forward on this is to escalate this content to Tanekwa in VBA and possibly OFO so that we can validate that this is a facility and get the appropriate data into Sandy's DB so that it populates correctly into Facilities API.

**Comment by JQuaggles** [comment] 2022-12-27 20:08
Thanks @davidconlon - so we will want to ensure:
- Regional Office facility locations
- Confirmed VA Satellite locations
- Other potential non-VA office located Satellite locations

What I was asking not very concisely is wanting to make sure that we understand what would be considered a satellite location that requires a facility within FL vs a location that a Regional Office sends someone to on a consistent basis (VA or not) but is not considered a satellite/full time location. (Similar to how we look at the other location types for VCs)

But definitely agree to the escalation as well.

**Comment by davidconlon** [comment] 2022-12-27 20:20
[VBA Facilities Data Call Instructions 1.0.pdf](https://github.com/department-of-veterans-affairs/va.gov-cms/files/10310538/VBA.Facilities.Data.Call.Instructions.1.0.pdf)
This may provide additional insight. 
"Satellite" is all of the above. There is currently no sub-definition per OFO.

**Comment by kmariepat-cityfriends** [comment] 2023-04-06 17:23
Next Steps:
- this is a data quality issue, @davidconlon to reach out to Hawaii to prompt them to review their data

**Comment by davidconlon** [comment] 2023-04-11 19:06
Email sent to Eileen Asing for data update call.

**Comment by davidconlon** [comment] 2023-04-20 13:07
Facilities added to VBA_facilities DB on 4/19. Populated in Drupal via nightly migration on 4/20. COVID facility statuses added.

**Closed by davidconlon** 2023-04-20 13:07 UTC
Labels: Facilities, Regional office, Facility Locator, VBA
