### ISSUE TITLE
[V1 & 3 Components] Implement available components for Event Detail Page 

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#17197] opened 2024-02-09 22:07 UTC
## Description
The Design team is releasing a Typography update (sometime in March), which means that the PW team needs to upgrade any of our products where components aren't currently being using, but a V1 or V3 component is available.

If the updates aren't made prior to the Typography update, there's a chance that Veteran-facing issues may occur.

The following have been identified by Laura Flannery:

- Breadcrumbs
  - Not using any component but should be using [v3](https://design.va.gov/components/breadcrumbs#examples---v3)
- Link
  - We should be using available components everywhere possible
- Accordion
  - On recurring events, there is an accordion to show more times which should use the [v3 component](https://design.va.gov/components/accordion#examples---v3)

### User story
**AS A** PO/PM for Public Websites products
**I WANT** to implement available V1 or V3 components in features & products currently under Public Websites management where components aren't currently being used
**SO THAT** all PW products are in alignment with the current component version.
**AND** Veterans and other users have a consistent experience within VA.gov

## Acceptance criteria

- [ ] Breadcrumbs are using V3
- [ ] Links are using available components (V1?)
- [ ] Accordions are using V3
- [ ] other features display correctly
- [ ] verify/review the E2E tests
- [ ] check desktop and mobile
- [ ] a11y review

**Comment by laflannery** [comment] 2024-02-19 13:54
Closing as a duplicate of #17057

**Closed by laflannery** 2024-02-19 13:54 UTC
Labels: VA.gov frontend, Needs refining, Public Websites, V3 Components
