### ISSUE TITLE
[V1 & 3 Components] Upgrade V1 components to V3 for Resources & Support taxonomy term page

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#16987] opened 2024-01-23 23:15 UTC
## Background
The Design team is migrating all V1 components to V3 on February 16, 2024, which means that the PW team needs to upgrade any of our products currently using V1 components to V3.

Example pages:

- [VA account and profile](https://www.va.gov/resources/va-account-and-profile/)
- [Education and training](https://www.va.gov/resources/education-and-training/)

### V1 components without V3 equivalents

1. Back to top: Currently [using v1](https://design.va.gov/components/back-to-top), which is the most up to date component

### Elements that are not using components that should be (Backlog)
1. Pagination
   - We are not using a component need to update to [v3 component](https://design.va.gov/components/pagination#examples---v3)

**Probably will be resolved with the [Resources Landing page ticket](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16986) but if not:**

1. Breadcrumbs
   - Not using any component but should be [using v3](https://design.va.gov/components/breadcrumbs#examples---v3)
2. Search input
   - We should be using [the v3](https://design.va.gov/components/search-input#examples---v3)
3. Radio buttons
   - There might be some technical limitations here, I'm not sure but if possible we should be using [v3 components](https://design.va.gov/components/form/radio-button#examples---v3)

## Documentation
[Sitewide V3 DS component review spreadsheet](https://docs.google.com/spreadsheets/d/1A7mQMnL2d5JcDKHZ2daVYQVr85qOljrwM0aUk_inO88/edit#gid=0)

### User story

**AS A** PO/PM for the PW team products, as well as for the Design team
**I WANT** all V1 components to be upgraded to V3 either before or soon after February 16, 2024
**SO THAT** all PW products are in alignment with the new components.

## Acceptance criteria

- [ ] V3 components are now used for the features listed above, and display/function correctly
- [ ] other features display correctly
- [ ] verify/review the E2E tests
- [ ]  check desktop and mobile

**Comment by laflannery** [comment] 2024-01-26 20:26
Adding Randi's notes from [a previous ticket](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14795) regarding the Pagination so when the element is updated to the component we don't lost these:
- Several templates in content-build utilize [this pagination template](https://github.com/department-of-veterans-affairs/content-build/blob/4dc5b26b912c9c14d0eb43c37e87ca9d297263f3/src/site/includes/pagination.drupal.liquid#L24C48-L24C48):
- Need to explore whether we can add unit testing for this (is it possible in CB?)

**Comment by randimays** [comment] 2024-03-01 21:09
Marking as a dupe of #17199 & #16986. This can be closed.

**Closed** 2024-03-01 21:33 UTC
Labels: VA.gov frontend, Public Websites, V3 Components
