### ISSUE TITLE
Events: make NCA Facilities VA Event locations

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#13557] opened 2023-05-01 21:58 UTC
### User story

**AS AN** Facility Editor
**I WANT** to be able to select NCA Facilities (Cemeteries, Monuments)
**SO THAT** I can select their locations from a VA facility list instead of entering the address manually.
**AND** there is a reduced chance of an address being entered with errors, which will cause a poor Veteran/other VA.gov user experience.

### Engineering notes / background

- Facilities team is responsible for pulling address data for cemeteries and VBA ROs into Drupal. Once it's there, we need to enable these facilities to be findable in the Edit Event UI.
- NCA's are draft nodes: https://prod.cms.va.gov/admin/content?title=&type=nca_facility&moderation_state=All&owner=All
- The filter won't be exposed to the event page

## Acceptance criteria

- [ ] Cemeteries are available in the entity reference search for Event location (at a VA facility)

**Comment by FranECross** [comment] 2023-12-12 19:30
@xiongjaneg Did the Facilities team Facilities complete pulling address data for cemeteries? Happy to chat about this.

**Comment by FranECross** [comment] 2023-12-12 19:39
- [ ] Front end ticket needs to be created so that there is no hyperlinks to a non-existent pages; only display the address. @FranECross

**Comment by FranECross** [comment] 2023-12-12 19:41
@FranECross to check with Dave on prioritizing this ticket.

**Comment by xiongjaneg** [comment] 2023-12-12 19:59
@FranECross It looks like it might be related to Facilities ticket #13340 but I'm going to tag in @jilladams for more info as this precedes me.

**Comment by FranECross** [comment] 2023-12-12 20:56
@jilladams @dsasser I found a Discovery ticket that this ticket wasn't linked to (that's I've linked) We can always pull that one forward and move this one back to Next Refinement if needed. Just wanted to call it to your attention. I've also added it to the Product Sync to check with Dave.

**Comment by jilladams** [comment] 2023-12-18 20:55
Closing as dupe of https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10535

**Closed by jilladams** 2023-12-18 20:55 UTC
Labels: Drupal engineering, Public Websites
