### ISSUE TITLE
Editing a page with paragraphs reports an error in the error log for every paragraph.

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#1329] opened 2020-03-25 14:58 UTC
**Describe the defect**

**To Reproduce**
1. Go to a page with a paragraph, eg /node/2/edit
2. See error 

**Expected behavior**
No errors when.

**Screenshots**
![Edit_Benefits_detail_page_VA_blind_and_low_vision_rehabilitation_services_-_EDITED___VA_gov_CMS.jpg](https://images.zenhubusercontent.com/5d6e57ad330f64311395f08b/f76af620-ced3-4ee9-976d-90ed39c7422d)

**Comment by swirtSJW** [comment] 2020-03-25 15:00
Stack trace is here 
` 
Notice: Undefined index: paragraph_type_title in Drupal\paragraphs_browser\Plugin\Field\FieldWidget\ParagraphsBrowserWidget->formElement() (line 87 of /app/docroot/modules/contrib/paragraphs_browser/src/Plugin/Field/FieldWidget/ParagraphsBrowserWidgetTrait.php) #0 /app/docroot/core/includes/bootstrap.inc(596): _drupal_error_handler_real(8, 'Undefined index...', '/app/docroot/mo...', 87, Array) #1 /app/docroot/modules/contrib/paragraphs_browser/src/Plugin/Field/FieldWidget/ParagraphsBrowserWidgetTrait.php(87): _drupal_error_handler(8, 'Undefined index...', '/app/docroot/mo...', 87, Array) #2 /app/docroot/core/lib/Drupal/Core/Field/WidgetBase.php(344): Drupal\paragraphs_browser\Plugin\Field\FieldWidget\ParagraphsBrowserWidget->formElement(Object(Drupal\entity_reference_revisions\EntityReferenceRevisionsFieldItemList), 0, Array, Array, Object(Drupal\Core\Form\FormState)) #3 /app/docroot/modules/contrib/paragraphs/src/Plugin/Field/FieldWidget/ParagraphsWidget.php(1113): Drupal\Core\Field\WidgetBase->formSingleElement(Object(Drupal\entity_reference_revisions\EntityReferenceRevisionsFieldItemList), 0, Array, Array, Object(Drupal\Core\Form\FormState)) #4 /app/docroot/modules/contrib/paragraphs_browser/src/Plugin/Field/FieldWidget/ParagraphsBrowserWidgetTrait.php(106): Drupal\paragraphs\Plugin\Field\FieldWidget\ParagraphsWidget->formMultipleElements(Object(Drupal\entity_reference_revisions\EntityReferenceRevisionsFieldItemList), Array, Object(Drupal\Core\Form\FormState)) #5 /app/docroot/core/lib/Drupal/Core/Field/WidgetBase.php(113): Drupal\paragraphs_browser\Plugin\Field\FieldWidget\ParagraphsBrowserWidget->formMultipleElements(Object(Drupal\entity_reference_revisions\EntityReferenceRevisionsFieldItemList), Array, Object(Drupal\Core\Form\FormState)) #6 /app/docroot/modules/contrib/paragraphs/src/Plugin/Field/FieldWidget/ParagraphsWidget.php(1207): Drupal\Core\Field\WidgetBase->form(Object(Drupal\entity_reference_revisions\EntityReferenceRevisionsFieldItemList), Array, Object(Drupal\Core\Form\FormState), NULL) #7 /app/docroot/core/lib/Drupal/Core/Entity/Entity/EntityFormDisplay.php(178): Drupal\paragraphs\Plugin\Field\FieldWidget\ParagraphsWidget->form(Object(Drupal\entity_reference_revisions\EntityReferenceRevisionsFieldItemList), Array, Object(Drupal\Core\Form\FormState)) #8 /app/docroot/core/lib/Drupal/Core/Entity/ContentEntityForm.php(125): Drupal\Core\Entity\Entity\EntityFormDisplay->buildForm(Object(Drupal\node\Entity\Node), Array, Object(Drupal\Core\Form\FormState)) #9 /app/docroot/core/modules/node/src/NodeForm.php(127): Drupal\Core\Entity\ContentEntityForm->form(Array, Object(Drupal\Core\Form\FormState)) #10 /app/docroot/core/lib/Drupal/Core/Entity/EntityForm.php(144): Drupal\node\NodeForm->form(Array, Object(Drupal\Core\Form\FormState)) #11 [internal function]: Drupal\Core\Entity\EntityForm->buildForm(Array, Object(Drupal\Core\Form\FormState)) #12 /app/docroot/core/lib/Drupal/Core/Form/FormBuilder.php(520): call_user_func_array(Array, Array) #13 /app/docroot/core/lib/Drupal/Core/Form/FormBuilder.php(277): Drupal\Core\Form\FormBuilder->retrieveForm('node_page_edit_...', Object(Drupal\Core\Form\FormState)) #14 /app/docroot/core/lib/Drupal/Core/Controller/FormController.php(91): Drupal\Core\Form\FormBuilder->buildForm(Object(Drupal\node\NodeForm), Object(Drupal\Core\Form\FormState)) #15 [internal function]: Drupal\Core\Controller\FormController->getContentResult(Object(Symfony\Component\HttpFoundation\Request), Object(Drupal\Core\Routing\RouteMatch)) #16 /app/docroot/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(123): call_user_func_array(Array, Array) #17 /app/docroot/core/lib/Drupal/Core/Render/Renderer.php(573): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() #18 /app/docroot/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(124): Drupal\Core\Render\Renderer->executeInRenderContext(Object(Drupal\Core\Render\RenderContext), Object(Closure)) #19 /app/docroot/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(97): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext(Array, Array) #20 /app/docroot/vendor/symfony/http-kernel/HttpKernel.php(151): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() #21 /app/docroot/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #22 /app/docroot/modules/contrib/simple_oauth/src/HttpMiddleware/BasicAuthSwap.php(67): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #23 /app/docroot/core/lib/Drupal/Core/StackMiddleware/Session.php(57): Drupal\simple_oauth\HttpMiddleware\BasicAuthSwap->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #24 /app/docroot/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(47): Drupal\Core\StackMiddleware\Session->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #25 /app/docroot/core/modules/page_cache/src/StackMiddleware/PageCache.php(106): Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #26 /app/docroot/core/modules/page_cache/src/StackMiddleware/PageCache.php(85): Drupal\page_cache\StackMiddleware\PageCache->pass(Object(Symfony\Component\HttpFoundation\Request), 1, true) #27 /app/docroot/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(47): Drupal\page_cache\StackMiddleware\PageCache->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #28 /app/docroot/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(52): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #29 /app/docroot/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #30 /app/docroot/core/lib/Drupal/Core/DrupalKernel.php(694): Stack\StackedHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #31 /app/docroot/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request)) #32 {main}.
`

**Comment by acrollet** [comment] 2020-10-19 22:52
Unable to reproduce on latest master, closing.

**Closed by acrollet** 2020-10-19 22:52 UTC
Labels: Content forms, Core Application team, Defect, Drupal engineering
