### ISSUE TITLE
[CONSIDER] Automate name change steps prior to publishing NCA 

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-cms#13998] opened 2023-06-05 14:27 UTC
### Issue description 

CONSIDER: It may be reasonable to automate the currently manual Drupal Admin step of editing the node and updating the alias to match the new facility name, lowercase with dashes, before publishing.

Relevant runbook: [Runbook - NCA Facility name change](https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/.github/ISSUE_TEMPLATE/runbook-nca-facility-name-change.md)

**Comment by davidmpickett** [comment] 2024-07-12 00:27
Closing as duplicate of #13644

**Closed by davidmpickett** 2024-07-12 00:27 UTC
