### ISSUE TITLE
Redirect Request - Combined Debt Portal - no hard timing

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-cms#11745] opened 2022-11-30 15:22 UTC
### Instructions
- Requests must be submitted **AT LEAST** 2 weeks in advance.  Some requests take a significant amount of time and coordination to implement, so start the process as soon as you know you will need one. 
- This issue will be used from initial request through implementation to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track differnt steps.
- It is your responsibility to notify VA stakeholders as appropriate.  

### Type of request
- [x] We are retiring or taking down a page and need to redirect the URL (complete redirect section)
- [ ] We are changing the URL of an existing page (complete redirect section)
- [ ] We need a custom vanity URL (complete vanity URL section)

### Implementation date
When does this request need to be live: can go out whenever it's ready, 12/15/2022 is 2 weeks from request

### Redirects 
Current URL  |  Redirect Destination or New URL
---  |  ---
`/manage-va-debt/your-debt` | `/manage-va-debt/summary/debt-balances`
`/manage-va-debt/your-debt/*` | `/manage-va-debt/summary/debt-balances`
`/health-care/pay-copay-bill/your-current-balances` | `/manage-va-debt/summary/copay-balances`
`/health-care/pay-copay-bill/your-current-balances/*` | `/manage-va-debt/summary/copay-balances`

### Vanity URLs 
Vanity URL  |  Landing page
---  |  ---
requested URL | landing page URL

**Link to campaign landing page request issue:**

### Process, Roles and Responsibilities
- [x] Requesting team: Above information is provided
- [ ] Requesting team: All appropriate VA stakeholders are notified as appropriate
- [ ] IA: Request is vetted and documented and implementation plan is clear 
- [ ] IA: Request is assigned to appropriate team for implementation 
- [ ] Implementation team: Work is complete
- [ ] Implementation team: Validated in production
- [ ] Requesting team: Validates everything is correct in production and closes ticket

**Comment by jilladams** [comment] 2022-12-09 18:04
@Dr-Pongo can you clarify: this redirect should not go out before 12/15?  Why I'm asking: the code for redirects like this deploys weekly on Wednesday mornings, so normally we would shoot to have this merged by Tuesday 12/13 EOD, so it can go out on the Wed 12/14 weekly deploy. However: if this redirect should _not_ be live _until_ 12/15, we can wait, merge after weekly deploy and request an out of band deploy on 12/15 to get it live. 

Please let us know either way.

**Comment by jilladams** [comment] 2022-12-09 18:38
@chri5tia this is in Review/QA column, but I can't find an open PR. Can you link it? Also note the timing question above re: when this should merge/deploy.

**Comment by Dr-Pongo** [comment] 2022-12-09 20:07
@jilladams this can go out whenever it's ready! I wanted to make sure you all had enough time to update as necessary!

**Comment by chri5tia** [comment] 2022-12-12 22:21
https://github.com/department-of-veterans-affairs/devops/pull/12333

**Comment by jilladams** [comment] 2022-12-12 23:07
Same here - this issue isn't listed on that PR as part of its scope.

**Comment by jilladams** [comment] 2022-12-16 22:59
4 redirects here: 

Current URL  |  Redirect Destination or New URL | Prod behavior
---  |  --- | ---
`/manage-va-debt/your-debt` | `/manage-va-debt/summary/debt-balances` | Redirect is working, but  `/manage-va-debt/summary/debt-balances` then further redirects to `/manage-va-debt`. I don't see that configured in the redirects file. @heyjoni is that known behavior / expected outcome? 
`/manage-va-debt/your-debt/*` | `/manage-va-debt/summary/debt-balances` | I can't find an example child page to verify. @heyjoni possible to help point us to one?
`/health-care/pay-copay-bill/your-current-balances` | `/manage-va-debt/summary/copay-balances` | is redirecting to `/manage-va-debt/summary/debt-balances` instead ([redirects.yml#4622](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/revproxy-vagov/vars/redirects.yml#L4622) ), which then bounces to  `/manage-va-debt`. **Reopening** and need to fix.
`/health-care/pay-copay-bill/your-current-balances/*` | `/manage-va-debt/summary/copay-balances` | Same ^ need to fix

**Comment by jilladams** [comment] 2022-12-16 23:21
Also - re: child pages, I realized we learned this with Josh on VRAPP ticket, the code change needs to look different to handle children, e.g.: https://github.com/department-of-veterans-affairs/devops/pull/12350/files. Updating my PR here to do that.

**Comment by jilladams** [comment] 2022-12-20 17:53
State in prod after PR merge yesterday: 

Current URL  |  Redirect Destination or New URL | Prod behavior
---  |  --- | ---
`/manage-va-debt/your-debt` | `/manage-va-debt/summary/debt-balances` | Redirect is working, but  `/manage-va-debt/summary/debt-balances` then further redirects to `/manage-va-debt`. I don't see that configured in the redirects file. @heyjoni is that known behavior / expected outcome? 
`/manage-va-debt/your-debt/*` | `/manage-va-debt/summary/debt-balances` | I can't find an example child page to verify. @heyjoni possible to help point us to one?
`/health-care/pay-copay-bill/your-current-balances` | `/manage-va-debt/summary/copay-balances` | Bounces to  `/health-care/pay-copay-bill/`
`/health-care/pay-copay-bill/your-current-balances/*` | `/manage-va-debt/summary/copay-balances` | Same ^


@Dr-Pongo, @heyjoni are you able to help us understand if this behavior is intended, or needs to be fixed somehow? And to identify child pages we could look at to confirm the child behavior is correct?

**Comment by mnorthuis** [comment] 2022-12-20 22:00
The URLs that are being redirected here are pages that require authentication, so if you are trying to hit those URLs while unauthenticated, they will bounce you back to the appropriate static page, that's part of the code in the app I believe.  You would have to validate these while logged into VA.gov.

**Comment by mnorthuis** [comment] 2022-12-20 22:01
Here are some child URLs to also test:
www.va.gov/manage-va-debt/your-debt/debt-detail/ 
www.va.gov/manage-va-debt/your-debt/debt-letters/
www.va.gov/health-care/pay-copay-bill/your-current-balances/balance-details/

**Comment by jilladams** [comment] 2022-12-20 22:24
Thank you so much Mikki - authed is experience is a blindspot and didn't think of that. 😬   Checked while logged into Staging as a test user, and confirmed 3/4.  

The last remaining one is mysterious: `/health-care/pay-copay-bill/your-current-balances` is still not redirecting correctly, despite being an identical code change to the manage debt parent change. 

Will need to discuss with FE folks re: necessary fix.

**Comment by Dr-Pongo** [comment] 2022-12-21 14:47
Hey @jilladams & @mnorthuis ! I'll dive into this today! I was out sick yesterday!

**Comment by jilladams** [comment] 2022-12-21 18:38
@Dr-Pongo we've sorted the question I had for you earlier. The remaining bit is a technical issue I need to work out with my team. Will update here once we've identified the fix.

**Comment by jilladams** [comment] 2022-12-22 00:05
@chri5tia reopening bc mystery in this comment is not yet resolved / redirecting correctly: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11745#issuecomment-1360396005

**Comment by chri5tia** [comment] 2022-12-22 20:37
Anything going to /manage-va-debt/* is redirecting back to va.gov/manage-va-debt/. Still investigating. None of the references to `manage-va-debt/` seem to be causing this unless it's the code in question.

```
# November 30, 2022: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11745
  - src: ^/manage-va-debt/your-debt/
    dest: /manage-va-debt/summary/debt-balances
    matcher: '~*'
  - src: ^/health-care/pay-copay-bill/your-current-balances/
    dest: /manage-va-debt/summary/copay-balances
    matcher: '~*'
```

Other code:

```
  # March 15, 2021: https://github.com/department-of-veterans-affairs/va.gov-team/issues/21229
  # Redirect /manage-va-debt/request-debt-help-form-5655/introduction to /manage-va-debt/request-debt-help-form-5655 for Financial Status Report Application
  - src: /manage-va-debt/request-debt-help-form-5655/introduction
    dest: /manage-va-debt/request-debt-help-form-5655
    rewrite: permanent
```

```
  # September 30, 2021: https://github.com/department-of-veterans-affairs/va.gov-team/issues/19908
  - src: ^/debtman/(.*)
    dest: /manage-va-debt/
    matcher: '~*'
```

**Comment by chri5tia** [comment] 2022-12-22 20:41
```
Status Code	URL	IP	Page Type	Redirect Type	Redirect URL	
301	https://va.gov/manage-va-debt/your-debt/	2600:8010:0:28::28:221	server_redirect	permanent	https://www.va.gov/manage-va-debt/your-debt/
301	https://www.va.gov/manage-va-debt/your-debt/	152.131.96.221	server_redirect	permanent	https://www.va.gov/manage-va-debt/summary/debt-balances
200	https://www.va.gov/manage-va-debt/summary/debt-balances	2600:8030:0:28::30:221	client_redirect	javascript	https://www.va.gov/manage-va-debt/
200	https://www.va.gov/manage-va-debt/	2600:8030:0:28::30:221	normal	none	none
```

**Comment by ryguyk** [comment] 2022-12-22 21:07
@chri5tia's comments above highlight exactly what should be happening per the [comment by Mikki above](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11745#issuecomment-1360376843).

**Comment by ryguyk** [comment] 2022-12-24 13:40
There's been a lot of discussion and runaround regarding why these two configurations are not behaving similarly:
```
  - src: ^/manage-va-debt/your-debt/
    dest: /manage-va-debt/summary/debt-balances
    matcher: '~*'
```
```
  - src: ^/health-care/pay-copay-bill/your-current-balances/
    dest: /manage-va-debt/summary/copay-balances
    matcher: '~*'
```

Specifically, when a user navigates to the route in question _without_ a trailing slash, the first redirect still takes effect while the second does not.

### This is why
- `src: ^/manage-va-debt/your-debt/`
    - This is the "standard" behavior. When a user navigates to `va.gov/manage-va-debt/your-debt`, nginx sees the path without a trailing slash and redirects to the path _with_ a trailing slash. Again, this is standard behavior and will be the case unless something else is at play (spoiler: something else is at play in the next one below). After the request is redirected to the path _with_ the trailing slash, that path now matches the `src` regex, so that request is then redirected to the `dest`.
- `src: ^/health-care/pay-copay-bill/your-current-balances/`
    - In this case, what's at play is [this line in react_routes.yml](https://github.com/department-of-veterans-affairs/devops/blob/c648e08c1ad1479b0c4018adc99241bf400d37bd/ansible/deployment/config/revproxy-vagov/vars/react_routes.yml#L133). This file effectively tells nginx to not take the standard behavior mentioned above on certain routes. This allows a React app to handle its own routing properly on the client side. So, in this particular case, when a user navigates to `va.gov/health-care/pay-copay-bill/your-current-balances` _without_ a trailing slash, **there is no redirect to the path _with_ a trailing slash**. Since that redirect doesn't happen, and since the `src` regex in question defines an explicit trailing slash, **the redirect configured here to the `dest` `/manage-va-debt/summary/copay-balances` does not take place**.

**Comment by jilladams** [comment] 2022-12-27 17:23
@chri5tia with Ryan's note above in mind, it's probably not worth pursuing the OOB deploy, is my guess. Since those notes imply react app specifics, I would probably suggest we reassign to a FE eng, but wanna take a look at the notes here and confirm that either way?

**Comment by jilladams** [comment] 2022-12-27 17:39
And actually: We may want to punt this back to the Debt team, if the routing for the remaining redirect does need to be handled within the application. 

Code owners of app/medical-copays ([codeowner file](https://github.com/department-of-veterans-affairs/vets-website/blob/main/.github/CODEOWNERS#L67))= [@department-of-veterans-affairs/vsa-debt-frontend ](https://github.com/orgs/department-of-veterans-affairs/teams/vsa-debt-frontend). Members = 
* @Dr-Pongo 
* @ScottyRJames 
* @OptionSelect 


@Dr-Pongo I see that Craig Wheeler was a main contributor to the [app file where routes are configured](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/medical-copays/routes.jsx) but he is now deactivated. Do you have thoughts about best way to proceed, given Ryan's notes above?

**Comment by Dr-Pongo** [comment] 2022-12-27 17:46
@jilladams Catching up on this now! I'll touch base with any questions!

**Comment by Dr-Pongo** [comment] 2022-12-28 14:26
[Updating thread with PR](https://github.com/department-of-veterans-affairs/devops/pull/12403) for removing `medical-copay` and `debt-letters` from react routes so other routing can take effect.

**Comment by jilladams** [comment] 2023-01-03 19:16
Moving to PO Review to reflect that code is merged and needs to be verified in Prod after deploy tomorrow for the final item here.

**Comment by jilladams** [comment] 2023-01-05 21:45
With a test user, I'm able to login into Staging and verified that the final missing case here is now correctly redirecting: 

Parent without trailing slash: **does** redirect - https://staging.va.gov/health-care/pay-copay-bill/your-current-balances resolves to /manage-va-debt/summary/copay-balances.

Closing!

**Closed by jilladams** 2023-01-05 21:45 UTC
Labels: VA.gov frontend, ⭐️ Public Websites, Sitewide IA
