### ISSUE TITLE
Lovell: "Manage your health online" section should not be showing on TRICARE

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#12686] opened 2023-02-20 21:40 UTC
## Description
While I was doing the final staging review for the Collab cycle I was told that the "Manage your health care" section that displays on the main VAMC system page was intentionally removed from TRICARE.  However, I cam seeing it here:
![image](https://user-images.githubusercontent.com/106678594/220202095-5f0a9669-341d-4082-a82f-18151335245b.png)

Can you confirm if this is correct or not? I will need to update the accessibility artifact either way.

## Acceptance Criteria
- [ ] Determine if this is correct behavior or not
- [ ] Remove "Manage your health care" section if it should not be there

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [x] `Facilities`
- [ ] `User support`

**Comment by laflannery** [comment] 2023-02-20 21:51
@Dottisea Tagging you for visibility

**Comment by Dottisea** [comment] 2023-02-23 17:18
See #12685

**Comment by Dottisea** [comment] 2023-02-23 17:22
Pulling in to Sprint 78 as potentially launch blocking

**Comment by JayDarnell** [comment] 2023-02-24 19:41
I suspect this is a regression due to the name change.

**Comment by ryguyk** [comment] 2023-02-28 00:24
Closing in favor of https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12776. This problem exists only because of the problem outlined in https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12776.

**Closed by ryguyk** 2023-02-28 00:24 UTC
Labels: Facilities, VA Lovell
