### ISSUE TITLE
Events detail page: Add to calendar for future recurrences creates a loop, cannot add to cal for dates beyond next upcoming recurrence

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#9476] opened 2022-06-15 18:18 UTC
## Describe the defect
On event detail pages with recurrence, "View other times for this event" panel displays all recurrences' date/time, and an Add to calendar link. The Add to Calendar link on each recurrence points to the Event node page, so is effectively just a page reload. (Recurrences do not each have their own page - you cannot effectively link to a single recurrence.)

The Add to Calendar link at page top will always be date and time of the next upcoming recurrence. So there is currently no way for a user to add a future recurrence to calendar.
 
Screen record of the loop: 
https://www.loom.com/share/7097cae76bd94484baa6d7b2217db375

https://staging.va.gov/minneapolis-health-care/events/42754/

## To Reproduce
1. Go to an event with recurrence: https://staging.va.gov/minneapolis-health-care/events/42754/
2. Click on recurrence pane, to expand
3. Click Add to calendar on a future recurrence
4. Observe page reload at the same uRL
5. Click Add to calendar at page top, download .ics
6. Import into calendar and observe the date and time are for the next upcoming recurrence, not the future recurrence you selected in step 3

## Expected behavior
Add to calendar link on each recurrence should act like the Add to calendar link top of page, and download an ICS file for that recurrence's date/time. If this is a bad idea for Reasons, please surface in ticket comments here and we can sync with design / PM about a reasonable path forward.

## Screenshots
![Screen Shot 2022-06-15 at 11 09 57 AM](https://user-images.githubusercontent.com/85581471/173896004-e8e243cf-4550-49b0-ab2a-2775612ac166.png)

## Additional context
Note that currently this recurrences panel appears on Staging, but not on Prod, due to https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9450.

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS workstream (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [X] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by wesrowe** [comment] 2022-06-16 16:49
We injected this into the sprint since it's Vet-facing and Claudio had capacity. Aslan approved the user experience. The solution was estimated at 3 points, so it's possible this will get merged by the end of sprint.

**Comment by kind-claudio** [comment] 2022-06-17 22:39
I haven't started this yet - I've been making updates to the PR for #9075 per platform feedback.

**Comment by kind-claudio** [comment] 2022-06-21 20:31
* Resolved the issue - All recurring events' links will now trigger a download of an ICS file upon clicking a link.
* Discovered a new issue where these downloaded ICS files are missing all event meta-data, rendering the files useless.
   * I'd speculate that the issue is w/ the CMS content - markup looks to be connected to the content, but not receiving any values from the CMS. The supporting markup for each add-to-calendar link for the templates, "social-share" vs "events", are shown below:

**Social Share**
```
<a
  data-description="{{ fieldDescription }}"
  data-end="{{ mostRecentDate.endValue }}"
  data-location="{{ fieldAddress.addressLine1 }} {{ fieldAddress.locality }}, {{ fieldAddress.administrativeArea }}"
  data-start="{{ mostRecentDate.value }}"
  data-subject="{{ title }}"
  href="{{ entityUrl.path }}"
  id="add-to-calendar-link"
>
  <i class="va-c-social-icon fas fa-calendar-check vads-u-margin-right--0p5" aria-hidden="true" role="presentation"></i>
  Add to Calendar
</a>
```
**Events**
```
<a
  class="recurring-event "
  data-description="{{ fieldDescription }}"
  data-end="{{ recurringEventDatetimeRangeTimezone.endValue }}"
  data-location="{{ fieldAddress.addressLine1 }} {{ fieldAddress.locality }}, {{ fieldAddress.administrativeArea }}"
  data-start="{{ recurringEventDatetimeRangeTimezone.value }}"
  data-subject="{{ title }}"
  href="{{ entityUrl.path }}"
  rel="noreferrer noopener"
  style="max-width: 140px;"
>
```

**Comment by allisonlu** [comment] 2022-06-30 20:19
Claudio's draft PR opened for review on `vets-website`: https://github.com/department-of-veterans-affairs/vets-website/pull/21471

**Comment by dsasser** [comment] 2022-07-12 18:51
This issue is now visible on prod: https://www.va.gov/central-western-massachusetts-health-care/events/47020/

**Comment by ryguyk** [comment] 2022-07-13 19:22
Claudio's solution looks very good. Some quality engineering. Merged PR and closing this ticket.

**Closed by ryguyk** 2022-07-13 19:22 UTC
Labels: Defect, VA.gov frontend, ⭐️ Public Websites

**Comment by jilladams** [comment] 2022-07-14 19:34
verified in Prod!
