### ISSUE TITLE
[V1 & 3 Components] Implement available components for Global Search Results

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#17176] opened 2024-02-09 00:12 UTC
### Status
**[2024-09-13]** DST blocking defect is resolved.
**[2024-08-19] [Fran]** DST defect is blocking the completion of this ticket: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3117
**[2024-07-18]** Note that the majority of the work has already been completed, so this won't be a '5' when pulled in. 
**[2024-07-16]** Unblocked. Moving to the Ready column.
**[2024-07-11]** Actually still blocked (info from Randi.) The code changes on DST's side have been merged, but they have not done a release for the component-library (and thus we won't be able to pull it in).
**[2024-07-08]** This appears to be unblocked.
**[2024-05-30]** Still blocked by DST ticket in progress [Bug - va-search-input suggestion box doesn't close #2795](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2795)
**[2024-05-21]**  Still blocked by DST ticket in progress [Bug - va-search-input suggestion box doesn't close #2795](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2795)
**[2024-05-15]**  Still blocked by DST ticket in progress [Bug - va-search-input suggestion box doesn't close #2795](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2795)
**[2024-05-07]** Blocked by DST ticket  [Bug - va-search-input suggestion box doesn't close #2795](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2795)

## Description

The Design team is releasing a Typography update (sometime in March) which means that the PW team needs to upgrade any of our products where components aren't currently being using, but a V1 or V3  component is available.

If the updates aren't made prior to the Typography update, there's a chance that Veteran-facing issues may occur.

[Search results](https://www.va.gov/search/)

## V3 Component that needs to be adjusted
1. The pagination is already using V3 (it was updated in Jan). However, I noticed a couple things that should be updated to improve this experience:
   - The `maxpagelistlength` is not formatted properly and is missing the dashes. It should be `max-page-list-length`
   - Also, the max pages is set to 5, however I think this should be increased to 7 because when you are on page 5 or above, you can only choose "Next" to go to the next page, there isn't an actual page number to choose. If you change this to 7 it will add the number before and after the active page.

## Elements that are not using components that should be
1. Link: We should be using the component wherever possible
2. Search Input: We should be using [the v3](https://design.va.gov/components/search-input#examples---v3)

Info from #17050 

### User story

**AS A** PO/PM for Public Websites products
**I WANT** to implement available V1 or V3 components in features & products currently under Public Websites management where components aren't currently being used
**SO THAT** all PW products are in alignment with the current component version
**AND** Veterans and other users have a consistent experience throughout VA.gov tools and information

## Acceptance criteria
- [x] Links are using V1 component
- [x] Search input is using V3 component
- [x] Pagination is adjusted
- [x] other features display correctly
- [x] verify/review the E2E tests
- [x] check desktop and mobile
- [ ] make sure all instances of `<i>` are removed with transition to web components
- [ ] a11y review

**Comment by jilladams** [comment] 2024-03-21 15:44
Very high gateway latency slowing down ability to work locally. Randi has escalated.

**Comment by randimays** [comment] 2024-03-26 13:57
End-of-sprint update: This will likely carry over. I believe the work is completed, but I have a bug or two to work out and need to address tests. Plus, CI has been a hurdle so it's unlikely this will get reviewed and merged today.

**Comment by randimays** [comment] 2024-03-28 17:04
Update here: this is taking longer than anticipated to upgrade to the search v3 component. This also requires splitting out the original search component as it is shared in a couple places in the global header.

**Comment by randimays** [comment] 2024-04-03 21:38
Update: This wrapped up a couple days ago, but we are against some strong headwinds with environments (review instances, Tugboat and ngrok not working). I've asked Chris and Eli to review locally, and we got Laura set up to run code locally so we can power through when the weather is brutal ✊🏻 Hoping this will be able to merge tomorrow.

**Comment by randimays** [comment] 2024-04-04 18:00
We are blocked on merging this due to a search typeahead web component issue ([Slack thread for context](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2676)). A bug has been filed with DST: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2676 so we'll be blocked on merging this (as it does break functionality) until they can release a fix.

**Comment by randimays** [comment] 2024-04-08 14:41
Putting into Blocked again. DST made a suggestion about how we could work around our typeahead blocker here: https://dsva.slack.com/archives/C01DBGX4P45/p1712343314348409?thread_ts=1712227557.801769&cid=C01DBGX4P45. In short, the suggestion was to leave the search field empty when entering the search results page with a search term.

This solution (while it may have worked temporarily while they fix the typeahead behavior) is an anti-pattern for how search results traditionally work and would not be a good experience for the user. 

We also cannot **only** apply this behavior this when the page is loaded with a search term (such as when the global header is used to search). Because of the way the page works, the search term would never appear in the input.

We're going to need to wait until DST can address this issue in order to get this merged in.

**Comment by randimays** [comment] 2024-04-08 15:17
DST update: their defect ticket (https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2676) will be picked up this coming Thursday at the beginning of their next sprint.

**Comment by jilladams** [comment] 2024-04-08 18:48
(FYI: That's in exchange for pushing work on the va-link component out by a sprint, @laflannery )

**Comment by randimays** [comment] 2024-04-18 20:28
Added an AC to make sure all instances of `<i>` are removed when we merge this in.

**Comment by randimays** [comment] 2024-04-22 22:53
Confirmed with Alex Taker today that the fix was merged last week, but DST has not done a release yet. Alex said he will make sure they do one tomorrow, which **should** unblock this ticket.

**Comment by randimays** [comment] 2024-04-25 13:31
Moving this ticket to Review/QA. The fix has been released and it seems to be working in my review instance!

**Comment by randimays** [comment] 2024-05-02 15:28
Typeahead web component still has issues. I've reported to DST. Moving this back to Blocked.

Slack thread: https://dsva.slack.com/archives/C01DBGX4P45/p1714663661141389?thread_ts=1714054912.852109&cid=C01DBGX4P45

**Comment by randimays** [comment] 2024-07-11 20:15
@FranECross @Agile6MSkinner This is still blocked. The code changes on DST's side have been merged, but they have not done a release for the component-library (and thus we won't be able to pull it in).

**Comment by randimays** [comment] 2024-07-16 17:11
@FranECross @Agile6MSkinner This ticket is now unblocked; DST has done the component-library release and pulled the new code into vets-website.

**Comment by FranECross** [comment] 2024-07-16 17:14
@randimays Excellent! Since it's pointed, I'll move it to the Ready column amidst the other component tickets. Thanks for pinging us!

**Comment by randimays** [comment] 2024-07-24 20:16
Putting down temporarily while we get the injected header/footer code merged. If that deploy is successful, I can modify the code I've written for this already to use web components for the search input in the header 🥳

**Comment by randimays** [comment] 2024-08-01 14:36
I discovered a defect in the `va-search-input` web component that already exists in production in Find Forms. Slack thread: https://dsva.slack.com/archives/C01DBGX4P45/p1722438937787339

This defect is blocking the completion of this ticket unfortunately, especially seeing as how the search API can be so fragile; we definitely don't want to be calling it more times than necessary. Hopefully we can get some eyes on it soon: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3117

**Comment by randimays** [comment] 2024-09-13 16:20
The [DST defect](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3117) has been resolved and a new release was put out. When possible, we can come back to this and see if it's fixed.

**Comment by jilladams** [comment] 2024-09-13 20:22
Added a status note to ticket body and moved back to Ready.

**Comment by randimays** [comment] 2024-10-10 10:01
Confirmed in Find Forms in production and Search in the local branch that the DST defect (search API being called twice when Enter key is used to submit) has been resolved 🥳

**Comment by jilladams** [comment] 2024-10-15 20:22
@chriskim2311 I'm not finding the related PR, to see if this has deployed. Are you able to help point me to that, and/or to verify if the last 2 ACs here are complete?

**Comment by chriskim2311** [comment] 2024-10-15 20:45
@jilladams This PR is for both this ticket and #11513. https://github.com/department-of-veterans-affairs/vets-website/pull/28812. PR merged today

**Comment by randimays** [comment] 2024-10-17 14:39
Successfully verified in production on desktop and mobile. Closing as complete! Thanks for the assist @chriskim2311!! 👏🏻

**Closed by randimays** 2024-10-17 14:39 UTC
Labels: VA.gov frontend, Public Websites, sitewide, V3 Components
