### ISSUE TITLE
VAMC System Police page: update hook or script to generate and place pages

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#16034] opened 2023-11-07 17:21 UTC
## Description or Additional Context 
For the VAMC System Police pages, we will need an update hook or script to run to generate 140 pages and put them in the right spots in the menu.

## Acceptance Criteria
- [ ] Testable_Outcome_X
- [ ] Testable_Outcome_Y
- [ ] Testable_Outcome_Z
- [ ] Requires design review
- [ ] Requires accessibility review

## Team
Please check the team(s) that will do this work.

- [ ] CMS Team
- [ ] Public Websites
- [x] Facilities
- [ ] Accelerated Publishing

**Comment by swirtSJW** [comment] 2023-11-14 18:35
Closing this as a duplicate of #15715

**Closed by swirtSJW** 2023-11-14 18:35 UTC
Labels: VAMC, Drupal engineering, Facilities, Needs refining
