### ISSUE TITLE
Document VAMC System creation

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#14559] opened 2023-07-28 15:22 UTC
## Description

In the beginning, there were VAMC systems, migrated into Drupal. We built a migration to create a new VAMC system node, but the menus,  are hand built. 

This is undocumented, we want to fix it. 

https://prod.cms.va.gov/admin/structure/types/manage/health_care_region_page/document is a reference. 

## ACs

- [ ] The basics of VAMC System node and collateral pieces of content is documented in Github https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/facilities/medical-centers/system-creation (new path)
    - [ ] Docs explain the need for Drupal admin user, and engineering support
    - [ ] Docs can point to https://prod.cms.va.gov/admin/structure/types/manage/health_care_region_page/document as single source of truth for steps
    - [ ] If a System runbook is appropriate, create one.

**Comment by jilladams** [comment] 2023-07-28 15:24
(The epic I put this in is weird, but is grouped for "we could do this when we worry about editorial UX")

**Comment by davidmpickett** [comment] 2024-08-14 20:04
With Manilla coming up, this is once again documentation that would be helpful. @jilladams The github link above is broken and I couldn't locate new location with basic browsing/searching, any ideas?

**Comment by jilladams** [comment] 2024-08-14 21:53
Working link is https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/facilities/medical-centers, and Past Jill proposed adding a new directory at `system-creation` to house the docs that will emerge from this ticket.

However: what Past Jill didn't know is that Nearer Past Jill changed the structure of our docs, and it generally prob doesn't make sense to house this info in that area anymore anyway -- it should almost certainly be a runbook. Michelle created a ticket to start a "New system" runbook: #15264. I think that's the right thing to do, and place to do it. 

I can work on jiving the details from this ticket into that one / closing this ticket tomorrow, unless you wanna go for it.

**Comment by davidmpickett** [comment] 2024-08-15 16:37
Closing as duplicate of https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15264

**Closed by davidmpickett** 2024-08-15 16:37 UTC
Labels: VAMC, Drupal engineering, Facilities, Needs refining, Documentation, sitewide, VA Manila
