### ISSUE TITLE
Content admins also need content_publisher to access important admin pages. 

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#1444] opened 2020-04-10 18:44 UTC
**Describe the defect**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information if relevant, or delete):**

**Additional context**

## Labels
- [/] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [/] CMS objective (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

**Comment by oksana-c** [comment] 2020-12-30 13:06
Defect was open in April. We haven't had any support requests related to this issue. Closing. @kevwalsh please reopen if you have more context on this and the issue is still relevant.

**Closed by oksana-c** 2020-12-30 13:06 UTC
Labels: Defect
