### ISSUE TITLE
FE some va-accordion-item instances do not support auto-open when referenced with a fragment

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#11354] opened 2022-10-26 22:18 UTC
## Describe the defect
[CMS support thread](https://dsva.slack.com/archives/CDHBKAL9W/p1666800192774649)

When linking with a fragment in the url, page loads and jumps to the accordion's id, but does not open it like it should

Working example  https://design.va.gov/components/accordion#checklist-code-assets   jumps to and opens the checklist-code-assets accordion.

~~Broken~~ Working example from preview server http://preview-prod.vfs.va.gov/preview?nodeId=488#what-if-i-dont-get-my-vhic-in--111295
 - EDIT: today (1/20/23) this one works

Broken example from VA.gov 
https://www.va.gov/resources/the-pact-act-and-your-va-benefits/#how-do-i-know-if-i-have-a-pres doesn't work  

Largely it seems to be an id problem
There is no id on the va-accordion-item
![image](https://user-images.githubusercontent.com/5752113/198149191-092042fb-0370-42a4-ab06-aecace643e00.png)

Example of one being implemented correctly that works to open when hit with a fragment.
https://www.va.gov/salt-lake-city-health-care/programs/horses-helping-veterans/#equine-assisted-psychotherapy-101790

### Implementation details

Per Josh: 
>The Pact act example uses the faq_multiple template at src/site/layouts/faq_multiple_q_a.drupal.liquid which doesnt assign an id in the same way the collapsible_panel template does in the horses example. First step will be checking all templates that use the va-accordion component to see if they assign ID. Second step, add them if they are missing (something like id="{{item.fieldTitle | hashReference: 30 }}-{{id}}". This could presumably be one ticket

## AC / Expected behavior
- [x] Audit codebase for templates that render accordions, note which do not have `id`s
- [x] All templates from audit open when url includes the appropriate fragment

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by wesrowe** [comment] 2023-01-24 18:22
@jtmst, I'm assigning this to you for pre-refinement. My suspicion is that this should be a spike ticket. Along the lines of "Spike: identify templates with accordions that don't auto-open correctly when linked."

**Comment by jtmst** [comment] 2023-01-24 18:41
@wesrowe The Pact act example uses the faq_multiple template at `src/site/layouts/faq_multiple_q_a.drupal.liquid` which doesnt assign an id in the same way the collapsible_panel template does in the horses example.  First step will be checking all templates that use the va-accordion component to see if they assign ID.  Second step,  add them if they are missing (something like `id="{{item.fieldTitle | hashReference: 30 }}-{{id}}"`.  This could presumably be one ticket

**Comment by randimays** [comment] 2023-07-31 23:22
Seems some design system things may have changed since earlier this year. The "Working" links from above aren't actually working. The page scrolls to the desired accordion and the `+` is changed to a `-` but it doesn't reveal the content. I [dropped a message](https://dsva.slack.com/archives/C01DBGX4P45/p1690845611312089) to the platform design team.

**Comment by randimays** [comment] 2023-08-01 15:17
I [filed an issue](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1963) with the Design System team. The accordions are missing the `open` property when they are deep-linked and this needs to be fixed on their side. We still need to adjust the IDs but won't be able to complete this until their bug is addressed.

**Comment by jilladams** [comment] 2023-08-03 15:43
Re: whether we make changes on behalf of Facilities: in general, it is probably best to ticket the Facilities team instead for awareness and link to our PR(s) so they can manage testing things like Lovell to ensure no regressions, etc.

**Comment by randimays** [comment] 2023-08-10 14:17
Confirmed this is working in production for the following URLs:

- http://preview-prod.vfs.va.gov/preview?nodeId=488#what-if-i-dont-get-my-vhic-in--111295
- https://www.va.gov/resources/the-pact-act-and-your-va-benefits/#how-do-i-know-if-i-have-a-pres
- https://www.va.gov/salt-lake-city-health-care/programs/horses-helping-veterans/#equine-assisted-psychotherapy-101790
- https://www.va.gov/south-texas-health-care/locations/north-central-federal-va-clinic/#pharmacy

**Closed by randimays** 2023-08-10 14:17 UTC
Labels: Defect, VA.gov frontend, Public Websites
