### ISSUE TITLE
SPIKE: Draft content on certain pages is publishing to production 

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-cms#19535] opened 2024-10-17 22:14 UTC
# Description
Draft content should not be available in Production. The content team regularly edits a node and leaves it in draft while working with stakeholders on messaging, accuracy, and plain language style issues. We've discovered that edits that are sitting in draft are getting published into production (VA.gov) when we aren't ready for that to happen. The draft content was still labelled as draft in Drupal CMS. 

## Example 1: SkillsBuild 
This issue was discovered yesterday (10/17/2024). 

Recent example: A team member had added a placeholder action link to this unpublished About page and @bethpottsVADEPO reported that the action link was showing up in search on production: https://www.va.gov/find-forms/?q=skillsbuild 

Background on this example: A form available in the API automatically generates an About page which is held in Draft. The form becomes findable in Search, even if the About page is not published. In this case, the About page had never been published, and the edit that had been made and was still in draft somehow published. The CMS did not show it as "published"--it was still in "draft." And the last updated date didn't change. So this is a silent publishing problem.

Here's the record of the first draft change:
10/15/2024 - 9:40 am by anthony.procik…
Updated to include new IBM SkillsBuild benefit detail page and a placeholder for the online form flow--don't publish this (Draft)

We don't know when this showed up on production, but we noticed it two days later.

Then Beth removed the link but didn't publish. It was saved as draft. Here's the record of this: 
10/17/2024 - 11:56 pm by beth.potts@va.gov
Removing the online form option that was linking to 5490. (Draft)

When we looked the morning of 10/18 it was no longer showing in search so the change went to prod without a content team member manually publishing.

A couple days ago, a team member put a placeholder link into a draft page. A couple days later, I noticed that pages was showing up in search. When a form gets created in the forms database, a draft about page was created in draft. Then we discovered that the the draft action link was showing up in search. Beth went back removed the link, but left it in draft for CMS. This morning, that draft changes were published. This content was still labeled as draft. 

### Root cause
* https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19545

## Example 2: Burials and Memorials
This issue was discovered this morning (10/18/2024). 

Second example: @RLHecht changed the YouTube link in the right rail of the [burials and memorials hub landing page](https://www.va.gov/burials-memorials/) and saved as a draft. This was done in a [separate node](https://prod.cms.va.gov/node/38441/edit) from the hub landing page. This change wound up on prod but the last updated date on the bottom of the page is showing June 10,2024. And in Drupal the node is still showing as draft. 

~~Same thing with burials. Changed the content with the burials page, left in draft, but that is published this morning. This content was still labeled as draft.~~ Burials hub page core content is still in draft and has not been published; the Youtube Link from the referenced NCA node is in draft and is published on www.va.gov at this time.

### Root cause
* https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19544

## Example 3: Secure Sign In Changes 
URL: [www.va.gov/sign-in-changes](http://www.va.gov/sign-in-changes)

Danielle Theirry reported that draft promos were incorrectly published to VA.gov a few weeks ago. TBD on the timing of when she added the draft promos when the draft promos were incorrectly published to the page. 

### Root cause
* https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19544

## Example 3: Secure Sign In Changes 
Per  Danielle Theirry: 
> This page's draft change in the first promo under "What you can do" did roll out to production last night despite being saved as draft:
https://www.va.gov/initiatives/prepare-for-vas-secure-sign-in-changes/ 

### User story
Veterans come to VA.gov expecting accurate, useful, timely information to help them get and manage their benefits. When content publishes before we're ready to release information, it might lead to inaccuracies on our site, degrade the trust our partners have in our careful content management, and ultimately cause harm to Veterans and impact their trust in VA.

**AS A** Content creator or editor
**I WANT** to know that Draft content will not be available in Production
**SO THAT** I can ensure that only complete and accurate information will be available to Veterans

### Engineering notes / background
Identified problems:
Draft content has been incorrectly published to VA.gov. The only identified instances of this situation have been when drafts are saved the day before and then getting published the next morning. 
The draft content that has been incorrectly published to VA.gov is still labeled as draft in Drupal CMS. 

### Scope / Impact analysis
_What, if anything, could break as a result of this change?_
_Engineer should assess this when approaching PR._

## Acceptance criteria
- [x] Understand the scope of draft content that was published to VA.gov from Drupal CMS. 
- [x] Understand the root cause of why draft content was incorrectly published to VA.gov from Drupal CMS.
- [x] A plan of action is created to address the issue of draft content being incorrectly published to VA.gov from Drupal CMS. 
- [ ] Content in Draft (not published) should not be visible/available to users in VA.gov

**Comment by jilladams** [comment] 2024-10-18 15:57
@edmund-dunn @timcosgrove I had wondered if this is something we might need to be controlling on the FE, to query only for Published items. If you find that its' a FE publishing thing in our templates, and that you need Public Websites support, please let us know. 

cc @FranECross

**Comment by gracekretschmer-metrostar** [comment] 2024-10-18 19:37
Example #2 Burials and Memorials and Example #3 Secure Sign: the root cause has been identified and the solution has been ticketed here: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19544

Sitewide team will own implementing the fix.

**Comment by jilladams** [comment] 2024-10-19 00:46
All 3 identified issues now have tracking tickets for follow up, which Sitewide will handle.

From what Tim has noted in those tickets, in all of these cases, Drupal didn't do anything wrong, and the issue is occurring downstream in the queries we make (whether that's in vets-api or graphQL FE code). Guaranteeing that no Draft content is visible on prod will have to be a process of auditing FE code and GraphQL queries to ensure we are only ever pulling Published items. 

I created an epic to look at the bigger picture, and we'll need to discuss on Sitewide (the only team that's practically pulling Drupal data through to the FE at this point) how to go about that bigger picture audit. 

I think CMS team can close this ticket, once @mmiddaugh has a chance to review and align with that thinking, as the final AC will not be fully doable in the context of this ticket.

**Comment by jilladams** [comment] 2024-11-13 18:12
Closing with Erika's ok.

**Closed by jilladams** 2024-11-13 18:12 UTC
Labels: Defect, Find a form, Public Websites, sitewide, current sprint, ghp-sprint
