### ISSUE TITLE
SPIKE: Make it possible to archive a facility

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#4849] opened 2021-03-29 04:47 UTC
**Describe the defect**
When archiving /salt-lake-city-health-care/locations/cache-valley-va-clinic (a clinic that is not yet in operation), broken links were created. 

How might we make it easier to archive intereleated content? 

**To Reproduce**
1. On a tugboat environment, as user Victor.A.MCtest (a content publisher with access to all VAMC facilities), go to /salt-lake-city-health-care/locations/cache-valley-va-clinic
2. Edit and archive it. 
3. Watch the content release fail. 

**Expected behavior**
I should be able to archive a facility without creating broken links.

**Comment by swirtSJW** [comment] 2021-04-19 18:57
The above broken link for "Cache Valley VA Clinic" is due to the facility appearing in a list of services
![image](https://user-images.githubusercontent.com/5752113/115288141-16973b00-a11f-11eb-81e9-0ff8293ff18f.png)

There are two entangled issues here.
1. The front end it outputing links to pages that are not published. (which may not be detectable due to #2)
2. The front end is getting bad information because the services assigned to a facility are not getting unpublished/archived when the associated facility is being archived. 

On the front end side

**Comment by swirtSJW** [comment] 2021-04-20 13:59
This spike has resulted in  https://github.com/department-of-veterans-affairs/va.gov-cms/issues/5072

**Comment by swirtSJW** [comment] 2021-04-20 14:20
Even after unpublishing the service (primary care) assigned to Cache Valley, it is still being rendered in the html output so this confirms this is also caused by a FE issue where the query is not properly filtering to "published" content only.
![image](https://user-images.githubusercontent.com/5752113/115412008-f8cee200-a1c1-11eb-824f-1322cb7551ac.png)

**Comment by swirtSJW** [comment] 2021-04-20 14:28
The front end issue is actually covered by these three issues in vagov team:
- events https://github.com/department-of-veterans-affairs/va.gov-team/issues/23256
- services  https://github.com/department-of-veterans-affairs/va.gov-team/issues/23470
- other https://github.com/department-of-veterans-affairs/va.gov-team/issues/23481

**Comment by swirtSJW** [comment] 2021-04-20 14:29
@kevwalsh I am suggesting that this spike is complete.  If you agree, lets call it done.

**Closed** 2021-04-23 12:05 UTC
Labels: Defect, Editorial workflow, Needs refining, Product Support Team, VAMC system
