### ISSUE TITLE
"Connect with us" block front end refactoring

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#2042] opened 2020-06-15 18:43 UTC
### AC

- [ ] Refactor FE template for Benefits Hub Landing Pages and query to pull the social media media fields out of the Office entity ref
- [ ] Refactor FE template for CLP and query to pull the social media media fields out of the Office entity ref
- [ ] Social media links from unpublished office nodes should still be displayed, despite them being unpublished.

**Comment by kelsonic** [comment] 2021-11-23 15:58
Duplicate of https://github.com/department-of-veterans-affairs/va.gov-team/issues/33176

**Closed** 2021-12-01 20:48 UTC
Labels: vsa-public-websites, Needs refining, Sitewide CMS Team
