### ISSUE TITLE
Content Audit: "address_2" in Sandy's DB

### ISSUE THREAD

**Issue by Agile6MSkinner** [department-of-veterans-affairs/va.gov-cms#19378] opened 2024-10-01 23:48 UTC
## Background
The Google directions link is failing to find directions for some facilities that have data in Line 2 of the address. The assumption is that this results from data passed in "address_2" that contain certain special characters (which ones is currently unknown). In order to test, scope and evaluate possible solutions, we need to know the volume of special characters in in "address_2" in Sandy's DB.

[Slack Thread](https://dsva.slack.com/archives/C0FQSS30V/p1727788566683409)

## Acceptance Criteria

- Determine number of locations that use "address_2"
- List of locations that have "&" in "address_2"
- List of locations that have "-" in "address_2"
- List of Locations that have "," in "address_2"

(Refinement note: it would save time to independently validate which of these characters causes the issue before pulling each list. Should we add that task to the ticket?)

**Comment by jilladams** [comment] 2024-10-02 21:43
dupe of https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19379

**Closed** 2024-10-02 21:43 UTC
Labels: Facilities, Needs refining, Content audit, CMS Team, sitewide
