### ISSUE TITLE
Resource and Support content types can not update alias

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#3406] opened 2020-11-06 15:55 UTC
## Notes from November 2023 (Jill):
Today, I was able to login as content admin (on Staging) and check the "Generate alias" box and save the update, so re: https://github.com/department-of-veterans-affairs/va.gov-cms/pull/2 in ticket body, that reported error validation piece of this doesn't repro anymore. I don't have a means to confirm the FE publish went through, since I was on Staging.

In general I do think we'll need to step through this report again and confirm if prod today behaves the same way or not. Could timebox this for that if we wanted to.

## Description

1. On a published R&S node: you cannot change the alias of a published node. 
If you check the box to make it use the alias pattern, it does not make it through the publishing pipeline.
![image](https://user-images.githubusercontent.com/5752113/98385943-97ed8c00-201d-11eb-99ef-cdadc25cc6b9.png)

2. As content-admin or admin: try to force a change in the alias field is validated / errors and will not save.
![image](https://user-images.githubusercontent.com/5752113/98385920-91f7ab00-201d-11eb-8399-83a7b3a42eb8.png)

3. Bulk Operations: if you use a bulk operation to move a node or many nodes from unpublished to published, aliases do not appear to get updated.

This seems to be a collision of the following two PR's that were merged in Nov 2020:
* https://github.com/department-of-veterans-affairs/va.gov-cms/pull/3259
* https://github.com/department-of-veterans-affairs/va.gov-cms/pull/3207

**Workaround:** For now the only workaround is to use /admin/config/search/path

## ACs
- [ ] Test in a tugboat to attempt to reproduce. 
- [ ] If not reproducible, then close ticket.
- [ ] If reproducible, we'll determine as a team what to do (use this ticket or create a new one)

**Comment by swirtSJW** [comment] 2020-11-06 18:59
This was put up as a quick undo, but decided against. 
https://github.com/department-of-veterans-affairs/va.gov-cms/pull/3408

https://dsva.slack.com/archives/CT4GZBM8F/p1604677259307200

**Comment by jilladams** [comment] 2023-11-16 22:37
Today, I was able to login as content admin (on Staging) and check the "Generate alias" box and save the update, so re: #2 in ticket body, that reported error validation piece of this doesn't repro anymore.  I don't have a means to confirm the FE publish went through, since I was on Staging. 

In general I do think we'll need to step through this report again and confirm if prod today behaves the same way or not. Could timebox this for that if we wanted to.

**Comment by dsasser** [comment] 2024-02-09 17:07
I tested this out on Tugboat logged in as a Content Admin (not a Drupal administrator) and was not able to reproduce the issue. See https://cms-6mm3rquwpzsiyujlegsbclkhozuxu6yj.demo.cms.va.gov/resources/my-healthevet-on-vagov-what-to-know

Per ACs, closing as a no-op.

**Closed by dsasser** 2024-02-09 17:07 UTC
Labels: Defect, Drupal engineering, Resources and support, crew-sitewide, Public Websites, non-quarter-prio
