### ISSUE TITLE
Update Vet Center runbook

### ISSUE THREAD

**Issue by omahane** [department-of-veterans-affairs/va.gov-cms#14099] opened 2023-06-16 13:08 UTC
## Description
The https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/.github/ISSUE_TEMPLATE/runbook-vet-center-name-change.md is not accurate. We had to do some rework and trigger an out of band deploy to the revproxy server because the steps in the runbook did not align to the needs of Veterans.

## Acceptance Criteria
- [ ] The Vet Center name change runbook has been updated to reflect the desired outcome when a Vet Center changes its name.

## Relevant context
- [Slack thread](https://dsva.slack.com/archives/C0FQSS30V/p1686769283950129) about the desired outcome for a Vet Center name change.
- [Slack thread](https://dsva.slack.com/archives/CBU0KDSB1/p1686843287798499) about the out of band deployment related to the above discussion

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [x] `Facilities`
- [ ] `User support`

**Comment by mmiddaugh** [comment] 2023-06-21 22:41
Michelle and Dave are reviewing and editing runbooks.

**Comment by xiongjaneg** [comment] 2024-03-06 18:41
closing as a duplicate of #17079 with an AC to review and update runbook

**Closed as completed by xiongjaneg** 2024-03-06 18:41 UTC
Labels: sitewide, Facilities, Needs refining
