### ISSUE TITLE
CLP Editors Instructed To Use 2:1 Hero Image Aspect Ratio; Published Page Displays Different Ratio

### ISSUE THREAD

**Issue by stefaniefgray** [department-of-veterans-affairs/va.gov-cms#10075] opened 2022-08-04 23:51 UTC
Originally reported in https://va-gov.atlassian.net/browse/VAHELP-4520

## Describe the defect
As the Communications Specialist for VA Health Connect, I would like to add a hero image to the Campaign Landing Page that I am working on. 

URLs:

- [Staging preview](http://preview-staging.vfs.va.gov/preview?nodeId=46511)
- [CMS page](https://staging.cms.va.gov/node/46511/edit)

The Hero Image upload field says to select an image with a 2:1 aspect ratio, so that is exactly what I have done:

![Screen Shot 2022-08-04 at 5 42 27 PM](https://user-images.githubusercontent.com/9059428/182973336-6bcbefcd-5a44-489c-aadd-e73425aa9373.png)

@davidmpickett has verified using Adobe Photoshop that the image from this example uses a 2:1 aspect ratio

However, when the page is published and viewed within a desktop browser, the VA Health Connect logo is cut off, and the woman is missing the top of her head:

![Screen Shot 2022-08-04 at 5 44 37 PM](https://user-images.githubusercontent.com/9059428/182973570-557bc28d-0653-489d-b0a1-4676d6c585f8.png)

The image is only displayed as intended, with the VA Health Connect logo visible, when the browser is shrunk down to _precisely_ mobile/tablet size. (Going narrower starts to crop the right side of the text.):

![Screen Shot 2022-08-04 at 5 45 35 PM](https://user-images.githubusercontent.com/9059428/182973646-d3d09a5c-35fd-4fa5-ab66-9ad1ee31c8b0.png)

## Questions:
- Do we need to fix how the image itself scales, or how it is displayed on the front end in accordance with the elements framing it?
- Is 2:1 the ratio that Public Websites wants?
- Should the Editors adding Campaign Landing Page content be uploading hero images with a different ratio altogether?

**Wes notes:**
- The chosen image is a poor choice since it has text inside a logo. Text should never be present in an image (right? a11y), and the logo is causing the crop to be very obvious.
- The range of aspect ratios that these images are meant to serve is unreasonably large, imho. At a wide-desktop view the ratio is extremely wide more like 3:1. At tablet size just above mobile breakpoint, the visible (right side) of the image is taller than it is wide (8:10 in this case, depends on text wrapping).
- The requirement that the photo have a large area that can be covered with text without looking weird is potentially a high barrier for Editors (speculating here).
- Laura points out in [this ticket](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12375) that the cropping in the CMS "View" screen is actually 7:2, which could confuse editors further.

Note: From the Helpdesk/Design discussion on 8/4/2022, it may be displayed at a 2:1 ratio on mobile and 3:1 on desktop

## To Reproduce
1. Create a Campaign Landing Page
2. Attempt to add the following 2:1 ratio image as the "hero image" for the page, and click "Preview":

![image](https://user-images.githubusercontent.com/9059428/182973882-58c0329b-c26d-403d-8fdf-787d2687883c.png)

## AC / Expected behavior
I expect to see the 2:1 aspect ratio hero image added to the Campaign Landing Page as intended, without the VA Health Connect logo being cut off or covered up.

## Screenshots
See above

 ## Additional context
Issue was discussed during 8/4/2022 Helpdesk/Design check-in meeting with @suzanne-gray @cjterdi @davidmpickett @TroyA6 and @stefaniefgray 

Issue originated in https://va-gov.atlassian.net/browse/VAHELP-4520

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS workstream (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [x] `⭐️ User support`

**Comment by davidconlon** [comment] 2023-07-12 12:45
@wesrowe do you know why this is "blocked" since April 2022?

**Comment by wesrowe** [comment] 2023-07-13 19:32
I don't think I've seen this before. It appears that the CMS team handled this internally (with DaveP?) and it never came PW's way. Seems like I should move it into PW's refinement flow. We need to investigate how it lays out at non-desk breakpoints.

**Comment by wesrowe** [comment] 2023-07-24 21:32
UX refinement: Jordan to poke around a little to see what seems to really be going on here across device sizes. She'll return the ticket to the refinement flow at that point, probably for FE engineers to review.

**Comment by wesrowe** [comment] 2023-07-25 16:08
@thejordanwood found the CLP page in the ticket. (will add)

@chri5tia to quickly pre-refine: is there a Drupal module/functionality available to enable Editors to pick a focal point that would prioritize an area of the photo when responsive cropping happens.

This will still be a difficult photo-selection challenge for Editors, as so much of the photo is covered by the text block. I'll make a note to discuss with DaveC when he returns.

**Comment by wesrowe** [comment] 2023-07-25 23:27
BE refinement:

- Because we're headless, both BE and FE have to be configured per-product to handle responsive images: both saving multiple formats and having the FE request different formats

Aspect ratios:
- a contrib module could (almost certainly) provide ability to manage different aspect ratios (Editor uploads separately) 
- FE would then place the different versions

Drupal core – "derivatives" of images
- can automate creation of different aspect ratios or resolutions, but it won't show them to Editors
- let's not use it

Next steps (Wes):
- detail high-level options for approach, with estimates if possible
- discuss with DaveC

**Comment by wesrowe** [comment] 2023-07-26 01:16
It's my opinion that the Editor chose an image that 1) looks especially bad when the aspect ratio changes due to logo and text, and  2) should not be allowed based on that text/logo. Way forward would be to require the Editor to provide the photo without text or logo.

**Comment by jilladams** [comment] 2023-07-26 16:21
@wesrowe in that case, could go ahead and provide feedback notes to Helpdesk and ask them to reach out to the editor for this change, esp since this originated from HD and they likely have an open JIRA ticket already.

**Comment by jilladams** [comment] 2023-07-27 15:45
For reference: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12375
> Actual state:
> The FE is not using any crop ratio, which I believe is because this is a background image. We should remove the reference to the 2:1 aspect ratio from the Help text
> Also, the View node actual does display an aspect ratio, it uses the 7:2 ratio. I'm not sure if there is anything we can do about the discrepancy between the View node and the actual FE display because this is headless but it is just something to note.

Team discussed, this is a CMS UX thing we _should_ fix, but will not happen in this ticket.

**Comment by wesrowe** [comment] 2023-09-07 18:53
Refinement:
- Be clear to Editors what they should do in the Drupal UI: manage their expectations, teach them how to Drupal
- i.e., look at all the aspect ratios in Drupal UI
- are aspect ratios "sticking" or is there a bug? Dave think probably it's the FE product not consuming the right image aspect ratios at the right break points
- the problem here is we're using image as background, which changes aspect ratio very fluidly

**Comment by jilladams** [comment] 2023-10-18 21:35
This issue will be resolved by: 
* #15635 
* #15632 

@stefaniefgray - closing this as a dupe of those.

**Closed by jilladams** 2023-10-18 21:35 UTC
Labels: Defect, Design, Drupal engineering, Needs refining, Campaign Landing Page, User support, Public Websites, backend, CMS design, UX
