### ISSUE TITLE
Drupal: Add VetCenter Banner Image to VetCenter Centralized Content

### ISSUE THREAD

**Issue by Agile6MSkinner** [department-of-veterans-affairs/va.gov-cms#18709] opened 2024-07-22 20:34 UTC
### Description:
To support the differentiation of Vet Centers from VA Medical Centers, we need to add the approved VetCenter banner image to Drupal as centralized content. This will allow us to consistently use the image across all Vet Center facility pages.

### Vet Center banner
![vet-center-banner](https://github.com/user-attachments/assets/76c8c958-b13c-48f1-8215-79eb58e49b7d)

### Acceptance Criteria
- [ ] 1. The VetCenter banner image is uploaded to Drupal's media library as embedded image
- [ ] 2. Update vet center facility content type adding banner image from centralized content
- [ ] 3. ~VetCenter banner image does not show on node edit or node view~ We will show this field, per [comment](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18709#issuecomment-2293897017).

**Comment by Agile6MSkinner** [comment] 2024-07-22 23:31
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VAgov-Sitewide-Product-Team-6645154188a81a1f7a0a9464/issues/department-of-veterans-affairs/va.gov-cms/18709?planning-poker) with Zenhub @davidmpickett @dsasser @omahane @jv-agile6

**Comment by aklausmeier** [comment] 2024-07-24 14:40
@Agile6MSkinner This work is blocked by design revisions in #18389

**Comment by davidmpickett** [comment] 2024-07-24 16:31
@aklausmeier I thought we agreed we weren't waiting for additional stakeholder feedback before moving forward with shipping small improvements to Vet Centers.

In story mapping earlier this week @Agile6MSkinner made a product call to go forward with the logo in order to start delivering value rather than trying to do the image exploration

**Comment by aklausmeier** [comment] 2024-07-24 17:34
stakeholder has requested we explore an alternative image solution over a logo, also stated in [design revision ticket](https://app.zenhub.com/workspaces/vagov-sitewide-product-team-6645154188a81a1f7a0a9464/issues/gh/department-of-veterans-affairs/va.gov-cms/18389), likely there will be an image here but it's not confirmed what it will be

**Comment by davidmpickett** [comment] 2024-07-24 20:05
@Agile6MSkinner @jv-agile6 @jilladams @mmiddaugh - I would recommend pulling this ticket out of sprint and marking as blocked

I just got out of a meeting with Amanda and Jordan. @aklausmeier emphasized that the stakeholders were have not approved moving forward with the logo. They want to first explore the image approach and only use the logo if that is untenable. 

If we go with the image route, it's possible that this ticket would be unchanged aside from it being one national image rather than a one national logo, but there's also the possibility that we might need to support images specified at regional / local level.

**Comment by omahane** [comment] 2024-07-24 20:24
> but there's also the possibility that we might need to support images specified at regional / local level.

Does that mean an image for the main Vet Center that would pertain to it and other facilities?

**Comment by jilladams** [comment] 2024-07-24 20:59
Making the sprint change, so we don't churn.

**Comment by jilladams** [comment] 2024-07-25 15:54
Scrum discussion: https://dsva.slack.com/archives/C079GFKN50D/p1721857502492419?thread_ts=1721857395.422269&cid=C079GFKN50D

**Comment by Agile6MSkinner** [comment] 2024-08-05 19:16
@thejordanwood Please add the image to this story.

**Comment by omahane** [comment] 2024-08-16 15:08
@jilladams @davidmpickett @Agile6MSkinner @mmiddaugh I looked at this last night. I believe, there's no way through the UI to populate the default content without showing the field on node:edit (at least). I'm wondering what the reasoning is behind not showing the image, as try to mirror the FE as much as possible normally. In any case, unless we want to write custom code, we'll need to show the image to editors.

**Comment by aklausmeier** [comment] 2024-08-16 16:03
Since it's not editable, I would advocate for showing it to mirror FE but not sure if there was reasoning behind the AC that I'm not aware of. 

> VetCenter banner image does not show on node edit or node view

**Comment by omahane** [comment] 2024-08-16 17:34
# Decision on AC about hiding the field on node:view and node:edit
Per conversation in [Slack](https://dsva.slack.com/archives/C0FQSS30V/p1723820711451709), we **will** show this field as uneditable. I will edit the ACs.

**Comment by omahane** [comment] 2024-08-21 14:50
Confirmed that this is visible on prod:
<img width="1792" alt="Screenshot 2024-08-21 at 9 49 22 AM" src="https://github.com/user-attachments/assets/4a136f25-d537-46c0-8855-02e470f58d50">

**Closed by omahane** 2024-08-21 14:50 UTC
Labels: Drupal engineering, Facilities, Vet Center, sitewide
