### ISSUE TITLE
CLP Hero Image UX

### ISSUE THREAD

**Issue by cmaeng** [department-of-veterans-affairs/va.gov-cms#4014] opened 2021-01-15 02:28 UTC
## Background
For the Campaign Landing Page product, there will be two options for the hero image:
  1. No image selected will default to the standard va.gov blue gradient
  2. An image will be selected from a library of designated CLP hero images

### Description
We want to enhance the current experience to improve:
- [ ] Image library UX and governance
  - [ ] Discovery needed to determine how these images will be governed, who will be able to add/edit/remove from the library
- [ ] Help text
- [ ] Image aspect ratio UX (desire from PO is to default to 2:1 and only have this as an option)

**Comment by kevwalsh** [comment] 2021-11-01 22:59
This may be a duplicate of other issues in #2415

**Comment by kevwalsh** [comment] 2022-03-09 05:05
Closing this in favor of #2415

**Closed by kevwalsh** 2022-03-09 05:05 UTC
Labels: Enhancement, Epic, ⭐️ Product support, Needs refining, Campaign landing page, Sitewide CMS Team, Candidate for closure
