### ISSUE TITLE
FE: Implement CLP image aspect ratio fix

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#15632] opened 2023-10-10 21:41 UTC
## Description
CLPs currently use an aspect ratio that causes problems for rendering. Design has proposed an updated treatment in #15351 / [Front end design in Sketch](https://sketch.com/s/b0ab7a47-11d3-4175-90c1-c54638ca9925), that needs to be implemented in the FE.

### Engineering notes / background

Design notes to confirm in design review / build:
Ensure that character limits protect the text box from getting "too tall"
Define exactly what happens to image ratio as desktop view is narrowed toward tablet width - current version seems to get wider than 1:1 at widest width
Update help text and help image for Editors

Engineering tasks:
- [x] Check whether Drupal already has a 1:1 image format pre-saved – we DO
- [x] BE: help text and help image updates - covered in #15635, not merged to main.
- [x] FE: update CLP template to reference correct image format (e.g. https://github.com/department-of-veterans-affairs/content-build/pull/1577/files)
- [x] build Tugboat: from CMS integration branch (`VACMS-15635-Update-CLP-Help-Text-and-Image`) and FE template pulls 1:1 image
- [x] Tugboat: Jordan visit all CLP published & Draft pages and sees if any published CLP looks unacceptably bad
- [x] CHANGE MANAGEMENT: #15806 

## Acceptance criteria
- [x] CLP template(s) use the design-recommended image aspect ratio & updated gradient across all breakpoints where the image should appear
- [x] Design review is required, including verifying existing published CLPs in a Tugboat
- [x] Include alt text tag but ensure value is NULL ("") - verify with Laura in Tugboat
- [x] **Mark PR DO NOT MERGE** - move ticket to Complete Pending Integration
  - [x] **Change management must be complete & signed off before merge**

**Comment by wesrowe** [comment] 2023-10-10 21:43
@jilladams, FYI this is the result the meeting on CLPs. Release steps are in ticket, most will stay in this FE ticket. I'll write a BE ticket for the help text & image.

**Comment by FranECross** [comment] 2023-10-23 22:14
@jilladams Based on the meeting with Dave today, I moved this ticket from the Stretch... bucket to Next Refinement. Is that the correct bucket so that we can coordinate Change Management? Thanks!

**Comment by jilladams** [comment] 2023-10-23 22:27
This is all up for negotiation, but we've been using Next Refinement as the agenda for refinement meetings, and "Refined" as the parking lot for work that's ready and isn't happening yet for blocker / priority reasons, so bumped it over there.

**Comment by randimays** [comment] 2023-11-14 17:34
@thejordanwood (CC:@laflannery for accessibility review)

## Tugboat instance
[Here](https://web-3n6ncfwdu1vtlq90kzrj36nofdlqim1e.demo.cms.va.gov/initiatives/protecting-veterans-from-fraud/)

## Published CLPs in prod (I tested all of these)
- /initiatives/protecting-veterans-from-fraud
- /initiatives/veterans-experience-action-centers
- /initiatives/national-buddy-check-week-talk-to-10-veterans
- /initiatives/sign-in-securely-with-logingov
- /initiatives/covid-flu
- /initiatives/veteran-trust-in-va
- /initiatives/end-of-life-benefits/
- /initiatives/emergency-room-911-or-urgent-care
- /initiatives/network-of-support
- /initiatives/vote
- /initiatives/flu
- /initiatives/recognizing-lgbtq-veterans-during-pride-month

## Issues Executing the Design
I saw the Sketch file's tablet design is the narrowest screen without the image, but the design worked much better changing that to 1007px (instead of 768).

For some of the CLPs, the text side was stacking quite a bit and it was difficult to keep the aspect ratio without ending up with extra space on the bottom of the image. See examples below:

<img width="797" alt="Screenshot 2023-11-14 at 9 59 37 AM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/19175324/30fad171-488b-4272-8dbe-792cc4ec1251">
<img width="913" alt="Screenshot 2023-11-14 at 9 59 24 AM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/19175324/b9e51412-46d8-4aa3-9c1c-8b6fb1c7d034">

## Implemented Design with Screenshots (Needs Your Feedback)

### 1201px
<img width="1201" alt="Screenshot 2023-11-14 at 11 31 34 AM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/19175324/f0e9270a-fd91-4c03-96f8-4f28612144ca">

### 1200px
<img width="1200px" alt="Screenshot 2023-11-14 at 11 31 29 AM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/19175324/fed6b2ce-9c51-4e06-8896-22639a921c31">

### 1008px
<img width="1008" alt="Screenshot 2023-11-14 at 11 29 20 AM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/19175324/49ea6591-92d8-4402-a5cd-2376a0aa8681">

### 1007px
<img width="1007" alt="Screenshot 2023-11-14 at 11 29 12 AM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/19175324/fa74ec22-2392-41a2-85dd-e40ebe4429c9">

### 768px
<img width="768" alt="Screenshot 2023-11-14 at 11 29 05 AM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/19175324/97c39a09-89ec-49a7-9388-621399f79e65">

### 767px
<img width="767" alt="Screenshot 2023-11-14 at 11 28 58 AM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/19175324/681d83d1-966c-4ff6-a223-b5f32c3ef48d">

### 320px
<img width="320" alt="Screenshot 2023-11-14 at 11 28 49 AM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/19175324/1d94526d-dbeb-4b65-adaa-66075f5f76ae">

**Comment by randimays** [comment] 2023-11-14 17:46
Pull request (with `Do not merge` label added): https://github.com/department-of-veterans-affairs/content-build/pull/1791

**Comment by thejordanwood** [comment] 2023-11-14 18:29
@randimays Does setting the breakpoint to 1007px, instead of 768px, solve the problem where the text side is stacked higher than the image? When I test this at 1007px, it looks like this solves the problem so I wanted to make sure this was your proposed solution. In that case, I'm fine with the breakpoint being at 1007px.

**Comment by laflannery** [comment] 2023-11-14 18:40
I confirmed the image has a null alt, checked off the AC in the description

**Comment by thejordanwood** [comment] 2023-11-14 19:20
@randimays I'm good with your proposed solution then! 

I [commented on the change management ticket](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15806#issuecomment-1811036696) and provided new images for 3 of the pages. I'm not sure how to add those so that they appear in your tugboat instance.

**Comment by randimays** [comment] 2023-11-14 19:25
Thanks @thejordanwood. You can enter the CMS for my Tugboat [here](https://cms-3n6ncfwdu1vtlq90kzrj36nofdlqim1e.demo.cms.va.gov/) and update the images accordingly. Let me know if you have trouble accessing it.

**Comment by randimays** [comment] 2023-11-14 19:27
@thejordanwood Hack for finding Tugboat CMS links: take the original link for the web preview:

```https://web-3n6ncfwdu1vtlq90kzrj36nofdlqim1e.demo.cms.va.gov/initiatives/protecting-veterans-from-fraud/```

Remove everything after `va.gov`, and replace `web` with `cms`.

**Comment by thejordanwood** [comment] 2023-11-15 15:50
@randimays Thanks! I've added the new images to those 3 pages and it looks like they're showing in your Tugboat now.

**Comment by jilladams** [comment] 2023-11-16 22:32
@randimays a question: Drupal provides specific paths for some image ratios. For example, Daniel made a similar change for homepage benefit promos here: https://github.com/department-of-veterans-affairs/content-build/pull/1577/files, using the GQL query for that `CROPSQUARE` image aspect ratio. I apologize - I thought we'd noted that in this ticket as a reference point. :/ I think we need to explore going that route, as the current implementation in Tugboat isn't always showing the images as 1:1. e.g. 

https://web-3n6ncfwdu1vtlq90kzrj36nofdlqim1e.demo.cms.va.gov/initiatives/veterans-experience-action-centers/
https://web-3n6ncfwdu1vtlq90kzrj36nofdlqim1e.demo.cms.va.gov/initiatives/veteran-trust-in-va/
https://web-3n6ncfwdu1vtlq90kzrj36nofdlqim1e.demo.cms.va.gov/initiatives/emergency-room-911-or-urgent-care/
https://web-3n6ncfwdu1vtlq90kzrj36nofdlqim1e.demo.cms.va.gov/initiatives/vote/

Once you're back online next week, I'll be out, but @dsasser  can give insights on the code side, and Fran can help make shot calls if you have more questions or if there are reasons the way you've gone about it here is preferable and you need signoff. 

@FranECross FYI that I noticed this while reviewing the email drafts. As it is, the Google doc contains some screenshots where we say the image will be updated to 1:1, but doesn't actually display at 1:1. So: I think we should wait to send those til Randi can review this feedback and sort out if she needs to make any changes and may need to update screenshots after.

**Comment by FranECross** [comment] 2023-11-16 22:41
@jilladams Thanks so much for the info! I'll hold on the emails as suggested. 🎉

**Comment by randimays** [comment] 2023-11-20 15:44
@jilladams Totally weird that some weren't rendering 1:1 in the Tugboat. In [this PR](https://github.com/department-of-veterans-affairs/content-build/pull/1791) I uploaded screenshots for every page with the 1:1 ratio working. 🤯  

@FranECross Do you know if we are going to be updating all Campaign Landing Page hero images to a square version as part of these updates? CC @thejordanwood 

The `CROPSQUARE` quick fix that @jilladams suggested only works if there is a square image uploaded to Drupal; otherwise we need extra code to force the images to crop.

For example:

This CLP (`/initiatives/end-of-life-benefits`) has a square image uploaded to Drupal

<img width="1198" alt="Screenshot 2023-11-20 at 9 33 05 AM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/19175324/d7b75e1b-972a-47bc-84c3-de66e8290136">

Drupal finds the image uploaded in the `crop_square` folder

<img width="386" alt="Screenshot 2023-11-20 at 9 33 12 AM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/19175324/3fb7fcc1-120b-417f-ac43-0972a077cd96">

When you go to this image's direct path, you can see it's 1:1

<img width="949" alt="Screenshot 2023-11-20 at 9 34 29 AM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/19175324/b9646725-3e55-46c7-81db-d5eb8e1a8dc5">

However, this CLP (`/initiatives/protecting-veterans-from-fraud`) does not have a square image uploaded to Drupal. It is displaying at 1:1 because I added some styling to force it that way

<img width="1198" alt="Screenshot 2023-11-20 at 9 34 51 AM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/19175324/11362d97-dc82-424f-b32c-984504b84ca7">

Notice in the browser that it's trying to find something in the `crop_square` folder but it's getting the old ratio (7:2?) for the image uploaded

<img width="489" alt="Screenshot 2023-11-20 at 9 35 01 AM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/19175324/bfd7bba3-38f0-4a76-a70d-65bdc4c065e5">

Navigating to the image's direct path, you can see the old ratio

<img width="1424" alt="Screenshot 2023-11-20 at 9 35 13 AM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/19175324/692af7b1-ed09-4285-8390-20f0cf901ce3">

I think I will be able to use less code if we update all the images to 1:1 for these changes (starting in Tugboat so I can verify the code, then updating in staging/prod).

**Comment by FranECross** [comment] 2023-11-20 17:11
@randimays Responding to your question below, if it's a fairly minimal effort, and to keep code lean, I think it would be ideal to update all the images. Would that be an additional ticket for Jordan (or you) to alter the images? Thanks! cc @thejordanwood 

_Do you know if we are going to be updating all Campaign Landing Page hero images to a square version as part of these updates?_

**Comment by randimays** [comment] 2023-11-20 18:01
@FranECross That wouldn't be a front end task; I think @thejordanwood would be able to do it or know who to pass it on to?

**Comment by davidconlon** [comment] 2023-11-20 20:14
@FranECross and I have chatted about this and due to the holiday we understand that this may not ship within this sprint because of code freeze/peoples' availability etc.

**Comment by randimays** [comment] 2023-11-20 21:23
Adding a [Slack thread](https://dsva.slack.com/archives/C52CL1PKQ/p1700506389016049) here for discussion about the `CROPSQUARE` implementation. It **should** automatically crop images from Drupal, but isn't working. @dsasser is troubleshooting this issue.

**Comment by randimays** [comment] 2023-11-21 16:10
End-of-sprint update: this ticket won't close by end of sprint anyway (since it is a `Complete pending integration` ticket when it is finished for now), but it's still in Review/QA because we have not yet figured out why `CROPSQUARE` isn't working properly in Drupal.

**Comment by dsasser** [comment] 2023-11-21 19:56
@randimays @thejordanwood @FranECross et al:

I figured out how to get the CROPSQUARE derivative to work as intended. It is a bit odd, but in some ways it makes sense. The cropping only takes place if it was intentionally set:

1. From a Drupal node, such as [/initiatives/protecting-veterans-from-fraud](https://staging.cms.va.gov/initiatives/protecting-veterans-from-fraud), find the image file name. In this case, it is 'fraud-prevention.jpeg'. The image file name can be obtained by inspecting the html code, or by right-clicking and choosing 'open image in new tab'.
2. [ Search for this file name in the Media content page](https://staging.cms.va.gov/admin/content/media?name=fraud-prevention.jpeg&bundle=All&field_owner_target_id=All&field_media_in_library_value=All).
3. Edit the media item.
4. Under the 'Square' cropping accordion, re-size and or move the crop area. You want to ensure that the system picks up a difference between the previous and new crop dimensions/placement.
5. Save the media entity.
6. You can then view your newly cropped square image at: [/sites/default/files/styles/crop_square/public/2023-09/fraud-prevention.jpeg](https://staging.cms.va.gov/sites/default/files/styles/crop_square/public/2023-09/fraud-prevention.jpeg)

The alternative would be to upload new images for all CLPs.

**Comment by randimays** [comment] 2023-11-21 20:16
@thejordanwood It seems we should upload new images for all CLPs now, and then going forward whomever adds a new CLP or changes the image can follow the guidance for adding new images?

**Comment by thejordanwood** [comment] 2023-11-22 17:25
@randimays Could I just go into the CMS and use the cropping feature there to resize the current images?

**Comment by randimays** [comment] 2023-11-22 17:30
@thejordanwood You're right - that is a better solution :)

**Comment by thejordanwood** [comment] 2023-11-22 22:49
@randimays I've cropped the images for all pages except /initiatives/flu. That one was giving me some trouble, but I see that we're recommending that it be archived anyway. Let me know if there's anything else that I should do for this!

**Comment by jilladams** [comment] 2023-11-27 17:04
Also: it looks like the Tugboat is down, so we'll need to revive it in order to pull new screenshots for @FranECross 's email outreach.

**Comment by randimays** [comment] 2023-11-28 17:35
Update: Trying to get Tugboat to reflect the correct code from my content-build branch. I had some issues with Git yesterday as a result of amending a commit and force-pushing, so I'm still trying to fix that, but it's slow going because of all the waiting for builds.

**Comment by jilladams** [comment] 2023-11-29 17:07
Re: my above comment with 1:1 issues: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15632#issuecomment-1815419474

I eyeballed the issues I reported and they look good as far as ratio in the updated Tugboat. One question: 
https://web-5wyecacp4hjlvfcfmw4varhtjij1vruu.demo.cms.va.gov/initiatives/veteran-trust-in-va/
https://cms-5wyecacp4hjlvfcfmw4varhtjij1vruu.demo.cms.va.gov/node/18299/edit

We're using cropsquare (yay, ugh) which in this case is cropping a native 730x370 image, down to 370x370, and then we're rendering it at 468x468. Is 468 a new minimum for 1:1? Should we be enforcing that as a minimum dimension in the CMS, when these images are uploaded, to prevent upscaling?  (@randimays @thejordanwood )
![Screenshot 2023-11-29 at 9 04 20 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/85581471/fd62dfcc-5992-4fdf-bc61-14e5ec669407)

**Comment by randimays** [comment] 2023-11-29 20:16
[The PR](https://github.com/department-of-veterans-affairs/content-build/pull/1810) is in draft and able to be merged when we are ready.

**Comment by FranECross** [comment] 2023-12-06 15:58
Followed up with John Santos today; will nudge him via Slack if no response.

**Comment by FranECross** [comment] 2023-12-06 21:32
Dave pinged John Santos, and he's approved the updates. He asked Maureen Elias about the /initiatives/vote image, and she wants to keep it displayed. I responded to her question as to what we need from her (that we need a new image where the book has an updated date range, or an agnostic image).

**Comment by randimays** [comment] 2023-12-08 21:35
Merged the FE changes on 12/7. They deployed to prod on 12/8. @jilladams and @thejordanwood updated the CLP images in production CMS, and we're good to go! [Slack confirmation](https://dsva.slack.com/archives/C52CL1PKQ/p1702071118044789?thread_ts=1701979898.379149&cid=C52CL1PKQ)

Closing.

**Closed by randimays** 2023-12-08 21:35 UTC
Labels: VA.gov frontend, Campaign Landing Page, Public Websites
