### ISSUE TITLE
Feature function for Story content types only allows one Featured story

### ISSUE THREAD

**Issue by TroyA6** [department-of-veterans-affairs/va.gov-cms#11221] opened 2022-10-14 14:13 UTC
## User Story
As a VAMC CMS Content Editor, I would like to be able to mark two Stories as Features (1st and 2nd) so that the stories appear in the specified order (1st and 2nd) at the top of the page.
However, the system is not allowing two stories to be featured. 
If a story is selected to be featured, and there is another story already marked as featured, the existing featured story loses is 'Featured' designation. 

## To Reproduce
1. Go to 'Content' and select SECTION: VISN 23 / VA Minneapolis health care; select CONTENT TYPE: Story
2. Click on 'Filter'
3. Select / Edit the following Stories: 'Help support Veterans in your life and reach out' and 'No cost flu shots in your community for eligible Veterans'
4. Story 1: 'Help support Veterans in your life and reach out' -- Select 'Feature this story' / 1st
5. Story 2: 'No cost flu shots in your community for eligible Veterans' -- Select 'Feature this story' / 2nd
6. Return to Story 1: 'Help support Veterans in your life and reach out' and select 'Edit'
7. Scroll down to 'Feature this story'
8. See error - 'Feature this story' check box has been deselected.

## Acceptance Criteria 
- [ ] I expect that TWO stories can be featured in a selected order (1st and 2nd)

## Screenshots
Listing of Stories in question:
![image](https://user-images.githubusercontent.com/108767736/195865893-69805c82-f0a7-447e-9b56-659058a33ae5.png)

## Story 1 - set to be Featured in position 1:
![image](https://user-images.githubusercontent.com/108767736/195866295-3621a5e9-6214-4fca-a1c0-b0fa68adaa97.png)

## Story 2 - default - Feature box unchecked:
![image](https://user-images.githubusercontent.com/108767736/195866862-4a54bd27-5182-4f3a-92d7-7d0e5e7c4a6c.png)

## Story 2 - Feature box and position 2 selected and Published:
![image](https://user-images.githubusercontent.com/108767736/195867057-6046706b-005a-49db-b0d5-0d418e903409.png)

## Return to Story 1 to find 'Feature' box unchecked:
![image](https://user-images.githubusercontent.com/108767736/195867321-d5e7bcb3-e8f6-4df6-9ba3-165390fec20e.png)

 ## Additional context
A work around has been found, but the functionality is not correct and has been frustrating for Editors.

Jira Ticket: [VAHELP-4738](https://va-gov.atlassian.net/jira/servicedesk/projects/VAHELP/queues/custom/12/VAHELP-4738)

## Desktop (please complete the following information if relevant, or delete)
 - OS: Windows 10 and 11
 - Browser: Chrome
 - Version: 106.0.5249.103 and prior version 105.x.xxxx.xxx

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [ ] CMS workstream (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

[VAHELP-4738]: https://va-gov.atlassian.net/browse/VAHELP-4738?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by TroyA6** [comment] 2022-10-14 14:14
I hope I've completed this correctly -- Please let me know if you have any questions!

**Comment by swirtSJW** [comment] 2022-10-19 01:43
There are several issues around this.  Behavioral decisions need to be made in line with featured, stories and events too. (maybe the same treatment for both, maybe not)

**Comment by dsinla** [comment] 2022-10-20 20:44
This needs to be considered as we refactor our overall approach to Featured Stories, and perhaps to Events 
We need to clarify the behavior for How stories get featured on Story pages and how it is listed at the top of the Facility page 

This needs to be incorporated as part of some epic for redesigning our overall approach and behavior.  @dsinla will create an epic  and add this ticket.

**Comment by TroyA6** [comment] 2022-10-31 14:52
Update from Editor -- Please use newer stories than those listed in the original ticket when working to resolve this issue.

**Comment by jilladams** [comment] 2022-11-01 22:36
Related tickets:  
* [#1314](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/1314) (3/2020) - featuring new story removes old one (Ethan's [code change to fix](https://github.com/department-of-veterans-affairs/va.gov-cms/pull/1334))
* [#29378](https://github.com/department-of-veterans-affairs/va.gov-team/issues/29378) (9/2021) - originally was intended to only allow one featured story; this ticket updated logic to allow max of 2 featured stories on VAMC & story listing pages, (No PR linked, 😢 )
* Merged then Reverted - [#1317](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/1317) 10/2021 - (Ethan's closed [PR](https://github.com/department-of-veterans-affairs/content-build/pull/680)) replaced Featured boolean with fieldOrder to  place stories & events in featured position at top of listing page, sorted by weight. Multiple [#1](https://github.com/department-of-veterans-affairs/content-build/pull/1)'s and [#2](https://github.com/department-of-veterans-affairs/content-build/pull/2)'s may appear.
* #1317 -- still open, not prioritized

**Comment by jilladams** [comment] 2022-11-01 23:07
Asked DaveC re: owner / priority: https://dsva.slack.com/archives/C52CL1PKQ/p1667344017010989

**Comment by jilladams** [comment] 2022-11-02 20:54
Made a correction above: the 9/21 fix to allow 2 featured stories _did_ have a [PR ](https://github.com/department-of-veterans-affairs/content-build/pull/549/files)linked -- it's front-end work in content-build, so doesn't affect the fact of the CMS only allowing 1 item to save as featured.

**Comment by stefaniefgray** [comment] 2022-12-13 23:53
Do we have any updates on this that we could relay to the editor @ VA Minneapolis?

Original Jira ticket: https://va-gov.atlassian.net/browse/VAHELP-4738

**Comment by jilladams** [comment] 2022-12-14 18:53
@wesrowe @dsinla I think we need a product exercise with Dave to determine who needs to own this story.

**Comment by stefaniefgray** [comment] 2023-01-20 18:43
@jilladams @wesrowe Hi Public Websites team! Resurfacing this ticket since the original Jira ticket is still open: https://va-gov.atlassian.net/browse/VAHELP-4738

**Comment by jilladams** [comment] 2023-01-27 23:55
My suspicion is that this will end up sitting with Facilities and will need to wait til our new PM gets in / starts getting ramped up in order renegotiate priorities.

**Comment by stefaniefgray** [comment] 2023-03-14 01:16
@kmariepat-cityfriends Here's a ticket from a while back that was noticed by one of our astute editors -- please let me know what we ought to do with this one. 

Thank you, and thank you for all your hard work on Facilities wrangling tickets like this!

**Comment by kmariepat-cityfriends** [comment] 2023-03-16 13:43
@stefaniefgray quite the history on this one, I'll bring it to the team in refinement today

**Comment by kmariepat-cityfriends** [comment] 2023-03-16 17:24
Next Steps: 
- the featured checkbox isn't working, maybe put in the scope of this card @laflannery can add more info here (featured is also on events)
- limiting the feature @omahane may know more https://github.com/department-of-veterans-affairs/va.gov-cms/issues/1317 (talk to @swirtSJW and @jilladams)

**Comment by kmariepat-cityfriends** [comment] 2023-03-16 17:24
Next Steps: 
- the featured checkbox isn't working, maybe put in the scope of this card @laflannery can add more info here (featured is also on events)
- limiting the feature @omahane may know more https://github.com/department-of-veterans-affairs/va.gov-cms/issues/1317 (talk to @swirtSJW and @jilladams)

**Comment by stefaniefgray** [comment] 2023-07-20 02:44
Still an issue -- https://va-gov.atlassian.net/browse/VAHELP-6140

**Comment by mmiddaugh** [comment] 2024-01-29 20:29
Additional details and examples in [Featured Story Checkmarks Behave Differently than expected #10771](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10771), which is closed as a duplicate to this one.

**Comment by davidmpickett** [comment] 2024-09-30 19:50
Closing as not planned since the intended behavior is to only Feature 1 per system. https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13687

**Closed by davidmpickett** 2024-09-30 19:50 UTC
Labels: Defect, VAMC, Drupal engineering, Facilities, Needs refining, sitewide, Story
