### ISSUE TITLE
New Vet Center Facility: Solano County Vet Center Outstation

### ISSUE THREAD

**Issue by omahane** [department-of-veterans-affairs/va.gov-cms#17797] opened 2024-04-09 21:43 UTC
## Description
Use this runbook if: a Vet Centers, Mobile Vet Centers, Vet Center Outstations is flagged as New, OR if an existing facility is flagged as New with a new Facility API ID. (This may happen  if a Vet Center moves districts, or a Mobile Vet Center is reallocated to a different Vet Center.)

## Intake
- [x] What triggered this runbook? (Flag in CMS, Help desk ticket, Product team, VHA Digital Media)
Trigger: @mmiddaugh informed us to be on the lookout via [Slack](https://dsva.slack.com/archives/C02730UEZPS/p1712672364039079)

- [x] Link to associated help desk ticket (if applicable)
Help desk ticket: [VAHELP-7612](https://va-gov.atlassian.net/browse/VAHELP-7612)

- [x] Name of submitter (if applicable)
Submitter: Joseph.Moglia@va.gov

- [ ] If the submitter is an editor, send them links to any relevate KB articles for the Vet Center product.
KB articles: <insert_kb_article_links>

- [x] Link to facility in production:
Facility CMS link: [https://prod.cms.va.gov/concord-vet-center/solano-county-vet-center-outstation](https://prod.cms.va.gov/concord-vet-center/solano-county-vet-center-outstation)
Facility API ID: vc_6021OS

### New Vet Center
[@TODO: KB ARTICLE FOR ADDING VET CENTERS - SEE runbook-vamc-facility-new]

#### CMS help desk steps
**Note: If the help desk is waiting on information from the facility staff or editor, add the `Awaiting editor` flag to the facility** with a log message that includes a link to this ticket. Remove the flag when the ticket is ready to be worked by the Facilities team. **Be sure to preserve the current moderation state of the node when adding or removing the flag.**

**If a Outstation:**
- [x] Confirm what Vet Center it belongs to, and set the "Main Vet Center location" field. The parent location may be derived by the Facility ID.
- [x] Contact the Vet Center editor to remind them to (1) add a photo of the Outstation and then they can publish when ready
- [ ] Consider: Following up with Barb/RCS Central office to be sure that she's aware that the Outstation is in-flight

**Drupal Admin steps**
- [x] 8. Bulk publish the nodes and facility.
- [x] 9. Edit the facility node: remove the `New facility` and `Awaiting editor` flags, save the node.
- [x] 10. Let Help desk know this has been done.

#### CMS Help desk (wrap up)
- [x] 11. Upgrade the Vet Center Director and Outreach Specialist accounts to the publisher role for that Vet Center.
- [x] 12. Notify editor and any other stakeholders.

[VAHELP-7612]: https://va-gov.atlassian.net/browse/VAHELP-7612?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by EWashb** [comment] 2024-04-30 21:03
Barb reached out to confirm that we haven't gotten any indication in Drupal that this has happened yet. @omahane confirmed it is neither in the API or Drupal yet.

**Comment by omahane** [comment] 2024-05-16 13:49
Conversation on [Slack](https://dsva.slack.com/archives/C02730UEZPS/p1714567316909319?thread_ts=1712672364.039079&cid=C02730UEZPS) shows that this facility has appeared in the API and Drupal, but with an API ID that doesn't conform to the outstation convention and resulted in creating a Vet Center rather than Outstation. Barb has been emailed to fix this.

**Comment by mmiddaugh** [comment] 2024-05-21 17:48
@omahane - it looks like the anticipated changes to the Solano County Vet Center Outstation have finally come through. Drupal now has two Solano County facilities. [Solano County Vet Center Outstation](https://prod.cms.va.gov/solano-county-vet-center-outstation) (vc_6021OS) is the one we want to keep. 

<details>
<summary> Drupal screenshot </summary>

<img width="1638" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOHI4QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5139c1f2dd2b79b6d9f08ccfdc375e7083b34c12/image.png" alt="image.png" />

</details>

**Comment by omahane** [comment] 2024-05-22 15:05
Sounds good. I'm archiving the other.

**Comment by omahane** [comment] 2024-05-22 15:39
@ian-sears @TroyCMSSupport Now that Solano has shown up, could you reach out to the editor to get the facility ready for the big show?

**Comment by mmiddaugh** [comment] 2024-05-29 22:59
@omahane Thanks for wrangling the new Outstation into the appropriate District. Barb with RCS will coordinate the editor effort.

**Comment by TroyCMSSupport** [comment] 2024-07-03 14:14
@omahane @jilladams @mmiddaugh @ian-sears  Editor has completed revisions and the site is published, and the facility is open - I have updated the information in this ticket as well.

**Comment by jilladams** [comment] 2024-07-03 23:17
The runbook here doesn't say anything about CSV. Is that a necessary step? (Meaning: does that also need to be added to this runbook, @omahane ?)

**Comment by jilladams** [comment] 2024-07-08 20:48
CSV request was made here: https://dsva.slack.com/archives/C02730UEZPS/p1719585916276039

To verify Solano once LH says CSV is updated:
- Go to https://www.va.gov/find-locations/?page=1&address=94534&facilityType=vet_center&serviceType&latitude=38.258344&longitude=-122.067489&radius=16&bounds%5B%5D=-122.817489&bounds%5B%5D=37.508344&bounds%5B%5D=-121.317489&bounds%5B%5D=39.008344&context=Fairfield%2C%20California%2094534%2C%20United%20States
- Click "Solano" title
- Before change, it pointed to facility locator detail page: https://www.va.gov/find-locations/facility/vc_6021OS
- After deploy, should point to: https://www.va.gov/concord-vet-center/locations/#solano-county-vet-center-outst

Noting: that's also being tracked sort of in #9534 so if this ticket gets verified to close, we can close that one too.

**Comment by ian-sears** [comment] 2024-07-10 23:43
@omahane 
Lighthouse CSV has a # symbol in the URL. Is this intentional?
Example:
vc_6021OS | https://www.va.gov/concord-vet-center/locations/#solano-county-vet-center-outst

**Comment by jilladams** [comment] 2024-07-11 15:50
@ian-sears @TroyCMSSupport this CSV update has been deployed. 

And yes, the # is intentional. For Vet Center outstations, they don't have their own pages. The main area where Outstation information appears is on the main Vet Center locations page. So this is an anchor link that allows people to jump to a specific area of that Locations page, for the Solano information. We'll be handling Outstations in this manner moving forward, probably. 

I've removed the New Facility and Awaiting CSV flags, and this ticket is ready for next steps from Helpdesk.

**Comment by ian-sears** [comment] 2024-07-15 21:47
Editor and Director have both been provisioned with Create/Publish privileges for this in the Concord Vet Center, and they and the Program Support Assistant have been provided awareness that the facility page in complete and theirs for review and use.

Closing this as complete.

**Closed by ian-sears** 2024-07-15 21:47 UTC
Labels: Drupal engineering, Facilities, Vet Center, User support, Change request, sitewide, Flagged Facilities
