### ISSUE TITLE
Homepage Hardening: Character Limits

### ISSUE THREAD

**Issue by dsasser** [department-of-veterans-affairs/va.gov-cms#11161] opened 2022-10-07 15:27 UTC
## Description
Impose character limits details in this document:
[Homepage promo guidance.docx](https://github.com/department-of-veterans-affairs/va.gov-cms/files/9730146/Homepage.promo.guidance.docx)

#### Homepage benefit promo

Promo headline: 35 characters
Use this headline to make it clear to Veterans what the topic of this promo is and that it’s relevant to them.
Promo text: 125 characters
Use this text to tell Veterans how this promo topic affects them. 
Promo CTA link text: 40 characters
Use this text to tell Veterans what to do next.
Note: For accessibility and cognitive clarity, link text must include the intended purpose of and keywords from the H1 page title of the destination page. 

#### Homepage news promo

Promo headline: 55 characters
Promo text: 125 characters

- [ ] Requires product review by Michelle

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by wesrowe** [comment] 2022-10-07 22:24
@mmiddaugh, I think you added the char limits to another ticket – is that the case?

**Comment by jilladams** [comment] 2022-11-07 18:46
Closing as dupe of https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11119

**Closed by jilladams** 2022-11-07 18:46 UTC
Labels: Drupal engineering, VA.gov homepage, Needs refining, ⭐️ Public Websites
