### ISSUE TITLE
BE: Events: Filter "Where to list" dropdown to only calendars user has permission for

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#15391] opened 2023-09-26 00:01 UTC
### User story

**AS AN**  Events editor
**I WANT** the dropdown selector for "Where should the event be listed" to include only Calendars I have permission for
**SO THAT** it's easy to find the Calendar I want to post to.

### Engineering notes / background

Per the PW engineering team (is this right?), Editors seem to see more sections/calendars in the dropdown than they have access to.

### Questions
- What does it meant to have access to certain calendars? What drives access/permissions?

E.g., here is Tim Hudak's (VEO) list of options (Outreach events calendar highlighted); he can see all VAMCs:
<img width="298" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/4054752/e20efb97-c463-443d-ac5c-d550ba678b25">

His permissions seem to be much narrower... :
<img width="364" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/4054752/b73f5cb6-1188-4570-b4f3-85d9c03f6176">

Yet I was able in Staging to use TimH's credentials to create a draft event at VA Amarillo. So he really does seem to have permission to create events at all the facilities in his dropdown (above). 🤷 

### Questions @FranECross 
- Find out how roles should map to permission of what they see in the dropdown; are there times where this isn't true.
- Should everyone have the ability to post on the Outreach calendar?
- Are there any 'super admin' roles or permissions?

## Acceptance criteria

- [ ]  @FranECross TBD based on answers to my task above.

>Consider
> - Design / Accessibility reviews
> - Collab cycle requirements
> - Device sizes (mobile first)
> - Documentation updates / Change management
< - [Content model documentation](https://prod.cms.va.gov/admin/structure/cm_document)
> - Testing notes

- [ ]

**Comment by wesrowe** [comment] 2023-09-26 00:19
@dsasser, for pre-finement...

 want to check this ticket against your understanding of the Event UI. I thought we _knew_ that all Event Editors see all calendars in their dropdown, regardless of permission. And I thought Tim Hudak was a good example of that. But (documented in ticket above) I was able to use his creds in Staging to create an event in a random VAMC.

So I'm wondering: do you think we need this ticket at all? or is Drupal already filtering the calendars?

**Comment by wesrowe** [comment] 2023-09-26 00:25
The bigger problem seems to be with permissions in general – in Staging I just created an event as Aliyah Blackmore (a random member of CAIA), assigned it a Section of a VBA regional office, and published it to the Outreach Calendar. Is there no governance around Events?

cc @swirtSJW for the background here. I seem to have taken a lot on assumption that turns out not to be accurate.

**Comment by swirtSJW** [comment] 2023-09-26 21:38
Wes there is not much governance around events and largely that was intentional.

Example:  As RyanS (a VAMC editor for multiple systems in PA) I should be able to add events to my own event lists and I should also be able to add an event to the outreach event list.  I probably should not be able add events to event lists in Texas, but that governance was not built out.

Ideally that list should winnow to only show the sections I am assigned to but we were a bit shy about implementing that because we always had the ultimate goal of COPE in mind.  RyanS should be able to select both his systems AND outreach on the same event, insteady of having to create three separate events.   Also I believe there was the idea that as a VISN level editor I should be able to put an event on multiple systems AND someone within that system should be able to remove their system from it.  None of that was implemented, but I think it was on the horizon and we knew that locking it down and unlocking it are at odds with each other.

This was the early days... and the early days goal was ship ship ship and govern later after we figure out what governance should look like.

**Comment by FranECross** [comment] 2023-11-29 16:36
@swirtSJW I'm getting caught up on this ticket and have questions, but am not sure who the stakeholder or stakeholders are that I can ask them of (questions below). Can you point me in the right direction? Thanks!


- Find out how roles should map to permission of what they see in the dropdown; are there times where this isn't true.
- Should everyone have the ability to post on the Outreach calendar?
- Are there any 'super admin' roles or permissions?

**Comment by davidmpickett** [comment] 2024-01-05 18:18
There's a possibility that @omahane's work on #15901 may resolve some of this. Tagging @jilladams for cross-team awareness

**Comment by omahane** [comment] 2024-01-05 21:17
> There's a possibility that @omahane's work on https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15901 may resolve some of this. Tagging @jilladams for cross-team awareness

@jilladams @FranECross After talking to @dsasser, @swirtSJW and @davidmpickett, I really want to make sure I understand what the desired functionality is for Events. As mentioned above, if I implement the change I need for #15901, it will filter out options that are **not** in the editor's Sections in the dropdowns of the following content types' fields.

| Content type | Field label | Field |
| ------------- | ---------- | ----- |
| News Release | News releases listing field | field_listing |
| Publication | Publication listing | field_listing |
| Story | Where should the story be listed? | field_listing |
| Event | Where should the event be listed? | field_listing |

The change I am making, however, is fixing code that is not longer being triggered on these pages, even though it was at some point, rather than creating some new unintended behavior.

That being said, if it's no longer desired functionality on some or all of these content types, I would like to confirm that with you and change the code to meet the current desired editorial experience while also enabling the functionality for the VBA Facility Service.

**Comment by FranECross** [comment] 2024-01-05 21:22
Thank you, @omahane . @jilladams  is back in the office on Monday and we'll be able to look at this then.

**Comment by FranECross** [comment] 2024-01-08 17:28
Thank you, @jilladams In light of your info above, it seems like we can just close this ticket? TIA.

**Comment by jilladams** [comment] 2024-01-08 17:35
Christian will get a PR up today for the change he's making. @omahane if you could reference this ticket in the PR as well, that will help with paper trail. I'll help verify on behalf of events (or ask Michael / Daniel to help, depending on timing), and when that PR merges / is verified, yep: this can close.

**Closed** 2024-01-09 23:59 UTC
Labels: Drupal engineering, Needs refining, Public Websites, backend, Events, non-quarter-prio
