### ISSUE TITLE
[Breakpoints] No Left/Right padding on smaller breakpoints on Outreach and Events

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#18102] opened 2024-05-10 19:43 UTC
## Description
On smaller breakpoints (768 and below), some event detail pages don't have any left/right padding on the side of the screen, not all though, just some. For example:
- Padding: https://www.va.gov/boston-health-care/events/68597/
- Padding: https://www.va.gov/columbia-south-carolina-health-care/events/68252/
- Padding: https://www.va.gov/outreach-and-events/events/67269/
- No Padding: https://www.va.gov/boston-health-care/events/66468/
- No Padding: https://www.va.gov/northern-indiana-health-care/events/67864/
- No Padding: https://www.va.gov/outreach-and-events/events/67410/

Also, the Outreach and Events page needs a style adjustment. Between page widths 768px 640px - 1014px, the content touches the left edge of the page, causing legibility issues. We should make the styling for this page consistent with other full-width pages on va.gov. See these examples: https://www.va.gov/find-forms/

## Acceptance Criteria
- [ ] All event detail pages should have proper padding at all breakpoints
- [ ] Requires design review

**Comment by randimays** [comment] 2024-05-15 17:36
This is a dupe of https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16416 I think. We can combine description details there if you like

**Comment by laflannery** [comment] 2024-05-15 17:39
@randimays This is about detail pages, I think the one you made is about the landing page specifically? I don't disagree that they might be able to be combined because maybe they are solved the same way but I just want to be sure I'm reading that other ticket correctly before I combine them

**Comment by FranECross** [comment] 2024-08-28 19:11
Closing as a no op. Taken care of in #16416

**Closed by FranECross** 2024-08-28 19:11 UTC
Labels: VA.gov frontend, Needs refining, Public Websites, Events, sitewide
