### ISSUE TITLE
Iteration on  "Link to file or video" content block 

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#3231] opened 2020-10-20 20:15 UTC
See [slack thread](https://dsva.slack.com/archives/CDHBKAL9W/p1603225350165400?thread_ts=1601564446.068500&cid=CDHBKAL9W) for background 

## User Story or Problem Statement

Currently, we risk having editors re-upload pdfs that have a single source of truth. 

![image](https://user-images.githubusercontent.com/643678/96639084-290af600-12ef-11eb-8d5a-396d32fb25f6.png)

As an editor, i should understand that i shouldn't add files that are managed via the VA Forms, or other sources of truth. 

Other issues
- "Link to file or video" content block label is confusing, it should indicate that the user is uploading or adding to the CMS media library. 
- No one is using the video capability, should that functionality be removed from this content block (and label/help text updated) 
   - [OC] we've discussed "Link to file or video" component locally and came to consensus that linking to video should be preserved, because there are use cases where editors want to have a link to a video instead of video embed on the page.

## Acceptance Criteria
- [ ] UX for adding PDFs provides good guidance about what should and shouldn't be added.

**Comment by rachel-kauff** [comment] 2021-01-05 17:29
@oksana-c / @kevwalsh I'm wondering if one way to handle this is to add a separate paragraph
 for videos, since the use case for content editors is pretty different than a document download.

![Screen Shot 2021-01-05 at 9 28 51 AM](https://user-images.githubusercontent.com/41017988/103678566-86026980-4f38-11eb-8fec-a860bd8b5f1e.png)

**Comment by rachel-kauff** [comment] 2021-01-05 17:33
...which takes us to a sort of philosophical question about the design intent of content blocks. I think that for editors, content blocks should present a menu of different formats they can choose from, and there should be roughly a 1:1 relationship where there's a separate paragraph for each kind of content design they might want to use. Download a file is quite different than link to a video, in terms of both the FE appearance, and the reason they might want to use that content block, so I'm in favor of splitting.

**Comment by rachel-kauff** [comment] 2021-01-05 18:23
Also: I think the guidance on source of truth for documents is best addressed in the media browser. I have some ideas for that, but wanted to alert you both to scope on this. 
<img width="621" alt="Screen Shot 2021-01-05 at 10 22 24 AM" src="https://user-images.githubusercontent.com/41017988/103684156-fbbe0380-4f3f-11eb-9e88-90d8b1624f4e.png">
<img width="621" alt="Screen Shot 2021-01-05 at 10 22 32 AM" src="https://user-images.githubusercontent.com/41017988/103684163-fcef3080-4f3f-11eb-9423-9904af7811e1.png">
<img width="983" alt="Screen Shot 2021-01-05 at 10 22 49 AM" src="https://user-images.githubusercontent.com/41017988/103684166-fd87c700-4f3f-11eb-8001-d0926f1c8bc0.png">

**Comment by rachel-kauff** [comment] 2021-01-29 00:11
@oksana-c I don't know which is the OG issue here, but I put the deliverables in #3443. Since this is a dupe of that one (with some bonus context), I'll also move this to review so it can be closed.

**Comment by oksana-c** [comment] 2021-01-29 14:39
opened a follow up here https://github.com/department-of-veterans-affairs/va.gov-cms/issues/4133

**Closed by oksana-c** 2021-01-29 14:39 UTC
Labels: Core Application Team, Enhancement, Stretch goal, UX writing
