### ISSUE TITLE
Alternative banners end to end QA test plan

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#19465] opened 2024-10-09 16:57 UTC
Brain dump to refine into an actual test plan: 
* make sure we understand the order of ops for flippers and what will happen when each is on or off, across CMS feature toggles / vets-api flippers
* test what happens when a banner is published to a VAMC system, and showing / hiding it 
* test situation updates: did we break them? they should still work the way they do in Prod
  * publish to Operating status page
  * send to GovDelivery
* test archiving: what happens
* Test the checkbox "not to home or operating status pages"
* test as the right kind of Editors, not just as admin

**Comment by laflannery** [comment] 2024-10-18 20:52
[Working test plan here](https://docs.google.com/spreadsheets/d/1PUgwtG8_NXnc54DzYw6bKCYG-Lfmq0rfNL1Va3URLZ4/edit?gid=0#gid=0)

**Comment by laflannery** [comment] 2024-10-23 15:00
@jilladams and @Agile6MSkinner I have mostly finished the test plan (linked above) however there are some questions I have:


Questions/discrepancies that have come up while determining current functionality:
1. Current VAMC banners do not respect the "Alert dissmissible?" checkbox.
   - [It was decided in this Slack thread](https://dsva.slack.com/archives/C0FQSS30V/p1729516175294989) that we will included this as an addition to the Alternative banners build and the new banners WILL included this functionality
2. It does not appear the the current VAMC banners are respecting the "Subscribe to email updates" CTA checkbox. During testing and looking at current banners, when it is selected, nothing is added to the banner on the FE.
  - Should this be ticketed for follow up to be investigated and/or fixed? 
3. When multiple Situation updates are added, [the current KB article](https://prod.cms.va.gov/help/vamc/how-to-create-a-situation-update) says that these will be displayed newest to oldest on the FE. However, after testing I have confirmed that this is not accurate. Instead, these are displayed according to the Drupal order, meaning if the editor manually changes the order in Drupal, that will be reflected on the FE 
   - It might be good to determine what the proper order should be on the FE and then either update the KB article or ticket any necessary engineering work to ensure this is working as intended
4. Situation Information content I am 90% sure should only display if there is also at least one Situation update. However there was one instance during my testing where Information showed without an Update.
   - In order to be able to do proper regression testing, it would be good to confirm the expected behavior and if necessary create follow up tickets if existing behavior is not currently matching this expected behavior.

Another main question I have just in general is around the GovDelivery - does anyone know how this works or if not, am I able to test this in a tugboat situation?

**Comment by laflannery** [comment] 2024-10-23 17:50
Update from refinement:
- Michelle found old instructions for testing GovDelivery. I have run through those, confirmed functionality and updated the test plan
- We also discussed setting up a meeting with Daniel, Bryan, Jill, Michael, Laura to make sure everything was on the same page QA wise

@jilladams @Agile6MSkinner

**Comment by jilladams** [comment] 2024-10-23 23:21
Scheduled for Friday!

**Comment by laflannery** [comment] 2024-11-15 19:28
@jilladams and @Agile6MSkinner I have all my questions answered so I believe the plan is done and I'm going to close this. The only pending this I believe is exactly HOW we are going to test. If you feel that requires this ticket to remain open, feel free to reopen this ticket.

**Closed by laflannery** 2024-11-15 19:28 UTC
Labels: VAMC, Facilities, testing, sitewide, Alternative banners, current sprint, ghp-refine
