### ISSUE TITLE
Search monitoring: Break up Search APM

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#19256] opened 2024-09-18 20:12 UTC
## Description
Our monitors are set up to monitor [Search APM](https://vagov.ddog-gov.com/apm/services/search/operations/rack.request/resources?dependencyMap=qson%3A%28data%3A%28telemetrySelection%3Aall_sources%29%2Cversion%3A%210%29&deployments=qson%3A%28data%3A%28hits%3A%28selected%3Aversion_count%29%2Cerrors%3A%28selected%3Aversion_count%29%2Clatency%3A%2195%2CtopN%3A%215%29%2Cversion%3A%210%29&env=eks-prod&errors=qson%3A%28data%3A%28issueSort%3ATOTAL_COUNT%29%2Cversion%3A%210%29&fromUser=false&groupMapByOperation=null&infrastructure=qson%3A%28data%3A%28viewType%3Apods%29%2Cversion%3A%210%29&logs=qson%3A%28data%3A%28indexes%3A%5B%5D%29%2Cversion%3A%210%29&panels=qson%3A%28data%3A%28%29%2Cversion%3A%210%29&resources=qson%3A%28data%3A%28visible%3A%21t%2Chits%3A%28selected%3Atotal%29%2Cerrors%3A%28selected%3Atotal%29%2Clatency%3A%28selected%3Ap95%29%2CtopN%3A%215%29%2Cversion%3A%211%29&summary=qson%3A%28data%3A%28visible%3A%21t%2Cerrors%3A%28selected%3Acount%29%2Chits%3A%28selected%3Acount%29%2Clatency%3A%28selected%3Alatency%2Cslot%3A%28agg%3A95%29%2Cdistribution%3A%28isLogScale%3A%21f%29%2CshowTraceOutliers%3A%21t%29%2Csublayer%3A%28slot%3A%28layers%3Aservice%29%2Cselected%3Apercentage%29%2ClagMetrics%3A%28selectedMetric%3A%21s%2CselectedGroupBy%3A%21s%29%29%2Cversion%3A%211%29&traces=qson%3A%28data%3A%28%29%2Cversion%3A%210%29&view=spans&start=1723666652581&end=1723670252581&paused=false) sort of globally. However, Search APM includes calls to 3 different endpoints: 

1. [V0::SearchController#index](https://vagov.ddog-gov.com/apm/resource/search/rack.request/72b7d62abdbc2323?query=env%3Aeks-prod%20operation_name%3Arack.request%20service%3Asearch&env=eks-prod&fromUser=false&summary=qson%3A%28data%3A%28visible%3A%21t%2Cerrors%3A%28selected%3Acount%29%2Chits%3A%28selected%3Acount%29%2Clatency%3A%28selected%3Alatency%2Cslot%3A%28agg%3A95%29%2Cdistribution%3A%28isLogScale%3A%21f%29%2CshowTraceOutliers%3A%21t%29%2Csublayer%3A%28slot%3A%28layers%3Aservice%29%2Cselected%3Apercentage%29%2ClagMetrics%3A%28selectedMetric%3A%21s%2CselectedGroupBy%3A%21s%29%29%2Cversion%3A%211%29&traces=qson%3A%28data%3A%28%29%2Cversion%3A%210%29&start=1723667089031&end=1723670689031&paused=false): When calls to this endpoint fail, a site user cannot search. Failures to this endpoint matter a lot. Historically a quieter / more stable endpoint.
2. [V0::SearchClickTrackingController#create](https://vagov.ddog-gov.com/apm/resource/search/rack.request/61905a2daa2ff864?query=env%3Aeks-prod%20operation_name%3Arack.request%20service%3Asearch&env=eks-prod&fromUser=false&summary=qson%3A%28data%3A%28visible%3A%21t%2Cerrors%3A%28selected%3Acount%29%2Chits%3A%28selected%3Acount%29%2Clatency%3A%28selected%3Alatency%2Cslot%3A%28agg%3A95%29%2Cdistribution%3A%28isLogScale%3A%21f%29%2CshowTraceOutliers%3A%21t%29%2Csublayer%3A%28slot%3A%28layers%3Aservice%29%2Cselected%3Apercentage%29%2ClagMetrics%3A%28selectedMetric%3A%21s%2CselectedGroupBy%3A%21s%29%29%2Cversion%3A%211%29&traces=qson%3A%28data%3A%28%29%2Cversion%3A%210%29&start=1723667099855&end=1723670699855&paused=false) - When calls to this endpoint fail, clicks don't get tracked by Search.gov. We don't care that much. Historically very noisy with errors.
3. [V0::SearchTypeaheadController#index](https://vagov.ddog-gov.com/apm/resource/search/rack.request/9bbc882c60579609?query=env%3Aeks-prod%20operation_name%3Arack.request%20service%3Asearch&env=eks-prod&fromUser=false&summary=qson%3A%28data%3A%28visible%3A%21t%2Cerrors%3A%28selected%3Acount%29%2Chits%3A%28selected%3Acount%29%2Clatency%3A%28selected%3Alatency%2Cslot%3A%28agg%3A95%29%2Cdistribution%3A%28isLogScale%3A%21f%29%2CshowTraceOutliers%3A%21t%29%2Csublayer%3A%28slot%3A%28layers%3Aservice%29%2Cselected%3Apercentage%29%2ClagMetrics%3A%28selectedMetric%3A%21s%2CselectedGroupBy%3A%21s%29%29%2Cversion%3A%211%29&traces=qson%3A%28data%3A%28%29%2Cversion%3A%210%29&start=1723667060750&end=1723670660750&paused=false) - When calls to this endpoint fail, a user doesn't receive back typeahead responses from Search.gov, but search can still be completed. It's a UX nicety, but it's not mission critical. Historically very noisy with errors.

![Screenshot 2024-08-14 at 2 09 49 PM](https://github.com/user-attachments/assets/538a06ec-42c5-4fa5-ad21-07ffaf3e16e8)

Based on [this conversation](https://dsva.slack.com/archives/C06RWEW3S3W/p1723665031778479) in the monitoring channel, if it's possible, we want to break up our monitors to be more clear about when SearchController proper is failing, vs. Typeahead noise. 

## End goal
An APM dashboard for `v0/search` that will show us if search, proper, has a real problem, without the noise of typeahead / click tracking endpoints. 

## Things to figure out
* Do typeahead and clicktracking still need to be monitored somewhere?  Pontifications: 
    * APM = "Application performance monitoring". In this case: the data from these endpoints doesn't really impact performance of the service itself, but it is data, and we would prefer that typeahead works. 
    * Is this ticket misguided, if typeahead is really part of overall search performance??
* Maybe this is a no op and we just get in the habit of looking at the [v0/search resource page](https://vagov.ddog-gov.com/apm/resource/search/rack.request/72b7d62abdbc2323?query=env%3Aeks-prod%20operation_name%3Arack.request%20service%3Asearch&env=eks-prod&fromUser=false&summary=qson%3A%28data%3A%28visible%3A%21t%2Cchanges%3A%28%29%2Cerrors%3A%28selected%3Acount%29%2Chits%3A%28selected%3Acount%29%2Clatency%3A%28selected%3Alatency%2Cslot%3A%28agg%3A95%29%2Cdistribution%3A%28isLogScale%3A%21f%29%2CshowTraceOutliers%3A%21t%29%2Csublayer%3A%28slot%3A%28layers%3Aservice%29%2Cselected%3Apercentage%29%2ClagMetrics%3A%28selectedMetric%3A%21s%2CselectedGroupBy%3A%21s%29%29%2Cversion%3A%211%29&traces=qson%3A%28data%3A%28%29%2Cversion%3A%210%29&start=1726687051818&end=1726690651818&paused=false), and leave it all alone? 

## ACs
?

**Comment by SnowboardTechie** [comment] 2024-09-18 21:23
Reviewing some notes from my earlier findings, if we decide we want to keep tracking typeahead and separately, it will [require getting a new service](https://depo-platform-documentation.scrollhelp.site/developer-docs/monitor-tagging-standards#MonitorTaggingStandards-Required:service) added to the [service catalog](https://vagov.ddog-gov.com/services?env=%2A&fromUser=false&start=1726670260338&end=1726673860338) in DataDog. Although hearing that the root cause was mostly around noise from the typeahead on the [Search Service Summary](https://vagov.ddog-gov.com/apm/services/search/operations/rack.request/resources?dependencyMap=qson%3A%28data%3A%28telemetrySelection%3Aall_sources%29%2Cversion%3A%210%29&deployments=qson%3A%28data%3A%28hits%3A%28selected%3Aversion_count%29%2Cerrors%3A%28selected%3Aversion_count%29%2Clatency%3A%2195%2CtopN%3A%215%29%2Cversion%3A%210%29&env=eks-prod&errors=qson%3A%28data%3A%28issueSort%3ATOTAL_COUNT%29%2Cversion%3A%210%29&fromUser=false&groupMapByOperation=null&infrastructure=qson%3A%28data%3A%28viewType%3Apods%29%2Cversion%3A%210%29&logs=qson%3A%28data%3A%28indexes%3A%5B%5D%29%2Cversion%3A%210%29&panels=qson%3A%28data%3A%28%29%2Cversion%3A%210%29&resources=qson%3A%28data%3A%28visible%3A%21t%2Chits%3A%28selected%3Atotal%29%2Cerrors%3A%28selected%3Atotal%29%2Clatency%3A%28selected%3Ap95%29%2CtopN%3A%215%29%2Cversion%3A%211%29&summary=qson%3A%28data%3A%28visible%3A%21t%2Cchanges%3A%28%29%2Cerrors%3A%28selected%3Acount%29%2Chits%3A%28selected%3Acount%29%2Clatency%3A%28selected%3Alatency%2Cslot%3A%28agg%3A95%29%2Cdistribution%3A%28isLogScale%3A%21f%29%2CshowTraceOutliers%3A%21t%29%2Csublayer%3A%28slot%3A%28layers%3Aservice%29%2Cselected%3Apercentage%29%2ClagMetrics%3A%28selectedMetric%3A%21s%2CselectedGroupBy%3A%21s%29%29%2Cversion%3A%211%29&traces=qson%3A%28data%3A%28%29%2Cversion%3A%210%29&view=spans&start=1726690711549&end=1726694311549&paused=false) I'm inclined to argue we keep things as is, though it produces more noise, ultimately the typeahead check is a piece of the Search that is offered to users and I tend to lean towards it's better to separate data on the DD side vs rails.

Either way this goes, I think we should look into handling the noise related to the not handling the `Faraday::TimeoutError` that is being returned. If we don't consider this error to be abnormal, we can rescue and rely on less elevated form of logging (info or warn instead).

**Comment by jilladams** [comment] 2024-09-18 21:35
Ok. That makes sense to me generally. If others agree, we can close this as a no op and cut a separate ticket for the typeahead Faraday error. 

Related / unrelated?: I searched to see if we have any existing ticket for the faraday error and I saw something similar has popped up for another team: https://github.com/department-of-veterans-affairs/va.gov-team/issues/86562. No investigation / root cause yet, but: we are not alone, apparently.

**Comment by SnowboardTechie** [comment] 2024-09-18 21:41
Ahhh ya, very possibly not related there, [Faraday](https://github.com/lostisland/faraday) refers to the Rails gem being utilized for HTTP communication. So what `Faraday::TimeoutError` is saying is when Typeahead tried to communicate to the API it interfaces with, the API timed out and did not respond. With the rails side being unprepared for this error, it is trying to access the `body` like it would on a healthy response. 
So while they are experiencing something similar it looks like that may be occurring with the Sentry API vs typeahead which is working against https://api.gsa.gov/technology/searchgov/v1.

**Comment by FranECross** [comment] 2024-09-20 16:00
I'm in agreement with closing this and creating new tickets as suggested. @SnowboardTechie are you okay with creating the new ticket(s)?

**Comment by SnowboardTechie** [comment] 2024-09-20 19:04
@FranECross all set! I've opened a bug ticket to capture the adjustments that should be made https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19279

**Closed by SnowboardTechie** 2024-09-20 19:04 UTC
Labels: VA.gov frontend, Needs refining, Public Websites, sitewide, VA.gov Search, Ruby, Monitoring
