### ISSUE TITLE
Improve the logic and functionality used by the "featured" fields on Stories

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#1317] opened 2020-03-24 17:19 UTC
## Background

1. Ethan Teague wrote / merged front-end code in https://github.com/department-of-veterans-affairs/content-build/pull/680 to partially address this issue. 
2. CMS code to make changes was written & is in closed PR https://github.com/department-of-veterans-affairs/va.gov-cms/pull/6766. 
3. Strategy around updating Featuring has changed since, and this ticket can either be:   
    * Closed, left for Public Websites deprecation in #1318 
    * Revised for future state of Featuring in Stories, and moved to Facilities epic

![Screenshot_2021-09-02__12_50_PM](https://user-images.githubusercontent.com/643678/131884872-fad560e1-073e-41fb-bbeb-10b560739568.png)

![Screenshot_2021-09-02__12_50_PM](https://user-images.githubusercontent.com/643678/131884985-2fcae5a7-1723-4eed-8962-0442845d38b1.png)

## ACs

- [x] Featured UI matches for Stories and Events.
  - [x] Get Events featured fieldset out of right rail 
- [x] Works with whatever FE is doing for VAMC events and Outreach hub. 
  - [x] Remove boolean from Graphql 
- [x] Remove the boolean field and replace "- No -" with "Not featured"
- [x] Help text that explains what the FE will do if there's more than one story or event with same "Featured" position.
- [x] "List page" view
  - [x] Fields for both
    - [x] Node title linked to content
    - [x] Featured status ("First feature", "Second feature", and nothing for "Not featured", 
    - [x] Moderation state
  - [x] "Stories list" display
  - [x] "Events list" display
    - [x] Add start date field
    - [x] Sort by start date ASC
    - [x] Filter out past events (or filter for "past and featured" AND "future", depending on how FE is configured)
- [ ] Design review

**Comment by xiongjaneg** [comment] 2022-01-18 19:47
sorry, accidentally removed the sprint 50 label from this one, then put it back

**Comment by jilladams** [comment] 2022-05-24 22:23
Note for when Events gets more priority: PR https://github.com/department-of-veterans-affairs/va.gov-cms/pull/6766 is open, with comment: 
> Taking into account this thread: https://dsva.slack.com/archives/C01H29ERVJ7/p1645211875246399 , not sure how to proceed with this. Sounds like Dave wants to explore options for this for a while, and maybe the path forward is to revert the front end work I did in https://github.com/department-of-veterans-affairs/content-build/pull/680, and let facilities team do it some other way, then merge in this pr once that is sorted?

& Note from Kev that the help text needs a content edit.

**Comment by swirtSJW** [comment] 2023-01-18 15:42
This could be either a Public Websites issue or a Facilities Issue.  It is most likely a Facilities issue to tackle only because they are by far the biggest user of the "featured" aspect.

**Comment by swirtSJW** [comment] 2023-01-18 15:44
@JayDarnell  I am adding the defect label because right now the "featured" aspect does not work the way anyone expects it to work and does not work the way the help text says it should work.

**Comment by jilladams** [comment] 2023-05-05 15:21
New occurrence of how this is now affecting Lovell: https://dsva.slack.com/archives/C0FQSS30V/p1683224452110549

**Comment by jilladams** [comment] 2023-05-11 20:28
We will not standardize this behavior, as the old mechanism for Featuring will be retired from Events entirely, and re-envisioned for Stories. Facilities owns the task moving forward, which may use an entirely different re-envisioned functionality. 

Leaving ticket open, and it may / should probably move to the new Facilities epic for Future state, when it is opened.

**Comment by davidmpickett** [comment] 2024-09-30 19:54
Closing as duplicate of https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13695

**Closed by davidmpickett** 2024-09-30 19:54 UTC
Labels: Defect, VAMC, Drupal engineering, Content forms, Facilities, UX writing, crew-sitewide, sitewide, Story, UX
