### ISSUE TITLE
Monitor GovDelivery Queue

### ISSUE THREAD

**Issue by indytechcook** [department-of-veterans-affairs/va.gov-cms#7135] opened 2021-12-02 19:36 UTC
## User Story or Problem Statement

If the GovDelivery Queue has not be triggered at XYZ then a alert should exist

## Acceptance Criteria
- [ ] Determine tool to host status page (e.g. Datadog)
- [ ] Identify outputs to display
- [ ] Testable_Outcome_Z

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [x] `Platform CMS Team`
- [ ] `Sitewide CMS Team`

**Comment by TheBoatyMcBoatFace** [comment] 2022-12-05 19:16
Alerts moving to #11675

**Closed by TheBoatyMcBoatFace** 2022-12-05 19:16 UTC
Labels: Needs refining, Platform CMS Team

**Comment by swirtSJW** [comment] 2023-06-09 20:54
@timcosgrove or @olivereri  I am in the process of documenting the govDelivery push.   Can either of you tell if this monitoring got implemented?  I can not find a record in #11675 that this is covered or if it is, what the alert threshold is or where it would alert the facilities team.

**Comment by swirtSJW** [comment] 2023-06-09 22:04
This is a tricky thing to monitor. 

- We never know when something will be added to the queue.  They get added by editors publishing VAMC Full with alerts or adding situation updates.
- We never know exactly when the queue will be processed, because it is only processed as the final step in a content-release.
- We never know when the queue should be completely emptied.  When the queue is processed by the content release, it only sends those items that were queued at the start of the content release (the time of the first graphql query), not any that were added to the queue during the content build (~45 min window of time).
- We can't run the check internally in the CMS when the Queue is triggered by the content-build, because the thing we are trying to detect is when the content build has failed to trigger it.

**Comment by swirtSJW** [comment] 2023-06-09 22:15
This isn't quite the same monitoring... I don't think. But there might be some monitoring of the callback being made
https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/READMES/downstream_dependencies.md?plain=1#L15

**Comment by swirtSJW** [comment] 2023-06-09 22:21
It looks like we are sending data to datadog, I am just not clear if there is any alarming done based on it 
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/6b669be1-3a17-4cb8-8f18-624544b9deab)

**Comment by swirtSJW** [comment] 2023-06-09 22:23
Probable duplicate of https://github.com/department-of-veterans-affairs/va.gov-cms/issues/6189

**Comment by swirtSJW** [comment] 2023-06-13 14:44
There is a new diagram of the process here https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/READMES/vamc-facilities.md#system-banner-alerts-and-situation-updates-to-govdelivery

and it is specifically the interaction between the Content-build and CMS that we want to monitor with this  issue.
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/9a18743a-64f8-4ad4-b550-dfaa204978bc)
