### ISSUE TITLE
Remove all Behat tests

### ISSUE THREAD

**Issue by edmund-dunn** [department-of-veterans-affairs/va.gov-cms#14331] opened 2023-07-12 19:31 UTC
## Description
All Behat tests will be removed. This is largely driven by the fact that the `goutte` driver has been abandoned. All functional testing needs to be moved to Cypress. 

## Acceptance Criteria
- [ ] Behat tests removed. 

### Team
Please check the team(s) that will do this work.

- [x] `CMS Team`
- [ ] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

**Comment by ndouglas** [comment] 2023-07-13 14:25
Duplicate of #12445.

**Closed by ndouglas** 2023-07-13 14:25 UTC
Labels: Drupal engineering, Needs refining, CMS Team
