### ISSUE TITLE
Perform VBA veteran interview sessions

### ISSUE THREAD

**Issue by jcklpe** [department-of-veterans-affairs/va.gov-cms#9951] opened 2022-07-28 22:36 UTC
## Description
[context](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/facilities/regional-offices/design)

## Acceptance Criteria
- [ ] Testable_Outcome_X
- [ ] Testable_Outcome_Y
- [ ] Testable_Outcome_Z
- [ ] Requires design review

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by davidmpickett** [comment] 2022-09-07 15:24
Duplicate of https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10194

**Closed by davidmpickett** 2022-09-07 15:24 UTC
Labels: ⭐️ Facilities, Needs refining
