### ISSUE TITLE
DSN Propose a wireframe graphic for what a VBA dashboard might look like

### ISSUE THREAD

**Issue by dsinla** [department-of-veterans-affairs/va.gov-cms#10701] opened 2022-09-12 16:46 UTC
Targeting Q1 for design (Dev can build a VC duplicate dashboard to get started - but no design input )

Start with existing VC research/feedback <-provided by DS
Incorporate findings from #10504 where Jay has been modeling content 

Reference: https://prod.cms.va.gov/section/vha/vet-centers/lincoln-vet-center

@omahane Get Figma access

**Comment by davidmpickett** [comment] 2023-05-18 20:03
Closing as duplicate of https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9954

**Closed by davidmpickett** 2023-05-18 20:03 UTC
