### ISSUE TITLE
Investigate Flakey Cypress Tests from 3/7/2024 Daily Deploy Failure

### ISSUE THREAD

**Issue by gracekretschmer-metrostar** [department-of-veterans-affairs/va.gov-cms#17465] opened 2024-03-08 18:41 UTC
## User Story or Problem Statement
To prevent the daily deploy from being blocked again, the CMS team needs to understand why the four cypress tests were failing and explore opportunities for improvement in the testing and deployment process.

## Description or Additional Context 
On 3/7/2024 the daily deploy for CMS failed because of two failed cypress feature files. The CMS team's hypothesis is that the tests failed because of missing data and was resolved when the deploy was manually rerun.

## Steps for Implementation
- [x] Understand the root cause of the cypress test failures.
- [x] Investigate if there are opportunities for these failures to be triggered in a lower environment, before reaching the daily deploy.

## Acceptance Criteria
- [x] Understanding the root cause of the cypress test failures. 
- [x] A plan of action of how to better from the cypress tests from blocking a daily deploy in the future.

## Team
Please check the team(s) that will do this work.

- [x] CMS Team
- [ ] Public Websites
- [ ] Facilities
- [ ] Accelerated Publishing

**Comment by keisterj-oddball** [comment] 2024-03-19 21:26
### Findings:

**Test Path:** _tests/cypress/integration/features/content_type/facilities/vamc/health_care_local_health_service.feature_
**Scenario:** _Administrators should be able to rename a VAMC Facility Health Service_
**Root Cause:**

> No cleanup steps are included at the conclusion of the test.  If, under any circumstances, there is stale data/state in the staging environment, the specific node being tested would be in an invalid state from the previous staging test run.

**Next Steps:**

> The original team that authored the test decided to remove the test, noting that testing an administrator's ability to rename a facility brings little value as administrators have nearly universal access within the CMS.  Instead, they found it more important to ensure that editors are not able to rename a facility.  An alternate approach if the original test is needed, could be to add clean up steps in the test to ensure the node is in a state that meets the test's pre-conditions.

**Link to Ticket:** https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17524

**Test Path:** _tests/cypress/integration/features/content_type/facilities/vba/vba_facility.feature_
**Scenario(s):**
_Test restricted_archive workflow prevents archiving a VBA Facility as a VBA editor
Test restricted_archive workflow allows archiving a VBA Facility as a content_admin
Enable banner segment and ensure expected fields are present_
**Root Cause:**

> No cleanup steps are included at the conclusion of "Enable banner segment and ensure expected fields are present". If, under any circumstances, there is stale data/state in the staging environment, the specific node being tested would be in an invalid state from the previous staging test run.

**Next Steps:**

> The suggestion to add cleanup steps was presented to the team that originally authored these tests, and they will be writing up a ticket to make any required changes.

**Link to Ticket:**

**Comment by keisterj-oddball** [comment] 2024-03-19 21:32
**Re:** _Investigate if there are opportunities for these failures to be triggered in a lower environment, before reaching the daily deploy._

> These failures would have surfaced if run repeatedly on a developer's local machine.

**Comment by keisterj-oddball** [comment] 2024-03-20 14:35
Closing as investigation is complete. Any remaining refactoring work for the flaky tests is linked in my comment above.

**Closed by keisterj-oddball** 2024-03-20 14:35 UTC
Labels: CMS Team
