### ISSUE TITLE
Update header / footer product documentation to cover technical behaviors

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#13351] opened 2023-04-19 18:38 UTC
## Existing Documentation

https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/header-footer/engineering

## Description

This will be done as a follow on to the new Federal Header/Footer work. (1/24/2024)

The Design System team is interested in potentially owning the Header and Footer as a design system component. If that transition takes place, we need to evaluate what other functionality is hidden in the Header / Footer and either needs to be mitigated or transitioned to that team.

In general: we should also have these things documented re: state of what is true today, even if no transition.

### User story
> _Describe the audience/user, enhancement or fix, and value / outcome desired._

**AS A(N)** Design System owner
**I WANT** to understand the scope of the current header/footer functionality
**SO THAT** I can effectively support these products moving forward.

**AS A(N)** Product owner
**I WANT** to have accurate documentation of the technical behaviors of the header / footer
**SO THAT** teams can effectively support these products moving forward.

### Engineering notes / background
Areas we already know of: 
* Injected header / [proxy-rewrite app](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite)
* Drupal SSOT data loading (including #13185)
* Sign in modal - ownership outside PW, etc.
* Veterans Crisis Line modal
* Header menu populated by Drupal
* Footer menu _not yet_ populated by Drupal, BUT footer menus are created in Drupal, just not yet integrated

Existing docs: 
* https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/header-footer -- this should be the final home of all documentation
* https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/public-websites/header - this should move into the path above, not urgent or an AC, but just a flag: don't add on in this location

## Acceptance criteria

- [ ] Header code has been reviewed for any functionality happening that is not immediately visible from the front-end
- [ ] Footer code has been reviewed for any functionality happening that is not immediately visible from the front-end 
- [ ] Findings are documented in this ticket

**Comment by FranECross** [comment] 2024-08-19 17:27
@jilladams I think this ticket is redundant/a dupe of the header/footer ticket you and Randi have been reviewing/updating. If true, we can close this one.

**Comment by jilladams** [comment] 2024-08-19 20:49
Good catch! If you don't mind, let's leave it open -- I haven't updated #18866 to rescope that beyond just the injected header, so this ticket will actually be handy to cover the rest of the docs review. I'll update to reflect I've already gotten started.

**Comment by jilladams** [comment] 2024-09-05 18:53
Help I need from @randimays :
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/header-footer/engineering - technically true?
  - [ ] Make sure the data origin / local storage is documented

**Comment by randimays** [comment] 2024-09-05 21:12
@jilladams Updated https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/header-footer/engineering 👍🏻

**Closed** 2024-09-05 23:04 UTC
Labels: VA.gov frontend, Needs refining, VA.gov megamenu, Public Websites, Injected header, sitewide, VA.gov Footer

**Comment by jilladams** [comment] 2024-09-23 19:29
From handoff meeting: 
* Ownership changes are signed off by Matt Dingee, Amanda Klausmeier, and Michelle Middaugh, effective today.
* If markup breaks injection, we need to be able to detect that before deploy. We do not want issues like that to be discovered after build / injection. This should be a goal, per Matt.
  * VFS teams should not update the header and footer, apart from Identity modifying the auth menu / login modal. 
  * How much can be automated to make it more bulletproof is a question to ask for long-term stability.
  * Micah will walk through injected header testing with DST engineers next week, and point out the PR template area.
  * DST may end up wanting CMS access long-term, if data issues become a blocker to progress.
* Design / Research notes: 
  * DST may make logical design changes, and AmandaK is available to consult. 
  * System Team doesn't have research capacity so any major redesign efforts will need support from Sitewide.

We need to verify DST are now codeowners on: 
* proxy-rewrite
* in content-build megamenu 
* vets-website platform/sitewide/header
* crisis panel from the footer

- [ ] @randimays to verify content-build codeowners changes and
- [ ] remove FE COP from codeowners of header/ footer in vets-website and content-build
- [ ] Jill to announce the transition in ToT
