### ISSUE TITLE
VA Forms not flagging Title changes during migration

### ISSUE THREAD

**Issue by dsasser** [department-of-veterans-affairs/va.gov-cms#17569] opened 2024-03-20 17:08 UTC
## Status
**[2024-04-05]** The CMS team took on this work. Putting this story into the Ice Box just in case we need to resurrect at any point.

## Description
The https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17450 revealed that the https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17450#issuecomment-2008310102 during the nightly Forms migration.

### User story

**AS A** Forms Administrator
**I WANT** all Forms who's title has changed to be flagged as such
**SO THAT** so that I can report and react to the title changing if needed

### Engineering notes / background
TBD

## Acceptance Criteria
 - [ ] **Scenario: Forms Administrator flags title changes**
  - Given a Content Publisher is reviewing a form
  - When the form's title is changed
  - Then the Content Publisher can see the Changed Title in the [VA Forms Changed Title queue](https://prod.cms.va.gov/admin/content/va-forms/changed-title) and respond accordingly
 
 - [ ] **Scenario: Forms Migration flags title changes**
  - Given the forms migration 
  - When the form's title is changed
  - The system sets a flag and the Content Publisher can see the Changed Title in the [VA Forms Changed Title queue](https://prod.cms.va.gov/admin/content/va-forms/changed-title) and respond accordingly
- [ ] Document the findings re: how migrations do / don't modify Form Name vs. Form Title Drupal fields in https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-a-va-form/engineering/data/data.md

**Comment by jilladams** [comment] 2024-03-22 15:33
Per Facilities research: 
> So I think this is something that happened in Drupal core. It looks like in 10.2 they made it so that when an entity is updating from a migrate there is an isSyncing flag that is being set. I guess this keeps the migrate from being able to set the update as a new Revision (see https://www.drupal.org/node/3052115). There is a workaround that's documented here: https://www.drupal.org/node/3426397

This is likely the same root cause for both revision logs, and for Title flags not getting correctly applied. Facilities has Drupal capacity to run this, so Michael is going to rally folks to discuss & make sure everyone's ok with the workaround.

**Comment by jilladams** [comment] 2024-03-22 16:25
@dsasser this should've been an AC on the spike, but since I didn't think of it til now, I added an AC on this ticket: 

- Document the findings re: how migrations do / don't modify Form Name vs. Form Title Drupal fields in https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-a-va-form/engineering/data/data.md

**Comment by jilladams** [comment] 2024-06-07 21:15
Resolved by the CMS work: 

![Screenshot 2024-06-07 at 2 15 23 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/85581471/eed9e5ab-bde7-4e7b-88af-8b873e9504a3)

**Closed by jilladams** 2024-06-07 21:15 UTC
Labels: Drupal engineering, Find a form, Public Websites, Icebox
