### ISSUE TITLE
Make Knowledge Base more product-oriented

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#5704] opened 2021-06-26 01:29 UTC

**Comment by EWashb** [comment] 2023-10-20 03:00
@joagnitti I think this is a dupe of your current work and the KB initiative. IF you think so too, can you close this? If not, let's refresh this issue

**Comment by joagnitti** [comment] 2023-10-20 12:52
@EWashb Looks like a dupe to me, will close! Pretty cool that we're reviving this work, years later 💪

**Closed** 2023-10-20 12:52 UTC
Labels: Epic, Knowledge Base, Icebox, CMS Team
