### ISSUE TITLE
Ensure GovDelivery is working on staging

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-cms#5545] opened 2021-06-08 16:26 UTC
## Description

As a Veteran, I need reliable and timely delivery of notifications from my VAMC, so that I have access to important information affecting me.

## Acceptance Criteria

- [x] Staging uses GovDelivery service account
- [x] Notifications have been tested and confirmed working on staging

**Comment by jefflbrauer** [comment] 2021-07-06 14:29
I tried on staging and got this, but it could be because I'm not whitelisted?

Debug information
The debug information below may be of interest to the administrator / help desk:

SimpleSAML\Error\Error: UNHANDLEDEXCEPTION

Backtrace:
1 www/_include.php:17 (SimpleSAML_exception_handler)
0 [builtin] (N/A)
Caused by: SAML2\Exception\InvalidArgumentException: Invalid Argument type: "non-empty string" expected, "string" given
Backtrace:
5 /var/www/cms/docroot/vendor/simplesamlphp/saml2/src/SAML2/Exception/InvalidArgumentException.php:21 (SAML2\Exception\InvalidArgumentException::invalidType)
4 /var/www/cms/docroot/vendor/simplesamlphp/saml2/src/SAML2/DOMDocumentFactory.php:28 (SAML2\DOMDocumentFactory::fromString)
3 /var/www/cms/docroot/vendor/simplesamlphp/saml2/src/SAML2/HTTPPost.php:74 (SAML2\HTTPPost::receive)
2 modules/saml/www/sp/saml2-acs.php:35 (require)
1 lib/SimpleSAML/Module.php:260 (SimpleSAML\Module::process)
0 www/module.php:10 (N/A)

**Comment by cmaeng** [comment] 2021-07-08 15:40
@ElijahLynn what's the ETA on this and then getting things turned on in prod? want to give Dave a heads up on when to expect it. thanks!

**Comment by ElijahLynn** [comment] 2021-07-15 21:49
Turns out this only worked on the first request from Jenkins, and not subsequent requests. @acrollet and I tracked this down to being an issue likely with the Dynamic Page Cache we added a while ago and @swirtSJW helped us get the correct code changed merged and released here > https://www.drupal.org/project/govdelivery_bulletins/issues/3223883. 

PR on the way to update via Composer.

**Closed** 2021-07-16 15:41 UTC
Labels: CMS notifications, Core Application Team, DevOps, Needs refining

**Comment by ElijahLynn** [comment] 2021-07-16 16:32
Confirmed that creating a new alert, triggers the build which then triggers the deploy, which triggers the callback which then processes the queue and sends the email bulletin. The source URLs below will all be 404 eventually but I put them in so we could see the URL pattern they can be found at. 

![image](https://user-images.githubusercontent.com/1504756/125979378-3729ac8f-2584-447e-8126-868143edb66c.png)
source: https://staging.cms.va.gov/va-pittsburgh-health-care/vamc-banner-alert/2021-07-16/elijah-test-staging-july-16th-9am-pt


![image](https://user-images.githubusercontent.com/1504756/125979302-2a65da9d-4b9b-490d-aae2-bf431b292947.png)
source: http://jenkins.vfs.va.gov/job/deploys/job/content-build-vagovstaging/307/console

![image](https://user-images.githubusercontent.com/1504756/125979086-b3b8a4ce-bcbd-439b-a71c-fc1481f9b724.png)
source: https://staging.cms.va.gov/admin/reports/dblog

![image](https://user-images.githubusercontent.com/1504756/125979486-ff31ee17-d682-419e-811f-59f35a665ab0.png)
source: https://staging.cms.va.gov/admin/reports/dblog/event/937

![image](https://user-images.githubusercontent.com/1504756/125979958-43c9be81-2712-4b39-9725-7d0128571e90.png)
source: my email on the subscriber list for the Pittsburgh topic bulletin
