### ISSUE TITLE
Design review after Design System typography updates are made

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#17315] opened 2024-02-22 19:38 UTC
## User Story or Problem Statement
The Design System will be updating typography in late March. This is a design review of various Facilities pages to make sure no unintended consequences occurred after the updates.

## Acceptance Criteria
- [ ] Testable_Outcome_X

**Comment by davidmpickett** [comment] 2024-04-11 23:48
@jilladams I'm closing this as a dupe of 17806

**Closed by davidmpickett** 2024-04-11 23:48 UTC
Labels: Design, Facilities, Needs refining, UX
