### ISSUE TITLE
Make the content of the PPMS trainings array available via vets-api 

### ISSUE THREAD

**Issue by kmariepat-cityfriends** [department-of-veterans-affairs/va.gov-cms#13359] opened 2023-04-20 13:13 UTC
##### Background 
There is an array from PPMS that includes information about providers that have completed the provider core training. We need to make that array consumable by vets-api so that it can be used on front end views. This work aligns to the updates being made to facility locator in order to identify providers that have completed the training on the front end.

##### Example data
Queries that successfully return trainings are available here:
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11627#issuecomment-1516980222

#### Acceptance Criteria 
- [x] I expect that the vets-api can return the values of the trainings array in the ProviderLocator end point
- [x] I expect that if possible this is an optional request 
- [x] I expect that vets-api console access is verified
- [ ] I expect that documentation in https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/facility-locator/data/ppms/ppms-data-discovery.md is updated to modern state of relevance after these changes, in any location that references PPMS, API data sources, or how filters connect to API endpoints
  - [ ] Add any learnings about use / data returned from facility-services endpoint
  - [ ] Add any new notes to Provider Locator section, regarding training data
  - [ ] Read / review the rest of the doc & update as needed
- [ ] I expect that tests are added to cover code changes

**Comment by kmariepat-cityfriends** [comment] 2023-04-20 16:19
Will also need a front end card to update for facility locator

**Comment by jilladams** [comment] 2023-05-10 16:45
@maxx1128 @kmariepat-cityfriends @ryguyk  am I right that this card is Ruby, and is the one Ryan alluded to during planning?

**Comment by maxx1128** [comment] 2023-05-12 12:20
@jilladams This is definitely a Ruby ticket, but I'm unsure if it's the one @ryguyk was talking about.

**Comment by ryguyk** [comment] 2023-05-13 01:37
This is the ticket I mentioned.

**Comment by mmiddaugh** [comment] 2023-06-07 16:32
@jilladams @kmariepat-cityfriends should we mark this as "blocked" pending assistance from the PPMS dev team?

**Comment by jilladams** [comment] 2023-06-07 22:49
@mmiddaugh @kmariepat-cityfriends yes - also - as a sideline, @maxx1128 is pursuing vets-api console access (via https://github.com/department-of-veterans-affairs/va.gov-team/issues/59791) and there's a slim chance that will tell us things we don't know right now about how to get at this data. So: I think we could mark it blocked, by either both of those things (PPMS dev team notes and/or console access.)

**Comment by jilladams** [comment] 2023-06-08 22:41
from that email: 

I have sent another message to try and get your answers but in the meantime. Provider trainings should be located on the Provider Locator endpoint. I have a screenshot of what the result should look like from the APIM end point.

![image002](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/85581471/78bf4dce-93a8-431f-8bbe-3ce28ac5a515)

**Comment by jilladams** [comment] 2023-06-20 22:10
Lane was affected by the workflow integration with the Speedrun board. Moving back to In progress.

**Comment by mmiddaugh** [comment] 2023-06-26 19:24
Found the following info posted in the PPMS Integration OFfice Hours Forum in Teams
[5/6/2022 8:47 AM] Snyder, Linda L. (GovCIO)
    

The following DWS endpoints will be updated with Sprint 16.0 to allow downstream partners to pull Provider Training Information. The updates are currently deployed to INT (NPROD)

- get /ProviderLocator	
- get /Providers	
- get /ProviderServices

The following Provider Training information will be provided in these updated endpoints:

- Course Name
- Course Code	
- Course Completion Date	
- Course Expiration Date

**Comment by davidmpickett** [comment] 2023-07-05 19:16
@mmiddaugh Do you have a sense of if this is unblocked and @maxx1128 could move forward once he returns?

**Comment by jilladams** [comment] 2023-07-05 19:23
(We need Max to try and confirm if that's true or not.)

**Comment by maxx1128** [comment] 2023-07-10 20:13
I believe this will unblock the ticket but am trying to confirm it now.

**Comment by jilladams** [comment] 2023-07-18 01:16
Slack thread from 7/11: https://dsva.slack.com/archives/C0FQSS30V/p1689090373754209

**Comment by davidmpickett** [comment] 2023-07-18 19:56
@maxx1128 Can you add a short summary of what you accomplished this sprint and what the current status is going into next sprint?

**Comment by maxx1128** [comment] 2023-07-18 23:38
@davidmpickett @omahane  and I both reached out to the PPMS support team to find out if the Training data is available on the NProd (non-production) environment. They said they would open a support ticket for us to either confirm if the data was on NProd and show us where, or add an instance of the needed data for us. The ticket was opened roughly a week ago and we have not had any updates since.

Michelle also connected me to Mark Dewey, who used to be on the Facilities team. He looked at my current code and said it looks like it should get the data from the API, and agreed the best course of action is to confirm if it's on the API endpoint I'm hitting or not.

**Comment by jilladams** [comment] 2023-07-28 18:30
Noting from 1:1 with Max: 
* ACs updated for modernity
* Right now endpoint / and vets-api console access are working
* Part 1: expanding the data net to pull in more data from PPMS: easy
* Part 2: verifying that we can catch the right data -- we have to merge adding the data to vets-api, in order to then query vets-api to receive it back to make sure that worked: 
    * isn't clear if it can be feature flagged
    * we don't think adding new data will break anything - it's not exposed in the FE. But: that means people may be able to find that data in the network response via dev tools. Do we care about this? (aka is it worth the effort to try and feature flag?)

**Comment by jilladams** [comment] 2023-07-31 23:47
Since we got signoff from Platform, our PO, and our team re: merging without a feature flag, I have no concerns about going that route.

**Comment by jilladams** [comment] 2023-08-02 00:15
@maxx1128 https://github.com/department-of-veterans-affairs/vets-api/pull/13213 merged. What remains here to close out, from the ACs?

**Comment by jilladams** [comment] 2023-08-02 16:16
Confirmed in planning: in Prod we have not yet been able to verify post-merge.

**Comment by jilladams** [comment] 2023-08-03 15:20
From data Michelle provided, Max was hitting same endpoint / location and getting different results than expected. Got back the expected provider, but without training data.

Would need location + specialty for each provider. **Max**: Need to double check that location is present for each in the data provided.

Hitting staging endpoint. **Max**: Check production endpoint access. We think the dataset is pointing to records in production that may not contain the same data in staging.

Can we request that Prod data gets synced to Staging? Not likely to get traction.

**Comment by mmiddaugh** [comment] 2023-08-07 18:45
To confirm, this is how results from the APIM endpoint should look

![image.png](https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/bd3bc3c8-cbd0-4ffb-a96f-6578855c5b0f)

**Comment by mmiddaugh** [comment] 2023-08-07 18:46
@maxx1128 please see above

**Comment by jilladams** [comment] 2023-08-16 22:23
Per discussion with @mmiddaugh & @xiongjaneg (dms in slack, [here](https://dsva.slack.com/archives/C05KUDPM60P/p1692123205217749)), this should be considered paused until we can identify help from PPMS to work out the Staging vs. Prod data problems. Removing from Sprints til we hear more / pull it back in, and adding Blocked label.

**Comment by jilladams** [comment] 2023-09-27 16:21
From planning: noting that we have a meeting with PPMS next week (week of 10/2). Facility Locator FE is not necessarily a priority for right now, but confirming that the PPMS data exists where they say it exists is.

Per Max, the meeting could result in 2 paths: 
1. Current work may be correct, we can pull the data from their indicated location. Done.
2. May find that our work doesn't expose the data where we are pointed to pull it from, and need to revise our approach.

**Comment by xiongjaneg** [comment] 2023-10-03 22:01
received access, keys, and sample data so this should be unblocked, will review at pre-refinement to see if any updates are needed to this ticket

**Comment by maxx1128** [comment] 2023-10-25 01:50
This pull request has been merged for this sprint (95), and it just needs to be confirmed as working tomorrow in production. Once that's done, it can be closed.

**Comment by maxx1128** [comment] 2023-10-25 01:53
I couldn't wait and did a quick confirmation at [this production API endpoint.](https://api.va.gov/facilities_api/v1/ccp/provider?specialties[]=101YP2500X&page=1&per_page=10&radius=26&address=268%20High%20Street,%20Morgantown,%20West%20Virginia%2026505,%20United%20States&bbox[]=-80.705944&bbox[]=38.879681&bbox[]=-79.205944&bbox[]=40.379681&latitude=39.629681&longitude=-79.955944) The training data is coming through! cc: @jilladams @mmiddaugh 

<img width="799" alt="Screen Shot 2023-10-24 at 9 52 36 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/10790736/874d9d58-45cb-4653-ad17-a7472ca8ba80">

**Closed** 2023-10-25 15:11 UTC
Labels: VA.gov frontend, Facilities, Facility Locator, Ruby
