### ISSUE TITLE
Jenkins Deploys failing due to test timeouts

### ISSUE THREAD

**Issue by indytechcook** [department-of-veterans-affairs/va.gov-cms#1657] opened 2020-05-01 12:59 UTC
We have several jenkins jobs failing due to performance tests failing.  This is occurring more consistently:

```
       Time: 55.14 seconds, Memory: 136.00MB
   
       There was 1 failure:
   
       1) tests\phpunit\LoginPerformance::testLoginPerformance with data set #0 (2)
   
       Operation took 2.021 seconds which is longer than the benchmark of 2 seconds.
   
       Failed asserting that '2.021' is less than 2.
   
       /var/www/cms/tests/phpunit/PerformanceLoginTest.php:47
```

**Comment by ElijahLynn** [comment] 2020-05-20 10:40
I dug into this locally with Blackfire and it _appeared_ to be the "Find content by section" block on the `/user/UID` path that was adding a half second to the response. The block is installed by va_gov_user.module that is loaded as the last request from `$this->drupalLogin($author);`. I profiled 5 runs with it enabled and without and noticed a 22.57% (.46 seconds) increase in request time, from 2.06 (disabled) > 2.52 (enabled) seconds. The [Blackfire profile diff can be viewed here, showing which functions increased time](https://blackfire.io/profiles/compare/aa7a5f32-9d74-4ae5-9fd8-fd1af596ff71...fa483559-4955-4e0a-ad75-d68fc13c3e0a/graph?settings%5Bdimension%5D=cpu&settings%5Bdisplay%5D=focused&settings%5BtabPane%5D=nodes&selected=&callname=Drupal%5CCore%5CRender%5CRenderer%3A%3AexecuteInRenderContext). 

![image.png](https://images.zenhubusercontent.com/5cdc72c50b7efe3f164150b2/6223b8d1-1165-41db-979d-7457744b377d)

![image.png](https://images.zenhubusercontent.com/5cdc72c50b7efe3f164150b2/9e25dfc7-5cbd-4524-b49b-4386f3d4b7cd)

But _then_ I realized I had my settings.local.php to `$settings['cache']['bins']['page'] = 'cache.backend.null';` which is not what DEV/STAGING have. So I unset that and ran again and now my benchmarks were showing a -32.21% (decrease) in response time for `/user/UID`, from 0.75 (disabled) > 0.51 (enabled) seconds. 

![image.png](https://images.zenhubusercontent.com/5cdc72c50b7efe3f164150b2/b7d191f2-7228-4015-99da-5ec2d77f3593)

So, seeing sub-1 second responses locally is making this hard to determine what is happening.

**Comment by ElijahLynn** [comment] 2020-05-20 22:13
As discussed on standup this morning with @swirtSJW and @oksana-c we are all okay with moving it up to 3 seconds based on the research above, below is our reasoning:
1. We did the research above and understand better what is going on now
1. Based on that research it appears this isn't a performance regression that is affecting every page on the site, only a single page, because of a block that is providing useful functionality
1. Our PHP 7.4 upgrade may bring this time back down
1. Most users login with PIV which is already quite a long process (5-10 seconds)
1. Most of the additional time is spent rendering, we may want a followup issue coming out of this to ensure the block is being cached for that user, on subsequent loads
1. I am making a PR for this issue to increase the time from 2-3 seconds

**Comment by ElijahLynn** [comment] 2020-05-21 03:36
K, once https://github.com/department-of-veterans-affairs/va.gov-cms/pull/1806 is merged we can mark this as done (for now).

**Closed** 2020-06-19 06:01 UTC
Labels: Critical defect, Defect, DevOps, Performance, Unplanned work
