### ISSUE TITLE
DSN: Review wording of modifications to taxonomy selector 

### ISSUE THREAD

**Issue by dsinla** [department-of-veterans-affairs/va.gov-cms#11472] opened 2022-11-04 15:39 UTC
## Description
Facilities team has recently modified/added checkboxes on the taxonomy selector to determine what taxonomy terms show in the drop-down menu of Services in the Services Content Type. 

[Modify taxonomy selector](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11138)

The current wording displays "Show for VBA Facilities". Can we get some eyes on the wording for any Ux improvements?

### Example
[Adaptive Sports term](https://prod.cms.va.gov/taxonomy/term/112/edit)
![prod cms va gov_taxonomy_term_112_edit](https://user-images.githubusercontent.com/766573/200071709-8de9245f-7df2-40e9-8a35-7c120c902e08.png)

## Acceptance Criteria
- [ ] New UI changes and wording are reviewed and recommendations for improved wording are made

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [x] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by EWashb** [comment] 2022-11-04 15:41
can you add a link for review to the ticket as well @dsinla?

**Comment by omahane** [comment] 2022-11-04 21:03
@EWashb I added a link and screenshot. 
We need to change the labels to be sentence case:
| Current VBA-specific taxonomy labels | Corrected labels |
| -------------------------------------- | -----------------|
|VBA Patient Friendly Name | VBA patient friendly name |
|VBA Common Conditions | VBA common conditions |
|VBA Description | VBA description |

Can we add that to the scope of this issue?

**Comment by dsinla** [comment] 2022-11-07 16:22
Moving to icebox - Could use design review, but not critical for now

**Comment by davidmpickett** [comment] 2023-10-17 00:46
Duplicate of https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14891

**Closed by davidmpickett** 2023-10-17 00:46 UTC
Labels: Facilities, Needs refining, Icebox, VA services taxonomy, UX debt
