### ISSUE TITLE
Double quotes breaking text field on Vet Center page

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-cms#12207] opened 2023-01-10 20:30 UTC
## Describe the defect
Double quotes breaking text field on Vet Center page

## To Reproduce
Add double quotes to the operation status of a Vet Center Community Access Point. When I add them, the text after the double quote gets cut off on the preview.

## AC / Expected behavior
The full text, including the double quotes, to show up on the preview page

## Screenshots
<img width="730" alt="Screen Shot 2023-01-10 at 11 48 31 AM" src="https://user-images.githubusercontent.com/1318579/211655526-cc88b324-bb50-4e4a-8f73-ed8dae363194.png">
<img width="560" alt="Screen Shot 2023-01-10 at 10 51 48 AM" src="https://user-images.githubusercontent.com/1318579/211655547-75918fc3-fdde-4931-8878-e571a4c741a5.png">

 ## Additional context
https://dsva.slack.com/archives/CDHBKAL9W/p1673371769809239

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS workstream (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by laflannery** [comment] 2024-05-06 21:25
This I think is a dup of https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17134 and could probably be closed

**Comment by davidmpickett** [comment] 2024-07-01 23:03
Dupe of https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17134

**Closed by davidmpickett** 2024-07-01 23:03 UTC
Labels: Defect, Drupal engineering, Facilities, Needs refining, Vet Center, sitewide
