### ISSUE TITLE
[Bug] Search box - Spaces-only query triggers search & inaccurate error-message

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-cms#12073] opened 2022-12-09 19:10 UTC
## What happened?
In Staging Redesigned Homepage > Search box, Header search, and Search results keyword form: submitting spaces-only query-term actually triggered search, and on **Search VA.gov** page a 400 error-message was displayed.

## Steps to Reproduce
- URL: https://staging.va.gov/new-home-page/
- In **Search** text-box, input 3+ **spaces**, then click **Search** button.  Observe that:
  -  browser navigates to **Search VA.gov**, as if a valid query was submitted.
  - on **Search VA.gov** page, the error-message mentions a fault "at our end", instead of actual invalid query-term.
- On **Search VA.gov** page, click into text-field.  Observe that spaces query-term is still in place, as if they constituted a valid search.
Error message: (400)
Your search didn't go through
We’re sorry. Something went wrong on our end, and your search didn't go through. Please try again

## Desired behavior
- [ ] Spaces-only query-term should not trigger search.
- [ ] IF search-trigger cannot be prevented:
  - [ ] error-message on **Search VA.gov** page should accurately describe invalid query.
  - [ ] text-field should not preserve inputted spaces.

**Video**

https://user-images.githubusercontent.com/587583/206778287-bc928237-8e5f-464c-a79f-e3eefc83bafc.mp4

## Acceptance Criteria
[see **Desired behavior** above]

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by jilladams** [comment] 2023-12-22 19:18
@FranECross this is a legit bug that reproduces today, and is cousin to the search error that @chriskim2311 implemented last sprint, so there may be some recency-efficiency to knocking this out soon if we are light on FE work.

**Comment by chriskim2311** [comment] 2023-12-22 19:29
@jilladams @FranECross I can definitely look at this over the code freeze break

**Comment by jilladams** [comment] 2023-12-22 19:35
Thanks, Chris -- noting, not urgent, and sprint work comes first esp mobile banners. But if you're looking for stretch, etc.

**Comment by chriskim2311** [comment] 2024-01-02 18:54
Code complete pending PR review

**Comment by randimays** [comment] 2024-01-02 20:18
I think we need @thejordanwood to lean in here with wording for this "invalid input" case. When the user searches with just spaces, they're still getting this:

<img width="594" alt="Screenshot 2024-01-02 at 2 16 24 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/19175324/3631b2f6-749e-4b73-97f6-0c9320cf27f7">

We need to show a message that indicates their query was invalid instead, since this isn't our error.

**Comment by thejordanwood** [comment] 2024-01-02 20:57
> **Your search didn't go through**
> Enter a search term that contains letters or numbers to find what you're looking for.

This is my suggestion, but I'm open to feedback. 

cc: @jilladams @laflannery (if interested)

**Comment by chriskim2311** [comment] 2024-01-04 19:56
<img width="1207" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMG1kQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ec606eeec886b397f6135417fc3a405e2d0660a8/Search_Results___Veterans_Affairs.png" alt="Search_Results___Veterans_Affairs.png" />

How does this look @thejordanwood @randimays

**Comment by randimays** [comment] 2024-01-04 22:21
@chriskim2311 Looks good to me!

**Comment by thejordanwood** [comment] 2024-01-04 22:27
@chriskim2311 This looks great!

**Comment by chriskim2311** [comment] 2024-01-09 22:24
Verified in prod that the new error message is displaying properly and preventing the search with empty strings. Closing!

**Closed by chriskim2311** 2024-01-09 22:24 UTC
Labels: Defect, VA.gov frontend, Public Websites, VA.gov Search
