### ISSUE TITLE
Q&A removed from the Q&A group entity reference field should not return `null`

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#3318] opened 2020-10-27 19:55 UTC
## Description

When a Single Q&A is deleted from Multiple FAQ Q&A group entity reference field, then its value becomes null, instead of the item being removed from the array of Q&As attached to the Q&A group.
This trips up the template logic. This has been temporarily patched in the template, but we need to resolve an issue at data provider (CMS).

## Acceptance Criteria

- [ ] When a Q&A is deleted from "FAQ - multiple Q&As" Q&A group entity reference field, the reference is completely removed in resulting GraphQL data instead of returning `null`

## Implementation notes

* troubleshoot the process of adding / removing Q&A to Q&A group on "FAQ - multiple Q&As" node to understand whether it's Drupal data or GraphQL issue

`/graphql/explorer` sample query:

```
{
  nodeQuery(limit: 10000, offset: 0, filter: {conditions: [{field: "type", value: ["faq_multiple_q_a"]}]}) {
    entities {
      entityId
      entityBundle
      ... on NodeFaqMultipleQA {
        fieldQAGroups {
          entity {
            ... on ParagraphQAGroup {
              fieldSectionHeader
              fieldQAs {
                entity {
                  ... on NodeQA {
                    title
                    entityId
                    entityBundle
                    entityPublished
                    fieldAnswer {
                      entity {
                        entityType
                        entityBundle
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
```

**Comment by kaise-lafrai** [comment] 2020-11-10 17:12
Seems to be the same issued in the DB

`Filter...
Filter...
Filter...
Filter...
Filter...
Filter...
Filter...
q_a_group	0	13480	161981	en	0	8421	
q_a_group	0	13480	161981	en	1	8422	
q_a_group	0	13480	161981	en	2	8424	
q_a_group	0	13480	161981	en	3	8428	
q_a_group	0	13480	161981	en	4	8425	
q_a_group	0	13480	161981	en	5	8426	
q_a_group	0	13480	161981	en	6	8429	
1-7 of 7`

**Comment by kaise-lafrai** [comment] 2020-11-12 17:58
This is working as intended. See below for testing steps:

- Navigated here: /node/8471/edit
- Removed a single Q&A
- Saved
- Published
- GraphiQL results for '8471' reflect the removal of the single Q&A.
- Create a new single Q&A and save as Draft
- Navigate back here: /node/8471/edit
- Add the draft Q&A in the Q&A Group section
- Save
- Publish
- GraphiQL results for '8471' reflect the newly added Draft single Q&A.

The tests above confirm that the editor MUST save and publish a node in order for the GraphiQL query to show changes made.

Moving this ticket to done.

**Comment by kaise-lafrai** [comment] 2020-11-12 17:59
@oksana-c Moving this to done. Testing steps reflected in above comment.

**Closed** 2020-11-23 15:42 UTC
Labels: Defect, Drupal engineering, Needs refining
