### ISSUE TITLE
DSN: Flesh out plan for content design/VA services taxonomy and update Epic

### ISSUE THREAD

**Issue by dsinla** [department-of-veterans-affairs/va.gov-cms#11134] opened 2022-10-06 19:30 UTC
## Description
We need our first draft of plan for how we will tackle the content design that incorporates VBA services into the VA services taxonomy.

## Acceptance Criteria
- [x] Write the user story 
- [x] Create issues and add dependencies
- [x] Epic #10517 has issues and order of operation established and verified with supporting teams 

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by davidmpickett** [comment] 2022-10-07 14:14
I know this came up yesterday in conversation with @JayDarnell @swirtSJW & @dsinla. Was there a specific task here that is blocking Jay's work? Otherwise, this feels like a duplicate of the #10517 which is blocked by research

**Comment by davidmpickett** [comment] 2022-10-10 22:51
I'm going to flag this is a stretch for this sprint. Lovell taxonomy needs take priority

**Comment by davidmpickett** [comment] 2022-10-11 15:20
@RWEagans @dsinla Flagging this as unlikely to fit in sprint 69

**Comment by davidmpickett** [comment] 2022-10-18 22:43
Took a crack at #10517. Perhaps something to talk through in Refinement this week?

**Comment by davidmpickett** [comment] 2022-10-20 15:22
Discussed in Scrum

**Closed by davidmpickett** 2022-10-20 15:22 UTC
Labels: Design, ⭐️ Facilities, Regional office, Content, VA services taxonomy
