### ISSUE TITLE
Design for VAMC System-level mental health phone number

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#17169] opened 2024-02-08 18:37 UTC
## Description
CMS became the source of truth for Mental health phone numbers in #9717
Content model options were provided in #16655

- [VAMC System content type](https://prod.cms.va.gov/node/add/health_care_region_page)
- [VAMC Facility content type](https://prod.cms.va.gov/node/add/health_care_local_facility)

![screencapture-prod-cms-va-gov-node-1823-edit-2024-02-09-13_28_59](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/e41011f5-038d-47e5-a376-af86f2134858)

## Design
Mental Health Numbers page in the [VAMC facilities Figma file](https://www.figma.com/file/bwnxdqh3b7W7Xp6KuQ4Sab/VAMC-facilities?type=design&node-id=6%3A2431&mode=design&t=6RvVwdDWYCYFgjJu-1)

## Background
Mental health numbers appear in a number of places throughout the VAMC sites and in the Facility Locator. 
- The main number is displayed at the facility level in the Facility Locator search results and in the Locations and Contact information block on VAMC pages. 
- One or more phone numbers can be added at the Mental health service level. 
- Contact information for Care Coordinators are displayed on required Mental health care pages (which are linked from within the service accordion)

**Problems to solve**

- The contact information for mental health care should be present, accurate, and represent the best way for a Veteran to access mental health care for that facility/system. 
- The contact information displayed should be consistent, accurate, and clearly labeled.
- VHA Facilities are required to provide a phone number which Veterans can all to access mental health care, even if they do not offer mental health services. (They likely list the VA Medical Center for the system - although some systems have more than one.)  

## Current content model includes
- A new Telephone number field is added to the **VAMC System** content type
  - **Field label:** Default mental health phone number 
  - **Help text:** This phone number will be the default mental health phone number for VAMC facilities in this system. You can override this at the facility level if there is a more specific number. For more guidance, read [the Knowledge Base article on mental health phone numbers (opens in a new window).](https://prod.cms.va.gov/help/vamc/how-to-add-or-edit-a-vamc-facility-mental-health-phone-number)
- The **VAMC Facility** content type is updated to reference the System number
  - Entity fetch field probably to grab the System number
  - Add a checkbox that says "Use the default mental health number for this VAMC system?" 
    - When checked the Mental health phone number field on the VAMC Facility should be hidden / uneditable.
    - When unchecked, the field is editable
    - New facilities should default to having this box unchecked (for intentionality)
- ~~Migration of current data to this new format~~
   - ~~Facilities that have a mental health phone number should migrate the box as unchecked and retain their current mental health phone number~~
   - ~~Facilities that don't currently have a mental health phone number specified should set the box as checked~~
- [ ] Validations?
  - What happens if a facility sets "use system number" but no system number has been specified?

## Acceptance criteria
- [x] Figma designs for the relevant portions of the Drupal interface for VAMC System and VAMC Facility are created
- [x]  Review with accessibility
- [x]  Review with content design
- [x]  Review with engineers
- [ ]  Review with UX/UI lead

**Comment by davidmpickett** [comment] 2024-02-09 19:37
@thejordanwood I added a few more details to this. Let me know if you wanna chat more about it.

**Comment by thejordanwood** [comment] 2024-02-12 18:05
@davidmpickett Thanks! This seems pretty clear, but some questions may come up whenever I start working on this. I'll let you know if we need to chat more.

**Comment by thejordanwood** [comment] 2024-02-20 16:21
@davidmpickett I added mockups to the Mental Health Numbers page in the [VAMC facilities Figma file](https://www.figma.com/file/bwnxdqh3b7W7Xp6KuQ4Sab/VAMC-facilities?type=design&node-id=6%3A2431&mode=design&t=6RvVwdDWYCYFgjJu-1). I have comments to explain any additions I made or ask questions. Can you review to check that the fields are shown correctly?

**Comment by davidmpickett** [comment] 2024-02-20 19:55
> @davidmpickett I added mockups to the Mental Health Numbers page in the [VAMC facilities Figma file](https://www.figma.com/file/bwnxdqh3b7W7Xp6KuQ4Sab/VAMC-facilities?type=design&node-id=6%3A2431&mode=design&t=6RvVwdDWYCYFgjJu-1). I have comments to explain any additions I made or ask questions. Can you review to check that the fields are shown correctly?

Just added a couple comments. This looks pretty spot on to what I expected. There will definitely need to be some discussion with product and engineering about conditional logic for how the System # interacts with the Facility #. But now that we have something to look at, it should be a lot easier to have that discussion.

One note that may not be that important to actually implement for the purpose of this ticket is that editors can't edit any of the other Facility data fields so they will actually see those all in a big gray box. The mental health phone number is the only field they can edit

![screencapture-prod-cms-va-gov-node-1216-edit-2024-02-20-13_52_16](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/31383e99-9084-4cfc-a8ff-d5db93021ef1)

**Comment by thejordanwood** [comment] 2024-02-20 20:55
@davidmpickett Thanks! I changed my mockups to show the experience that editors have and included the gray box.

**Comment by laflannery** [comment] 2024-02-21 17:41
Looks good @thejordanwood just one minor comment on help text

**Comment by aklausmeier** [comment] 2024-02-26 23:37
@thejordanwood 

This seems like an opportunity to help the editor understand why they are seeing a mental health phone number in the grey box that they can not edit and below where they can edit. Is there a way to help the editor understand with distinct "plain language" field labels?

This design makes it appear that if they enter a phone number in this open field it will update what they currently see in the gray box... unless that is true. 

![Screenshot 2024-02-26 at 4 34 17 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/137226108/75c4de8a-fb2d-4f45-a014-5d23665fb953)

**Comment by jilladams** [comment] 2024-02-27 22:53
Also maybe a question for @omahane . I'm wondering if this is because we haven't finished cutting over to CMS as source of truth for mental health numbers, and if this locked version will go away once that's completely done.

**Comment by jilladams** [comment] 2024-02-27 22:58
@thejordanwood @aklausmeier Christian just confirmed this in a DM in Slack. The Mental health number in the greyed out box is coming from Lighthouse right now. Once we complete the work in #15686 (unblocked as of ~30mins ago), the editable CMS field in the screenshot will be source of truth, and the version in the greyed out box will be deprecated.

Amanda, let us know if, with that in mind, you have any add'l feedback.

**Comment by aklausmeier** [comment] 2024-02-28 01:06
@jilladams @thejordanwood I have no feedback for the field Jordan created, looks great. I'd like to see what this page is going to look like w/o the grey box locked to ensure there is no duplication of any mental health phone fields and Jordan's design lines up with this. 

Are we able to see a screenshot of the new version? I'm locked out of Drupal currently. 

cc @omahane

**Comment by aklausmeier** [comment] 2024-02-28 01:09
Here's last screenshot I grabbed before I got locked out. No grey box (possibly because of my admin role in Drupal) and still has 2 mental health phone fields. I'm hoping this is not correct but looking for confirmation. 
![Screenshot 2024-02-27 at 6 07 14 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/137226108/a267cffa-a573-44a6-9a4c-8d0784115f42)

**Comment by jilladams** [comment] 2024-02-28 16:20
In sprint planning, Christian confirmed: the top MH number will go away on cutover, the bottom MH number will remain. Amanda signed off, closing.

**Closed by jilladams** 2024-02-28 16:20 UTC
Labels: VAMC, Facilities, UX
