### ISSUE TITLE
Magichead: reproduce tabledrag challenge seen in hallway tests and recommend how to get user unstuck

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#14532] opened 2023-07-26 00:49 UTC
### User story

**AS AN** Editor
**I WANT** not to be prevented from dragging Benefit Overview Sections into any a11y-allowed depth
**SO THAT** bugs don't determine content.

### Engineering notes / background

The issue has been observed in a couple settings, first internal testing then a hallway usability session. 

- See the 15:00 mark of the Zoom recording of the session with Danielle. (Request recording link from Wes.) In that case, Tabledrag prevented a second child Section from being placed at the same depth as its sibling, forcing it to a depth either one greater or one less than the (desired) sibling.
- Note:  after she saved and went back in to edit, now with the collapsed view of Sections, Drupal cooperated and easily let her drag that same section to be a sibling to the one above it. This almost seems like a bug, I wonder if she just moved her mouse a little differently or otherwise changed how Drupal viewed what she was trying to do.
- at 27:00 drupal again prevents creating a sibling, in collapsed mode this time. 

## Acceptance criteria

- [x] Reproduce scenario(s) that challenged Danielle and Michelle (above), and documented in this ticket
- [x] Suggest instructions that could be given to a user to get the section/child into the depth/position they want

**Comment by dsasser** [comment] 2023-08-29 19:53
# Results

I reviewed both videos and noted that both Danielle and Michelle were having similar issues. I have collated the findings into a list of issues:

1. jerky-ness when dragging. This occurs when the window is too small (or there are too many sections) to show all sections. Characterized as jerky back and forth swapping of dragged rows. It can result in nothing changing, or an undesired change in order or depth. I was able to replicate this issue by having a screen height smaller than 2 items.
2. Intermitent inability to indent. Unsure what causes this. Characterized as not being able to drag an item to the right in order to nest it under a parent. I was not able to replicate this. I suspect it was caused by the jerky behavior that proceeded the occurrence.
3. Inability to indent at the expected depth. Unsure what causes this. Characterized as being able to indent, but it skips a depth. I was not able to reproduce this.
4. Item 1 depth is not always 0. Cause is likely a result from the jerky issue number 1. Characterized as the first element/section having a depth > 0 (this breaks the hierarchy). I noticed this during testing, but couldn't reproduce it a second time.

<details>
<summary>Issue Timestamps</summary

16:25
Attempt to move a lower item to up to the first item caused a jerky, unexpected behavior. Elements were swapping back and forth very quickly for a time. It took two moves to get the element in place at the top.

17:00
Attempt to drag item 2 to nest under item 1 failed. This was immediately following step [1]. I noted that Danielle's window was very small in height. I approximate only 600px based on duplicating the test. Danielle seemed to intuitively know that she could use more screen real estate so she zoomed out the browser scale to make more room. At that point 1-1/3 sections were visible on screen.

18:13
Immediately following [2], Danielle experienced the inability to drag a middle item to the right to indent it. This occurred while the section forms were all expanded. It appeared, as best I could tell, that all items were currently a depth of 0. However, due to the screen height, it was not possible to see all 3 items in one view.

18:20
Danielle tries to fix this "stuck" behavior by indenting the 3rd item, which succeeds. She then tries to indent item 2, which now succeeds.

18:30
Danielle attempts to make item 3 a sibling of 2 and she was able to do so. While dragging left or right, it would "jump" a depth, so always being a parent or sibling. (item 2 was a child of 1). It appeared to be a situation where item 1 had a depth > 0.
</details>

## Bail out Solutions
 - Ensure you can see the entire tree when dragging if possible: make window taller; zoom out on browser; save and revisit with collapsed view.
 - Move an item above, or below to "unstick" things.
 - Use accessibility mode (show row weights) to force depth/order.

## Recommended Magichead Changes:
 - Create a collapsed view which is accessible in all scenarios, including during initial edit.

**Comment by jilladams** [comment] 2023-08-30 00:05
@wesrowe suggestions for workarounds/ next tickets are documented in Daniel's comment above. I'm closing this as complete. I do think we need a ticket re: the collapsed view, so that's a follow up step not captured in ACs. @dsasser if you're willing to make that ticket, please do, and if not, just holler and I can help stub something out or Wes can.

**Closed by jilladams** 2023-08-30 00:05 UTC
Labels: Drupal engineering, Public Websites, VA Benefits Taxonomy

**Comment by wesrowe** [comment] 2023-08-31 17:50
Perversely, I'm glad that @dsasser was able to reproduce the first-item-depth-1 bug, as that was an elusive one. Too bad it's not bad enough to actually catch consistently though...

**Comment by dsasser** [comment] 2023-09-07 18:24
I noticed issue 3 "Inability to indent at the expected depth" on a Tugboat instance setup to demonstrate some CSS changes to the magichead field. I documented the steps to reproduce in [Slack](https://dsva.slack.com/archives/C52CL1PKQ/p1694039467540869?thread_ts=1694039423.488059&cid=C52CL1PKQ), which included:

- I clicked the link in the thread to take me to https://cms-zezzrlutxmwrp3tnpxaygudem7k2y2lj.ci.cms.va.gov/taxonomy/term/1137/edit
- I broke the editorial lock
- I moved the offending item to the right, then to the left, and saw it skip the depth, preventing it from being a sibling of the above row.
