### ISSUE TITLE
Test the mobile app banners for Android & iOS browsers

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#15318] opened 2023-09-19 21:40 UTC
## Description

#13481 added mobile app banners to Safari on IOS for specific pages. We now want to expand those to appear on all Android browsers. 

Android Design: Add mobile app banners for Android browsers #15317

## Pre-Conditions
- [x] Dave has viewed new designs and signed off (he has queued follow-up the week of 10/30)
- [ ] Activities on Change Management [ticket ](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15806)pertaining to sharing with existing editors is completed.

## Notes
- Mark-up and meta-tags are done and in PR environment. The main work on this ticket is QA only.
- Safari banner is live
- This is currently Blocked due to needing Platform approval to use smartbanner.js

## Acceptance criteria
- [ ] Implement using the SmartBanner.js NPM package instead the CDN.
- [x] Create a CMS feature flag for this
- [x] Supported browsers on Android according to the Platform team: Chrome & Firefox
- [x] Mobile banners expanded to appear in Android browsers, and all other iOS browsers that aren't Safari, and design follows native Android banner design
- [x] Carry over previously implemented accessibility color changes 
- [x] All mobile banner features in both Android & iOS function as expected.
- [x] Verify that Safari hasn't been changed; we're still using the native Safari iOS app banner
- [x] Verify on lower environments (branch to Dev environment?)
- [x] Ensure no content policy errors occur in the browser dev tools console
- [x] A11y review (Randi will test Android (Chrome and Samsung?) Laura's guidance; Laura will test iOS device > Safari/Chrome/Firefox)

**Comment by jilladams** [comment] 2023-11-01 18:29
Launching: 
* CMS feature flag is not useful, we won't have one / it's been deprecated.
* Previously we tested in Staging, using an environment check.

**Comment by jilladams** [comment] 2023-11-08 20:10
Unmarked as blocked, moved to Stretch. This is refined, and now that we have Platform approval on the SmartBanner.js library, this could move whenever we have time / are ready. Dave approved in planning today. cc @FranECross @chriskim2311

**Comment by laflannery** [comment] 2023-11-21 18:50
iOS Testing:
- Device: iPhone 13
- Version: 17.1.1
- No issues found
- Screenshots below for reference
**Chrome**
- No issues found
- SmartBanner
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/106678594/9c8c4995-6d33-43b4-847f-04efe546a70d)

**FireFox**
- No issues found
- SmartBanner
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/106678594/b986397b-d99d-41c3-b50d-1bed4853e238)

**Safari**
- This is supposed to be the Default Apple Banner
- It no longer looks like what it does on prod
- Prod is on the right, your most recent ngork is on the left:
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/106678594/5c6f707f-0a5c-4207-aa06-5c77445681ad)


**Desktop**
Just for the heck of it, I opened this on my desktop and the banner is appearing, can you confirm that this banner will NOT appear on desktop?
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/106678594/cfab4653-fa56-4980-a650-ab44624c4770)

**Comment by laflannery** [comment] 2023-11-21 21:31
Android, from @randimays 

View button has a color combination that does not pass contrast ratios (`#d1d1d1` text against a `#42B6C9` background - 1.57 ratio). I would ideally like to change the background property color to `#112e51`
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/106678594/6cf166f4-9979-4934-b712-70c8f4e03c2b)

![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/106678594/9c8820e5-79f6-4ff5-9d77-671e0024ad66)

**Comment by chriskim2311** [comment] 2023-11-22 21:51
@laflannery I was able to make the background color change for the view button on android. Let me know if this works! [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd3ovQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--999d463953990c8236126d43d3c406dd50e41429/VA_Prescription_Refill_And_Tracking___Veterans_Affairs_and_VA_Health_Care___Veterans_Affairs.png)

**Comment by chriskim2311** [comment] 2023-11-27 21:33
@laflannery I was able to change the color to #716F6F. Let me know what you think! [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL01PQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a0c86edab5623da73c1fcf934f4e7675de35f7a3/iPhone_13_v15_4.png)

**Comment by laflannery** [comment] 2023-11-27 21:35
@chriskim2311 The old color and the new color are so close it's hard to tell from just a screenshot but as long as it's that hex value it should pass WCAG contrast requirements so we should be good

**Comment by chriskim2311** [comment] 2023-11-27 21:40
@laflannery It definitely is close. I can make it darker like #2a2929 so there is more contrast.

**Comment by laflannery** [comment] 2023-11-27 21:47
Ya let's do that, since we are changing it anyway, thanks!

**Comment by jilladams** [comment] 2023-12-05 20:43
We are rolling back the changes here: https://dsva.slack.com/archives/CBU0KDSB1/p1701801851929449

Next steps TBD.

**Comment by jilladams** [comment] 2023-12-06 19:43
@chriskim2311 @FranECross Moving this to blocked by #16319 for now

**Comment by jilladams** [comment] 2023-12-13 19:59
In FE refinement today, we discussed that since these banners are coming in through content-build, we could use a CMS feature toggle to on/off them, to make rollback easier if needed. Chris / Randi are open to doing that work, TBD the technical understanding to make sure they're comfortable in that Drupal depth. (FYI @dsasser and @Becapa , will likely require a little support and your code review if so.)

However: a related discussion where we flagged that the original mobile banner toggle didn't work as expected to keep things out of Prod. So: this may actually be a nonstarter? Or maybe it's different now with the smarbanner implementation somehow?: 
* Github: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15079#issuecomment-1747392718
* Slack: https://dsva.slack.com/archives/CBU0KDSB1/p1689697829129919

In case we do decide it's useful to have a toggle: for reference: some previous CMS feature toggle PRs to look over: 
* Previous time we did this for mobile banners: https://github.com/department-of-veterans-affairs/va.gov-cms/commit/2180e93966ff6ea115b9de4cd4bbede9c7d12ea3
* Adding Events checkbox + Events feature toggles: https://github.com/department-of-veterans-affairs/content-build/pull/1752/files
* Removing those toggles: https://github.com/department-of-veterans-affairs/va.gov-cms/pull/16215/files

**Comment by randimays** [comment] 2023-12-13 20:24
@jilladams When we struggled with the CMS feature flag for the iOS banners, that was because we wanted the content to stay in staging for a prolonged period of time. There isn't a way to control the staging environment's content separate from prod. This time, we need the ability to quickly remove the banners if they cause more friction. In theory, these situations should be mutually exclusive.

**Comment by chriskim2311** [comment] 2024-01-02 18:55
PR merged will be testing against content policies in staging. Has env flag and wont be live in production.

**Comment by randimays** [comment] 2024-01-03 16:15
(I thought I posted this here yesterday, but I must have posted it in the wrong spot or forgot to submit a draft 🤔)

The mobile banners are coming through with the new implementation, but the styles did not follow suit for some reason; we'll need further investigation.

Android - Chrome
<img width="328" alt="Screenshot 2024-01-02 at 4 04 50 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/19175324/345c27c7-9496-4cdb-9234-59a4fb11fb79">

iOS - Chrome (Browserstack)
<img width="328" alt="Screenshot 2024-01-02 at 4 04 50 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/19175324/1dc765da-93ba-47fd-af72-2a4e5787dbe7">

**Comment by chriskim2311** [comment] 2024-01-03 17:56
Unfortunately the same content policy issues are still being seen. The style sheet wont load and theres an issue loading the image from the google play store URL that is included in the metadata.

<img width="1673" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWFYQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b09739c6ff6272e372710a3cc883f2b65bd04d60/VA_Prescription_Refill_And_Tracking___Veterans_Affairs.png" alt="VA_Prescription_Refill_And_Tracking___Veterans_Affairs.png" />

**Comment by randimays** [comment] 2024-01-08 14:18
Picking this back up today to see if I can help resolve the style issues.

**Comment by randimays** [comment] 2024-01-09 16:36
I grabbed the SmartBanner code directly and added it to content-build. Banners are working as expected including their close buttons and View buttons. 

[PR for feature toggle](https://github.com/department-of-veterans-affairs/va.gov-cms/pull/16769) will be merged soon. This will help us with a quick rollback in production should any issues arise. Once that PR is merged, we need to wait for the overnight sync to implement the feature toggle in staging.

We'll still be using the environment check to keep the banner in staging until we can confirm there are no security policy issues. Once that is confirmed, we can remove the environment check and move forward to check in prod (with the feature toggle).

**Comment by randimays** [comment] 2024-01-09 17:16
Confirming per Jill's 16th minute item in Scrum today: Smart Banner JS has a GNU General Public License that allows us free usage of the Smart Banner source code. I've also added in the GNU GPL in the same folder as the source code, and attributed all code to the source project's Github and NPM link.

**Comment by jilladams** [comment] 2024-01-12 17:44
wompity womp. Thanks for the continued effort!

**Comment by randimays** [comment] 2024-01-15 19:35
After the last update, I added `nonce` to the JS. The helps quiet the Content Security Policy errors for using a local JS file. But we were still seeing issues with bringing in the Google Play / App Store icons from a remote upload.

<img width="424" alt="Screenshot 2024-01-15 at 11 28 53 AM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/19175324/79720608-ee19-44c9-b7ba-23f9d20ba211">

To fix these, we deleted the meta data for those remote images, download the images and put them in the src/site/assets folder of `content-build` so it can pull them in locally as well. [Here's the PR](https://github.com/department-of-veterans-affairs/content-build/pull/1869/) for that change. It's a holiday today so it might be slow going getting this to staging, but testing there is the next step.

**Comment by randimays** [comment] 2024-01-16 16:11
Merged the above PR and validated that everything is working as expected in staging with no security errors. Asking some team members to help validate. Next step will be removing the staging environment check and moving to code to staging, then production and validating there.

**Comment by jilladams** [comment] 2024-01-16 17:39
nice solves, y'all.

**Comment by randimays** [comment] 2024-01-16 19:53
Slack thread for tracking production validation (and any issues that may crop up): https://dsva.slack.com/archives/C52CL1PKQ/p1705425173724749

**Comment by randimays** [comment] 2024-01-16 21:27
Smart banners are functional and live in production! See screenshots for all environments below & validation of the Content Security Policy errors being resolved.

All "View"/"Get" buttons and "X" buttons (to close the banners) have been tested.

Chrome (Desktop, responsive mode) - no console errors/warnings about Content Security Policy
<img width="832" alt="Screenshot 2024-01-16 at 3 23 45 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/19175324/e04d658e-5629-472b-8ce4-f16b9fcd5878">

Android Firefox
<img width="350" alt="Screenshot 2024-01-16 at 3 23 23 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/19175324/c5f245a5-beae-4c43-abc2-81457f936445">

Android Chrome
<img width="350" alt="Screenshot 2024-01-16 at 3 22 44 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/19175324/8ea15471-becf-4749-be7b-5edc884513d4">

iOS Chrome
<img width="350" alt="Screenshot 2024-01-16 at 3 19 46 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/19175324/8a9a39bd-84a4-4d30-99f5-caaa5323e9c5">

iOS Safari
<img width="350" alt="Screenshot 2024-01-16 at 3 19 28 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/19175324/dae7b973-2e0e-4d08-bb65-ca3672f99d5b">

**Closed by randimays** 2024-01-16 21:27 UTC
Labels: VA.gov frontend, Public Websites, Mobile app banners
