### ISSUE TITLE
Global: Update DS classes in template

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#19668] opened 2024-10-31 17:31 UTC
## Description
Related issue created for specific template. [See global issue for details](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19667)

```[tasklist]
###
- [ ] The problem as described is fixed
- [ ] The repro steps result in 'expected result'
- [ ] An automated test is written to catch the problem, if appropriate
```

### How can we see the problem? (repro steps)

1. Please include a set of steps that allows an independent tester to see the problem.
2. Write them so that after the defect is fixed, the steps will result in the expected result.
3. It is helpful to write the steps methodically so they can be the foundation of an automated test.

**Expected result:** What should be the outcome?<br />
**Actual result:** What currently happens?

### Is there any additional information?
Screenshots:

Log messages (please specify from where or what commands(s))
```
Log messages here
```

**Comment by jilladams** [comment] 2024-12-24 20:41
This is really a dupe of #19667, which contains the scope. We figured out a mechanism to keep track of issues that affect more than one template. I'm going to close this as a dupe. 

@mcommons10 @AdamKing0126 if you all still plan to work on it, please assign #19667 to yourselves to track.

**Closed by jilladams** 2024-12-24 20:41 UTC
Labels: Defect, Accelerated Publishing
