### ISSUE TITLE
Content moderation status for Vet Center services is lost through the current IEF configuration

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#7144] opened 2021-12-03 03:44 UTC
## Describe the defect

When an editor adds a service to a Vet Center, the content moderation status is opaque. 

## To Reproduce
1. As an admin user (same behavior for all roles), go to https://staging.cms.va.gov/node/3756/edit#edit-field-health-services 
2. Note that it's impossible to tell if services are published or not
3. Add a new service, and see that there's no indication of published
4. Save the node form
4. Go to /admin/content
5. Note that the service you created is draft

## Expected behavior

1. I should be able to tell the content moderation state of the service, and move it through the content moderation service

OR 

2. I shouldn't have to worry about moderation state. If the node is there, it should match my Vet Center's service

The latter is preferable. 

## Screenshots 

<details><summary>Screenshot</summary>
<img width="1151" alt="Edit_Vet_Center_Nashville_Vet_Center___VA_gov_CMS" src="https://user-images.githubusercontent.com/643678/144541513-ce1a375f-1aaa-4d71-8112-65f4b1f33e1f.png">

</details>

 ## Additional context
PR #7065 gives Vet Center editors delete permissions. 
 

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS workstream (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Platform CMS Team`
- [x] `Sitewide CMS Team`

**Comment by davidmpickett** [comment] 2024-07-01 20:53
Closing as duplicate of https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17708

**Closed by davidmpickett** 2024-07-01 20:53 UTC
Labels: Defect, Editorial workflow, Facilities, Needs refining, Vet Center, crew-sitewide, sitewide
