### ISSUE TITLE
SPIKE: Understand why validation of the Operating Status Details is different for CAPs than facilities

### ISSUE THREAD

**Issue by omahane** [department-of-veterans-affairs/va.gov-cms#19901] opened 2024-11-19 14:57 UTC
## User Story or Problem Statement

As an editor, I want to ensure that I have filled out the Details section of the Operating status when the status is anything but normal.

## Implementation steps
This used to behave as expected, as described in the PR that introduced this behavior:
https://github.com/department-of-veterans-affairs/va.gov-cms/pull/9273

### Constraint validation using PHP (VBA)
We have done something like this on VBA facility banners. If the editor chooses
**Display a banner alert on this facility**, then subordinate empty fields will throw a validation error.
![Image](https://github.com/user-attachments/assets/141a676d-1bd0-4d32-b725-42bfeba2502d)

### Javascript validation (Campaign Landing Page)
We have another pattern on Campaign Landing Page which prevents the user from **submitting** the form if they have enabled a given section, such as Events, but have not filled out the required fields for those sections.

This is done using form states.

![Image](https://github.com/user-attachments/assets/e2c87904-f29d-41b3-91b3-d3aea7e1a700)

### Events: Registration info
Has similar validation. Choose Registration method, and exposed fields are required, using custom JS. There is no server-side mechanism for this. 

![Image](https://github.com/user-attachments/assets/ff13eb1a-c0c7-4bbd-ab62-79b62fbea4de)

## Design principles
For background, the field appears to be required, showing with an asterisk.
![Image](https://github.com/user-attachments/assets/48ff6442-c17f-4225-977e-e03533f7532a)

## In a post-OS update world
~The Operating Status iteration in q4 will change the way that CAPs work. (They will no longer be an example of the working state of this.) If Operating Status changes merge before we work this ticket, we will need to make a Tugboat from a prior state of main, to get back to the point where CAPs were working this way.~

~(To do that, branch off main, checkout a commit state from prior to the OS iteration merge, then build Tugboat from that branch.)~

The Vet Center - Community Access Point does continue to behave as it did before the additional operation statuses. Below is a recording of the Vet Center - CAP on the integration branch:
https://integration-operating-statuses-ffjtmst27rrt1xy8l9ztq75ijustu4sn.demo.cms.va.gov/node/48564/latest

### Screen recording of editing Vet Center - CAP
![Image](https://github.com/user-attachments/assets/a6a401e1-0522-4da4-af97-aa9b58883c9f)

## Acceptance Criteria
- [ ] When trying to save a page with a non-normal operating status, an empty Details field triggers a validation error. On all content types: 
  - [ ] VAMC
  - [ ] Vet Centers
  - [ ] CAPs
  - [ ] Outstations
  - [ ] VBA
  - [ ] NCA
- [ ] It is not possible to save a Details field with only blank spaces 

We don't necessarily expect markup to change, as fix is likely to be in PHP or JS, so we did not list a11y review as an AC. If markup does change, A11y review becomes required.

**Comment by jilladams** [comment] 2024-11-19 16:54
Per Laura / Michelle discussion: Editors seem to think it's required and only leave it blank for CAPs. 
Leaving it blank doesn't break FE. The blank field does pipe through to FE.

A good example of handling, per Daniel, may be the Registration Info field on Events.

**Comment by jilladams** [comment] 2024-11-19 17:01
@omahane wlll take a look at the JS solution on Events to determine path forward. That's necessary before we can refine and point.

**Comment by laflannery** [comment] 2024-11-26 15:51
Noting that CAPs currently works properly - I **cannot** submit a status with an empty `Operating status - more info` field

**Comment by laflannery** [comment] 2024-11-26 21:57
@omahane So there was some confusion with Tugboats earlier today and it led me to the discovery that on CAPS on staging, the Details field is required and acting correctly:
![Image](https://github.com/user-attachments/assets/77534882-7534-4e4c-a7a3-77bfebb34139)

But on your tugboat with the updates ([Link](https://cms-ffjtmst27rrt1xy8l9ztq75ijustu4sn.demo.cms.va.gov/) so we know which environment we are looking at, CAPs DO NOT require the Details field anymore.

This feels like a regression but also this is the only field currently on Prod respecting `required` so I don't know what to do

CC: @jilladams d @Agile6MSkinner

**Comment by jilladams** [comment] 2024-11-29 19:58
Also: You can skirt the requirement by hitting space bar a few times. Per [this Slack thread](https://dsva.slack.com/archives/C0FQSS30V/p1732898546592679), the FE will translate that as empty, and will not present an expandable alert, since there's no additional content to show. But ideally: that wouldn't be possible. @Agile6MSkinner @omahane should preventing that be an AC on this ticket? Or does validating against a spaces-only entry fall outside the scope here?

**Comment by omahane** [comment] 2024-12-02 14:24
@jilladams We can make sure that the content is of adequate length and content. It's a bit of a blunt instrument, but we use it in `va_gov_vet_center/src/EventSubscriber/EntityEventSubscriber.php` for service descriptions with a custom `longEnough()` function that removes white space and html and is true if the resulting text is greater than 15 characters. I would recommend adding it.

**Comment by jilladams** [comment] 2024-12-02 16:59
From scrum: @Agile6MSkinner @mmiddaugh agree we should try to fix this for launch. 
Michelle agreed we can try to fix this on the business side with better Editor behavior. 

We will go ahead and refine this to pull into Sprint 19. We will try to root cause, and if we can identify root cause, we will determine whether to wait on a fix or not for launch. (Because: this is a Drupal mystery so far, as to why the requirement is not being correctly enforced.)

For FE: we will make sure to present any status or details in an expandable alert if they exist; if no Details, show a slim alert. That's a failsafe we can revert once we are enforcing Details correctly from Drupal.

**Comment by omahane** [comment] 2024-12-20 22:17
# Investigation results
In comparing the difference between the Vet Center Community Access Points and other facilities, I noticed that the other facilities were throwing this error upon clicking save:
- `Step attribute on input type time is not supported`

A little research led me to [this issue on Drupal Clientside Validation module](https://www.drupal.org/project/clientside_validation/issues/3200530). Ironically (or not), I had posted [a comment on this very issue](https://www.drupal.org/project/clientside_validation/issues/3200530#comment-15489636) back in March 2024.

This error was being thrown on the hours widget, which is typically not shown the CAPs.

## Screenshot of Vet Center CAP without hours widget and with
<img width="1535" alt="Image" src="https://github.com/user-attachments/assets/3e2e6357-a776-439f-bf63-04d967aa4da4" />

## How do we know it's Clientside Validation?
When I disabled the module, the **Details** could no longer be left blank even if the hours widget was showing.

### Animation of trying to save a facility after disabling Clientside Validation
![Image](https://github.com/user-attachments/assets/634f27e4-b33c-4f2b-93c9-82cde38c9848)

# Next steps
There has been no movement on the underlying issues either in the Drupal module or jQuery, which has a [PR for this issue](https://github.com/jquery-validation/jquery-validation/pull/2119) that causes different errors, apparently.

**Comment by jilladams** [comment] 2024-12-20 23:17
That issue is 4+ years old, and the not-merged PR was created in 2017. 😂 😭 

Do I catch the meaning here correctly that:
1. We _could_ try to fix it ourselves in the module if we felt that strongly, which could be a big time sink of unpredictable nature given that previous fixes didn't verify as expected.
2. We can wait for the module maintainers to get it together, which they might never given that it's been many years, so IRL we should probably acknowledge: this is not fixable as long as we are using the client-side validation module?

**Comment by omahane** [comment] 2024-12-20 23:49
Actually, I think we can work around this if we just decide where we really need the Clientside Validation to run. I just tested this:

## Clientside Validation configuration settings
- `/admin/config/user-interface/clientside-validation`
- We can uncheck **Use Clientside Validation in all forms**
- Instead, we can add the validation on the forms we need, e.g.
  - `media_add_form`
  - `media_edit_form`
### Screenshot of clientside validation configuration
<img width="1283" alt="Image" src="https://github.com/user-attachments/assets/c5605070-5c8a-495b-b04a-4fb749a847b8" />

## Vet Center - CAP
- Media clientside validation is working
### Screenshot of clientside validation
<img width="1283" alt="Image" src="https://github.com/user-attachments/assets/2c624fe9-91cc-4739-beed-918506984e14" />
- The Vet Center CAP form is not using the validation, so the form submission does not throw a javascript error, hence "Fill out this field" is being shown, preventing the submission of the form when the **Operating status** is non-normal and **Details** is empty
### Screenshot of Vet Center - CAP not using clientside validation
<img width="1283" alt="Image" src="https://github.com/user-attachments/assets/7eee6524-aef4-4cbd-a6f7-e70d726b32b5" />

**Comment by omahane** [comment] 2024-12-20 23:50
This more selective use of Clientside Validation is what I would recommend.

**Comment by jilladams** [comment] 2024-12-23 17:01
We will need to discuss with the CMS team. We contemplated that approach under #17896.  Per the l[ast notes there in August](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17896#issuecomment-2297315760), there are some next steps that need to happen that neither us nor CMS team have gotten to yet.

@mmiddaugh (cc @Agile6MSkinner  @FranECross) FYI that it would probably be a long-term convenience, if we have Drupal resources available in Q1, to try and take on the work in #17896, since it keeps popping up as an implicated factor when Drupal javascript has weirdness going on with validation. (In this case: for Facility hours stuff, but previously for Events, and facility phone numbers.)

**Comment by jilladams** [comment] 2024-12-23 22:46
I'm going to go ahead and close this spike since we know the root cause, and the rest of the conversation will need to happen on 17896.

**Closed by jilladams** 2024-12-23 22:46 UTC
Labels: Enhancement, VAMC, Drupal engineering, Facilities, Needs refining, Vet Center, sitewide, VBA
