### ISSUE TITLE
Lovell breadcrumbs that are initially correct get malformed

### ISSUE THREAD

**Issue by maxx1128** [department-of-veterans-affairs/va.gov-cms#12777] opened 2023-02-28 00:57 UTC
## Describe the defect

On Lovell, breadcrumbs that already have the correct variation text get updated to the incorrect text. For example, "Lovell Federal health care - TRICARE" would be updated to "Lovell Federal health care - TRICARE - TRICARE."

## To Reproduce
1. Go to the Tricare or VA homepages
2. Read the breadcrumb.

## AC / Expected behavior

The expected behavior is that the breadcrumb text won't have any repeated content or text.

## Screenshots

<img width="1051" alt="Screen Shot 2023-02-27 at 7 44 53 PM" src="https://user-images.githubusercontent.com/10790736/221724167-6b408b02-9aa1-4ed3-abcd-d9b5cbf84584.png">

 ## Additional context

This bug is only seen when [this cloning issue](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12776) is addressed, and will likely be fixed in the same pull request.

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS workstream (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [x] `Facilities`
- [ ] `User support`

**Comment by ryguyk** [comment] 2023-02-28 01:40
This might be a duplicate of or very similar ticket to https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12690. Both these tickets should be closed by https://github.com/department-of-veterans-affairs/content-build/pull/1488#pullrequestreview-1316678989.

**Comment by ryguyk** [comment] 2023-02-28 18:19
Closing in favor of #12690.

**Closed by ryguyk** 2023-02-28 18:19 UTC
Labels: Defect, Facilities, Needs refining
