### ISSUE TITLE
Service location: "Unspecified" walk-ins should map to NULL following migration and should not be included in front end display

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-cms#17516] opened 2024-03-13 21:38 UTC
## Description
Lewiston VA Optometry "Unspecified" walk-ins requirement maps to "Yes, by appointment only" in Tugboat following migration and to  "Visit our office, by appointment only" in the Tugboat front end

[Tugboat FE](https://web-xptmfsnjoodldn85nzgkrgljqtfbz24b.ci.cms.va.gov/maine-health-care/locations/lewiston-va-clinic/)
[Tugboat CMS Service node](https://pr15622-xptmfsnjoodldn85nzgkrgljqtfbz24b.ci.cms.va.gov/node/64397/edit)
[Prod FE](https://www.va.gov/maine-health-care/locations/lewiston-va-clinic/)
[Prod Service node](https://prod.cms.va.gov/node/64397/edit?destination=/node/1065)

## Current behavior
<details>
<summary> Prod FE and CMS display </summary>

<img width="887" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3JiQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--30528abf4bed040435c8a10e5e0922c9b094990b/image.png" alt="image.png" />

<img width="551" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3ZiQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--68ad2ca2eede6eb9972f7d25253cb989fc257bb4/image.png" alt="image.png" />

</details> 

## Expected behavior
- [ ] OLD walk-ins = Unspecified, [null], or 2
- [ ] should map to NEW office visits = null in Drupal 
- [ ] should not be included in the front end display. 

## ACs
For the question, "Are walkins accepted?"
- [ ] If "Unspecified", "2" or [null]  is selected, this should map to null.
- [ ] On the front end, null should not show anything for walk-ins in the front end.

**Comment by davidmpickett** [comment] 2024-03-13 23:29
"Unspecified" --> "Yes by appointment only" is the intended mapping that we specified in #14837 and confirmed in #15559. The decision was based on the fact that on conception VAMC health services were considered appointment-only by default. 

<img width="1518" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdzNjQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2e5e993571611e422324dbb21a74951935930aee/VBA%20Content%20model_2024-03-13_23-16-00.png" alt="VBA Content model_2024-03-13_23-16-00.png" />

There is no longer an "unspecified" option to map to on the new field. We could alternatively map "unspecified" to "no" or have a null mapping, but is which of these choices is most likely to result in Veterans having the most accurate information?

**Comment by davidmpickett** [comment] 2024-03-19 16:03
## Option 1 - [null]

## Option 2 - "No"

## Option 3  - "Yes by appointment only"
- Current behavior
- No change needed to migration

**Comment by davidmpickett** [comment] 2024-03-19 23:51
Per conversation with @mmiddaugh today, **Option 1 - Map to [null]** is the desired path

**Comment by davidmpickett** [comment] 2024-03-22 19:14
Here's a really good example of why we should map to NULL rather than by Appointment only.

[Suicide prevention at Los Angeles VA Clinic](https://www.va.gov/greater-los-angeles-health-care/locations/los-angeles-va-clinic/#suicide-prevention) currently has walk-ins accepts set to unspecified. The custom appointment text emphasizes that no appointments are needed.

![Screenshot 2024-03-22 at 2 12 50 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/1f3f365b-008b-4bf2-b59d-14220d259b53)

Because the migration is currently mapping unpsecified to yes, by appointment only, this is how it's showing up on tugboat

![Screenshot 2024-03-22 at 11 03 49 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/c6d45a1b-cc4a-43a0-9253-3753c6c93bb5)

**Comment by davidmpickett** [comment] 2024-03-25 21:50
@omahane while doing additional testing, I discovered that we also need to account for the possibility of "2" and [Null] as existing data that should map to [Null] after migration. I updated the ACs and here are two examples

![Screenshot 2024-03-25 at 4 34 30 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/9b4d9fef-cdbb-4cd9-ae15-61ee8acce330)

![Screenshot 2024-03-25 at 4 41 31 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/531385bd-595c-442e-9002-14a4c2e2af7f)

**Comment by eselkin** [comment] 2024-04-08 21:21
Because the NULL condition no longer fits that matrix for when to show the Appointments section, we have to change that logic to show the Appointments header and the text in content-build. Right now it displays like this on the integration tugboat:
<img width="700" alt="Screenshot 2024-04-08 at 2 20 26 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5606931/036ed339-175a-497e-a119-638a42196df0">

**Comment by davidmpickett** [comment] 2024-04-10 20:00
# Dave's confirmation testing WIP

## No -> Yes, by appointment only
![Screenshot 2024-04-10 at 2 56 21 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/0871b16a-2cea-419d-8af7-ab41676b9635)

https://web-xptmfsnjoodldn85nzgkrgljqtfbz24b.ci.cms.va.gov/pittsburgh-health-care/locations/h-john-heinz-iii-department-of-veterans-affairs-medical-center/

## Yes -> Yes, with or without an appointment 

![Screenshot 2024-04-10 at 2 59 08 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/168d776a-10f4-4178-82ec-fa0070d817cd)

https://web-xptmfsnjoodldn85nzgkrgljqtfbz24b.ci.cms.va.gov/new-york-harbor-health-care/locations/brooklyn-va-medical-center/

**Comment by davidmpickett** [comment] 2024-04-18 22:37
Hey @omahane, in verifying Eli's spinoff issue, I noticed that the current tugboat instance seems to had some kind of regression with the migration. 2 and Null are correctly mapping to Null, but Unspecifed is mapping to Yes. Might just mean that we need to rebuild Tugboat and run the migration again?
 
![Screenshot 2024-04-18 at 5 25 47 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/56042518-88db-4057-9747-5016e60245bd)

![Screenshot 2024-04-18 at 5 28 09 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/4aeee45c-edc2-4339-89f9-2185bde6b8d9)

![Screenshot 2024-04-18 at 5 36 41 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/385f6809-c182-4725-a1e3-8aa6f3082c64)

**Comment by omahane** [comment] 2024-04-19 12:05
I'll take a look at the script this morning.

**Comment by omahane** [comment] 2024-04-19 12:26
I know what happened and when it happened. What I am unclear about is how it happened and why it happened.

# Rebasing main produced conflicts
For some reason, last week while rebasing main into `integration-service-loction`, I ran into many merge conflicts. I went through them, but apparently in the process, two formerly merged PR branches were lost:
- https://github.com/department-of-veterans-affairs/va.gov-cms/pull/17703
- https://github.com/department-of-veterans-affairs/va.gov-cms/pull/17517

I'll make a PR to restore them.

**Comment by jilladams** [comment] 2024-04-19 15:22
Changes are merged to integration branch. 
To get it staged to QA again: 
* Tugboat is rebuilt
* Christian is running the migration

For Jill brain: OLD walkins should = empty after this change/migration

**Comment by jilladams** [comment] 2024-04-19 22:19
View for verification: https://pr15622-xptmfsnjoodldn85nzgkrgljqtfbz24b.ci.cms.va.gov/admin/content/audit/service-locations-detailed

**Comment by jilladams** [comment] 2024-04-19 23:05
| Service | Facility FE | Old: walkins? value | NEW: Office visits value | FE shows | 
| --- | --- | --- | --- | --- |
|  [Patient advocates - Beaver County VA Clinic](https://pr15622-xptmfsnjoodldn85nzgkrgljqtfbz24b.ci.cms.va.gov/pittsburgh-health-care/locations/beaver-county-va-clinic/patient-advocates) |  [FE](https://web-xptmfsnjoodldn85nzgkrgljqtfbz24b.ci.cms.va.gov/pittsburgh-health-care/locations/beaver-county-va-clinic/) | Unspecified | NULL |  No text (Screenshot in accordion below) | 
| [Homeless Veteran care - Colonel Mary Louise Rasmuson Campus of the Alaska VA Healthcare System](https://pr15622-xptmfsnjoodldn85nzgkrgljqtfbz24b.ci.cms.va.gov/alaska-health-care/locations/colonel-mary-louise-rasmuson-campus-of-the-alaska-va-healthcare-system/homeless-veteran-care) | [FE](https://web-xptmfsnjoodldn85nzgkrgljqtfbz24b.ci.cms.va.gov/alaska-health-care/locations/colonel-mary-louise-rasmuson-campus-of-the-alaska-va-healthcare-system/) | 2 | NULL | 2 in the > |
| [Medical records - Cheyenne VA Medical Center](https://pr15622-xptmfsnjoodldn85nzgkrgljqtfbz24b.ci.cms.va.gov/node/41989) | [FE](https://web-xptmfsnjoodldn85nzgkrgljqtfbz24b.ci.cms.va.gov/cheyenne-health-care/locations/cheyenne-va-medical-center/) | NULL | NULL | No references to walkins.  | 
| [Homeless Veteran care @ Bemidji](https://pr15622-xptmfsnjoodldn85nzgkrgljqtfbz24b.ci.cms.va.gov/fargo-health-care/locations/bemidji-va-clinic/homeless-veteran-care) | [FE](https://web-xptmfsnjoodldn85nzgkrgljqtfbz24b.ci.cms.va.gov/fargo-health-care/locations/bemidji-va-clinic/) | Yes |  Yes, with or without appt |  Visit our office, with or without an appointment , 3 in >|
| [Plastics @ Orlando VAMC](https://pr15622-xptmfsnjoodldn85nzgkrgljqtfbz24b.ci.cms.va.gov/orlando-health-care/locations/orlando-va-medical-center/plastic-and-reconstructive-surgery) | [FE](https://web-xptmfsnjoodldn85nzgkrgljqtfbz24b.ci.cms.va.gov/orlando-health-care/locations/orlando-va-medical-center/)  | No | Yes, by appt only |  Visit our office, by appointment only |  

### NULL > NULL 
For a facility health service that started as NULL, Dave provided an example in comments above ([Optometry - Allentown VA Clinic](https://pr15622-xptmfsnjoodldn85nzgkrgljqtfbz24b.ci.cms.va.gov/admin/content/audit/service-locations-detailed?title=Optometry+-+Allentown&type_op=in&type%5B%5D=health_care_local_health_service&moderation_state_multiple_workflow_filter=All&field_administration_target_id=All)), but OLD:Office visits is set to No on that one today. I'm not sure how to re-test this since the updated Drupal UI doesn't include the old field to modify.

The only NULL > NULL examples I could find were all non-clinical options, and I haven't looked at these as much to know what the design would show if walkins were allowed. Need to review Figma, Monday.

<details><summary>screenshot receipts</summary>

### Unspecified > NULL

![Screenshot 2024-04-19 at 3 45 43 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/85581471/9a0a30d2-dbb2-4650-9f5f-173028b0183b)

### 2 > NULL

![Screenshot 2024-04-19 at 3 48 12 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/85581471/3fd54859-228a-41d0-891a-9ceafc5dfd33)

### Yes > Yes 

![Screenshot 2024-04-19 at 3 31 38 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/85581471/b1ed4acb-322f-43ca-8d3f-a891bced2108)

### Yes, by appt only (formerly no)

![Screenshot 2024-04-19 at 3 33 48 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/85581471/5e5db8ea-06d7-426e-b8a6-05be46d23a7f)


</details>


Spot checked [all results](https://pr15622-xptmfsnjoodldn85nzgkrgljqtfbz24b.ci.cms.va.gov/admin/content/audit/service-locations-detailed?title=&type_op=in&type%5B%5D=health_care_local_health_service&moderation_state_multiple_workflow_filter=All&field_administration_target_id=All), and didn't find any examples that don't match expected behavior: 
* Old: walkins accepted = Yes; New: Office visits = Yes, with or w/o an appt
* Old: walkins accepted = No; New: Office visits = Yes, by appt only
* Old: walkins accepted = Unspecified; New: Office visits = NULL / empty

**Comment by omahane** [comment] 2024-04-22 13:18
Please note that the migration of health services is only happening for the VAMC Facility health service.

I downloaded the CSV and noted that we have over 600 blank/NULL "Old Walkins" (which, incidentally, sounds like a good sippin whiskey). 

<img width="2168" alt="Screenshot 2024-04-22 at 08 14 24" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/766573/25873d62-3595-47f0-aa34-ee4beed5720b">

Filtering for those finds that the Old and New are both blank/NULL:
<img width="1070" alt="Screenshot 2024-04-22 at 08 15 38" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/766573/bc91fdaf-8643-4828-8e68-27b5768fb757">

**Comment by jilladams** [comment] 2024-04-22 16:06
@omahane makes sense, however:  I think all of those are non-clinical services being displayed? (Medical records, Register for Care, Biliing & Insurance, Travel Reimbursement?)

**Comment by omahane** [comment] 2024-04-23 03:59
Oh, yes, the audit shows any services with service locations, including Service Regions and VBA Facility Services, too.

**Comment by davidmpickett** [comment] 2024-04-23 23:03
I just reviewed Jill's QA comments and verified that this is all working as intended on the integration branch. Closing the ticket. Thanks for all the hard work on this @omahane

**Closed by davidmpickett** 2024-04-23 23:03 UTC
Labels: Defect, VAMC, Drupal engineering, Facilities, CY24-Q2
