### ISSUE TITLE
Character counter not working on Staff Profile, Bio First Sentence Field

### ISSUE THREAD

**Issue by edmund-dunn** [department-of-veterans-affairs/va.gov-cms#14667] opened 2023-08-04 19:39 UTC
## Describe the defect
The character counter is not working on the Staff Profile, Bio first sentence filed. It does work on other fields that do use the character counter. 

## To Reproduce
1. Go to https://prod.cms.va.gov/node/add/person_profile
2. Click on Create profile page with biography
3. Start typing in the First sentence field
4. Character count does not change

AC / Expected behavior
The character count should change as user types.

## Screenshots
![CleanShot2023-08-04at12.35.33.jpg](https://images.zenhubusercontent.com/62e017d215adbc33b1310f7b/e6216c87-ca70-4eee-9b6d-2a6c97d624d2)## 
 
![CleanShot2023-08-04at12.36.48.jpg](https://images.zenhubusercontent.com/62e017d215adbc33b1310f7b/c5797ffd-fa05-4268-b8ee-86fe3b9080af)

## Additional context
Add any other context about the problem here. Reach out to the Product Managers to determine if it should be escalated as critical (prevents users from accomplishing their work with no known workaround and needs to be addressed within 2 business days).

## ACs
- [ ] Character counter should update as editor types whether it starts of hidden or not.

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS workstream (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [x] `Facilities`
- [ ] `User support`
- [ ] `Accelerated Publishing`

**Comment by productmike** [comment] 2023-08-04 19:49
@jilladams @xiongjaneg FYI, looks like @edmund-dunn  discovered a prod/non-D10 related defect why he was testing. Passing along :)
cc: @BerniXiongA6

**Comment by swirtSJW** [comment] 2023-08-04 20:39
Likely this is getting broken by the JS that hides/shows the field based on the state of the checkbox.
Odd that is shows no JS error though.

**Comment by swirtSJW** [comment] 2024-01-23 16:05
confirmed bug is still present 
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/fefd27d4-8f1f-46e8-a541-ee5efbc22154)

**Comment by swirtSJW** [comment] 2024-01-23 18:36
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Sitewide-Facilities-639f5253e4b702a32376339e/issues/department-of-veterans-affairs/va.gov-cms/14667?planning-poker) with Zenhub @omahane

**Comment by xiongjaneg** [comment] 2024-01-23 19:54
Timeboxing at a 5. Potentially it could be something that we can't fix without patching the contrib module for the counter.

**Comment by xiongjaneg** [comment] 2024-02-14 17:10
The character counter is from a contrib module.

textfield_counter provides the widget

**Comment by omahane** [comment] 2024-02-14 17:20
I believe this is related to the markup in the widget config.
<img width="1435" alt="Screenshot 2024-02-14 at 11 13 20 AM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/766573/a2c9f1ab-123d-41fb-bafa-37caaa7a239e">

**Comment by jilladams** [comment] 2024-02-27 22:51
Merged, and blocked from deploying by the CMS CI issues. Should deploy once those are resolved.

**Comment by jilladams** [comment] 2024-03-09 02:45
Verified in prod

**Closed by jilladams** 2024-03-09 02:45 UTC
Labels: Defect, VAMC, Drupal engineering, Facilities, Change request
